import type {HeroDeathModel} from '../hero-death-journal.js';
import {esc} from './render.js';
import {heroImage} from './game-assets.js';
const n=(v:number)=>v.toLocaleString('ru-RU');
/** Only verified attribution cells; an absent observation is never an invented zero. */
export function renderHeroKillMatrix(model:HeroDeathModel|null|undefined):string {
 if(!model)return '<section class="kill-matrix" id="kill-matrix" aria-labelledby="kill-matrix-title"><h3 id="kill-matrix-title">Кто кого убивал</h3><p class="micro-note">Матрица убийств появится после проверки журнала смертей реплея.</p></section>';
 const icon=(p:HeroDeathModel['players'][number])=>{const image=heroImage(p.hero);return `${image?`<img src="${esc(image)}" alt="" width="32" height="20" loading="lazy" data-game-image>`:''}<span>${esc(p.heroLabel)}</span>`;};
 const lookup=new Map(model.cells.map(c=>[`${c.killer}:${c.victim}`,c]));
 const max=Math.max(1,...model.cells.map(c=>c.count??0));
 const indexed=model.players.map((p,index)=>({...p,index}));
 const matrices=(['radiant','dire'] as const).map(team=>{
  const killers=indexed.filter(p=>p.team===team),victims=indexed.filter(p=>p.team!==team);
  const title=team==='radiant'?'Radiant → Dire':'Dire → Radiant';
  const rows=killers.map(p=>`<tr><th scope="row"><span class="kill-axis-hero" data-team="${p.team}">${icon(p)}</span></th>${victims.map(v=>{const cell=lookup.get(`${p.index}:${v.index}`),count=cell?.count??(model.coverage.complete?0:null);return `<td>${count!==null&&count>0?`<button type="button" class="kill-cell" data-kill-pair="${p.index}:${v.index}" style="--kill-weight:${count/max}" aria-label="${esc(p.heroLabel)} → ${esc(v.heroLabel)}: ${model.coverage.complete?'':'не менее '}${count} подтверждённых убийств">${n(count)}${model.coverage.complete?'':'+'}</button>`:`<span class="kill-empty" ${count===null?'aria-label="Нет достаточных данных"':''}>${count===null?'—':'0'}</span>`}</td>`;}).join('')}</tr>`).join('');
  return `<div class="kill-side"><h4 class="kill-side-title" data-team="${team}">${title}</h4><div class="kill-table-scroll" tabindex="0" role="region" aria-label="Матрица убийств ${title}"><table class="kill-table"><caption>${title}: убийца → погибший</caption><thead><tr><th scope="col">Убийца ↓<br>Погибший →</th>${victims.map(p=>`<th scope="col"><span class="kill-axis-hero" data-team="${p.team}">${icon(p)}</span></th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div></div>`;
 }).join('');
 return `<section class="kill-matrix" id="kill-matrix" aria-labelledby="kill-matrix-title"><div class="kill-matrix-head"><h3 id="kill-matrix-title"><a href="#kill-matrix">Кто кого убивал</a></h3><button type="button" class="share-section" data-share-section="kill-matrix" aria-label="Скопировать ссылку на матрицу убийств">↗</button></div><p class="micro-note">Строки — убийцы, столбцы — погибшие. Это подтверждённые связи событий; официальный KDA показан в составе.</p>${model.coverage.complete?'':`<p class="kill-warning">Покрытие неполное: число с «+» — подтверждённый минимум, «—» — неизвестно.</p>`}<div class="kill-coverage"><span>Смертей подтверждено <b>${n(model.coverage.verifiedDeaths)}</b></span><span>Убийств подтверждено <b>${n(model.coverage.verifiedKills)}</b></span></div><p class="kill-scroll-hint">Прокрути таблицу → · нажми число для подробностей</p><div class="kill-sides">${matrices}</div><div class="kill-pair-detail" id="kill-pair-detail"><p class="micro-note">Выбери число в матрице, чтобы открыть времена подтверждённых событий.</p></div><details class="kill-matrix-notes"><summary>Что не входит в клетки</summary><p>Смерти без засчитанного убийства герою: <b>${n(model.coverage.nonHeroKills)}</b>. Возвраты / реинкарнации без смерти в D: <b>${n(model.coverage.reincarnations)}</b>.</p><p>Неразрешённых наблюдений: ${n(model.coverage.unresolved)}; отклонённых записей: ${n(model.coverage.invalid)}. Неясная атрибуция не назначается герою по догадке.</p></details><script type="application/json" id="hero-kill-matrix-data">${JSON.stringify(model).replace(/</g,'\\u003c')}</script></section>`;
}
