import {playerAvatar} from "./player-avatar-render.js";
import type {FeedMatch} from './feed.js';
import type {ProfileRoster} from '../apm-store.js';
import {heroImage} from './game-assets.js';
import {heroName} from '../player-profile.js';
import {esc,layout} from './render.js';
import {PROFILE_CSS} from './profile-style.js';
import {HOME_CSS} from './home-style.js';
const time=(s:number)=>`${Math.floor(s/60)}:${String(Math.floor(s)%60).padStart(2,'0')}`;
const date=(s:number)=>new Date(s*1000).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const img=(hero:string,cls='',eager=false)=>{const src=heroImage(hero);return src?`<img class="${cls}" src="${src}" alt="" width="128" height="72" loading="${eager?'eager':'lazy'}" decoding="async" data-game-image>`:'';};
export function renderHome(all:FeedMatch[],updatedAt:number,analyzed:Set<number>,filter?:string,rosters:ProfileRoster[]=[],requestedPage=1){
 const matches=filter?all.filter(m=>m.ours.some(o=>o.name===filter)):all;
 const result=(m:FeedMatch):boolean|null=>{const selected=filter?m.ours.filter(o=>o.name===filter):m.ours;return selected.length&&selected.every(o=>o.win===selected[0].win)?selected[0].win:null;};
 const wins=matches.filter(m=>result(m)===true).length,losses=matches.filter(m=>result(m)===false).length;
 const pages=Math.max(1,Math.ceil(matches.length/12)),page=Math.min(pages,Math.max(1,Number.isSafeInteger(requestedPage)?requestedPage:1)),chunk=matches.slice((page-1)*12,page*12),featured=page===1?chunk[0]:undefined;
 const rosterMap=new Map(rosters.map(r=>[r.match_id,r]));
 const hrefPage=(p:number)=>'/?'+new URLSearchParams({...filter?{player:filter}:{},page:String(p)}).toString();
 const badge=(m:FeedMatch)=>result(m)===null?'Наши по разные стороны':result(m)?'Победа':'Поражение';
 const status=(m:FeedMatch)=>rosterMap.has(m.matchId)?'Реплей разобран':analyzed.has(m.matchId)?'Есть комментарий':'Ждём реплей';
 const members=(m:FeedMatch)=>m.ours.map(o=>`<a class="home-member" href="/player/${o.steamId}"><span class="identity-pair">${playerAvatar(o.steamId,o.name)}${img(o.hero,'home-avatar')}</span><span><strong>${esc(o.name)}</strong><small>${esc(o.hero)}</small></span><b>${o.kills}<i>/</i>${o.deaths}<i>/</i>${o.assists}</b></a>`).join('');
 const lineup=(m:FeedMatch)=>{const r=rosterMap.get(m.matchId);return r?`<div class="home-lineups" aria-label="Составы обеих команд">${(['radiant','dire'] as const).map(team=>`<div class="${team}"><span>${team==='radiant'?'R':'D'}</span>${r.players.filter(p=>p.team===team).map(p=>`<a href="/match/${m.matchId}?player=${encodeURIComponent(p.steam_id)}#combat" aria-label="${esc(heroName(p.hero))}: разбор">${img(p.hero)}</a>`).join('')}</div>`).join('')}</div>`:'';};
 const card=(m:FeedMatch,feature=false)=>`<article class="home-match ${result(m)===true?'is-win':result(m)===false?'is-loss':'is-mixed'} ${feature?'is-featured':''}"><div class="home-match-art" aria-hidden="true">${m.ours.slice(0,3).map(o=>img(o.hero,'',feature)).join('')}<span></span></div><div class="home-match-body"><div class="home-match-top"><span class="home-result">${badge(m)}</span><span class="home-mode">${m.gameMode===23?'Turbo':m.lobbyType===7?'Рейтинг':'Dota 2'}</span><time>${esc(date(m.startTime))}</time></div><a class="home-match-title" href="/match/${m.matchId}"><h2>${feature?'Последняя катка':'Матч '+m.matchId}</h2><span>${time(m.duration)}${feature?' · #'+m.matchId:''}</span></a><div class="home-members">${members(m)}</div>${lineup(m)}<div class="home-match-footer"><span>${status(m)}</span><a href="/match/${m.matchId}" class="home-open">Открыть матч <span aria-hidden="true">↗</span></a></div></div></article>`;
 const names=[...new Set(all.flatMap(m=>m.ours.map(o=>o.name)))].sort();
 const body=`<main class="home-view"><header class="home-heading"><div><p class="home-eyebrow">ПЁСИКИ · DOTA 2</p><h1>Каждая катка —<br><em>своя история.</em></h1><p>От первого преимущества до последнего трона.<br>Матчи, герои и моменты нашего стака.</p></div><a class="home-directory" href="/players">Наши игроки <span aria-hidden="true">↗</span></a></header><div class="home-stats"><div><strong>${matches.length}</strong><span>матчей в ленте</span></div><div><strong>${wins+losses?Math.round(wins/(wins+losses)*100)+'%':'—'}</strong><span>${wins} побед · ${losses} поражений</span></div><div><strong>${Math.round(matches.reduce((s,m)=>s+m.duration,0)/3600)}</strong><span>часов игры</span></div></div><div class="home-feed-tools"><form class="home-filter" method="get"><label for="home-player">Чьи матчи</label><select id="home-player" name="player" class="data-select"><option value="">Весь стак</option>${names.map(name=>`<option value="${esc(name)}" ${filter===name?'selected':''}>${esc(name)}</option>`).join('')}</select><button class="plain-button" type="submit">Показать</button></form><form class="home-sync" method="post" action="/refresh"><button type="submit" aria-label="Синхронизировать матчи" title="Синхронизировать матчи"><span aria-hidden="true">↻</span></button></form></div>${featured?card(featured,true):''}<div class="home-section-title"><h2>${page===1?'Ещё матчи':'История матчей'}</h2><span>Страница ${page} / ${pages}</span></div><div class="home-match-grid">${chunk.filter(m=>m!==featured).map(m=>card(m)).join('')||(!featured?'<p class="empty">Матчей по этому фильтру нет.</p>':'')}</div><nav class="home-pagination" aria-label="Страницы матчей">${page>1?`<a href="${esc(hrefPage(page-1))}">← Новее</a>`:''}${page<pages?`<a href="${esc(hrefPage(page+1))}">Ранее →</a>`:''}</nav><footer class="home-footer"><p>Обновлено ${esc(new Date(updatedAt).toLocaleString('ru-RU'))} · OpenDota и реплеи Valve</p></footer></main>`;
 return layout('Пёсики · истории наших матчей',body,`{const form=document.querySelector('.home-filter');form.querySelector('button').hidden=true;form.querySelector('select').addEventListener('change',()=>form.requestSubmit());const sync=document.querySelector('.home-sync');sync.addEventListener('submit',()=>{sync.setAttribute('aria-busy','true');const button=sync.querySelector('button');button.disabled=true;button.setAttribute('aria-label','Синхронизация матчей');});}`,PROFILE_CSS+HOME_CSS,{description:'Матчи стака, общий разбор, герои и ключевые эпизоды.'});
}
