import type {LiveMatch} from '../live-match.js';
import {heroImage} from './game-assets.js';
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const time=(s:number)=>`${s<0?'−':''}${Math.floor(Math.abs(s)/60)}:${String(Math.floor(Math.abs(s))%60).padStart(2,'0')}`;
export function renderLiveMatch(match:LiveMatch|null):string{
 if(!match)return '';
 return `<article class="live-card" aria-label="Текущий матч"><header class="live-heading"><div><span class="live-label">● СЕЙЧАС В ИГРЕ</span><h2>${match.kind==='stack'?'Играют наши':'Публичный матч'}</h2><p>${match.kind==='stack'?`Участников стака: ${match.stackCount}`:'Пока нет доступного матча стака'} · #${esc(match.matchId)}</p></div><div class="live-score"><strong><span>${match.teams[0]?.score??'—'}</span> : <span>${match.teams[1]?.score??'—'}</span></strong><span>${match.time===undefined?'Время недоступно':time(match.time)}</span></div></header><div class="live-teams">${match.teams.map(team=>`<section><h3>${esc(team.name)} <small>Ур. · K / D / A</small></h3>${team.players.map(p=>{const image=heroImage(p.hero);return `<div class="live-player ${p.ours?'live-ours':''}">${image?`<img src="${esc(image)}" alt="" width="48" height="27" loading="lazy">`:''}<div>${p.ours?`<a href="/player/${p.account}">${esc(p.name)}</a>`:`<strong>${esc(p.name)}</strong>`}<small>${esc(p.hero)}</small></div><span>${p.level??'—'}</span><b>${p.kills??'—'} / ${p.deaths??'—'} / ${p.assists??'—'}</b></div>`;}).join('')}</section>`).join('')}</div><footer>DotaTV · ${match.delay===undefined?'Задержка трансляции неизвестна':`Задержка трансляции ${time(match.delay)}`} · обновление каждые 30 сек.${match.detailed?'':' · Подробная статистика пока недоступна'}</footer></article>`;
}
export const LIVE_MATCH_CSS=`
.live-card{margin:0 0 32px;padding:24px;background:var(--surface);border:1px solid var(--line);border-top:3px solid var(--radiant);border-radius:16px}.live-heading{display:flex;justify-content:space-between;align-items:center;gap:16px}.live-label{color:var(--radiant);font-size:11px;letter-spacing:1.5px;font-weight:800}.live-heading h2{margin:8px 0;font-size:26px}.live-heading p,.live-card footer{color:var(--muted);font-size:12px}.live-score{display:grid;text-align:center;gap:6px;font-variant-numeric:tabular-nums}.live-score strong{font-size:32px;white-space:nowrap}.live-score strong span:first-child{color:var(--radiant)}.live-score strong span:last-child{color:var(--dire)}.live-teams{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:18px 0}.live-teams h3{display:flex;justify-content:space-between;font-size:14px}.live-teams h3 small{font-size:11px;color:var(--muted);font-weight:400}.live-player{display:flex;align-items:center;gap:9px;padding:9px 0;border-top:1px solid var(--line);font-size:12px;min-width:0}.live-player img{object-fit:cover;border-radius:4px}.live-player>div{flex:1;min-width:0}.live-player strong,.live-player a{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.live-player small{display:block;color:var(--muted);margin-top:3px}.live-player>span{color:var(--muted);width:22px;text-align:center}.live-player b{font-size:11px;font-variant-numeric:tabular-nums;white-space:nowrap}.live-ours a{color:var(--accent);font-weight:800}.live-card footer{border-top:1px solid var(--line);padding-top:14px;line-height:1.7}@media(max-width:700px){.live-card{padding:16px}.live-teams{grid-template-columns:1fr;gap:8px}.live-heading h2{font-size:22px}.live-score strong{font-size:26px}}
`;
export const LIVE_MATCH_SCRIPT=`{const slot=document.getElementById('home-live');let busy=false,expires=0;async function updateLive(){if(busy||document.hidden)return;busy=true;try{const response=await fetch('/api/live-match',{cache:'no-store',signal:AbortSignal.timeout(65000)});if(!response.ok)throw new Error('live');const data=await response.json();expires=data.expiresAt||0;slot.innerHTML=expires>Date.now()?data.html:'';slot.hidden=!slot.innerHTML;}catch{if(Date.now()>=expires){slot.innerHTML='';slot.hidden=true;}}finally{busy=false;}}updateLive();setInterval(()=>{if(expires&&Date.now()>=expires){slot.innerHTML='';slot.hidden=true;}updateLive();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateLive();});}`;
