import type {AdviceState} from '../live-advice.js';
import {heroImage,itemImage} from './game-assets.js';
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
export function renderLiveAdvice(state?:AdviceState):string{
 if(!state)return '';
 if(state.status!=='ready')return `<details class="advice-panel advice-wait"><summary class="advice-heading"><h3>Что собираем дальше</h3><span class="advice-toggle" aria-hidden="true">⌄</span></summary><p>${esc(state.message)}</p></details>`;
 const a=state.advice,minute=Math.floor(a.gameTime/60),seconds=String(Math.floor(a.gameTime)%60).padStart(2,'0');
 return `<details class="advice-panel" aria-label="Советы нашим игрокам"><summary class="advice-heading"><div><span class="advice-eyebrow">ПЛАН СБОРКИ</span><h3>Что собираем дальше</h3></div><span class="advice-time">По снимку ${minute}:${seconds}${a.gameMode===23?' · Turbo':''}</span><span class="advice-toggle" aria-hidden="true">⌄</span></summary>${a.plan?`<p class="advice-plan">${esc(a.plan)}</p>`:''}<div class="advice-grid">${a.cards.map(c=>{
 const hero=heroImage(c.hero),item=itemImage(c.item.key),alt=c.alternative;
 return `<article class="advice-player"><div class="advice-identity">${hero?`<img src="${esc(hero)}" alt="" loading="lazy">`:''}<div><strong>${esc(c.name)}</strong><span>${esc(c.hero)}</span></div></div><div class="advice-purchase">${item?`<img src="${esc(item)}" alt="" loading="lazy">`:''}<div><small>ЦЕЛЬ СБОРКИ</small><h4>${esc(c.item.name)}</h4><span>По видимым компонентам ещё ${c.item.remainingCost.toLocaleString('ru-RU')} золота</span></div></div>${c.matchups?.length?`<div class="advice-why"><small>ПОЧЕМУ В ЭТОМ МАТЧЕ</small>${c.matchups.map(m=>`<p><span class="advice-vs">vs ${esc(m.hero)}</span>${esc(m.why)}</p>`).join('')}</div>`:''}<p>${esc(c.reason)}</p>${c.item.ownedComponents.length?`<p class="advice-components">Уже есть: ${esc(c.item.ownedComponents.join(', '))}</p>`:''}${alt?`<div class="advice-alternative"><span>ИЛИ ${esc(alt.name)}</span><p>${esc(c.alternativeReason)}</p></div>`:''}</article>`;
 }).join('')}</div><div class="advice-footnote"><span>Вариант плана, а не команда к действию · фактическая задержка данных не измерена</span><span>Учтён инвентарь наших; курьер и тайник неизвестны.</span><span>${a.statisticsAt?'Сборки: OpenDota · '+new Date(a.statisticsAt).toISOString().slice(0,16).replace('T',' ')+' UTC':'Статистика сборок недоступна — учитываем описания предметов.'} · <a href="https://github.com/odota/dotaconstants/tree/${esc(a.knowledgeRevision)}" target="_blank" rel="noopener noreferrer">Механики предметов ↗</a></span></div></details>`;
}
export const LIVE_ADVICE_CSS=`.advice-panel{margin:24px 0 8px;padding:18px 24px;border:1px solid #314238;border-radius:18px;background:linear-gradient(145deg,#18271f,#111a17)}.advice-heading{cursor:pointer;list-style:none;display:flex;justify-content:space-between;gap:16px;align-items:center}.advice-heading::-webkit-details-marker{display:none}.advice-heading:focus-visible{outline:2px solid #b7d69b;outline-offset:6px;border-radius:4px}.advice-toggle{font-size:22px;color:#b7d69b;margin-left:auto}.advice-panel[open]>.advice-heading>.advice-toggle{transform:rotate(180deg)}.advice-eyebrow{font-size:10px;letter-spacing:2px;color:#b7d69b;font-weight:800}.advice-heading h3{font-size:19px;letter-spacing:-.6px;margin:6px 0 0;color:#f0f4e9}.advice-time{font-size:12px;color:#b5c4b6;white-space:nowrap}.advice-plan{font-size:15px;line-height:1.65;color:#d8e5d5;max-width:850px;margin:18px 0}.advice-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin-top:20px}.advice-player{background:#101914;border:1px solid #2c3b30;border-radius:12px;padding:18px;min-width:0}.advice-identity{display:flex;align-items:center;gap:10px;margin-bottom:20px}.advice-identity>img{width:48px;height:30px;object-fit:cover;border-radius:5px}.advice-identity strong{display:block;font-size:13px;color:#dfe9db;overflow-wrap:anywhere}.advice-identity span{font-size:11px;color:#90a18f}.advice-purchase{display:flex;gap:12px;align-items:center}.advice-purchase>img{width:58px;height:43px;object-fit:cover;border-radius:5px;border:1px solid #50624b}.advice-purchase small{font-size:8px;letter-spacing:1.1px;color:#a6b494}.advice-purchase h4{margin:4px 0;font-size:17px;color:#e4f4c8;line-height:1.2}.advice-purchase span{font-size:11px;color:#c0ae75}.advice-player>p{font-size:13px;line-height:1.6;color:#c6d0c4;margin:15px 0}.advice-why{margin-top:15px}.advice-why>small{font-size:9px;letter-spacing:1px;color:#a8b99e}.advice-why p{font-size:12px;line-height:1.55;color:#d3dfcb;margin:10px 0}.advice-vs{display:block;color:#e0edbf;font-weight:700;font-size:11px;margin-bottom:3px}.advice-player .advice-components{font-size:11px;color:#90a18f}.advice-alternative{border-top:1px solid #28372d;padding-top:12px;margin-top:15px}.advice-alternative>span{font-size:10px;font-weight:700;letter-spacing:.7px;color:#a8b99e}.advice-alternative p{font-size:12px;line-height:1.6;color:#a7b3a3;margin:7px 0 0}.advice-footnote{display:grid;gap:5px;color:#879780;font-size:10px;line-height:1.5;margin-top:16px}.advice-footnote a{color:#a8bd96}.advice-wait p{color:#aebda7;font-size:13px;margin-bottom:0}@media(max-width:700px){.advice-panel{padding:17px;margin-top:16px}.advice-heading{flex-wrap:wrap;gap:9px}.advice-time{order:3;flex-basis:100%}.advice-heading h3{font-size:18px}.advice-grid{grid-template-columns:1fr}.advice-plan{font-size:14px}}`;
