import {buildMatchCombatWindow} from "../match-combat-window.js";
import type {ParsedMatch} from '../replay.js';
import type {MatchInsights} from '../match-insights.js';
import type {MatchApi,MatchApiPlayer} from '../opendota.js';
import {PLAYERS} from '../config.js';
import {heroImage} from './game-assets.js';
import {playerAvatar} from './player-avatar-render.js';
import {resolveOfficialRosterPlayer,rosterAccount} from './match-official.js';
import {esc} from './render.js';
const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)&&v>=0?Math.round(v).toLocaleString('ru-RU'):'—';
export function renderMatchRoster(m:ParsedMatch,x:MatchInsights,api?:MatchApi,officialPlayers?:MatchApiPlayer[]):string{
 const combat=buildMatchCombatWindow(m,0,m.apm_duration_seconds??m.duration_min*60),combatKnown=combat.coverage.state==='complete'||combat.coverage.state==='partial';
 const metrics=[['heroDamage','Урон врагам'],['healing','Лечение союзников'],['buildings','Урон строениям'],['stuns','Оглушение, секунды']] as const;
 const rows=x.players.map(p=>{const raw=m.players.find(q=>q.steam_id===p.steamId&&q.hero===p.hero),official=resolveOfficialRosterPlayer(m,p,api,officialPlayers),account=rosterAccount(p.steamId),ours=PLAYERS.find(q=>q.steamId===account),name=ours?.dotaName??p.heroLabel,art=heroImage(p.heroLabel),observed=combat.players.find(q=>q.steamId===p.steamId&&q.hero===p.hero);return {p,raw,official,account,ours,name,art,values:{heroDamage:combatKnown?observed?.recorded.damageEnemies??null:null,healing:combatKnown?observed?.recorded.healingAllies??null:null,buildings:p.damage.buildings,stuns:p.control.stunSeconds}};});
 const compact=(['radiant','dire'] as const).map(team=>`<span class="roster-compact-team ${team}"><small>${team==='radiant'?'Radiant':'Dire'}</small><span>${rows.filter(r=>r.p.team===team).map(r=>r.art?`<img src="${esc(r.art)}" alt="${esc(r.p.heroLabel)}" width="40" height="24" loading="lazy" data-game-image>`:`<i>${esc(r.p.heroLabel)}</i>`).join('')}</span></span>`).join('');
 const cards=(team:string)=>rows.filter(r=>r.p.team===team).map(({p,raw,official,account,ours,name,art,values})=>`<article class="roster-player ${ours?'ours':''}" data-roster-side="${team}"><a class="roster-identity" href="/match/${m.match_id}?player=${encodeURIComponent(p.steamId)}#combat">${ours&&account?playerAvatar(account,name):''}${art?`<img class="roster-hero" src="${esc(art)}" alt="" width="56" height="34" loading="lazy" data-game-image>`:''}<span><strong>${esc(name)}</strong>${ours?`<small>${esc(p.heroLabel)}</small>`:''}</span><b aria-hidden="true">↗</b></a><div class="roster-primary"><span><small>K / D / A</small><strong>${official?`${official.kills} / ${official.deaths} / ${official.assists}`:'—'}</strong></span><span><small>APM</small><strong>${n(raw?.actions_per_min)}</strong></span><span><small>Имущество</small><strong>${n(raw?.networth_final)}</strong></span></div><div class="roster-contribution">${metrics.map(([key,label],i)=>`<div data-roster-metric="${key}" data-value="${values[key]??''}" ${i?'hidden':''}><span>${label}</span><strong>${n(values[key])}</strong><i></i></div>`).join('')}</div><details class="roster-more"><summary>Все показатели</summary><dl>${metrics.map(([key,label])=>`<div><dt>${label}</dt><dd>${n(values[key])}</dd></div>`).join('')}<div><dt>Добивания</dt><dd>${n(raw?.last_hits)}</dd></div></dl><p>Прочерк — измерение не сохранено. Самолечение исключено из помощи союзникам.</p></details></article>`).join('');
 return `<details class="roster-fold" id="scoreboard"><summary><span class="roster-compact"><strong>Составы · KDA · вклад</strong><span class="roster-compact-teams">${compact}</span></span><b aria-hidden="true">+</b></summary><div class="roster-body"><div id="teams" class="roster-toolbar"><div><h3>Сравнить вклад</h3><p>Длина полосы — относительно максимума в матче. ${combat.coverage.state==='partial'?'Урон и лечение: неполный журнал, показана записанная часть.':combat.coverage.state==='complete'?'Урон и лечение: полный сохранённый журнал.':'Журнал урона врагам и лечения не сохранён.'}</p></div><label for="roster-metric" class="sr-only">Показатель вклада</label><select id="roster-metric" class="data-select">${metrics.map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select><button type="button" class="share-section" data-share-section="scoreboard" aria-label="Скопировать ссылку на составы">↗</button></div><div class="roster-teams">${(['radiant','dire'] as const).map(team=>`<section class="roster-team ${team}" aria-label="${team==='radiant'?'Radiant':'Dire'}"><h3>${team==='radiant'?'Radiant':'Dire'}${m.winner===team?' <span>Победа</span>':''}</h3>${cards(team)}</section>`).join('')}</div><p class="roster-note">KDA — итоговое табло реплея; OpenDota используется как запасной источник. Герой, сторона и аккаунт проверяются. APM и имущество — реплей. Урон и лечение не дают общего балла полезности; сравнивай с учётом роли.</p></div></details>`;
}
