import {buildMatchCombatWindow,type CombatWindowActor} from '../match-combat-window.js';
import type {ParsedMatch} from '../replay.js';
import {heroName} from '../player-profile.js';
import {abilityLabel} from '../ability-labels.js';
import {gameLabel} from './game-icon.js';
import {esc} from './render.js';
const n=(v:number)=>Math.round(v).toLocaleString('ru-RU');
const time=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
const label=(key:string)=>heroName(key)!==key?heroName(key):abilityLabel(key);
function breakdown(rows:Record<string,number>,title:string){return `<h5>${title}</h5>${Object.entries(rows).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([key,value])=>`<div class="cw-detail-row"><span>${gameLabel(key,label(key))}</span><strong>${n(value)}</strong></div>`).join('')||'<p class="ep-note">Не записано.</p>'}${Object.keys(rows).length>12?`<p class="ep-note">Показаны 12 из ${Object.keys(rows).length} источников.</p>`:''}`;}
function actor(p:CombatWindowActor,max:number,matchId:number){const t=p.recorded;return `<details class="cw-actor ${p.team}"><summary><span class="cw-identity">${gameLabel(p.hero,heroName(p.hero),'hero')}</span><span class="cw-bar" aria-hidden="true"><i style="width:${max&&t.damageEnemies?t.damageEnemies/max*100:0}%"></i></span><strong>${n(t.damageEnemies)}</strong><span aria-hidden="true">⌄</span></summary><div class="cw-details"><p><a href="/match/${matchId}?player=${encodeURIComponent(p.steamId)}#combat">Личный разбор ${esc(heroName(p.hero))} ↗</a></p><div class="cw-stats"><div><strong>${n(t.incoming)}</strong><span>Получено урона</span></div><div><strong>${n(t.controlledEnemyDamage)}</strong><span>Из урона врагам: подконтрольные источники</span></div><div><strong>${n(t.healingSelf)}</strong><span>Лечение себя</span></div><div><strong>${n(t.healingAllies)}</strong><span>Лечение союзников</span></div></div><p class="ep-note">Всего урона героям: ${n(t.damage)}. Врагам ${n(t.damageEnemies)}, себе ${n(t.damageSelf)}, союзникам ${n(t.damageAllies)}. В подконтрольные источники входят иллюзии: ${n(t.illusionEnemyDamage)} урона врагам.</p>${t.healingEnemies?`<p class="ep-note">Также записано лечение врагов: ${n(t.healingEnemies)}.</p>`:''}${breakdown(p.enemyDamage.byAbility,'Чем нанесён урон врагам')}${breakdown(p.enemyDamage.byTarget,'Кому из врагов нанесён урон')}<details class="fold"><summary>Источники урона и лечения</summary>${breakdown(p.damage.bySource,'Атакующие сущности · все цели')}${breakdown(p.healing.byAbility,'Источники лечения')}${breakdown(p.healing.byTarget,'Получатели лечения')}</details></div></details>`;}
/** This is a time window across the whole map, never inferred fight participation. */
export function renderMatchCombatWindow(match:ParsedMatch,startSeconds:number,endSeconds:number):string {
 if(!match.combat_timeline)return '';
 const w=buildMatchCombatWindow(match,startSeconds,endSeconds);
 if(!w.actualWindow||w.coverage.state==='invalid')return '<p class="ep-note">Журнал урона этого окна не прошёл проверку. Итоги не показаны.</p>';
 const complete=w.coverage.state==='complete',max=Math.max(0,...w.players.map(p=>p.recorded.damageEnemies)),total=w.teams.radiant.recorded.damageEnemies+w.teams.dire.recorded.damageEnemies;
 return `<section class="combat-window" aria-labelledby="combat-window-title"><div class="cw-heading"><p class="pulse-eyebrow">Урон под микроскопом</p><h3 id="combat-window-title">Кто давил в этот момент</h3><p class="ep-note">${time(w.actualWindow.startSecond)}–${time(w.actualWindow.endSecondExclusive)} · события всей карты, включая подконтрольных юнитов. Это не список участников одной драки.</p></div>${!complete?'<p class="cw-warning">Журнал этого окна неполный. Ниже только сохранившиеся события, а не полный итог.</p>':''}<div class="cw-versus"><div class="radiant"><span>Radiant</span><strong>${n(w.teams.radiant.recorded.damageEnemies)}</strong></div><span>урона врагам</span><div class="dire"><span>Dire</span><strong>${n(w.teams.dire.recorded.damageEnemies)}</strong></div></div><div class="cw-team-bar" aria-hidden="true"><i style="width:${total?w.teams.radiant.recorded.damageEnemies/total*100:50}%"></i></div><p class="ep-note">Сравнение включает только урон вражеским героям с подтверждённым владельцем источника. Урон себе, союзникам и источники без владельца исключены. Нажми на героя для разбивки.</p><div class="cw-actors">${[...w.players].sort((a,b)=>b.recorded.damageEnemies-a.recorded.damageEnemies).map(p=>actor(p,max,match.match_id)).join('')}</div>${w.unknownOwner.recorded.damage||w.unknownOwner.recorded.healing?`<details class="fold"><summary>Без установленного владельца · ${n(w.unknownOwner.recorded.damage)} урона</summary><p class="ep-note">Эти события не приписаны героям или командам. Здесь могут быть башни, крипы и другие сущности.</p>${breakdown(w.unknownOwner.damage.bySource,'Источники урона')}${breakdown(w.unknownOwner.healing.bySource,'Источники лечения')}</details>`:''}<p class="ep-note">Только реальные герои в качестве целей. Входящий урон включает урон себе и от союзников. Полнота означает сохранность наблюдений журнала, а не всех событий игрового движка. Лечение себя и союзников разделено. Интервал округлён наружу до целых секунд; правая граница не включена.</p></section>`;
}
export const COMBAT_WINDOW_CSS=`.combat-window{margin:28px 0;padding:20px;border:1px solid var(--line);border-radius:16px;background:var(--surface-2)}.cw-heading h3{font-size:25px;line-height:1.1;margin:8px 0 12px}.cw-versus{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:20px 0 12px}.cw-versus>div{display:flex;flex-direction:column;gap:5px}.cw-versus>div:last-child{text-align:right}.cw-versus strong{font-size:28px}.cw-versus>span{color:var(--muted);font-size:12px}.cw-team-bar{height:6px;border-radius:8px;background:var(--dire);overflow:hidden;margin-bottom:20px}.cw-team-bar i{display:block;height:100%;background:var(--radiant)}.cw-actor{border-top:1px solid var(--line)}.cw-actor>summary{min-height:56px;display:grid;grid-template-columns:minmax(125px,1.5fr) minmax(20px,1fr) auto 12px;gap:10px;align-items:center;cursor:pointer;list-style:none}.cw-actor>summary::-webkit-details-marker{display:none}.cw-identity{font-size:12px;font-weight:700;min-width:0}.cw-bar{height:5px;background:var(--line);border-radius:4px;overflow:hidden}.cw-bar i{display:block;height:100%;background:var(--radiant)}.cw-actor.dire .cw-bar i{background:var(--dire)}.cw-actor>summary>strong{font-size:13px;font-variant-numeric:tabular-nums}.cw-details{padding:0 0 18px}.cw-stats{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.cw-stats>div{display:flex;flex-direction:column;gap:5px}.cw-stats strong{font-size:20px}.cw-stats span{font-size:12px;color:var(--muted)}.cw-detail-row{display:flex;justify-content:space-between;gap:12px;padding:7px 0;font-size:12px}.cw-detail-row>span{min-width:0;overflow-wrap:anywhere}.cw-details h5{font-size:13px;margin:18px 0 5px}.cw-warning{border-left:3px solid var(--accent);padding-left:12px;font-size:13px}@media(max-width:400px){.combat-window{padding:12px}.cw-actor>summary{grid-template-columns:minmax(108px,1fr) minmax(12px,.4fr) auto 8px;gap:6px}.cw-identity .game-icon{width:30px;height:22px}.cw-heading h3{font-size:22px}}`;
