export const MATCH_COMPARISON_SCRIPT=`
(()=>{const node=document.getElementById('comparison-data');if(!node)return;const data=JSON.parse(node.textContent),svg=document.getElementById('comparison-svg'),range=document.getElementById('comparison-minute'),empty=document.getElementById('comparison-empty'),area=document.getElementById('comparison-controls'),buttons=[...document.querySelectorAll('[data-comparison-metric]')],readout=document.getElementById('comparison-readout');
const names={networth:'Имущество',xp:'Опыт',lastHits:'Добивания'},units={networth:'золота имущества',xp:'опыта',lastHits:'добиваний'},format=n=>Math.round(n).toLocaleString('ru-RU');let metric='networth',points=[];
const leftPicker=document.getElementById('comparison-left'),rightPicker=document.getElementById('comparison-right');function validatePair(){rightPicker.setCustomValidity(leftPicker.value===rightPicker.value?'Выбери два разных матча.':'');}leftPicker.addEventListener('change',validatePair);rightPicker.addEventListener('change',validatePair);validatePair();
const saved=new URL(location.href),requestedMetric=saved.searchParams.get('metric');if(Object.hasOwn(names,requestedMetric))metric=requestedMetric;
function el(tag,attrs,text){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));if(text!==undefined)n.textContent=text;return n;}
function select(save){const p=points[Number(range.value)];if(!p)return;document.getElementById('comparison-minute-label').textContent='Минута '+p.minute;range.setAttribute('aria-valuetext',p.minute+' минута');document.getElementById('comparison-left-value').textContent=format(p.left);document.getElementById('comparison-right-value').textContent=format(p.right);document.getElementById('comparison-delta').textContent='Во второй игре '+(p.delta>0?'+':'')+format(p.delta)+' '+units[metric]+' на той же минуте.';const marker=svg.querySelector('[data-marker]');if(marker){const maxMinute=points[points.length-1].minute;marker.setAttribute('x1',50+p.minute/maxMinute*420);marker.setAttribute('x2',50+p.minute/maxMinute*420);}if(save){const url=new URL(location.href);url.searchParams.set('metric',metric);url.searchParams.set('minute',p.minute);history.replaceState(null,'',url.pathname+url.search+url.hash);}}
function draw(save=false){points=data.curves[metric];buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.comparisonMetric===metric)));svg.replaceChildren();const present=points.length>0;area.hidden=!present;svg.hidden=!present;empty.hidden=present;readout.hidden=!present;if(!present){if(save){const url=new URL(location.href);url.searchParams.set('metric',metric);url.searchParams.delete('minute');history.replaceState(null,'',url.pathname+url.search+url.hash);}return;}
svg.setAttribute('aria-label',names[metric]+' двух игр на общих записанных минутах');const max=Math.max(1,...points.flatMap(p=>[p.left,p.right])),maxMinute=points[points.length-1].minute,x=m=>50+m/maxMinute*420,y=v=>190-v/max*160;
for(const n of[0,max/2,max]){svg.append(el('line',{x1:50,x2:470,y1:y(n),y2:y(n),class:'cmp-grid'}));svg.append(el('text',{x:3,y:y(n)+4},format(n)));}for(const minute of[0,maxMinute])svg.append(el('text',{x:x(minute),y:214,'text-anchor':minute?'end':'start'},minute+' мин'));
for(const side of['left','right']){let group=[];const flush=()=>{if(!group.length)return;svg.append(el('polyline',{points:group.map(p=>x(p.minute)+','+y(p[side])).join(' '),fill:'none','stroke-width':2.5,class:'cmp-'+side}));if(group.length===1)svg.append(el('circle',{cx:x(group[0].minute),cy:y(group[0][side]),r:3,fill:'none','stroke-width':2,class:'cmp-'+side}));group=[];};for(const p of points){if(group.length&&p.minute!==group[group.length-1].minute+1)flush();group.push(p);}flush();}
svg.append(el('line',{x1:50,x2:50,y1:24,y2:190,stroke:'var(--muted)','stroke-dasharray':'2 4','data-marker':''}));range.max=points.length-1;const minute=Number(new URL(location.href).searchParams.get('minute'));let index=points.findIndex(p=>p.minute===minute);if(index<0)index=points.findIndex(p=>p.minute===10);range.value=index<0?0:index;select(save);}
buttons.forEach(b=>b.addEventListener('click',()=>{metric=b.dataset.comparisonMetric;draw(true);}));range.addEventListener('input',()=>select(true));draw();
const share=document.getElementById('comparison-share'),status=document.getElementById('comparison-share-status');share.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);status.textContent='Ссылка скопирована';}catch{status.replaceChildren();const a=document.createElement('a');a.href=location.href;a.textContent='Текущая ссылка — удерживай, чтобы скопировать';status.append(a);}});
})();
`;
