import {buildMatchOverview,type MatchOverview,type OverviewMetric} from '../match-overview.js';
import type {ParsedMatch} from '../replay.js';
import type {MatchApi} from '../opendota.js';
import {heroName} from '../player-profile.js';
import {HERO_CATALOG} from '../hero-catalog.js';
import {esc} from './render.js';
const n=(v:number|null)=>v===null?'—':Math.round(v).toLocaleString('ru-RU');
const clock=(m:number)=>`${Math.floor(Math.round(m*60)/60)}:${String(Math.round(m*60)%60).padStart(2,'0')}`;
const lead=(v:number)=>v===0?'Равенство':`${v>0?'Radiant':'Dire'} +${n(Math.abs(v))}`;
const team=(s:string)=>s==='radiant'?'Radiant':'Dire';
function section(id:string,title:string,sub:string,body:string){return `<section class="panel insight-panel" id="${id}" aria-labelledby="${id}-title"><div class="section-head"><div><h2 id="${id}-title"><a href="#${id}">${title}</a></h2><p class="sub">${sub}</p></div><button type="button" class="share-section" data-share-section="${id}" aria-label="Скопировать ссылку: ${title}">↗</button></div>${body}</section>`;}
function chart(o:MatchOverview){return `<div class="ov-section-head"><h3>Кто владел преимуществом</h3><label for="overview-metric" class="control-label">Показатель</label><select class="data-select" id="overview-metric"><option value="networth">Имущество команд</option><option value="xp">Опыт команд</option></select></div><div id="overview-chart" class="ov-curve"></div><label class="control-label" for="overview-minute">Момент игры</label><input id="overview-minute" class="chart-range" type="range" min="1" max="${Math.max(1,Math.floor(o.durationSeconds/60))}" value="${Math.max(1,Math.floor(o.durationSeconds/60))}"><p id="overview-reading" class="ov-chart-reading" aria-live="polite"></p><p class="ov-note">Выше нуля — преимущество Radiant, ниже — Dire. Суммируем пять героев каждой команды в одну и ту же минуту. Пропуски не соединяем.</p><noscript>${o.phases.map(p=>`<p>${p.key==='end'?'Финал':p.key+' мин'}: ${p.networth?lead(p.networth.advantage):'нет полного измерения имущества'}</p>`).join('')}</noscript>`;}
function overview(o:MatchOverview){return `<div class="ov-scoreline"><div class="ov-team radiant">Radiant<strong>${n(o.score.radiant)}</strong></div><div class="ov-duration">${clock(o.durationSeconds/60)}<small>${o.score.radiant===null||o.score.dire===null?'Счёт не сохранён полностью':'Официальный счёт'}</small></div><div class="ov-team dire">Dire<strong>${n(o.score.dire)}</strong></div></div><div class="ov-summary"><p class="label">История всей игры</p><h3>${esc(o.headline)}</h3>${o.story.map(s=>`<p>${esc(s)}</p>`).join('')}</div><div class="ov-evidence-grid">${o.evidence.filter(e=>e.kind!=='swing').map(e=>`<article class="ov-evidence"><h3>${esc(e.title)}</h3><p>${esc(e.body)}</p>${e.title==='Имущество к концу'?'<a href="#scoreboard">Проверить итоговое имущество ↗</a>':e.minute!==null?`<a href="?minute=${Math.max(1,Math.floor(e.minute))}#farm">Проверить фарм на ${clock(e.minute)} ↗</a>`:''}</article>`).join('')}</div>${chart(o)}<div class="ov-section-head"><h3>Самые заметные изменения</h3><p class="ov-note">Сдвиги имущества за короткие окна. События рядом по времени дают контекст; сами по себе они не доказывают причину.</p></div><div class="ov-events">${o.swings.map((s,i)=>`<article class="ov-event" id="swing-${i}"><time>${clock(s.fromMinute)}–${clock(s.toMinute)}</time><div><h3>${team(s.beneficiary)}: сдвиг на ${n(Math.abs(s.delta))}</h3><p>${s.xpDelta===null?'Нет полного измерения опыта в этом окне.':'Изменение перевеса по опыту: '+lead(s.xpDelta)+'.'}</p>${s.events.length?`<ul>${s.events.slice(0,4).map(e=>`<li>${clock(e.startMinute)} · ${esc(e.label)}</li>`).join('')}</ul>`:'<p class="ov-note">Крупных событий в доступном журнале рядом нет. Причина изменения не установлена.</p>'}<a href="#${s.events.length?'moment-'+o.events.indexOf(s.events[0]):'timeline'}">Открыть события этого отрезка ↗</a></div></article>`).join('')||'<p class="empty">Недостаточно непрерывных измерений для выделения изменений.</p>'}</div><p class="ov-note">Покрытие: имущество ${o.coverage.networthMinutes} / ${o.coverage.totalFullMinutes} полных минут; опыт ${o.coverage.xpMinutes} / ${o.coverage.totalFullMinutes}. Время убийств и строений — из реплея.</p>`;}
function eventEconomy(o:MatchOverview,start:number,end:number){
 const before=o.networthAdvantage.find(p=>p.minute===Math.floor(start)),after=o.networthAdvantage.find(p=>p.minute===Math.ceil(end)+1);
 if(!before||!after)return '<p class="ov-note">Нет двух полных минутных снимков вокруг этого эпизода.</p>';
 const change=after.advantage-before.advantage;
 return `<div class="ov-evidence"><h3>Имущество вокруг эпизода</h3><p>${clock(before.minute)} · ${lead(before.advantage)}<br>${clock(after.minute)} · ${lead(after.advantage)}</p><p>Сдвиг за это окно: ${lead(change)}.</p><p class="ov-note">Минутные снимки охватывают и другие события на карте. Это не стоимость конкретной драки.</p></div>`;
}
function timeline(o:MatchOverview,m:ParsedMatch){return `<p class="sub">Раскрой эпизод, чтобы увидеть события и состав участников. На любой эпизод можно отправить ссылку.</p><label for="overview-event-filter" class="control-label">Показать</label><select id="overview-event-filter" class="data-select"><option value="all">Все ключевые события</option><option value="fight">Боевые эпизоды</option><option value="building">Строения</option><option value="roshan">Roshan</option></select><p id="overview-event-count" class="ov-note" role="status"></p><div class="ov-events">${o.events.map((e,i)=>{const kills=(m.kills??[]).filter(k=>k.min>=e.startMinute&&k.min<=e.endMinute);return `<details class="ov-event ov-moment" id="moment-${i}" data-overview-event="${e.kind}"><summary><time>${clock(e.startMinute)}${e.endMinute>e.startMinute?'–'+clock(e.endMinute):''}</time><span>${esc(e.label)}</span></summary><div class="ov-event-body">${e.kind==='fight'?`<p class="ov-note">Серия смертей с промежутками не более 20 секунд. Стычки могли происходить в разных местах; повторные смерти одного героя считаются отдельно.</p>${kills.map(k=>`<p class="ov-kill"><time>${clock(k.min)}</time> ${esc(heroName(k.killer))} → ${esc(heroName(k.victim))}</p>`).join('')}`:e.kind==='roshan'?'<p>Roshan погиб. Команда, забравшая его, и получатель Aegis в этих данных не установлены.</p>':'<p>Зафиксирована потеря строения. Участники атаки и возможный денай не определяются по одному событию.</p>'}${eventEconomy(o,e.startMinute,e.endMinute)}<div class="ov-event-actions"><a href="#moment-${i}">Ссылка на эпизод</a><button type="button" class="share-section" data-share-section="moment-${i}" aria-label="Скопировать ссылку на эпизод ${clock(e.startMinute)}">↗</button><a href="?minute=${Math.max(1,Math.floor(e.startMinute))}#farm">Фарм в этот момент ↗</a></div></div></details>`;}).join('')||'<p class="empty">События для хронологии не сохранены.</p>'}</div>`;}
const metrics=[['heroDamage','Урон героям'],['towerDamage','Урон строениям'],['alliedHealing','Лечение союзных героев'],['wardsPlaced','Установлено вардов'],['buybacks','Выкупы'],['damageTaken','Полученный урон']] as const;
function metricTeam(metric:OverviewMetric,side:string,id:number){return `<div class="ov-team"><h3 class="${side}">${team(side)} <strong>${n(metric.total)}</strong></h3><p class="ov-note">Данные ${metric.known} из ${metric.expected} героев${metric.total===null?' · общий итог неизвестен':''}</p>${[...metric.players].sort((a,b)=>(b.value??-1)-(a.value??-1)).map(p=>{const hero=heroName(p.hero),key=HERO_CATALOG.find(h=>h.localized_name===hero)?.name.replace('npc_dota_hero_','');return `<a class="ov-player" href="/match/${id}?player=${encodeURIComponent(p.steamId)}#combat">${key?`<img src="https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${key}.png" alt="" width="48" height="28" loading="lazy">`:''}<span>${esc(hero)}<small>${p.share===null?'Доля неизвестна':Math.round(p.share*100)+'% команды'}</small></span><strong>${n(p.value)}</strong><i style="width:${p.share===null?0:p.share*100}%"></i></a>`;}).join('')}</div>`;}
function teams(o:MatchOverview){return `<p class="sub">Урон героям — из единой разбивки реплея для всех десяти участников. Сравнение по конкретному вкладу. Урон, обзор и лечение показаны отдельно; общего «балла полезности» нет.</p><label class="control-label" for="overview-team-metric">Что сравниваем</label><select id="overview-team-metric" class="data-select">${metrics.map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select>${metrics.map(([key,label],i)=>`<div data-team-metric="${key}" ${i?'hidden':''}><h3>${label}</h3><div class="ov-grid">${o.teams.map(t=>metricTeam(t[key],t.team,o.matchId)).join('')}</div></div>`).join('')}<p class="ov-note">Самолечение и лечение существ исключены из помощи союзным героям. Установка варда подтверждается созданием его сущности; покупка не считается установкой. Большой показатель сам по себе не доказывает хорошую игру.</p><a class="plain-button" href="#scoreboard">Составы, KDA и APM всех игроков ↗</a>`;}
export function renderMatchOverview(m:ParsedMatch,api?:MatchApi){const verified=api?.match_id===m.match_id;const o=buildMatchOverview(verified?{...m,radiant_score:api!.radiant_score,dire_score:api!.dire_score}:m);return section('overview','Общий разбор','Обе команды · весь матч',overview(o))+section('timeline','Ход игры','Боевые эпизоды, строения и Roshan',timeline(o,m))+section('teams','Вклад команд','Десять героев в контексте своих команд',teams(o))+`<script type="application/json" id="match-overview-data">${JSON.stringify({networth:o.networthAdvantage,xp:o.xpAdvantage}).replace(/</g,'\\u003c')}</script>`;}
