import type {ParsedMatch} from '../replay.js';
import type {MatchOverview} from '../match-overview.js';
import type {MatchEpisodes} from '../match-episodes.js';
import {HERO_CATALOG} from '../hero-catalog.js';
import {heroName} from '../player-profile.js';
import {esc} from './render.js';
export function renderMatchPulse(m:ParsedMatch,o:MatchOverview,episodes?:MatchEpisodes):string {
 const rosters=(['radiant','dire'] as const).map(team=>`<div class="pulse-team ${team}"><div class="pulse-team-heading"><strong>${team==='radiant'?'Radiant':'Dire'}</strong><span>${o.winner===team?'Победа':''}</span></div><div class="pulse-heroes">${m.players.filter(p=>p.team===team).map(p=>{const name=heroName(p.hero),hero=HERO_CATALOG.find(h=>h.localized_name===name),key=hero?.name.replace('npc_dota_hero_','');return `<a href="/match/${m.match_id}?player=${encodeURIComponent(p.steam_id)}#combat" aria-label="${esc(name)}: личный разбор" title="${esc(name)}">${key?`<img src="https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${key}.png" alt="${esc(name)}" width="64" height="36" loading="lazy">`:`<span>${esc(name)}</span>`}</a>`;}).join('')}</div></div>`).join('');
 const events=o.events.map((e,i)=>{const episode=episodes?.episodes.find(x=>e.kind==='fight'&&x.startSeconds<=e.endMinute*60&&x.endSeconds>=e.startMinute*60);return {...e,index:i,href:episode?`?episode=${encodeURIComponent(episode.id)}#episodes`:`#moment-${i}`};});
 const payload={duration:o.durationSeconds,networth:o.networthAdvantage,xp:o.xpAdvantage,events,phases:o.phases.map(p=>({key:p.key,minute:p.networth?.minute??p.xp?.minute??null})),winner:o.winner};
 return `<section class="match-pulse" aria-labelledby="pulse-title"><div class="pulse-heading"><div><p class="pulse-eyebrow">Две команды. Одна история.</p><h3 id="pulse-title">Пульс матча</h3></div><span class="pulse-source">По реплею</span></div><div class="pulse-rosters">${rosters}</div><div class="pulse-toolbar"><div class="pulse-metrics" role="group" aria-label="Показатель графика"><button type="button" data-pulse-metric="networth" aria-pressed="true">Имущество</button><button type="button" data-pulse-metric="xp" aria-pressed="false">Опыт</button></div><span class="pulse-sample" id="pulse-sample"></span></div><div class="pulse-readout"><div><span id="pulse-leader">Выбери момент</span><strong id="pulse-advantage">—</strong></div><div class="pulse-clock"><strong id="pulse-time">—</strong><span>минута матча</span></div></div><div id="pulse-chart" class="pulse-chart"></div><div class="pulse-playback"><button type="button" id="pulse-play" aria-label="Воспроизвести ход матча">▶</button><div><label for="pulse-minute" class="pulse-range-label">Ход матча <span>Проведи по шкале</span></label><input id="pulse-minute" class="chart-range" type="range" min="1" max="${Math.max(1,Math.floor(o.durationSeconds/60))}" value="${Math.max(1,Math.floor(o.durationSeconds/60))}"></div></div><div class="pulse-phases" role="group" aria-label="Перейти к периоду матча"><button type="button" data-pulse-minute="10">10 мин</button><button type="button" data-pulse-minute="20">20 мин</button><button type="button" data-pulse-minute="${Math.max(1,Math.floor(o.durationSeconds/60))}">Последняя минута</button></div><div class="pulse-team-totals"><span>Radiant <strong id="pulse-radiant">—</strong></span><span>Dire <strong id="pulse-dire">—</strong></span></div><div class="pulse-context"><div class="pulse-context-head"><h4>В эту минуту</h4><span id="pulse-event-count"></span></div><div id="pulse-events"></div></div><p class="pulse-footnote">Выше линии — перевес Radiant, ниже — Dire. Точки — события журнала. Пропуски измерений не соединяем; близость событий не доказывает причину изменения.</p><noscript><p>Для интерактивной шкалы нужен JavaScript. Контрольные точки и события доступны ниже в разборе.</p></noscript><script type="application/json" id="match-pulse-data">${JSON.stringify(payload).replace(/</g,'\\u003c')}</script></section>`;
}
