/** Mobile episode details; all colours inherit the shared accessible themes. */
export const EPISODE_CSS = `
.ep-summary{margin:18px 0;padding-bottom:16px;border-bottom:1px solid var(--line)}.ep-summary h3{font-size:22px;line-height:1.3;margin:0 0 8px;text-transform:none;letter-spacing:-.02em}.ep-summary p{font-size:13px;line-height:1.65;color:var(--muted);margin:7px 0}
.ep-controls{display:flex;align-items:end;gap:10px;flex-wrap:wrap;margin:14px 0}.ep-controls>label,.ep-controls>div{flex:1 1 200px;min-width:0}.ep-controls select{width:100%;min-width:0}.ep-controls button,.ep-controls a{min-height:44px;min-width:44px}.ep-controls .control-label{display:block;margin-bottom:7px}
.ep-score{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:var(--line);border:1px solid var(--line);border-radius:4px;overflow:hidden;margin:14px 0}.ep-score>div{padding:13px 15px;background:var(--surface-2);min-width:0}.ep-score span,.ep-score small{display:block;font-size:12px;line-height:1.5;color:var(--muted)}.ep-score strong{display:block;font-size:27px;line-height:1.25;font-variant-numeric:tabular-nums;margin:4px 0}.ep-score .radiant strong{color:var(--radiant)}.ep-score .dire strong{color:var(--dire)}
.ep-rosters{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin:18px 0}.ep-team{min-width:0}.ep-team h3,.ep-team h4{font-size:14px;line-height:1.5;margin:0 0 9px;text-transform:none}.ep-team.radiant h3,.ep-team.radiant h4{color:var(--radiant)}.ep-team.dire h3,.ep-team.dire h4{color:var(--dire)}.ep-heroes{display:flex;gap:7px;flex-wrap:wrap}.ep-hero{display:inline-flex;flex-direction:column;align-items:flex-start;gap:5px;min-width:44px;max-width:100%;font-size:12px;line-height:1.5;text-decoration:none;color:var(--ink)}.ep-hero img{width:48px;height:28px;object-fit:cover;border-radius:2px;display:block}.ep-hero small{font-size:11px;color:var(--muted)}.ep-hero:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
.ep-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.25fr);gap:22px;align-items:start;margin:18px 0}.ep-grid>*{min-width:0}.ep-map{width:100%;max-width:540px;margin:0 auto;background:var(--ground);border:1px solid var(--line);border-radius:4px;overflow:hidden}.ep-map svg{width:100%;height:auto;display:block;aspect-ratio:1}.ep-map [role=button]{cursor:pointer}.ep-map [role=button]:focus-visible{outline:none;stroke:var(--ink);stroke-width:4}.ep-map .ep-note,.ep-map .map-selection{margin:12px;font-size:12px;line-height:1.65}.ep-map text{font-size:13px}
.ep-log{display:flex;flex-direction:column;margin:0;padding:0;list-style:none}.ep-row{display:grid;grid-template-columns:48px minmax(0,1fr);gap:10px;padding:12px 0;border-bottom:1px solid var(--line);min-width:0}.ep-row:last-child{border-bottom:0}.ep-row time{font-size:12px;color:var(--accent);font-variant-numeric:tabular-nums;white-space:nowrap;line-height:1.7}.ep-row>div,.ep-row>span{min-width:0;overflow-wrap:anywhere}.ep-row strong{font-size:13px;line-height:1.5;font-weight:650}.ep-row p,.ep-row small{display:block;font-size:12px;line-height:1.65;color:var(--muted);margin:4px 0 0}.ep-row img{width:28px;height:28px;object-fit:cover;border-radius:2px;vertical-align:middle;margin-right:5px}.ep-row a{color:var(--accent);display:inline-flex;align-items:center;min-height:44px;font-size:12px}
.ep-context{padding:15px;background:var(--surface-2);border:1px solid var(--line);border-left:2px solid var(--accent);border-radius:4px;margin:16px 0}.ep-context h3,.ep-context h4{margin:0 0 8px;font-size:15px;line-height:1.5;text-transform:none}.ep-context p{font-size:12px;line-height:1.7;color:var(--muted);margin:6px 0}.ep-context strong{color:var(--ink)}.ep-note{font-size:12px;color:var(--muted);line-height:1.65;margin:10px 0}.ep-note strong{color:var(--ink)}.ep-empty{padding:14px;border:1px dashed var(--line);border-radius:4px;color:var(--muted);font-size:13px;line-height:1.65}
@media(max-width:700px){.ep-grid{grid-template-columns:1fr;gap:18px}.ep-rosters{grid-template-columns:1fr;gap:14px}.ep-summary h3{font-size:20px}.ep-score>div{padding:12px}.ep-score strong{font-size:25px}}
@media(max-width:480px){.ep-row{grid-template-columns:42px minmax(0,1fr);gap:8px}.ep-context{padding:12px}.ep-controls{gap:8px}.ep-summary p{font-size:12px}.ep-heroes{gap:8px}.ep-hero{font-size:11px}}
#episode-picker{display:flex;flex-direction:column;gap:8px;margin:16px 0}#episode-picker>.control-label{margin:0}#episode-picker>.plain-button{align-self:flex-start;min-height:44px}.ep-controls>a{flex:1 1 120px;justify-content:center;text-align:center}.ep-team>h3.radiant{color:var(--radiant)}.ep-team>h3.dire{color:var(--dire)}.ep-hero{flex:0 1 calc(33.333% - 6px);min-width:72px}.ep-hero a{color:var(--ink);text-decoration:none;display:inline-flex;align-items:center;min-height:44px;overflow-wrap:anywhere}.ep-hero a:hover{text-decoration:underline}.ep-hero>span{min-width:0;max-width:100%}.ep-hero small{display:block}.ep-death-detail h3{overflow-wrap:anywhere}.ep-death-detail h3 a{color:var(--accent);text-decoration:none;min-height:44px;display:inline-flex;align-items:center}.ep-damage-sources .ep-row{grid-template-columns:minmax(0,1fr) auto;align-items:baseline;gap:12px;padding:9px 0;font-size:12px;line-height:1.6}.ep-damage-sources .ep-row strong{font-variant-numeric:tabular-nums;white-space:nowrap}.ep-death-detail .fold{margin-top:12px}.ep-grid>div>h3{font-size:17px;line-height:1.4;margin:0 0 9px;text-transform:none}.ep-context>.ep-row{font-size:12px;line-height:1.65}.ep-log .ep-row a{min-height:32px}.ep-score>div>span{color:var(--muted)}.ep-score>div>strong{color:inherit}.ep-score>.radiant>strong{color:var(--radiant)}.ep-score>.dire>strong{color:var(--dire)}
`;
