import {gameLabel} from "./game-icon.js";
import {buildMatchEpisodes,type MatchEpisode,type MatchEpisodes,type EpisodeActor} from '../match-episodes.js';
import type {ParsedMatch} from '../replay.js';
import {heroName} from '../player-profile.js';
import {HERO_CATALOG} from '../hero-catalog.js';
import {abilityLabel} from '../ability-labels.js';
import {esc} from './render.js';
const clock=(seconds:number)=>`${Math.floor(Math.round(seconds)/60)}:${String(Math.round(seconds)%60).padStart(2,'0')}`;
const n=(v:number|null)=>v===null?'—':Math.round(v).toLocaleString('ru-RU');
const label=(s:string)=>heroName(s)!==s?heroName(s):abilityLabel(s);
const advantage=(v:number)=>v===0?'равенство':`${v>0?'Radiant':'Dire'} +${n(Math.abs(v))}`;
const actorLink=(a:EpisodeActor,id:number)=>`<a href="/match/${id}?player=${encodeURIComponent(a.steamId)}#combat">${esc(a.heroLabel)}</a>`;
const portrait=(hero:string)=>{const key=HERO_CATALOG.find(h=>h.localized_name===hero)?.name.replace('npc_dota_hero_','');return key?`<img src="https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${key}.png" alt="" width="48" height="28" loading="lazy">`:'';};
function roster(e:MatchEpisode,id:number){return `<div class="ep-rosters">${(['radiant','dire'] as const).map(team=>`<div class="ep-team"><h3 class="${team}">${team==='radiant'?'Radiant':'Dire'}</h3><div class="ep-heroes">${e.uniqueDeadHeroes.filter(p=>p.team===team).map(p=>`<div class="ep-hero">${portrait(p.heroLabel)}<span>${actorLink(p,id)}<small>${p.deaths>1?p.deaths+' смерти':'1 смерть'}</small></span></div>`).join('')||'<p class="ep-note">Смертей не записано</p>'}</div></div>`).join('')}</div>`;}
function deaths(e:MatchEpisode,id:number){return `<div id="episode-map" class="ep-map"></div><p id="episode-map-status" class="ep-note" role="status">Выбери маркер или смерть в списке.</p><label class="control-label" for="episode-death">Смерть в эпизоде</label><select id="episode-death" class="data-select">${e.deaths.map((d,i)=>`<option value="${i}">${clock(d.seconds)} · ${esc(d.heroLabel)}${d.killer?' ← '+esc(label(d.killer)):''}</option>`).join('')}</select>${e.deaths.map((d,i)=>`<article class="ep-death-detail ep-context" data-episode-death="${i}" ${i?'hidden':''}><h3>${clock(d.seconds)} · ${actorLink(d,id)}</h3><p>${d.killer?'Убийца в журнале: '+esc(label(d.killer)): 'Убийца не записан.'}</p>${d.incoming?`<p><strong>${n(d.incoming.total)}</strong> входящего урона за 8 секунд перед смертью</p><div class="ep-damage-sources">${d.incoming.byAbility.slice(0,5).map(r=>`<div class="ep-row"><span>${gameLabel(r.key,label(r.key))}</span><strong>${n(r.value)}</strong></div>`).join('')}</div><details class="fold"><summary>Все источники и атакующие</summary>${d.incoming.byAbility.map(r=>`<p>${esc(label(r.key))} · ${n(r.value)}</p>`).join('')}<h4>Атакующие</h4>${d.incoming.byAttacker.map(r=>`<p>${esc(label(r.key))} · ${n(r.value)}</p>`).join('')}</details><p class="ep-note">${d.incoming.complete?'Буфер этого окна не усечён.':'Окно могло быть усечено.'} Включает наблюдаемый урон существ и иллюзий.</p>`:'<p class="ep-note">Разбивка урона перед этой смертью не сохранена или не прошла проверку сумм.</p>'}</article>`).join('')}`;}
function log(e:MatchEpisode,id:number){
 const rows=[...e.deaths.map(d=>({seconds:d.seconds,kind:'death',html:`<strong>Смерть · ${actorLink(d,id)}</strong><small>${d.killer?esc(label(d.killer))+' → '+esc(d.heroLabel):'Убийца не записан'}</small>`})),...e.buybacks.map(b=>({seconds:b.seconds,kind:'buyback',html:`<strong>Выкуп · ${actorLink(b,id)}</strong><small>${b.goldCost===null?'Стоимость не подтверждена':n(b.goldCost)+' золота · подтверждено событием списания'}</small>`}))].sort((a,b)=>a.seconds-b.seconds);
 const ultimateGroups=new Map<string,typeof e.casts>();for(const c of e.casts.filter(c=>c.ultimate===true)){const key=c.steamId+':'+c.hero+':'+c.ability;ultimateGroups.set(key,[...(ultimateGroups.get(key)??[]),c]);}
 return `<h3>Смерти и выкупы</h3><p class="ep-note">Окно ${clock(e.contextStartSeconds)}–${clock(e.contextEndSeconds)}. Журналы применений: ${e.coverage.castPlayers} из ${e.coverage.totalPlayers} героев. Применения способностей могут происходить в другой части карты.</p><div class="ep-log">${rows.map(r=>`<div class="ep-row ep-${r.kind}"><time>${clock(r.seconds)}</time><div>${r.html}</div></div>`).join('')}</div><details class="fold"><summary>Применения ультимейтов · ${e.casts.filter(c=>c.ultimate===true).length}</summary>${[...ultimateGroups.values()].map(cs=>`<div class="ep-context"><h4>${gameLabel(cs[0].ability,cs[0].label,'ability')} × ${cs.length}</h4><p>${actorLink(cs[0],id)}</p><p class="ep-note">${cs.map(c=>clock(c.seconds)).join(' · ')}</p></div>`).join('')||'<p class="ep-note">Распознанных применений в этом окне нет.</p>'}</details><details class="fold"><summary>Все записанные применения · ${e.casts.length}</summary><div class="ep-log">${e.casts.map(c=>`<div class="ep-row"><time>${clock(c.seconds)}</time><div><strong>${gameLabel(c.ability,c.label,'ability')}</strong><small>${actorLink(c,id)}${c.target?' → '+esc(label(c.target)):''}</small></div></div>`).join('')||'<p class="ep-note">В этом окне применений не записано.</p>'}</div></details><p class="ep-note">Показаны события применения, а не успешность ультимейтов. Каталог включает некоторые вспомогательные кнопки остановки и возврата.</p>`;
}
function context(e:MatchEpisode){return `<div class="ep-context"><h3>Как изменилось имущество</h3>${e.networth.before?`<p>${clock(e.networth.before.minute*60)} · ${advantage(e.networth.before.advantage)}</p>`:'<p>Снимок перед эпизодом отсутствует.</p>'}${e.networth.after?`<p>${clock(e.networth.after.minute*60)} · ${advantage(e.networth.after.advantage)}${e.networth.after.source==='final'?' · финальный снимок':''}</p>`:'<p>Снимок после эпизода отсутствует.</p>'}${e.networth.delta===null?'':`<p><strong>Изменение: ${advantage(e.networth.delta)}</strong></p>`}<p class="ep-note">Разница снимков включает всю карту. Это не награда за конкретное столкновение.</p><h3>Что произошло в следующие две минуты</h3>${e.followingObjectives.length?e.followingObjectives.map(o=>`<div class="ep-row"><time>${clock(o.startMinute*60)}</time><span>${esc(o.label)}</span></div>`).join(''):'<p>Башни, казармы, Древний и Roshan в этом окне не отмечены.</p>'}</div>`;}
export function renderMatchEpisodes(m:ParsedMatch,selected?:string,model?:MatchEpisodes){
 const data=model??buildMatchEpisodes(m),episodes=data.episodes,e=episodes.find(e=>e.id===selected)??[...episodes].sort((a,b)=>Math.abs(b.networth.delta??0)-Math.abs(a.networth.delta??0)||b.deaths.length-a.deaths.length)[0];
 const head=`<div class="section-head"><div><h2 id="episodes-title"><a href="#episodes">Эпизод под микроскопом</a></h2><p class="sub">Обе команды · действия и события по журналу</p></div><button type="button" class="share-section" data-share-section="episodes" aria-label="Скопировать ссылку на эпизод">↗</button></div>`;
 if(!e)return `<section class="panel insight-panel" id="episodes" aria-labelledby="episodes-title">${head}<p class="empty">В сохранённом журнале нет цепочки из трёх смертей с паузами до 20 секунд.</p><p class="ep-note">Это не означает, что в матче не было столкновений. Одиночные смерти доступны в личном разборе.</p></section>`;
 const at=episodes.indexOf(e),link=(index:number,title:string)=>`<a class="plain-button" data-episode-select="${episodes[index].id}" href="?episode=${episodes[index].id}#episodes">${title}</a>`;
 return `<section class="panel insight-panel" id="episodes" aria-labelledby="episodes-title">${head}<form id="episode-picker" method="get" action="/match/${m.match_id}#episodes"><label class="control-label" for="match-episode">Выбрать эпизод</label><select name="episode" id="match-episode" class="data-select">${episodes.map(x=>`<option value="${x.id}" ${x===e?'selected':''}>${clock(x.startSeconds)}–${clock(x.endSeconds)} · смерти ${x.deathCounts.radiant}:${x.deathCounts.dire}</option>`).join('')}</select><button class="plain-button" type="submit">Показать</button></form><div class="ep-controls">${at?link(at-1,'← Предыдущий'):''}${at<episodes.length-1?link(at+1,'Следующий →'):''}</div><div class="ep-summary"><h3>${clock(e.startSeconds)}–${clock(e.endSeconds)}</h3><p>${esc(e.summary)}</p><div class="ep-score"><div class="radiant"><span>Смертей Radiant</span><strong>${e.deathCounts.radiant}</strong></div><div class="dire"><span>Смертей Dire</span><strong>${e.deathCounts.dire}</strong></div></div></div><h3>Погибшие герои</h3>${roster(e,m.match_id)}<div class="ep-grid"><div>${deaths(e,m.match_id)}</div><div>${log(e,m.match_id)}</div></div>${context(e)}<details class="fold"><summary>Покупки перед эпизодом и в его окне · ${e.purchases.length}</summary><p class="ep-note">${clock(e.purchaseStartSeconds)}–${clock(e.contextEndSeconds)}. Время покупки не равно доставке; здесь события всей карты.</p>${e.purchases.map(p=>`<div class="ep-row"><time>${clock(p.seconds)}</time><div><strong>${gameLabel(p.item,p.label,'item')}</strong><small>${actorLink(p,m.match_id)}</small></div></div>`).join('')}</details><details class="fold"><summary>Покрытие и правила разбора</summary><p class="ep-note">Координаты ${e.coverage.locatedDeaths}/${e.deaths.length} смертей; входящий урон ${e.coverage.incomingDeaths}/${e.deaths.length}. Журналы применений ${e.coverage.castPlayers}/${e.coverage.totalPlayers} героев; без усечения ${e.coverage.uncappedCastPlayers}/${e.coverage.totalPlayers}.</p>${data.notes.map(s=>`<p class="ep-note">${esc(s)}</p>`).join('')}</details><script type="application/json" id="episode-map-data">${JSON.stringify({id:e.id,deaths:e.deaths.map(d=>({seconds:d.seconds,hero:d.heroLabel,team:d.team,x:d.x,y:d.y}))}).replace(/</g,'\\u003c')}</script></section>`;
}
