/** Match analysis extends the profile's shared colour and touch-target system. */
export const MATCH_CSS = `
.match-view{display:flex;flex-direction:column;gap:14px;min-width:0}
.match-head{padding:22px 24px;background:var(--surface);border:1px solid var(--line);border-top:3px solid var(--accent);border-radius:5px}
.match-view .btn{min-height:44px;display:inline-flex;align-items:center;justify-content:center;background:var(--accent);border-color:var(--accent);color:var(--surface);border-radius:4px}.match-view .btn.ghost{background:transparent;color:var(--accent)}.match-view .card{border-radius:5px;padding:18px}.match-head h1{font-size:30px;line-height:1.2;letter-spacing:-.025em;margin:0 0 8px}
.match-head .sub{line-height:1.6}.match-head-meta{display:flex;gap:10px 20px;flex-wrap:wrap;margin-top:12px;color:var(--muted);font-size:13px}
.match-tabs{position:sticky;top:0;z-index:20;display:flex;overflow-x:auto;overscroll-behavior-x:contain;max-width:100%;gap:0;padding:3px;background:var(--surface);border:1px solid var(--line);border-radius:4px;scrollbar-width:thin;scroll-padding-inline:3px;box-shadow:0 5px 10px #00000012;-webkit-overflow-scrolling:touch}
.match-tabs a{display:flex;align-items:center;justify-content:center;flex:1 0 82px;min-width:82px;min-height:44px;padding:6px 9px;color:var(--muted);font-size:13px;font-weight:600;text-decoration:none;white-space:nowrap;border-radius:2px}
.match-tabs a[aria-current=location]{color:var(--accent);background:var(--surface-2);box-shadow:inset 0 -3px var(--accent)}
.match-view .insight-panel{min-width:0;scroll-margin-top:80px}.insight-panel>h2{margin-bottom:12px}.insight-panel h3{font-size:15px;line-height:1.4;margin:20px 0 10px}.insight-panel .sub{line-height:1.6}
.player-picker{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:12px 0 16px}.player-picker label{font-size:12px;color:var(--muted);font-weight:600}.player-picker select{display:block;min-height:48px;min-width:0;max-width:100%;flex:1 1 200px;border:1px solid var(--line);border-radius:4px;background:var(--surface-2);color:var(--ink);font:inherit;font-size:16px;padding:10px 12px}.player-picker button{min-height:44px;padding:8px 16px;border:1px solid var(--line);border-radius:4px;background:var(--surface-2);color:var(--ink);font:inherit;font-size:13px;cursor:pointer}
.match-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.match-columns>*{min-width:0}.match-view .match-chart,.match-view .insight-chart{display:block;width:100%;height:auto;margin:14px 0}.match-view .match-chart text,.match-view .insight-chart text{fill:var(--muted);font-size:13px}
.match-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid var(--line);background:var(--surface-2);border-radius:4px;overflow:hidden;margin:14px 0}.match-kpi{padding:12px;border-right:1px solid var(--line);min-width:0}.match-kpi:last-child{border-right:0}.match-kpi span{display:block;font-size:12px;color:var(--muted);line-height:1.5}.match-kpi strong{display:block;font-size:23px;font-variant-numeric:tabular-nums;letter-spacing:-.025em;margin:3px 0}
.stat-bars{display:flex;flex-direction:column;gap:0;margin:12px 0}.bar-row{display:grid;grid-template-columns:minmax(90px,1fr) minmax(60px,1.6fr) auto;gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid var(--line);font-size:13px;min-height:44px}.bar-row:last-child{border-bottom:0}.bar-row>:first-child{min-width:0;overflow-wrap:anywhere}.bar-row strong,.bar-row b{font-variant-numeric:tabular-nums;white-space:nowrap}.bar-row .bar-track{height:8px;background:var(--ground);border-radius:2px}.bar-row .bar-track i{background:var(--accent);opacity:1;border-radius:2px}.bar-row small{display:block;color:var(--muted);font-size:11px;margin-top:2px}
.event-list{display:flex;flex-direction:column;list-style:none;margin:12px 0;padding:0}.event-row{display:grid;grid-template-columns:48px minmax(0,1fr) auto;align-items:start;gap:10px;padding:12px 0;border-bottom:1px solid var(--line);font-size:13px;line-height:1.55}.event-row:last-child{border-bottom:0}.event-row time{color:var(--muted);font-size:12px;font-variant-numeric:tabular-nums;white-space:nowrap}.event-row>div,.event-row>span{min-width:0;overflow-wrap:anywhere}.event-row small{display:block;color:var(--muted);font-size:12px}.event-row b{font-variant-numeric:tabular-nums}.event-row img{width:36px;height:27px;object-fit:contain}.event-row a{color:var(--accent)}
.scoreboard-list{display:flex;flex-direction:column;margin-top:12px}.scoreboard-row{display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:10px;align-items:center;min-height:66px;padding:10px 0;border-bottom:1px solid var(--line);font-size:13px}.scoreboard-row:last-child{border:0}.scoreboard-row img{width:48px;height:29px;object-fit:cover;border-radius:3px}.scoreboard-row strong{font-size:14px}.scoreboard-row small{display:block;font-size:12px;color:var(--muted);margin-top:3px}.scoreboard-row .player-score{text-align:right;font-variant-numeric:tabular-nums}.scoreboard-row a{min-height:44px;display:flex;flex-direction:column;justify-content:center;text-decoration:none;overflow-wrap:anywhere}.team-label{font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;padding:10px 0;border-bottom:2px solid var(--line)}.team-label.radiant{color:var(--radiant);border-color:var(--radiant)}.team-label.dire{color:var(--dire);border-color:var(--dire)}
.match-view .data-scroll{max-width:100%;overflow-x:auto;overscroll-behavior-x:contain;scrollbar-width:thin;margin:12px 0}.match-view .data-scroll table{width:100%;border-collapse:collapse;font-size:13px}.match-view .data-scroll th,.match-view .data-scroll td{padding:10px 9px;text-align:left;border-bottom:1px solid var(--line);font-variant-numeric:tabular-nums}.match-view .data-scroll th{font-size:11px;color:var(--muted);font-weight:600}.match-view .data-scroll tbody tr:nth-child(even){background:var(--surface-2)}
.vision-map{display:block;width:100%;height:auto;aspect-ratio:1;max-width:560px;margin:14px auto;background:var(--ground);border:1px solid var(--line);border-radius:4px;touch-action:pan-y}.map-legend{display:flex;flex-wrap:wrap;gap:8px 16px;font-size:12px;color:var(--muted);margin:10px 0}.map-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.map-controls input[type=range]{width:100%;height:44px;accent-color:var(--accent)}.map-controls button{min-height:44px;padding:8px 12px;border:1px solid var(--line);background:var(--surface-2);color:var(--ink);border-radius:3px;font:inherit;font-size:13px}
@media(hover:hover){.match-tabs a:hover{color:var(--ink);background:var(--surface-2)}.scoreboard-row a:hover{color:var(--accent)}}
@media(max-width:800px){.match-columns{grid-template-columns:1fr}}
@media(max-width:480px){.match-view{gap:12px}.match-head{padding:18px 16px}.match-head h1{font-size:26px}.match-head-meta{gap:6px 12px;font-size:12px}.match-tabs{border-radius:3px}.match-tabs a{font-size:12px;min-width:80px;flex-basis:80px}.match-view .insight-panel{scroll-margin-top:72px}.player-picker{align-items:stretch;gap:7px}.player-picker label{width:100%}.player-picker select{width:100%;flex-basis:100%}.player-picker button{flex:1}.match-kpi{padding:10px 8px}.match-kpi strong{font-size:21px}.match-kpi span{font-size:11px}.bar-row{grid-template-columns:minmax(82px,1fr) minmax(42px,1.2fr) auto;gap:8px;font-size:12px}.event-row{grid-template-columns:42px minmax(0,1fr);gap:8px;font-size:13px}.event-row>:nth-child(3){grid-column:2}.scoreboard-row{grid-template-columns:44px minmax(0,1fr) auto;gap:8px}.scoreboard-row img{width:44px;height:27px}.scoreboard-row strong{font-size:13px}.scoreboard-row small{font-size:11px}.match-view .data-scroll th,.match-view .data-scroll td{padding:9px 7px}}

/* Concrete replay renderer. Labels remain in normal flow; progress bars
   sit below each label/value pair, so long ability names never collide. */
.match-view:has(.match-insights) #analysis{min-height:calc(100vh - 80px);min-height:calc(100svh - 80px)}.match-insights{display:flex;flex-direction:column;gap:14px;min-width:0}
.match-view .player-picker{display:block}.player-picker>label{display:block;margin-bottom:7px}.player-picker>div{display:flex;gap:8px;min-width:0}.player-picker>div select{flex:1;min-width:0}
.control-label{display:block;font-size:12px;font-weight:600;color:var(--muted);margin:12px 0 7px}.data-select{font:inherit;font-size:16px;color:var(--ink);background:var(--surface-2);border:1px solid var(--line);border-radius:4px;min-height:48px;padding:10px 12px;width:100%;min-width:0;max-width:100%}
select.data-select{appearance:none;-webkit-appearance:none;background-image:linear-gradient(45deg,transparent 50%,var(--muted) 50%),linear-gradient(135deg,var(--muted) 50%,transparent 50%);background-position:calc(100% - 18px) 21px,calc(100% - 13px) 21px;background-size:5px 5px;background-repeat:no-repeat;padding-right:32px}
.match-tabs a:focus-visible,.profile-jumps a:focus-visible{outline-offset:-3px}
.score-team+.score-team{margin-top:22px}.team-title{padding:0 0 9px;border-bottom:2px solid var(--line);font-size:13px!important;letter-spacing:.06em;text-transform:uppercase}.team-title.radiant{color:var(--radiant);border-color:var(--radiant)}.team-title.dire{color:var(--dire);border-color:var(--dire)}
.score-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.score-player{min-width:0;border:1px solid var(--line);background:var(--surface-2);border-radius:4px;padding:12px}.score-player.ours{border-top:2px solid var(--accent)}.score-identity{display:flex;align-items:center;gap:10px;min-height:44px;text-decoration:none}.score-identity>span{min-width:0;overflow-wrap:anywhere}.score-identity img{display:block;width:52px;height:32px;object-fit:cover;border-radius:3px;flex-shrink:0}.score-identity strong{font-size:14px;font-weight:650}.score-identity small{display:block;color:var(--muted);font-size:12px;line-height:1.5;margin-top:2px}.score-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:10px;padding-top:9px;border-top:1px solid var(--line)}.score-stats>span{min-width:0}.score-stats small{display:block;color:var(--muted);font-size:10px;line-height:1.5}.score-stats b{display:block;font-size:13px;font-variant-numeric:tabular-nums;white-space:nowrap;margin-top:3px}
.stat-bars>.bar-row,.fold-body>.bar-row{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:10px 0 16px;min-height:48px;border-bottom:1px solid var(--line);font-size:13px}.bar-row>i{display:block;position:absolute;bottom:4px;left:0;height:4px;background:var(--accent);border-radius:1px;max-width:100%}.bar-row>span{overflow-wrap:anywhere;min-width:0}.bar-row>b{font-variant-numeric:tabular-nums;white-space:nowrap}.combat-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:0;background:var(--surface-2);border:1px solid var(--line);border-radius:4px;margin:12px 0;overflow:hidden}.combat-metrics>div{padding:12px;border-right:1px solid var(--line);min-width:0}.combat-metrics>div:last-child{border-right:0}.combat-metrics span{display:block;color:var(--muted);font-size:12px;line-height:1.45}.combat-metrics strong{display:block;font-size:23px;letter-spacing:-.02em;font-variant-numeric:tabular-nums;margin-top:5px}
.farm-chart{width:100%;min-width:0;margin:14px 0}.farm-chart svg{display:block;width:100%;height:auto;overflow:visible}.farm-values{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:12px 0}.farm-value{display:grid;grid-template-columns:8px minmax(0,1fr) auto;align-items:center;gap:8px;min-height:44px;text-align:left;width:100%;border:1px solid var(--line);border-radius:3px;padding:8px 10px;background:var(--surface-2);color:var(--ink);font:inherit;font-size:12px;cursor:pointer}.farm-value>i,.farm-value .color-dot{display:block;width:7px;height:7px;border-radius:50%;flex-shrink:0}.farm-value .name,.farm-value>span{min-width:0;overflow-wrap:anywhere}.farm-value strong{white-space:nowrap;font-size:13px;font-variant-numeric:tabular-nums}.farm-value small{display:block;color:var(--muted);font-size:11px;line-height:1.5;margin-top:2px}.farm-value[aria-pressed=false]{opacity:1;color:var(--muted);background:var(--ground);text-decoration:line-through}.farm-value[aria-pressed=false]>i{opacity:.35}.farm-value:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
.event-map{max-width:540px;margin:16px auto;background:var(--ground);border:1px solid var(--line);border-radius:4px;overflow:hidden}.event-map:empty{display:none}.event-map>.empty,.event-map>.micro-note{margin:12px;padding:0}.event-map svg{display:block;width:100%;height:auto;aspect-ratio:1}.event-map text{font-size:12px}.event-map [role=button]{cursor:pointer}.event-map [role=button]:focus-visible{outline:none;stroke:var(--ink);stroke-width:4}.event-count{font-size:12px;color:var(--muted);padding:12px 0 4px}#combat-events{margin-bottom:14px}.event-row{grid-template-columns:48px minmax(0,1fr) auto}.event-row>small{font-size:11px;color:var(--muted)}
@media(max-width:800px){.score-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:480px){.farm-chart text{font-size:24px}.match-insights{gap:12px}.player-picker>div{flex-wrap:wrap}.player-picker>div select{flex:1 1 100%}.player-picker>div button{width:100%}.score-grid{grid-template-columns:1fr}.score-player{padding:10px}.score-stats{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 12px}.score-stats small{font-size:10px}.score-stats b{font-size:12px;margin:0}.score-stats>span{display:flex;align-items:center;justify-content:space-between;gap:4px}.score-stats small{font-size:10px;white-space:nowrap}.combat-metrics>div{padding:10px 8px}.combat-metrics span{font-size:11px}.combat-metrics strong{font-size:20px}.farm-values{grid-template-columns:1fr;gap:5px}.farm-value{font-size:13px}.farm-value strong{font-size:14px}.event-row{grid-template-columns:42px minmax(0,1fr);gap:8px}.event-row>small{grid-column:2}.event-map text{font-size:13px}}

@media(min-width:360px) and (max-width:480px){.farm-values{grid-template-columns:repeat(2,minmax(0,1fr))}.farm-value{grid-template-columns:7px minmax(0,1fr);gap:4px 7px;padding:8px;font-size:12px}.farm-value strong{grid-column:2;font-size:16px}.farm-value small{font-size:10px}}
`;
