export const VISION_SCRIPT=`
{
 const node=document.getElementById('match-vision-data');if(node){
 const data=JSON.parse(node.textContent);const deathData=JSON.parse(document.getElementById('match-deaths-data')?.textContent||'{"events":[]}');data.events=[...data.events,...deathData.events.map((e,i)=>({...e,event:'death',kind:'death',deathId:e.id,mapNumber:'D'+(i+1)}))].sort((a,b)=>a.seconds-b.seconds);const state=new URL(location.href),visionRange=document.getElementById('vision-time');
 const escapeText=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const clock=s=>Math.floor(s/60)+':'+String(Math.floor(s)%60).padStart(2,'0');
 function drawWardMap(events){
  const target=document.getElementById('vision-map'),config=data.mapConfig??JSON.parse(document.getElementById('match-insights-data')?.textContent||'{}').mapConfig;
  const configured=config&&typeof config.imageUrl==='string'&&(/^(?:https:\\/\\/|\\/[^\\/])/.test(config.imageUrl))&&[config.xMin,config.xMax,config.yMin,config.yMax].every(Number.isFinite)&&config.xMax>config.xMin&&config.yMax>config.yMin;
  const bounds=configured?config:{xMin:-10000,xMax:10000,yMin:-10000,yMax:10000};
  const positioned=events.filter(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)),located=positioned.filter(e=>e.x>=bounds.xMin&&e.x<=bounds.xMax&&e.y>=bounds.yMin&&e.y<=bounds.yMax),outside=positioned.length-located.length,missing=events.length-positioned.length;
  const x=v=>20+(v-bounds.xMin)/(bounds.xMax-bounds.xMin)*300,y=v=>320-(v-bounds.yMin)/(bounds.yMax-bounds.yMin)*300;
  const kind=e=>e.kind==='death'?'героя':e.kind==='observer'?'Observer':e.kind==='sentry'?'Sentry':'Вард неизвестного типа',label=e=>(e.event==='death'?'Смерть':e.event==='destroy'?'Уничтожение':'Установка')+' · '+kind(e)+' · '+e.hero+' · '+(e.team==='radiant'?'Radiant':'Dire'),color=e=>e.event==='death'?(e.team==='radiant'?'#83C998':'#FF8A7E'):e.kind==='observer'?'#FFD166':e.kind==='sentry'?'#68C8FF':'#D0D6DF';
  const background=configured?'<image href="'+escapeText(config.imageUrl)+'" x="20" y="20" width="300" height="300" preserveAspectRatio="none"/>':'<rect x="20" y="20" width="300" height="300" fill="var(--surface-2)" stroke="var(--line)"/>'+[95,170,245].map(v=>'<path d="M'+v+' 20V320M20 '+v+'H320" stroke="var(--line)" stroke-dasharray="3 5"/>').join('');
  const symbol=e=>e.event==='death'?(e.image?'<image href="'+escapeText(e.image)+'" x="-10" y="-10" width="20" height="20"/><path d="M5 5L13 13M5 13L13 5" stroke="#17212B" stroke-width="5"/><path d="M5 5L13 13M5 13L13 5" stroke="#FFFFFF" stroke-width="2"/>':'<path d="M-7-7L7 7M-7 7L7-7"/>'):e.kind==='observer'?'<path d="M-9 0Q0-11 9 0Q0 11-9 0Z"/><circle r="3"/>':e.kind==='sentry'?'<path d="M0-10L10 0L0 10L-10 0Z"/><path d="M-5 0H5M0-5V5"/>':'<circle r="7"/><path d="M0-4V2M0 5V6"/>';
  target.innerHTML='<svg viewBox="0 0 340 340" role="group" aria-label="'+(configured?'Карта смертей и вардов':'Координатная схема смертей и вардов')+'">'+background+located.map(e=>'<g data-ward-number="'+e.mapNumber+'" transform="translate('+x(e.x)+' '+y(e.y)+')"><circle class="ward-marker-base" r="14" fill="#17212B" fill-opacity=".94" stroke="'+color(e)+'" stroke-width="1.5"/><g fill="none" stroke="'+color(e)+'" stroke-width="2" pointer-events="none">'+symbol(e)+'</g>'+(e.event==='destroy'?'<path d="M-11 11L11-11" stroke="#17212B" stroke-width="6" pointer-events="none"/><path d="M-11 11L11-11" stroke="#FFFFFF" stroke-width="2.5" pointer-events="none"/>':'')+'<g class="ward-marker-number"><circle cx="12" cy="-12" r="8" fill="#17212B" pointer-events="none"/><text x="12" y="-8.5" text-anchor="middle" fill="#FFFFFF" style="font-size:10px;font-weight:700" pointer-events="none">'+e.mapNumber+'</text></g></g>').join('')+'</svg><p class="map-selection" role="status">'+(located.length?'Нажми героя, глаз или ромб, чтобы посмотреть событие.':'Нет событий с координатами по выбранному фильтру.')+'</p><p class="micro-note">'+located.length+' из '+events.length+' событий показано'+(outside?' · вне диапазона: '+outside:'')+(missing?' · без координат: '+missing:'')+'. '+(configured?escapeText(config.label||'Карта по данным реплея'):'Фиксированная координатная схема ±10 000, без ландшафта.')+' Это не состояние видимости.</p>';
  const svg=target.querySelector('svg'),markers=[...svg.querySelectorAll('[data-ward-number]')],status=target.querySelector('.map-selection');
  const choose=i=>{const e=located[i];status.textContent='№'+e.mapNumber+' · '+clock(e.seconds)+' · '+label(e);if(e.event==='death')document.dispatchEvent(new CustomEvent('match-map-death',{detail:{id:e.deathId}}));markers.forEach((m,index)=>{m.setAttribute('aria-pressed',String(index===i));m.querySelector('.ward-marker-base').setAttribute('stroke',index===i?'#FFFFFF':color(located[index]));m.querySelector('.ward-marker-base').setAttribute('stroke-width',index===i?'3':'1.5');});};
  markers.forEach((m,i)=>{m.setAttribute('role','button');m.setAttribute('tabindex','0');m.setAttribute('aria-pressed','false');m.setAttribute('aria-label','Событие '+located[i].mapNumber+', '+clock(located[i].seconds)+', '+label(located[i]));m.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(i);}});});
  svg.addEventListener('pointerdown',e=>{const direct=e.target.closest('[data-ward-number]');if(direct){choose(markers.indexOf(direct));return;}const rect=svg.getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*340,py=(e.clientY-rect.top)/rect.height*340;let best=0,distance=Infinity;located.forEach((event,i)=>{const d=Math.hypot(px-x(event.x),py-y(event.y));if(d<distance){distance=d;best=i;}});if(located.length&&distance<=Math.max(28,22*340/rect.width))choose(best);});
 }

 const controls={wardTeam:document.getElementById('ward-team'),wardHero:document.getElementById('ward-hero')};
 const layers=[...document.querySelectorAll('[data-map-layer]')],savedLayers=state.searchParams.get('mapLayers');if(savedLayers!==null)layers.forEach(el=>el.checked=savedLayers.split(',').includes(el.dataset.mapLayer));else if(state.searchParams.get('wardKind'))layers.forEach(el=>el.checked=el.dataset.mapLayer===state.searchParams.get('wardKind'));
 layers.forEach(el=>el.addEventListener('change',()=>render(true)));
 Object.entries(controls).forEach(([key,el])=>{const value=state.searchParams.get(key);if([...el.options].some(o=>o.value===value))el.value=value;el.addEventListener('change',()=>render(true));});
 const saved=Number(state.searchParams.get('visionTime'));if(state.searchParams.has('visionTime')&&saved>=0&&saved<=data.duration)visionRange.value=saved;
 function render(update=false){const sec=Number(visionRange.value),enabled=new Set(layers.filter(el=>el.checked).map(el=>el.dataset.mapLayer)),team=controls.wardTeam.value,hero=controls.wardHero.value;const rows=data.events.filter(e=>e.seconds<=sec&&enabled.has(e.event==='death'?'deaths':e.event==='destroy'?'deward':e.kind)&&(team==='all'||e.team===team)&&(hero==='all'||e.steamId===hero));drawWardMap(rows);document.getElementById('vision-time-label').textContent=clock(sec);document.getElementById('ward-visible-count').textContent=rows.length;document.getElementById('vision-events').innerHTML=rows.map(e=>'<div class="event-row"><time>'+clock(e.seconds)+'</time><span><b>№'+e.mapNumber+' · '+(e.event==='death'?'Смерть':e.event==='destroy'?'Уничтожение':'Установка')+' · '+escapeText(e.event==='death'?'героя':e.kind)+'</b><small>'+escapeText(e.hero)+' · '+(e.team==='radiant'?'Radiant':'Dire')+'</small></span></div>').join('')||'<p class="empty">Событий по выбранному фильтру нет.</p>';if(update){const u=new URL(location.href);u.searchParams.set('visionTime',sec);u.searchParams.set('mapLayers',[...enabled].join(','));u.searchParams.delete('wardKind');u.searchParams.delete('wardEvent');Object.entries(controls).forEach(([key,el])=>{if(el.value==='all')u.searchParams.delete(key);else u.searchParams.set(key,el.value)});history.replaceState(null,'',u.pathname+u.search+u.hash);}}
 visionRange.addEventListener('input',()=>render(true));render();
 }
}
`;
