import {abilityLabel} from '../ability-labels.js';
import {heroName} from '../player-profile.js';
import type {MatchInsights} from '../match-insights.js';
import type {MatchEpisodes} from '../match-episodes.js';
import {heroImage} from './game-assets.js';
import {gameLabel} from './game-icon.js';
import {esc} from './render.js';
export function renderMatchDeaths(x:MatchInsights,episodes?:MatchEpisodes):string {
 const journal=x.heroDeathJournal;
 const verified=journal?.entries.filter(e=>e.status==='verified_death'&&e.victim!==null)??null;
 const recapIds=verified?new Set(verified.flatMap(e=>e.legacyDeathId?[e.legacyDeathId]:[])):null;
 const bySteam=new Map<string,number>();if(verified&&journal)for(const e of verified){const steam=journal.players[e.victim!]?.steamId;if(steam)bySteam.set(steam,(bySteam.get(steam)??0)+1);}
 const shown=(count:number)=>journal&&!journal.coverage.complete?(count?count+'+':'—'):String(count);
 const heroCount=(p:MatchInsights['players'][number])=>journal?shown(bySteam.get(p.steamId)??0):p.deaths===null?'—':String(p.deaths.length);
 const events=x.players.flatMap(p=>(p.deaths??[]).map((d,index)=>({...d,incoming:d.incoming?{...d.incoming,byAbility:d.incoming.byAbility.map(r=>({...r,label:abilityLabel(r.key)})),byAttacker:d.incoming.byAttacker.map(r=>({...r,label:heroName(r.key)}))}:null,id:p.steamId+':'+index,index,steamId:p.steamId,hero:p.heroLabel,team:p.team,image:heroImage(p.hero),episode:episodes?.episodes.find(e=>d.seconds>=e.startSeconds&&d.seconds<=e.endSeconds)?.id??null}))).filter(e=>recapIds===null||recapIds.has(e.id)).sort((a,b)=>a.seconds-b.seconds||a.id.localeCompare(b.id));
 const buybacks=x.players.flatMap(p=>(p.buybacks.events??[]).map(e=>({seconds:e.seconds,hero:p.heroLabel,steamId:p.steamId,team:p.team}))).sort((a,b)=>a.seconds-b.seconds);
 const teamSummary=(team:string)=>{const players=x.players.filter(p=>p.team===team),known=players.filter(p=>p.deaths!==null).length,count=journal?players.reduce((n,p)=>n+(bySteam.get(p.steamId)??0),0):players.reduce((n,p)=>n+(p.deaths?.length??0),0);return `<div class="${team}"><span>${team==='radiant'?'Radiant':'Dire'}</span><strong>${shown(count)}</strong><small>${journal?'подтверждённых смертей'+(journal.coverage.complete?'':' · неполное покрытие'):'событий смерти'+(known<players.length?' · неполный журнал':'')}</small></div>`;};
 const coverageNote=journal?`За весь матч · ${journal.coverage.verifiedDeaths} подтверждённых смертей, ${events.length} связанных разборов; ${Math.max(0,journal.coverage.verifiedDeaths-events.length)} без доступного разбора. Возвраты без смерти в D исключены: ${journal.coverage.reincarnations}.${journal.coverage.complete?'':' Покрытие неполное: числа с «+» — подтверждённый минимум, «—» — неизвестно.'}`:`За весь матч · журнал смертей, а не официальный счёт. Данные ${x.players.filter(p=>p.deaths!==null).length}/${x.players.length} героев.`;

 return `<div class="md-summary">${teamSummary('radiant')}${teamSummary('dire')}</div><p class="micro-note">${coverageNote}</p><div class="md-filters"><label>Команда<select class="data-select" id="death-team"><option value="all">Обе команды</option><option value="radiant">Radiant</option><option value="dire">Dire</option></select></label><label>Герой<select class="data-select" id="death-hero"><option value="all">Все герои</option>${x.players.map(p=>`<option value="${esc(p.steamId)}">${esc(p.heroLabel)}</option>`).join('')}</select></label></div><div class="md-roster" aria-label="Смерти героев за матч">${x.players.map(p=>`<button type="button" data-death-hero="${esc(p.steamId)}" class="${p.team}" aria-label="${esc(p.heroLabel)}: ${journal?heroCount(p)+' подтверждённых смертей':p.deaths===null?'журнал отсутствует':p.deaths.length+' событий смерти'}">${gameLabel(p.hero,p.heroLabel,'hero')}<strong>${heroCount(p)}</strong></button>`).join('')}</div><label class="control-label" for="match-death-time">События до <span id="match-death-time-label"></span></label><input class="chart-range" id="match-death-time" type="range" min="0" max="${x.durationSeconds}" value="${x.durationSeconds}"><div class="md-map" id="match-death-map"></div><p class="micro-note" id="match-death-coverage"></p><label class="control-label" for="match-death-event">Смерть в журнале</label><select class="data-select" id="match-death-event"></select><article class="md-detail" id="match-death-detail" aria-live="polite"></article><details class="fold"><summary>Выкупы за всю игру · ${buybacks.length}</summary><p class="micro-note">События выкупа подтверждены журналом ${x.players.filter(p=>p.buybacks.events!==null).length}/${x.players.length} героев. Фильтры карты на этот список не влияют.</p>${buybacks.map(e=>`<p><time>${Math.floor(e.seconds/60)}:${String(e.seconds%60).padStart(2,'0')}</time> · ${gameLabel(e.hero,e.hero,'hero')} · ${e.team==='radiant'?'Radiant':'Dire'}</p>`).join('')||'<p class="empty">Записанных событий нет.</p>'}</details><noscript><p>Для карты и фильтров нужен JavaScript.</p>${events.map(e=>`<p>${Math.floor(e.seconds/60)}:${String(e.seconds%60).padStart(2,'0')} · ${esc(e.hero)} · ${e.team}</p>`).join('')}</noscript><script type="application/json" id="match-deaths-data">${JSON.stringify({matchId:x.matchId,events,duration:x.durationSeconds}).replace(/</g,'\\u003c')}</script>`;
}
export const MATCH_DEATHS_CSS=`.map-death-details .md-filters,.map-death-details .md-roster,.map-death-details .md-map,.map-death-details #match-death-coverage,.map-death-details label[for=match-death-time],.map-death-details #match-death-time{display:none}.md-summary{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:20px 0}.md-summary>div{display:flex;flex-direction:column;gap:6px;padding:16px;background:var(--surface-2);border-radius:10px}.md-summary strong{font-size:36px}.md-summary small{font-size:11px;color:var(--muted)}.md-filters{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}.md-filters label{display:flex;flex-direction:column;gap:7px;font-size:12px;color:var(--muted);min-width:0}.md-filters select{width:100%;min-width:0}.md-roster{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:14px 0 20px}.md-roster button{display:flex;align-items:center;justify-content:space-between;gap:8px;text-align:left;min-height:44px;padding:8px;background:var(--surface-2);color:var(--ink);border:1px solid var(--line);border-radius:6px;font-size:11px;min-width:0}.md-roster button[aria-pressed=true]{border-color:var(--accent)}.md-roster .game-label{min-width:0}.md-roster .game-icon{width:32px;height:22px}.md-map{max-width:620px;margin:20px auto}.md-map svg{width:100%;display:block}.md-detail{background:var(--surface-2);padding:18px;border-radius:10px;margin:18px 0}.md-detail h3{margin-top:0;font-size:20px}.md-detail .game-label img{width:48px;height:28px}.md-source{display:flex;justify-content:space-between;gap:12px;margin:8px 0;font-size:13px}.md-source span{overflow-wrap:anywhere}.md-marker{cursor:pointer}.md-marker:focus{outline:none}.md-marker:focus circle{stroke:var(--ink);stroke-width:4px}@media(min-width:800px){.md-roster{grid-template-columns:repeat(5,1fr)}}`;
