export const MATCH_DEATHS_SCRIPT=`
{
 const node=document.getElementById('match-deaths-data');
 if(node){
 const data=JSON.parse(node.textContent),team=document.getElementById('death-team'),hero=document.getElementById('death-hero'),range=document.getElementById('match-death-time'),select=document.getElementById('match-death-event'),map=document.getElementById('match-death-map'),detail=document.getElementById('match-death-detail'),state=new URL(location.href);
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clock=s=>Math.floor(s/60)+':'+String(Math.floor(s)%60).padStart(2,'0'),num=n=>Math.round(n).toLocaleString('ru-RU');
 if(['radiant','dire'].includes(state.searchParams.get('deathTeam')))team.value=state.searchParams.get('deathTeam');
 const selectedHero=state.searchParams.get('deathHero')??(state.searchParams.has('death')?state.searchParams.get('player'):null);if([...hero.options].some(o=>o.value===selectedHero))hero.value=selectedHero;
 const savedTime=Number(state.searchParams.get('deathTime'));if(state.searchParams.has('deathTime')&&Number.isFinite(savedTime)&&savedTime>=0&&savedTime<=data.duration)range.value=savedTime;
 let current=state.searchParams.get('deathEvent')??(state.searchParams.has('death')&&selectedHero?selectedHero+':'+state.searchParams.get('death'):null),visible=[];
 const updateURL=()=>{const u=new URL(location.href);for(const [key,value]of [['deathTeam',team.value],['deathHero',hero.value],['deathTime',range.value],['deathEvent',current]]){if(value!==null)u.searchParams.set(key,value);else u.searchParams.delete(key);}u.hash='deaths';history.replaceState(null,'',u.pathname+u.search+u.hash);};
 function choose(update){const e=visible.find(e=>e.id===current);select.value=current??'';map.querySelectorAll('[data-death-id]').forEach(g=>{const active=g.dataset.deathId===current;g.setAttribute('aria-pressed',String(active));g.querySelector('circle').setAttribute('stroke',active?'var(--ink)':'var(--surface)');g.querySelector('circle').setAttribute('stroke-width',active?'4':'2');});if(!e){detail.innerHTML='<p class="empty">В выбранном отрезке событий нет.</p>';return;}
 const source=rows=>rows.slice(0,8).map(r=>'<div class="md-source"><span>'+escape(r.label??r.key)+'</span><strong>'+num(r.value)+'</strong></div>').join('');
 detail.innerHTML='<h3>'+clock(e.seconds)+' · '+escape(e.hero)+'</h3><p>'+ (e.team==='radiant'?'Radiant':'Dire')+(e.killer?' · Убийца в журнале: '+escape(e.killer):' · Убийца не записан')+'</p>'+(e.incoming?'<p><strong>'+num(e.incoming.total)+'</strong> входящего урона за '+e.incoming.windowSeconds+' секунд перед смертью</p>'+source(e.incoming.byAbility)+'<details class="fold"><summary>Кто наносил урон</summary>'+source(e.incoming.byAttacker)+'</details><p class="micro-note">'+(e.incoming.complete?'Буфер этого окна не усечён.':'Окно может быть неполным.')+' Включает наблюдаемые источники, в том числе существ и иллюзии.</p>':'<p class="micro-note">Разбивка урона перед смертью не сохранена.</p>')+(e.episode?'<a class="plain-button" href="?episode='+encodeURIComponent(e.episode)+'#episodes">Открыть эпизод обеих команд ↗</a>':'');if(update)updateURL();}
 function draw(update=false){visible=data.events.filter(e=>(team.value==='all'||e.team===team.value)&&(hero.value==='all'||e.steamId===hero.value)&&e.seconds<=Number(range.value));if(!visible.some(e=>e.id===current))current=visible.at(-1)?.id??null;
 document.getElementById('match-death-time-label').textContent=clock(Number(range.value));range.setAttribute('aria-valuetext','До '+clock(Number(range.value)));document.querySelectorAll('[data-death-hero]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.deathHero===hero.value)));
 select.innerHTML=visible.map(e=>'<option value="'+escape(e.id)+'">'+clock(e.seconds)+' · '+escape(e.hero)+' · '+(e.team==='radiant'?'Radiant':'Dire')+'</option>').join('');select.disabled=!visible.length;
 const config=JSON.parse(document.getElementById('match-insights-data').textContent).mapConfig,bounds=config??{xMin:-10000,xMax:10000,yMin:-10000,yMax:10000},x=v=>20+(v-bounds.xMin)/(bounds.xMax-bounds.xMin)*300,y=v=>320-(v-bounds.yMin)/(bounds.yMax-bounds.yMin)*300;
 const located=visible.filter(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)&&e.x>=bounds.xMin&&e.x<=bounds.xMax&&e.y>=bounds.yMin&&e.y<=bounds.yMax);
 const background=config?'<image href="'+escape(config.imageUrl)+'" x="20" y="20" width="300" height="300" preserveAspectRatio="none"/>':'<rect x="20" y="20" width="300" height="300" fill="var(--surface-2)" stroke="var(--line)"/><path d="M170 20V320M20 170H320" stroke="var(--line)" stroke-dasharray="3 5"/>';
 map.innerHTML='<svg viewBox="0 0 340 340" role="group" aria-label="Карта смертей обеих команд">'+background+located.map(e=>'<g class="md-marker" data-death-id="'+escape(e.id)+'" tabindex="0" role="button" aria-label="'+escape(clock(e.seconds)+' '+e.hero+' '+e.team)+'"><circle cx="'+x(e.x)+'" cy="'+y(e.y)+'" r="9" fill="'+(e.team==='radiant'?'var(--radiant)':'var(--dire)')+'" stroke="var(--surface)" stroke-width="2"/><text x="'+x(e.x)+'" y="'+(y(e.y)+4)+'" text-anchor="middle" font-size="12" font-weight="800" fill="#111">×</text></g>').join('')+'</svg>';
 document.getElementById('match-death-coverage').textContent=located.length+' из '+visible.length+' событий показаны на карте. Остальные доступны в списке.'+(config?' '+config.label:' Координатная схема без ландшафта.');
 map.querySelectorAll('[data-death-id]').forEach(g=>g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();current=g.dataset.deathId;choose(true);}}));map.querySelector('svg').addEventListener('pointerdown',e=>{const direct=e.target.closest('[data-death-id]');if(direct){current=direct.dataset.deathId;choose(true);return;}const r=e.currentTarget.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*340,py=(e.clientY-r.top)/r.height*340;let nearest=null,distance=Infinity;for(const event of located){const d=Math.hypot(px-x(event.x),py-y(event.y));if(d<distance){distance=d;nearest=event;}}if(nearest&&distance<=Math.max(28,22*340/r.width)){current=nearest.id;choose(true);}});choose(false);if(update)updateURL();
 }
 document.addEventListener('match-map-death',event=>{const found=data.events.find(e=>e.id===event.detail?.id);if(!found)return;team.value='all';hero.value='all';range.value=data.duration;current=found.id;draw(false);const fold=document.getElementById('deaths');fold.open=true;const u=new URL(location.href);u.searchParams.set('deathEvent',current);history.replaceState(null,'',u.pathname+u.search+u.hash);detail.scrollIntoView({block:'nearest',behavior:'smooth'});});
 team.addEventListener('change',()=>draw(true));hero.addEventListener('change',()=>draw(true));range.addEventListener('input',()=>draw(true));select.addEventListener('change',()=>{current=select.value;choose(true);});document.querySelectorAll('[data-death-hero]').forEach(b=>b.addEventListener('click',()=>{hero.value=hero.value===b.dataset.deathHero?'all':b.dataset.deathHero;team.value='all';draw(true);}));draw();
 }
}
`;
