import {playerAvatar} from "./player-avatar-render.js";
import {gameLabel} from "./game-icon.js";
import {buildMatchEpisodes} from "../match-episodes.js";
import {renderMatchEpisodes} from "./match-episode-render.js";
import {renderMatchOverview} from "./match-overview-render.js";
import {abilityLabel} from "../ability-labels.js";
import { buildMatchInsights, damageTypeLabel, goldReasonLabel, type MatchInsights, type MatchPlayerInsights, type BreakdownEntry } from "../match-insights.js";
import type { ParsedMatch } from "../replay.js";
import type { MatchApi, MatchApiPlayer } from "../opendota.js";
import { PLAYERS } from "../config.js";
import { HERO_CATALOG } from "../hero-catalog.js";
import { heroName } from "../player-profile.js";
import { esc } from "./render.js";
const number=(v:number|null|undefined)=>v===null||v===undefined?"—":Math.round(v).toLocaleString("ru-RU");
const clock=(s:number)=>`${Math.floor(s/60)}:${String(Math.floor(s)%60).padStart(2,"0")}`;
const label=(s:string)=>s==="unknown"?"Источник не указан":s==="unknown_or_attack"?"Атака / источник не указан":s.startsWith("illusion:")?"Иллюзия: "+heroName(s.slice(9)):s==="attack"?"Атаки":heroName(s)!==s?heroName(s):abilityLabel(s);
const account=(s:string)=>{try{const id=Number(BigInt(s)-76561197960265728n);return id>0?id:null;}catch{return null;}};
const name=(p:MatchPlayerInsights)=>PLAYERS.find(x=>x.steamId===account(p.steamId))?.dotaName??p.heroLabel;
const art=(hero:string)=>{const h=HERO_CATALOG.find(h=>h.localized_name===hero);return h?`https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${h.name.replace("npc_dota_hero_","")}.png`:"";};
const portrait=(p:MatchPlayerInsights)=>`<img src="${art(p.heroLabel)}" alt="" width="60" height="36" loading="lazy">`;
const missing=(s:string)=>`<p class="empty">${esc(s)}</p>`;
const fold=(title:string,body:string)=>`<details class="fold"><summary>${title}</summary><div class="fold-body">${body}</div></details>`;
function section(id:string,title:string,sub:string,body:string){return `<section class="panel insight-panel" id="${id}" aria-labelledby="${id}-title"><div class="section-head"><div><h2 id="${id}-title"><a href="#${id}">${title}</a></h2><p class="sub">${sub}</p></div><button type="button" class="share-section" data-share-section="${id}" aria-label="Скопировать ссылку на ${title}">↗</button></div>${body}</section>`;}
function breakdown(rows:BreakdownEntry[]|null,emptyText:string){
 if(rows===null)return missing(emptyText);
 if(!rows.length)return missing("В этом матче таких событий не зафиксировано.");
 const max=Math.max(...rows.map(r=>r.value),1);
 const row=(r:BreakdownEntry)=>`<div class="bar-row"><span>${gameLabel(r.key,label(r.key))}</span><b>${number(r.value)}</b><i style="width:${r.value/max*100}%"></i></div>`;
 return `<div class="stat-bars">${rows.slice(0,8).map(row).join("")}</div>`+(rows.length>8?fold(`Все источники (${rows.length})`,rows.slice(8).map(row).join("")):"");
}
function scoreboard(m:ParsedMatch,x:MatchInsights,api?:MatchApi,officialPlayers?:MatchApiPlayer[]){
 return ["radiant","dire"].map(team=>`<div class="score-team"><h3 class="team-title ${team}">${team==='radiant'?'Radiant':'Dire'} ${m.winner===team?'· ПОБЕДА':''}</h3><div class="score-grid">${x.players.filter(p=>p.team===team).map(p=>{
 const raw=m.players.find(q=>q.steam_id===p.steamId&&q.hero===p.hero)!;
 const id=account(p.steamId),official=(officialPlayers??(api?.match_id===m.match_id?api.players:[])).find(q=>HERO_CATALOG.find(h=>h.id===q.hero_id)?.localized_name===p.heroLabel&&(q.player_slot<128)===(p.team==="radiant")&&(!q.account_id||q.account_id===4294967295||id===null||q.account_id===id)),ours=PLAYERS.some(q=>q.steamId===id);
 return `<article class="score-player ${ours?'ours':''}"><a class="score-identity" href="/match/${m.match_id}?player=${esc(p.steamId)}#combat" data-select-player="${esc(p.steamId)}">${ours&&id?playerAvatar(id,name(p)):''}${portrait(p)}<span><strong>${esc(name(p))}</strong>${name(p)!==p.heroLabel?`<small>${esc(p.heroLabel)}</small>`:""}</span></a><div class="score-stats"><span><small>K / D / A</small><b>${official?`${official.kills} / ${official.deaths} / ${official.assists}`:'—'}</b></span><span><small>APM</small><b>${number(raw.actions_per_min)}</b></span><span><small>Имущество</small><b>${number(raw.networth_final)}</b></span><span><small>Добивания</small><b>${number(raw.last_hits)}</b></span></div></article>`;
 }).join("")}</div></div>`).join("")+`<p class="micro-note">KDA показывается из сохранённого ответа OpenDota. Остальные показатели — из реплея. Прочерк означает отсутствие измерения.</p>`;
}
function farm(x:MatchInsights){
 return `<label for="farm-metric" class="control-label">Что сравниваем</label><select id="farm-metric" class="data-select"><option value="networth">Стоимость имущества</option><option value="xp">Полученный опыт</option><option value="lastHits">Добивания</option><option value="denies">Денаи</option></select><div id="farm-chart" class="farm-chart"></div><label for="farm-minute" class="control-label">Минута <output id="farm-minute-label"></output></label><input id="farm-minute" type="range" min="1" max="${Math.max(1,Math.floor(x.durationSeconds/60))}" value="${Math.max(1,Math.floor(x.durationSeconds/60))}" class="chart-range"><div id="farm-values" class="farm-values"></div><p class="micro-note">Каждая линия — один герой. Нажми на имя под графиком, чтобы скрыть или вернуть его. Пропуски не заменяются нулями. Имущество включает предметы и золото; это не заработанное золото в минуту.</p>`;
}
function combat(p:MatchPlayerInsights,x:MatchInsights){
 const total=x.players.reduce((sum,q)=>sum+(q.damage.heroes??0),0);
 return `<div class="combat-metrics"><div><span>Урон героям</span><strong>${number(p.damage.heroes)}</strong></div><div><span>Получено урона</span><strong>${number(p.damage.received)}</strong></div><div><span>Урон зданиям</span><strong>${number(p.damage.buildings)}</strong></div></div><h3>Источники урона</h3>${breakdown(p.damage.byAbility,'Нужен новый разбор сохранённого реплея для подробностей урона.')}${fold('По целям',breakdown(p.damage.byTarget,'Цели урона ещё не разобраны.'))}${fold('Типы урона',breakdown(p.damage.byType?.map(r=>({...r,key:damageTypeLabel(r.key)}))??null,'Типы урона ещё не разобраны.'))}<h3>Кого лечил</h3><div class="combat-metrics"><div><span>Себя</span><strong>${number(p.healing.self)}</strong></div><div><span>Союзных героев</span><strong>${number(p.healing.allies)}</strong></div><div><span>Всего HEAL</span><strong>${number(p.healing.totalIncludingSelf)}</strong></div></div><p class="micro-note">Суммарное лечение включает себя и существ. Других героев: ${number(p.healing.otherHeroes)}; существ: ${number(p.healing.units)}. Самолечение не считается помощью союзникам.</p>${fold('Получатели лечения',breakdown(p.healing.byTarget,'Старый разбор хранит только общий HEAL. Разделить его без исходного реплея нельзя.'))}${fold('Источники лечения',breakdown(p.healing.byAbility,'Источники лечения ещё не разобраны.'))}<h3>Контроль</h3><p class="sub">Оглушение по официальной статистике: <b>${p.control.stunSeconds===null?'—':p.control.stunSeconds.toFixed(1)+' с'}</b></p>${p.control.observations?fold(`События контроля (${p.control.observations.length})`,p.control.observations.slice(0,100).map(c=>`<div class="event-row"><time>${clock(c.seconds)}</time><span><b>${esc(label(c.modifier))}</b><small>${esc(label(c.target))}${c.elapsed!==null?' · '+c.elapsed.toFixed(1)+' с':''}</small></span></div>`).join("")+`<p class="micro-note">Наблюдения эффектов могут пересекаться. Их длительности не складываются в «общий контроль».</p>`):missing('События контроля появятся после нового разбора реплея.')}<h3>Вклад всех игроков</h3>${breakdown(x.players.map(q=>({key:name(q)+(name(q)!==q.heroLabel?' · '+q.heroLabel:''),value:q.damage.heroes??0})).sort((a,b)=>b.value-a.value),'')}<p class="micro-note">Суммарный урон героям по участникам: ${number(total)}. Урон сам по себе не измеряет полезность роли.</p>`;
}
function vision(p:MatchPlayerInsights){
 const rows=p.vision.events;
 return `<div class="combat-metrics"><div><span>Куплено Observer</span><strong>${number(p.vision.observerPurchases)}</strong></div><div><span>Куплено Sentry</span><strong>${number(p.vision.sentryPurchases)}</strong></div><div><span>Уничтожено вардов</span><strong>${number(p.vision.wardsKilled)}</strong></div></div><div id="vision-map" class="event-map"></div><label class="control-label" for="vision-time">События до <output id="vision-time-label"></output></label><input id="vision-time" class="chart-range" type="range" min="0" max="3600" value="3600"><details class="fold"><summary>Журнал вардов · ${rows?.length??"—"}</summary><div id="vision-events">${rows?rows.map(e=>`<div class="event-row" data-event-time="${e.seconds}"><time>${clock(e.seconds)}</time><span>${e.event==='destroy'?'Уничтожение':e.event==='place'?'Установка':'Покупка'} · ${esc(e.kind)}</span></div>`).join("")||missing('Событий вардов у этого героя не зафиксировано.'):missing('Журнал вардов ещё не разобран.')}</div></details><p class="micro-note">Координаты покупки не считаются установкой. Карта показывает только события с известными координатами; отсутствие маркеров не означает отсутствие вардов на карте.</p>`;
}
function deaths(p:MatchPlayerInsights){
 const list=p.deaths;
 const detail=list?.map((e,i)=>`<div data-death="${i}" ${i?'hidden':''}><h3>${clock(e.seconds)} · ${e.killer?esc(label(e.killer)):"Источник смерти неизвестен"}</h3>${e.incoming?`<p class="sub">За ${e.incoming.windowSeconds} секунд перед смертью зафиксировано <b>${number(e.incoming.total)}</b> входящего урона.</p>${breakdown(e.incoming.byAbility,'Нет источников')}${fold('Кто наносил урон',breakdown(e.incoming.byAttacker,'Нет атакующих'))}<p class="micro-note">${e.incoming.complete?'Журнал не усечён внутренним лимитом.':'Часть событий могла быть усечена.'} Это зафиксированный урон в окне перед смертью, включая существ и иллюзии.</p>`:missing('Разбивка урона перед этой смертью ещё не восстановлена.')}</div>`).join('');
 return `${list?.length?`<label class="control-label" for="death-select">Выбрать смерть</label><select id="death-select" class="data-select">${list.map((e,i)=>`<option value="${i}">${clock(e.seconds)} · ${e.killer?esc(label(e.killer)):'смерть героя'}</option>`).join('')}</select>`:''}<div id="death-map" class="event-map"></div><div class="combat-metrics"><div><span>Потеряно золота</span><strong>${number(p.economy.goldLostToDeath)}</strong></div><div><span>Выкупы</span><strong>${number(p.buybacks.total)}</strong></div><div><span>Смертей в журнале</span><strong>${list?.length??'—'}</strong></div></div>${detail||(list===null?missing('Журнал смертей не сохранён.'):missing('Смертей в доступном журнале нет.'))}<h3>Кто убивал за матч</h3>${breakdown(p.killedBy,'Убийцы не сохранены.')}<h3>Выкупы по времени</h3>${p.buybacks.events===null?missing('Время выкупов ещё не разобрано.'):p.buybacks.events.map(e=>`<div class="event-row"><time>${clock(e.seconds)}</time><span>Выкуп</span></div>`).join('')||missing('Выкупов не зафиксировано.')}<p class="micro-note">События combat log могут отличаться от официального числа смертей. Карта схематична и не подменяет ландшафт текущего патча.</p>`;
}
function builds(m:ParsedMatch,p:MatchPlayerInsights){
 const raw=m.players.find(q=>q.steam_id===p.steamId&&q.hero===p.hero)!;
 const rows=(raw.item_timings??[]).map(i=>`<div class="event-row"><time>${clock(Math.round(i.min*60))}</time><span>${gameLabel(i.item,label(i.item),'item')}</span></div>`).join("");
 return `<p class="sub">Покупки ${esc(p.heroLabel)}. Время покупки, а не доставки или завершения сборки.</p>${rows||missing('Покупки не сохранены.')}<p class="micro-note">Предстартовые покупки и часть расходников могут отсутствовать. Список показывает наблюдаемые события, повторные покупки сохраняются.</p>`;
}
function events(p:MatchPlayerInsights,x:MatchInsights){
 const rows=[...(p.castLog??[]).map(e=>({seconds:e.seconds,type:e.ultimate?'ultimate':'cast',text:label(e.ability)+(e.target?' → '+label(e.target):'')})),...x.kills.map(e=>({seconds:e.seconds,type:'kill',text:e.killer+' → '+e.victim})),...x.buildings.map(e=>({seconds:e.seconds,type:'building',text:label(e.name)+' · '+e.team})),...x.roshans.map(e=>({seconds:e.seconds,type:'roshan',text:'Roshan'})),...(p.economy.goldEvents??[]).map(e=>({seconds:e.seconds,type:'gold',text:`${e.value>0?'+':''}${number(e.value)} золота · ${goldReasonLabel(e.reason)}`}))].sort((a,b)=>a.seconds-b.seconds);
 return `${fold('Командные сражения',x.teamfights.map(f=>`<div class="event-row"><time>${clock(f.startSeconds)}</time><span>Radiant −${f.radiantDeaths} / Dire −${f.direDeaths}<small>${esc(f.heroes.join(', '))}</small></span></div>`).join('')||missing('Сражения не выделены.'))}<label class="control-label" for="event-filter">Тип события</label><select id="event-filter" class="data-select"><option value="all">Все события</option><option value="ultimate">Ультимейты героя</option><option value="cast">Способности и предметы героя</option><option value="kill">Убийства на карте</option><option value="gold">Золото героя</option><option value="building">Строения</option><option value="roshan">Roshan</option></select><label class="control-label" for="event-search">Найти способность, героя или предмет</label><input id="event-search" class="data-select" type="search" placeholder="Например, black hole"><div class="event-count" id="event-count" role="status"></div><div id="combat-events"></div><button type="button" class="plain-button" id="more-events">Ещё 50 событий</button>${p.ultimates===null?'<p class="micro-note">В реплее нет надёжного признака ультимейта. Пустой фильтр не означает, что герой не применял ультимейт.</p>':p.detailCoverage?.ultimateClassificationComplete===false?'<p class="micro-note">Признак ультимейта записан не для всех применений. Журнал ультимейтов частичный.</p>':''}<p class="micro-note">Каст не означает попадание или успешное завершение. Тип Ultimate определяется по явному признаку реплея или зафиксированному каталогу игровых файлов. В нём вспомогательные кнопки вроде остановки ульта тоже могут иметь этот тип.</p><script type="application/json" id="combat-events-data">${JSON.stringify(rows).replace(/</g,'\u003c')}</script>`;
}
export function renderReplayInsights(m:ParsedMatch,steam?:string,api?:MatchApi,officialPlayers?:MatchApiPlayer[],episode?:string){
 const episodes=buildMatchEpisodes(m),x=buildMatchInsights(m),p=x.players.find(p=>p.steamId===steam)??x.players.find(p=>PLAYERS.some(q=>q.steamId===account(p.steamId)))??x.players[0];
 if(!p)return '';
 const picker=`<form class="player-picker" method="get" action="/match/${m.match_id}"><label for="match-player">Детальный разбор игрока</label><div><select id="match-player" name="player" class="data-select">${x.players.map(q=>`<option value="${esc(q.steamId)}" ${q===p?'selected':''}>${esc(name(q))} · ${esc(q.heroLabel)} · ${q.team}</option>`).join("")}</select><button type="submit" class="plain-button">Показать</button></div></form>`;
 const groups=[{key:'overview',title:'Обзор',sections:[['overview','Общий разбор'],['analysis','Комментарий бота']]},{key:'events',title:'События',sections:[['timeline','Ход игры'],['episodes','Эпизод подробно']]},{key:'teams',title:'Команды',sections:[['teams','Вклад'],['scoreboard','Составы и KDA'],['farm','Фарм']]},{key:'heroes',title:'Герои',sections:[['combat','Урон и лечение'],['vision','Варды'],['deaths','Смерти'],['builds','Предметы'],['events','Применения']]}];
 const nav=`<div class="match-navigation"><nav class="match-groups" aria-label="Основные разделы матча">${groups.map(g=>`<a href="#${g.sections[0][0]}" data-match-group="${g.key}">${g.title}</a>`).join('')}</nav><nav class="profile-jumps match-tabs match-subnav" aria-label="Подразделы матча">${groups.map(g=>g.sections.map(([id,title])=>`<a href="#${id}" data-section-group="${g.key}">${title}</a>`).join('')).join('')}</nav></div>`;

 return `${nav}${picker}<div class="match-insights">${renderMatchOverview(m,api,episodes)}${renderMatchEpisodes(m,episode,episodes)}${section('scoreboard','Итоги матча','Две команды. Все десять героев.',scoreboard(m,x,api,officialPlayers))}${section('farm','Фарм по минутам','Сравнение игроков на одном графике.',farm(x))}${section('combat','Урон, лечение и контроль',esc(name(p)+' · '+p.heroLabel),combat(p,x))}${section('vision','Варды и обзор',esc(p.heroLabel),vision(p))}${section('deaths','Смерти и выкупы',esc(p.heroLabel),deaths(p))}${section('builds','История предметов',esc(p.heroLabel),builds(m,p))}${section('events','Журнал героя и события карты',esc(p.heroLabel)+' · касты и золото выбранного героя.',events(p,x))}</div><div id="copy-status" class="copy-status" role="status"></div><script type="application/json" id="match-insights-data">${JSON.stringify({players:x.players.map(q=>({name:name(q),hero:q.heroLabel,steamId:q.steamId,team:q.team,economy:q.economy})),selected:p,duration:x.durationSeconds}).replace(/</g,'\u003c')}</script>`;
}
