/** Whole-match overview. Uses the existing light/dark design tokens. */
export const OVERVIEW_CSS = `
.match-commentary{margin:0 0 12px;border-bottom:1px solid var(--line);padding-bottom:12px;scroll-margin-top:var(--section-offset,120px)}.match-commentary>summary{list-style:none;cursor:pointer;min-height:44px}.match-commentary>summary::-webkit-details-marker{display:none}.match-commentary>summary>span{display:flex;justify-content:space-between;font-size:12px;font-weight:750;color:var(--accent)}.match-commentary>summary p{margin:6px 0 0;font-size:13px;line-height:1.5;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden}.match-commentary .card{margin:12px 0 0;padding:0;border:0;background:none}.commentary-full{padding-top:8px}.overview-story{margin-top:16px}

.ov-summary{padding-bottom:18px;margin-bottom:18px;border-bottom:1px solid var(--line);min-width:0}
.ov-kicker{margin:0 0 7px;color:var(--accent);font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
.ov-title,.ov-summary h3{margin:0 0 9px;font-size:25px;font-weight:750;line-height:1.25;letter-spacing:-.025em;overflow-wrap:anywhere}
.ov-summary p:not(.ov-kicker){font-size:14px;line-height:1.7;margin:8px 0 0;color:var(--muted);max-width:80ch}
.ov-summary strong{color:var(--ink);font-weight:650}
.ov-scoreline{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:18px;padding:18px;background:var(--surface-2);border:1px solid var(--line);border-radius:4px;margin:16px 0}
.ov-team{min-width:0;display:flex;flex-direction:column;gap:5px}.ov-team:last-child{text-align:right;align-items:flex-end}.ov-team strong{font-size:16px;font-weight:700;line-height:1.3}.ov-team small{font-size:12px;color:var(--muted);line-height:1.5}.ov-team.radiant strong{color:var(--radiant)}.ov-team.dire strong{color:var(--dire)}
.ov-score{text-align:center;font-size:34px;font-weight:750;line-height:1.2;font-variant-numeric:tabular-nums;letter-spacing:-.03em;white-space:nowrap}.ov-score small,.ov-duration{display:block;color:var(--muted);font-size:12px;font-weight:500;letter-spacing:0;line-height:1.5;margin-top:5px}.ov-team-heroes{display:flex;gap:4px;flex-wrap:wrap}.ov-team-heroes img{display:block;width:34px;height:21px;object-fit:cover;border-radius:2px}
.ov-evidence-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:18px 0}
.ov-evidence{min-width:0;position:relative;padding:15px;background:var(--surface-2);border:1px solid var(--line);border-radius:4px;border-top:2px solid var(--accent)}
.ov-label,.ov-evidence>small{display:block;color:var(--muted);font-size:12px;line-height:1.5;margin:0 0 6px}.ov-value,.ov-evidence>strong{display:block;font-size:27px;font-weight:750;letter-spacing:-.025em;line-height:1.25;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.ov-evidence p{font-size:13px;line-height:1.65;margin:8px 0 0;color:var(--muted)}.ov-evidence p strong{color:var(--ink);font-weight:650}.ov-evidence a{display:inline-flex;align-items:center;gap:5px;min-height:44px;font-size:12px;color:var(--accent);text-decoration:none;margin-top:3px}.ov-evidence a:hover{text-decoration:underline}.ov-evidence .ov-sample{font-size:11px;color:var(--muted);line-height:1.55;margin-top:8px}
.ov-grid{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr);gap:22px;align-items:start;margin:22px 0}.ov-grid>*{min-width:0}
.ov-section-head{display:flex;justify-content:space-between;align-items:baseline;gap:12px;margin:0 0 12px;padding-bottom:10px;border-bottom:1px solid var(--line)}.ov-section-head h3{margin:0;font-size:18px;line-height:1.4;letter-spacing:-.015em}.ov-section-head small{font-size:11px;line-height:1.5;color:var(--muted);text-align:right}.ov-section-head>a{min-height:44px;display:inline-flex;align-items:center;color:var(--accent);font-size:12px;text-decoration:none}
.ov-note{font-size:12px;line-height:1.65;color:var(--muted);margin:10px 0}.ov-note strong{color:var(--ink);font-weight:650}
.ov-curve{min-width:0;margin:14px 0}.ov-curve svg{display:block;width:100%;height:auto;overflow:visible}.ov-curve text{fill:var(--muted);font-size:14px}.ov-curve .zero-line{stroke:var(--muted);stroke-dasharray:4 4;opacity:.6}.ov-curve-key{display:flex;gap:12px;flex-wrap:wrap;font-size:12px;color:var(--muted);margin:10px 0}.ov-curve-key>span{display:inline-flex;align-items:center;gap:6px}.ov-curve-key i{display:inline-block;width:8px;height:8px;border-radius:50%}.ov-curve-key .radiant{background:var(--radiant)}.ov-curve-key .dire{background:var(--dire)}
.ov-compare{display:flex;flex-direction:column;gap:0}.ov-compare-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:6px 15px;align-items:baseline;padding:12px 0;border-bottom:1px solid var(--line);font-size:13px}.ov-compare-row:last-child{border-bottom:0}.ov-compare-label{color:var(--muted);font-size:12px;line-height:1.5;min-width:0;overflow-wrap:anywhere}.ov-compare-row b,.ov-compare-row strong{font-size:15px;font-variant-numeric:tabular-nums;white-space:nowrap}.ov-compare-row .radiant{color:var(--radiant)}.ov-compare-row .dire{color:var(--dire)}.ov-compare-bar{grid-column:1/-1;display:flex;gap:3px;height:5px;background:var(--ground);border-radius:2px;overflow:hidden;margin-top:2px}.ov-compare-bar>i{display:block;min-width:0;height:100%;background:var(--radiant)}.ov-compare-bar>i:last-child{background:var(--dire)}.ov-compare-row>.ov-note{grid-column:1/-1;margin:2px 0 0;font-size:11px}
.ov-events{display:flex;flex-direction:column;gap:0;list-style:none;margin:0;padding:0}.ov-event{display:grid;grid-template-columns:48px minmax(0,1fr);gap:12px;padding:13px 0;border-bottom:1px solid var(--line);position:relative}.ov-event:last-child{border-bottom:0}.ov-event time{font-size:12px;font-variant-numeric:tabular-nums;color:var(--accent);line-height:1.6;white-space:nowrap}.ov-event>div,.ov-event>span{min-width:0;overflow-wrap:anywhere}.ov-event strong{font-size:14px;font-weight:650;line-height:1.45}.ov-event p,.ov-event small{display:block;font-size:12px;line-height:1.65;color:var(--muted);margin:4px 0 0}.ov-event a{display:inline-flex;align-items:center;min-height:44px;color:var(--accent);font-size:12px;text-decoration:none}.ov-event-marker{width:6px;height:6px;border-radius:50%;background:var(--accent);display:inline-block;margin-right:6px}
.ov-empty{padding:16px;border:1px dashed var(--line);border-radius:4px;font-size:13px;line-height:1.65;color:var(--muted);background:var(--surface-2)}
@media(max-width:800px){.ov-grid{grid-template-columns:1fr;gap:20px}.ov-scoreline{gap:12px}.ov-evidence-grid{gap:8px}.ov-evidence{padding:13px}}
@media(max-width:480px){.ov-summary{padding-bottom:15px;margin-bottom:15px}.ov-title,.ov-summary h3{font-size:22px}.ov-summary p:not(.ov-kicker){font-size:13px;line-height:1.65}.ov-scoreline{padding:13px 11px;gap:10px;margin:14px 0}.ov-team strong{font-size:14px}.ov-team small{font-size:11px}.ov-score{font-size:29px}.ov-duration,.ov-score small{font-size:11px}.ov-team-heroes img{width:28px;height:18px}.ov-team-heroes{gap:3px}.ov-evidence-grid{grid-template-columns:1fr;margin:15px 0;gap:8px}.ov-evidence{padding:13px}.ov-value,.ov-evidence>strong{font-size:25px}.ov-label,.ov-evidence>small{font-size:12px}.ov-evidence p{font-size:12px}.ov-grid{margin:18px 0;gap:20px}.ov-section-head{gap:8px;align-items:flex-start}.ov-section-head h3{font-size:17px}.ov-curve text{font-size:22px}.ov-compare-row{gap:6px 12px;font-size:12px}.ov-compare-row b,.ov-compare-row strong{font-size:14px}.ov-event{grid-template-columns:42px minmax(0,1fr);gap:9px;padding:12px 0}.ov-event strong{font-size:13px}.ov-note{font-size:12px}}
@media(min-width:360px) and (max-width:480px){.ov-evidence-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ov-evidence-grid>.ov-evidence:last-child:nth-child(odd){grid-column:1/-1}}
.match-tabs a[href="#combat"]{border-left:1px solid var(--line);margin-left:8px;padding-left:18px}
.ov-summary h3,.ov-evidence h3,.ov-event h3,#teams .ov-team h3{text-transform:none;letter-spacing:-.015em}
.ov-scoreline>.ov-team{font-size:12px;color:var(--muted)}.ov-scoreline>.ov-team strong{font-size:32px;line-height:1.1;font-variant-numeric:tabular-nums}.ov-scoreline>.ov-duration{text-align:center;font-size:16px;color:var(--ink);margin:0}.ov-scoreline>.ov-duration small{display:block;font-size:10px;line-height:1.4;color:var(--muted);margin-top:5px}
/* Renderer-specific controls, contributions and expandable moments. */
.ov-evidence h3{font-size:16px;line-height:1.4;margin:0;letter-spacing:-.015em;overflow-wrap:anywhere}
.ov-section-head:has(#overview-metric){display:grid;grid-template-columns:minmax(0,1fr) 220px;align-items:center}.ov-section-head:has(#overview-metric) h3{grid-column:1;grid-row:1/3}.ov-section-head:has(#overview-metric) label{grid-column:2;margin:0}.ov-section-head #overview-metric{grid-column:2;width:100%;min-width:0}
.ov-section-head:has(>.ov-note){display:block}.ov-section-head>.ov-note{margin:7px 0 0;max-width:80ch}.ov-chart-reading{font-size:15px;line-height:1.6;font-variant-numeric:tabular-nums;min-height:48px;margin:10px 0}
.ov-events>.ov-event:not(details){grid-template-columns:95px minmax(0,1fr)}.ov-event h3{margin:0;font-size:15px;line-height:1.45}.ov-event ul{padding-left:17px;margin:9px 0;font-size:12px;line-height:1.7;color:var(--muted)}
.ov-moment{display:block;padding:0;scroll-margin-top:80px}.ov-moment>summary{display:grid;grid-template-columns:95px minmax(0,1fr) 16px;gap:10px;align-items:center;min-height:58px;padding:12px 0;cursor:pointer;list-style:none;font-size:14px;line-height:1.5;font-weight:600}.ov-moment>summary::-webkit-details-marker{display:none}.ov-moment>summary::after{content:'+';font-size:20px;color:var(--accent);text-align:center}.ov-moment[open]>summary::after{content:'−'}.ov-moment>summary:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.ov-moment>summary time{font-weight:500}.ov-event-body{padding:0 0 15px 105px}.ov-event-actions{display:flex;gap:8px 18px;flex-wrap:wrap;align-items:center;margin-top:10px}.ov-event-actions .share-section{flex:none}.ov-kill{padding:5px 0;border-bottom:1px solid var(--line)}.ov-kill time{margin-right:6px}
#teams .ov-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}#teams .ov-team:last-child{align-items:stretch;text-align:left}#teams .ov-team h3{margin:0;display:flex;justify-content:space-between;gap:12px;font-size:17px}#teams .ov-team h3 strong{font-size:20px}#teams .ov-team h3.radiant{color:var(--radiant)}#teams .ov-team h3.dire{color:var(--dire)}#teams .ov-team>.ov-note{margin:1px 0 7px}#teams [data-team-metric]>h3{font-size:17px;margin:20px 0 0}
.ov-player{display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:10px;align-items:center;position:relative;padding:12px 0 15px;min-height:64px;text-decoration:none;color:var(--ink);border-bottom:1px solid var(--line)}.ov-player img{width:48px;height:28px;object-fit:cover;border-radius:2px}.ov-player>span{font-size:13px;line-height:1.4;min-width:0;overflow-wrap:anywhere}.ov-player small{display:block;font-size:11px;margin-top:2px;color:var(--muted)}.ov-player>strong{font-size:15px!important;font-variant-numeric:tabular-nums;white-space:nowrap}.ov-player>i{position:absolute;bottom:4px;left:0;height:3px;background:var(--radiant);border-radius:2px;max-width:100%}.ov-team:last-child .ov-player>i{background:var(--dire)}.ov-player:hover>span{text-decoration:underline}.ov-player:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
@media(max-width:600px){#teams .ov-grid{grid-template-columns:1fr;gap:24px}.ov-section-head:has(#overview-metric){grid-template-columns:1fr;gap:8px}.ov-section-head:has(#overview-metric) h3{grid-column:1;grid-row:auto;margin-bottom:4px}.ov-section-head:has(#overview-metric) label,.ov-section-head #overview-metric{grid-column:1}.ov-events>.ov-event:not(details){grid-template-columns:1fr;gap:5px}.ov-moment>summary{grid-template-columns:minmax(0,1fr) 16px;gap:4px 8px;font-size:13px}.ov-moment>summary time{grid-column:1}.ov-moment>summary span{grid-column:1}.ov-moment>summary::after{grid-column:2;grid-row:1/3}.ov-event-body{padding-left:0}.ov-moment{scroll-margin-top:72px}.ov-evidence h3{font-size:14px}.ov-chart-reading{font-size:13px}}
`;
