export const VISION_SCRIPT=`
{
 const node=document.getElementById('match-vision-data');if(node){
 const data=JSON.parse(node.textContent);const deathData=JSON.parse(document.getElementById('match-deaths-data')?.textContent||'{"events":[]}');data.events=[...data.events,...deathData.events.map((e,i)=>({...e,event:'death',kind:'death',deathId:e.id,mapNumber:'D'+(i+1)}))].sort((a,b)=>a.seconds-b.seconds);const state=new URL(location.href),visionRange=document.getElementById('vision-time');
 const escapeText=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const mapDialog=document.getElementById('map-dialog'),mapCanvas=document.getElementById('vision-map'),mapExpand=document.getElementById('map-expand'),mapLayers=document.getElementById('map-layer-controls'),mapTime=document.querySelector('.map-time-controls');let previousBodyOverflow='';
 function closeLargeMap(){if(!mapDialog.open)return;document.getElementById('map-inline-slot').append(mapCanvas);document.getElementById('map-layers-inline').append(mapLayers);document.getElementById('map-time-inline').append(mapTime);mapDialog.close();document.body.style.overflow=previousBodyOverflow;mapExpand.focus({preventScroll:true});}
 mapExpand.addEventListener('click',()=>{previousBodyOverflow=document.body.style.overflow;document.getElementById('map-dialog-slot').append(mapCanvas);document.getElementById('map-dialog-layers').append(mapLayers);document.getElementById('map-dialog-time').append(mapTime);mapDialog.showModal();document.body.style.overflow='hidden';document.getElementById('map-close').focus();});
 document.getElementById('map-close').addEventListener('click',closeLargeMap);mapDialog.addEventListener('cancel',e=>{e.preventDefault();closeLargeMap();});window.addEventListener('hashchange',closeLargeMap);
 const clock=s=>(s<0?'−':'')+Math.floor(Math.abs(s)/60)+':'+String(Math.floor(Math.abs(s))%60).padStart(2,'0');
 const teamLabel=t=>t==='radiant'?'Radiant':t==='dire'?'Dire':'Команда неизвестна';
 const eventLabel=e=>e.life?'Наблюдавшийся вард':e.event==='death'?'Смерть':e.event==='place'?'Установка':e.destroyKind==='enemy_deward'?'Девардинг':e.destroyKind==='allied_deny'?'Добивание союзного варда':'Уничтожение (тип неизвестен)';
 const sourceNote=e=>(e.sourceControlled?' · управляемый юнит':'')+(e.sourceIllusion?' · иллюзия':'')+(e.targetTeam?' · вард '+teamLabel(e.targetTeam):'');
 let selectedWardId=state.searchParams.get('wardId');
 const preciseClock=s=>(s<0?'−':'')+Math.floor(Math.abs(s)/60)+':'+(Math.abs(s)%60).toFixed(2).padStart(5,'0');
 const lifetimeCard=e=>{const l=e.life,k=l.killer,end=l.endReason==='death-observed'?'Смерть зафиксирована '+clock(l.deathSeconds):l.endReason==='replay-end'?'Существовал в конце матча':l.endReason==='observation-lost'?'Наблюдение потеряно':'Конец не установлен';return '<div class="ward-lifetime-card"><strong>'+escapeText(l.kind==='observer'?'Observer':'Sentry')+' · '+escapeText(l.ownerLabel||'Владелец неизвестен')+'</strong><span>'+teamLabel(l.team)+' · '+(l.placedSeconds!==null?'Появился '+clock(l.placedSeconds):'Впервые записан '+clock(l.firstObservedSeconds))+'</span><span>'+end+'</span><span>Наблюдался '+(l.observedDurationSeconds===null?'—':clock(l.observedDurationSeconds))+'</span>'+(k?'<span>Уничтожил '+escapeText(k.label)+(k.controlled?' · управляемый юнит':'')+(k.illusion?' · иллюзия':'')+'</span>':'')+'<details class="ward-provenance"><summary>Как определено</summary><p>Последняя запись сущности: '+preciseClock(l.lastObservedSeconds)+'.</p><p>Интервал подтверждён наблюдениями сущности варда. За пределами интервала его существование не предполагается.</p>'+(l.deathWindow?'<p>Переход к смерти записан между '+preciseClock(l.deathWindow.from)+' и '+preciseClock(l.deathWindow.to)+'.</p>':'')+(k?'<p>Уничтожитель найден однозначно: совпали владелец, тип и команда варда, а также последняя запись урона в окне смерти ('+preciseClock(k.seconds)+').</p>':'<p>Однозначного сопоставления уничтожителя нет.</p>')+'</details></div>';};
 function drawWardMap(events){
  const target=document.getElementById('vision-map'),config=data.mapConfig??JSON.parse(document.getElementById('match-insights-data')?.textContent||'{}').mapConfig;
  const configured=config&&typeof config.imageUrl==='string'&&(/^(?:https:\\/\\/|\\/[^\\/])/.test(config.imageUrl))&&[config.xMin,config.xMax,config.yMin,config.yMax].every(Number.isFinite)&&config.xMax>config.xMin&&config.yMax>config.yMin;
  const bounds=configured?config:{xMin:-10000,xMax:10000,yMin:-10000,yMax:10000};
  const positioned=events.filter(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)),located=positioned.filter(e=>e.x>=bounds.xMin&&e.x<=bounds.xMax&&e.y>=bounds.yMin&&e.y<=bounds.yMax),outside=positioned.length-located.length,missing=events.length-positioned.length;
  const x=v=>20+(v-bounds.xMin)/(bounds.xMax-bounds.xMin)*300,y=v=>320-(v-bounds.yMin)/(bounds.yMax-bounds.yMin)*300;
  const kind=e=>e.kind==='death'?'героя':e.kind==='observer'?'Observer':e.kind==='sentry'?'Sentry':'Вард неизвестного типа',label=e=>eventLabel(e)+' · '+kind(e)+' · '+e.hero+' · '+teamLabel(e.team)+sourceNote(e),color=e=>e.event==='death'?(e.team==='radiant'?'#83C998':'#FF8A7E'):e.kind==='observer'?'#FFD166':e.kind==='sentry'?'#68C8FF':'#D0D6DF';
  const background=configured?'<image href="'+escapeText(config.imageUrl)+'" x="20" y="20" width="300" height="300" preserveAspectRatio="none"/>':'<rect x="20" y="20" width="300" height="300" fill="var(--surface-2)" stroke="var(--line)"/>'+[95,170,245].map(v=>'<path d="M'+v+' 20V320M20 '+v+'H320" stroke="var(--line)" stroke-dasharray="3 5"/>').join('');
  const symbol=e=>e.event==='death'?(e.image?'<image href="'+escapeText(e.image)+'" x="-10" y="-10" width="20" height="20"/><path d="M5 5L13 13M5 13L13 5" stroke="#17212B" stroke-width="5"/><path d="M5 5L13 13M5 13L13 5" stroke="#FFFFFF" stroke-width="2"/>':'<path d="M-7-7L7 7M-7 7L7-7"/>'):e.kind==='observer'?'<path d="M-9 0Q0-11 9 0Q0 11-9 0Z"/><circle r="3"/>':e.kind==='sentry'?'<path d="M0-10L10 0L0 10L-10 0Z"/><path d="M-5 0H5M0-5V5"/>':'<circle r="7"/><path d="M0-4V2M0 5V6"/>';
  target.innerHTML='<svg viewBox="0 0 340 340" role="group" aria-label="'+(configured?'Карта смертей и вардов':'Координатная схема смертей и вардов')+'">'+background+located.map(e=>'<g data-ward-number="'+e.mapNumber+'" transform="translate('+x(e.x)+' '+y(e.y)+')"><circle class="ward-marker-base" r="14" fill="#17212B" fill-opacity=".94" stroke="'+color(e)+'" stroke-width="1.5"/><g fill="none" stroke="'+color(e)+'" stroke-width="2" pointer-events="none">'+symbol(e)+'</g>'+(e.event==='destroy'?'<path d="M-11 11L11-11" stroke="#17212B" stroke-width="6" pointer-events="none"/><path d="M-11 11L11-11" stroke="#FFFFFF" stroke-width="2.5" pointer-events="none"/>':'')+'<g class="ward-marker-number"><circle cx="12" cy="-12" r="8" fill="#17212B" pointer-events="none"/><text x="12" y="-8.5" text-anchor="middle" fill="#FFFFFF" style="font-size:10px;font-weight:700" pointer-events="none">'+e.mapNumber+'</text></g></g>').join('')+'</svg><div class="map-selection" role="status">'+(located.length?(mapMode==='wards'?'Нажми вард, чтобы открыть его наблюдаемый интервал.':'Нажми героя, глаз или ромб, чтобы посмотреть событие.'):(mapMode==='wards'?'Нет подтверждённых вардов с координатами на этой минуте.':'Нет событий с координатами по выбранному фильтру.'))+'</div><p class="micro-note">'+located.length+' из '+events.length+(mapMode==='wards'?' вардов подтверждено на этой минуте':' событий показано')+(outside?' · вне диапазона: '+outside:'')+(missing?' · без координат: '+missing:'')+'. '+(configured?escapeText(config.label||'Карта по данным реплея'):'Фиксированная координатная схема ±10 000, без ландшафта.')+' Это не состояние видимости.</p>';
  const svg=target.querySelector('svg'),markers=[...svg.querySelectorAll('[data-ward-number]')],status=target.querySelector('.map-selection');
  const choose=(i,save=true)=>{const e=located[i];if(e.life){status.setAttribute('role','group');status.setAttribute('aria-label','Выбранный вард');status.setAttribute('aria-live','off');status.innerHTML=lifetimeCard(e);if(save){selectedWardId=e.life.id;const u=new URL(location.href);u.searchParams.set('wardId',selectedWardId);history.replaceState(null,'',u.pathname+u.search+u.hash);}}else status.textContent='№'+e.mapNumber+' · '+clock(e.seconds)+' · '+label(e);if(e.event==='death'){closeLargeMap();document.dispatchEvent(new CustomEvent('match-map-death',{detail:{id:e.deathId}}));}markers.forEach((m,index)=>{m.setAttribute('aria-pressed',String(index===i));m.querySelector('.ward-marker-base').setAttribute('stroke',index===i?'#FFFFFF':color(located[index]));m.querySelector('.ward-marker-base').setAttribute('stroke-width',index===i?'3':'1.5');});};
    markers.forEach((m,i)=>{m.setAttribute('role','button');m.setAttribute('tabindex','0');m.setAttribute('aria-pressed','false');m.setAttribute('aria-label','Событие '+located[i].mapNumber+', '+clock(located[i].seconds)+', '+label(located[i]));m.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(i);}});});
  const selectedIndex=located.findIndex(e=>e.life?.id===selectedWardId);if(selectedIndex>=0)choose(selectedIndex,false);
  svg.addEventListener('pointerdown',e=>{const direct=e.target.closest('[data-ward-number]');if(direct){choose(markers.indexOf(direct));return;}const rect=svg.getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*340,py=(e.clientY-rect.top)/rect.height*340;let best=0,distance=Infinity;located.forEach((event,i)=>{const d=Math.hypot(px-x(event.x),py-y(event.y));if(d<distance){distance=d;best=i;}});if(located.length&&distance<=Math.max(28,22*340/rect.width))choose(best);});
 }

 const controls={wardTeam:document.getElementById('ward-team'),wardHero:document.getElementById('ward-hero')};
 const layers=[...document.querySelectorAll('[data-map-layer]')],savedLayers=state.searchParams.get('mapLayers');if(savedLayers!==null)layers.forEach(el=>el.checked=savedLayers.split(',').includes(el.dataset.mapLayer));else if(state.searchParams.get('wardKind'))layers.forEach(el=>el.checked=el.dataset.mapLayer===state.searchParams.get('wardKind'));
 layers.forEach(el=>el.addEventListener('change',()=>render(true)));
 Object.entries(controls).forEach(([key,el])=>{const value=state.searchParams.get(key);if([...el.options].some(o=>o.value===value))el.value=value;el.addEventListener('change',()=>render(true));});
 const windowPicker=document.getElementById('map-window'),savedWindow=state.searchParams.get('mapWindow');if(['120','300'].includes(savedWindow))windowPicker.value=savedWindow;windowPicker.addEventListener('change',()=>render(true));
 const modeButtons=[...document.querySelectorAll('[data-map-mode]')];let mapMode=data.lifetimes&&state.searchParams.get('mapMode')==='wards'?'wards':'history';modeButtons.forEach(b=>b.addEventListener('click',()=>{mapMode=b.dataset.mapMode;render(true);}));
 const saved=Number(state.searchParams.get('visionTime'));if(state.searchParams.has('visionTime')&&saved>=Number(visionRange.min)&&saved<=data.duration)visionRange.value=saved;
 function render(update=false){const sec=Math.min(Number(visionRange.value),data.duration),enabled=new Set(layers.filter(el=>el.checked).map(el=>el.dataset.mapLayer)),team=controls.wardTeam.value,hero=controls.wardHero.value,live=mapMode==='wards';
 document.getElementById('map-explanation').textContent=live?'Варды с подтверждённым интервалом существования на выбранной минуте. Это не обзор и не туман войны.':'Смерти и варды в выбранном периоде до указанного времени. Это история событий, а не живые варды или текущая видимость.';modeButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mapMode===mapMode)));layers.forEach(el=>el.closest('label').hidden=live&&['deaths','deward'].includes(el.dataset.mapLayer));windowPicker.closest('label').hidden=live;
 const lower=windowPicker.value==='all'?-Infinity:sec-Number(windowPicker.value),eligible=(e)=>(team==='all'||e.team===team)&&(hero==='all'||e.steamId===hero);
 const rows=live?(data.lifetimes?.entries||[]).filter(l=>Number.isFinite(l.knownFromSeconds)&&Number.isFinite(l.knownUntilSeconds)&&l.knownFromSeconds<=sec&&sec<=l.knownUntilSeconds&&enabled.has(l.kind)).map((l,i)=>({life:l,event:'place',kind:l.kind,seconds:l.firstObservedSeconds,hero:l.ownerLabel||'Владелец неизвестен',steamId:l.ownerSteamId||'',team:l.team||'unknown',x:l.position?.x??null,y:l.position?.y??null,mapNumber:'L'+(data.lifetimes.entries.indexOf(l)+1)})).filter(eligible):data.events.filter(e=>e.seconds<=sec&&e.seconds>=lower&&enabled.has(e.event==='death'?'deaths':e.event==='destroy'?'deward':e.kind)&&eligible(e));
 drawWardMap(rows);document.getElementById('vision-time-label').textContent=clock(sec);document.getElementById('ward-visible-count').textContent=rows.length;
 const coverage=live?'<p class="micro-note">Подтверждённые интервалы: '+data.lifetimes.coverage.knownIntervals+' / '+data.lifetimes.coverage.stored+'. Неизвестный конец: '+data.lifetimes.coverage.unknownEnds+'. Пропущено при сохранении: '+data.lifetimes.coverage.dropped+'. Это наблюдения реплея, не обзор и не туман войны.</p>':'';
 document.getElementById('vision-events').innerHTML=coverage+(rows.map(e=>e.life?lifetimeCard(e):'<div class="event-row"><time>'+clock(e.seconds)+'</time><span><b>№'+e.mapNumber+' · '+eventLabel(e)+' · '+escapeText(e.event==='death'?'героя':e.kind)+'</b><small>'+escapeText(e.hero)+' · '+teamLabel(e.team)+escapeText(sourceNote(e))+'</small></span></div>').join('')||'<p class="empty">По выбранному фильтру записей нет.</p>');
 if(live){const note=document.querySelector('#vision-map .micro-note');note.textContent+=' Подтверждённые интервалы '+data.lifetimes.coverage.knownIntervals+'/'+data.lifetimes.coverage.stored+'; неизвестный конец '+data.lifetimes.coverage.unknownEnds+'.';}
 if(update){const u=new URL(location.href);u.searchParams.set('visionTime',sec);if(live)u.searchParams.set('mapMode','wards');else u.searchParams.delete('mapMode');if(windowPicker.value==='all')u.searchParams.delete('mapWindow');else u.searchParams.set('mapWindow',windowPicker.value);u.searchParams.set('mapLayers',[...enabled].join(','));u.searchParams.delete('wardKind');u.searchParams.delete('wardEvent');Object.entries(controls).forEach(([key,el])=>{if(el.value==='all')u.searchParams.delete(key);else u.searchParams.set(key,el.value)});history.replaceState(null,'',u.pathname+u.search+u.hash);}}

 visionRange.addEventListener('input',()=>render(true));render();
 }
}
`;
