export const MATCH_SCRIPT = `
const insightNode=document.getElementById('match-insights-data');
if(insightNode){
 const data=JSON.parse(insightNode.textContent),selected=data.selected;
 const panels=[...document.querySelectorAll('.match-insights>.insight-panel,#analysis')];
 const groupSections={overview:['overview','analysis'],events:['timeline','episodes'],teams:['teams','scoreboard','farm'],heroes:['combat','vision','deaths','builds','events']},lastSections={overview:'overview',events:'timeline',teams:'teams',heroes:'combat'};
 function showMatchSection(){let target;try{target=document.getElementById(decodeURIComponent(location.hash.slice(1)));}catch{}const active=target?.closest('.insight-panel')||panels[0];panels.forEach(panel=>panel.hidden=panel!==active);const group=Object.keys(groupSections).find(g=>groupSections[g].includes(active.id))||'overview';lastSections[group]=active.id;document.querySelectorAll('[data-section-group]').forEach(a=>a.hidden=a.dataset.sectionGroup!==group);document.querySelectorAll('[data-match-group]').forEach(a=>{a.href='#'+lastSections[a.dataset.matchGroup];if(a.dataset.matchGroup===group)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});document.querySelector('.player-picker').hidden=!['combat','vision','deaths','builds','events'].includes(active.id);const navigation=document.querySelector('.match-navigation');if(navigation)document.documentElement.style.setProperty('--section-offset',(navigation.offsetHeight+14)+'px');if(typeof updateJump==='function')updateJump();}
 addEventListener('hashchange',showMatchSection);addEventListener('resize',showMatchSection);showMatchSection();
 const escapeText=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const fmt=n=>Math.round(n).toLocaleString('ru-RU'),clock=s=>Math.floor(s/60)+':'+String(Math.floor(s)%60).padStart(2,'0');
 const picker=document.querySelector('.player-picker');picker.querySelector('button').hidden=true;
 picker.querySelector('select').addEventListener('change',()=>{const u=new URL(location.href);u.searchParams.set('player',picker.querySelector('select').value);u.searchParams.delete('death');u.searchParams.delete('visionTime');location.href=u.href;});
 document.querySelectorAll('[data-select-player]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const u=new URL(location.href);u.searchParams.set('player',a.dataset.selectPlayer);u.searchParams.delete('death');u.searchParams.delete('visionTime');u.hash='combat';location.href=u.href;}));
 const colors=Array.from({length:10},(_,i)=>'var(--series-'+i+')');
 const metric=document.getElementById('farm-metric'),range=document.getElementById('farm-minute'),hiddenPlayers=new Set();
 const state=new URL(location.href);for(const value of (state.searchParams.get('hide')||'').split(',')){const i=Number(value);if(value!==''&&Number.isInteger(i)&&i>=0&&i<data.players.length)hiddenPlayers.add(i);}if(['networth','xp','lastHits','denies'].includes(state.searchParams.get('metric')))metric.value=state.searchParams.get('metric');const at=Number(state.searchParams.get('minute'));if(at>=1&&at<=Number(range.max))range.value=at;
 function renderFarm(update=false){
  const key=metric.value,minute=Number(range.value),all=data.players.flatMap((p,i)=>(p.economy[key]||[]).map(v=>({...v,i}))),visible=all.filter(v=>!hiddenPlayers.has(v.i));
  const max=Math.max(1,...visible.map(p=>p.value)),last=Number(range.max),x=m=>45+m/last*540,y=v=>210-v/max*185;
  let svg='<svg viewBox="0 0 600 240" role="img" aria-label="Сравнение фарма по минутам">';
  for(const f of [0,.5,1])svg+='<line x1="45" x2="590" y1="'+y(f*max)+'" y2="'+y(f*max)+'" stroke="var(--line)"/><text x="40" y="'+(y(f*max)+5)+'" text-anchor="end" fill="var(--muted)" font-size="17">'+(max>=1000?Math.round(f*max/1000)+'к':Math.round(f*max))+'</text>';
  data.players.forEach((p,i)=>{if(hiddenPlayers.has(i))return;const runs=[];for(const point of p.economy[key]||[]){const run=runs[runs.length-1];if(!run||point.minute!==run[run.length-1].minute+1)runs.push([point]);else run.push(point);}for(const run of runs){svg+='<polyline fill="none" stroke="'+colors[i%10]+'" stroke-width="'+(p.steamId===selected.steamId?3:1.7)+'" points="'+run.map(v=>x(v.minute)+','+y(v.value)).join(' ')+'"/>';}});
  svg+='<line x1="'+x(minute)+'" x2="'+x(minute)+'" y1="18" y2="215" stroke="var(--ink)" stroke-dasharray="4 4"/><text x="45" y="235" fill="var(--muted)" font-size="17">0 мин</text><text x="585" y="235" text-anchor="end" fill="var(--muted)" font-size="17">'+last+' мин</text></svg>';
  document.getElementById('farm-chart').innerHTML=visible.length?svg:'<p class="empty">Нет наблюдений для выбранного показателя или все герои скрыты.</p>';
  document.getElementById('farm-minute-label').textContent=minute;
  const list=document.getElementById('farm-values');list.replaceChildren();data.players.forEach((p,i)=>{const point=(p.economy[key]||[]).find(v=>v.minute===minute),b=document.createElement('button');b.type='button';b.className='farm-value';b.setAttribute('aria-pressed',String(!hiddenPlayers.has(i)));b.innerHTML='<i style="background:'+colors[i%10]+'"></i><span>'+escapeText(p.name)+'<small>'+escapeText(p.hero)+'</small></span><strong>'+(point?fmt(point.value):'—')+'</strong>';b.onclick=()=>{hiddenPlayers.has(i)?hiddenPlayers.delete(i):hiddenPlayers.add(i);renderFarm(true);};list.append(b);});
  if(update){const u=new URL(location.href);u.searchParams.set('metric',key);u.searchParams.set('minute',range.value);if(hiddenPlayers.size)u.searchParams.set('hide',[...hiddenPlayers].sort((a,b)=>a-b).join(','));else u.searchParams.delete('hide');history.replaceState(null,'',u.pathname+u.search+u.hash);}
 }
 metric.addEventListener('change',()=>renderFarm(true));range.addEventListener('input',()=>renderFarm(true));renderFarm();
 function drawMap(id,events){
  const target=document.getElementById(id),positioned=events.map((e,i)=>({...e,mapNumber:e.mapNumber??i+1})).filter(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)),located=positioned.filter(e=>Math.abs(e.x)<=10000&&Math.abs(e.y)<=10000),outside=positioned.length-located.length,missing=events.length-positioned.length;
  const coverage=located.length+' из '+events.length+' событий на схеме'+(outside?' · вне диапазона: '+outside:'')+(missing?' · без координат: '+missing:'')+'.';
  if(!located.length){target.innerHTML='<p class="empty">'+(outside?'События с координатами вне диапазона схемы не показаны.':'Для этих событий нет координат в сохранённом реплее.')+'</p><p class="micro-note">'+coverage+'</p>';return;}
  const x=v=>20+(v+10000)/20000*300,y=v=>320-(v+10000)/20000*300;
  const label=e=>(e.event==='place'?'Установка ':e.event==='destroy'?'Уничтожение ':'Смерть ')+(e.kind||'героя');
  const color=e=>e.event==='place'?'var(--good)':e.event==='destroy'?'var(--attack)':'var(--bad)';
  const grid=[95,170,245].map(v=>'<path d="M'+v+' 20V320M20 '+v+'H320" stroke="var(--line)" stroke-dasharray="3 5"/>').join('');
  target.innerHTML='<svg viewBox="0 0 340 340" role="group" aria-label="Координатная схема событий, фиксированный диапазон от минус 10000 до плюс 10000"><rect x="20" y="20" width="300" height="300" fill="var(--surface-2)" stroke="var(--line)"/>'+grid+'<text x="27" y="309" fill="var(--muted)" font-size="11">Юго-запад</text><text x="228" y="36" fill="var(--muted)" font-size="11">Северо-восток</text>'+located.map(e=>'<circle data-map-number="'+e.mapNumber+'" cx="'+x(e.x)+'" cy="'+y(e.y)+'" r="10" fill="var(--surface)" stroke="'+color(e)+'" stroke-width="3"/><text x="'+x(e.x)+'" y="'+(y(e.y)+3.5)+'" text-anchor="middle" fill="var(--ink)" style="font-size:10px;font-weight:700;pointer-events:none">'+e.mapNumber+'</text>').join('')+'</svg><p class="map-selection micro-note" role="status">Выбери номер на схеме, чтобы посмотреть событие.</p><p class="micro-note">'+coverage+' Зелёная обводка — установка, жёлтая — уничтожение, красная — смерть. Фиксированный масштаб ±10 000; координатная схема без ландшафта и видимости.</p>';
  const svg=target.querySelector('svg'),markers=[...svg.querySelectorAll('circle')],status=target.querySelector('.map-selection');
  const choose=index=>{const e=located[index];status.textContent='№'+e.mapNumber+' · '+clock(e.seconds)+' · '+label(e);markers.forEach((marker,i)=>{marker.setAttribute('stroke',i===index?'var(--ink)':color(located[i]));marker.setAttribute('stroke-width',i===index?'4':'3');marker.setAttribute('aria-pressed',String(i===index));});};
  markers.forEach((marker,i)=>{marker.setAttribute('tabindex','0');marker.setAttribute('role','button');marker.setAttribute('aria-pressed','false');marker.setAttribute('aria-label','Событие '+located[i].mapNumber+', '+clock(located[i].seconds)+', '+label(located[i]));marker.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(i);}});});
  svg.addEventListener('pointerdown',e=>{const direct=e.target.closest('[data-map-number]');if(direct){choose(markers.indexOf(direct));return;}const rect=svg.getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*340,py=(e.clientY-rect.top)/rect.height*340;let best=0,distance=Infinity;located.forEach((point,i)=>{const d=Math.hypot(px-x(point.x),py-y(point.y));if(d<distance){distance=d;best=i;}});if(distance<=Math.max(28,22*340/rect.width))choose(best);});
 }
 const deathSelect=document.getElementById('death-select');
 function renderDeath(update=false){const index=deathSelect?Number(deathSelect.value):0;drawMap('death-map',selected.deaths?.[index]?[{...selected.deaths[index],mapNumber:index+1}]:[]);document.querySelectorAll('[data-death]').forEach(e=>e.hidden=Number(e.dataset.death)!==index);if(update){const u=new URL(location.href);u.searchParams.set('death',index);history.replaceState(null,'',u.pathname+u.search+u.hash);}}
 if(deathSelect){const d=Number(state.searchParams.get('death'));if(d>=0&&d<deathSelect.options.length)deathSelect.value=d;deathSelect.addEventListener('change',()=>renderDeath(true));}renderDeath();
 const visionRange=document.getElementById('vision-time');visionRange.max=data.duration;visionRange.value=data.duration;const savedTime=Number(state.searchParams.get('visionTime'));if(state.searchParams.has('visionTime')&&savedTime>=0&&savedTime<=data.duration)visionRange.value=savedTime;
 function renderVision(update=false){const sec=Number(visionRange.value);document.getElementById('vision-time-label').textContent=clock(sec);drawMap('vision-map',(selected.vision.events||[]).filter(e=>e.event!=='purchase').map((e,i)=>({...e,mapNumber:i+1})).filter(e=>e.seconds<=sec));document.querySelectorAll('#vision-events [data-event-time]').forEach(e=>e.hidden=Number(e.dataset.eventTime)>sec);if(update){const u=new URL(location.href);u.searchParams.set('visionTime',sec);history.replaceState(null,'',u.pathname+u.search+u.hash);}}
 visionRange.addEventListener('input',()=>renderVision(true));renderVision();
 const eventData=JSON.parse(document.getElementById('combat-events-data').textContent),filter=document.getElementById('event-filter'),search=document.getElementById('event-search'),more=document.getElementById('more-events');let limit=50;
 if([...filter.options].some(o=>o.value===state.searchParams.get('event')))filter.value=state.searchParams.get('event');search.value=state.searchParams.get('q')||'';
 function renderEvents(reset=false,update=false){if(reset)limit=50;const rows=eventData.filter(e=>(filter.value==='all'||e.type===filter.value)&&e.text.toLocaleLowerCase().includes(search.value.trim().toLocaleLowerCase()));document.getElementById('combat-events').innerHTML=rows.slice(0,limit).map(e=>'<div class="event-row"><time>'+clock(e.seconds)+'</time><span>'+escapeText(e.text)+'</span></div>').join('');document.getElementById('event-count').textContent=rows.length?'Показано '+Math.min(limit,rows.length)+' из '+rows.length:'Событий по этому фильтру нет';more.hidden=limit>=rows.length;if(update){const u=new URL(location.href);u.searchParams.set('event',filter.value);if(search.value)u.searchParams.set('q',search.value);else u.searchParams.delete('q');history.replaceState(null,'',u.pathname+u.search+u.hash);}}
 filter.addEventListener('change',()=>renderEvents(true,true));search.addEventListener('input',()=>renderEvents(true,true));more.addEventListener('click',()=>{limit+=50;renderEvents();});renderEvents();
}
`;
