import {playerAvatar} from "./player-avatar-render.js";
import type {PlayerProgress} from "../player-progress.js";
import {renderProgress} from "./player-progress-render.js";
import { PLAYERS } from "../config.js";
import { HERO_CATALOG } from "../hero-catalog.js";
import type { Period, PlayerProfile, ProfileMatch } from "../player-profile.js";
import { groupActions } from "../action-counts.js";
import { esc, layout } from "./render.js";
import { profileInsights } from "../profile-insights.js";
import { PROFILE_CSS } from "./profile-style.js";
import type { ProfileEconomy } from "../profile-economy.js";
import { renderEconomy } from "./profile-economy-render.js";
import { PROFILE_SCRIPT } from "./profile-script.js";

const PAGE_SIZE=10;
const word=(value:number,one:string,few:string,many:string)=>value%100>=11&&value%100<=14?many:value%10===1?one:value%10>=2&&value%10<=4?few:many;
const gameCount=(value:number)=>`${value} ${word(value,"игра","игры","игр")}`;
const matchCount=(value:number)=>`${value} ${word(value,"матч","матча","матчей")}`;
const heroCount=(value:number)=>`${value} ${word(value,"герой","героя","героев")}`;
const commandCount=(value:number)=>`${value.toLocaleString("ru-RU")} ${word(value,"команда","команды","команд")}`;
const n=(value:number)=>value.toLocaleString("ru-RU");
const pct=(a:number,b:number)=>!b?"—":a>0&&a/b<.01?"<1%":Math.round(a/b*100)+"%";
const nick=(id:number)=>PLAYERS.find(p=>p.steamId===id)?.dotaName??String(id);
const date=(ts:number|null,short=false)=>ts?new Date(ts*1000).toLocaleDateString("ru-RU",{timeZone:"Europe/Moscow",day:"numeric",month:"short",...(short?{}:{year:"numeric"})}):"Дата неизвестна";
const time=(ts:number|null)=>ts?new Date(ts*1000).toLocaleTimeString("ru-RU",{timeZone:"Europe/Moscow",hour:"2-digit",minute:"2-digit"}):"";
const duration=(sec:number)=>`${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,"0")}`;
function art(hero:string){const h=HERO_CATALOG.find(h=>h.localized_name===hero);return h?`https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${h.name.replace("npc_dota_hero_","")}.png`:"";}
const portrait=(hero:string)=>art(hero)?`<img class="hero-thumb" loading="lazy" src="${art(hero)}" alt="" width="52" height="32">`:"";
const periods=(period:Period,base:string)=>`<nav class="periods" aria-label="Период статистики">${([["7","7 дней"],["30","30 дней"],["all","Вся история"]] as const).map(([value,label])=>`<a href="${base}?period=${value}" ${period===value?'aria-current="page" class="selected"':""}>${label}</a>`).join("")}</nav>`;
const empty=(text:string)=>`<p class="empty">${text}</p>`;
const fold=(title:string,body:string,id="")=>`<details class="fold" ${id?`id="${id}"`:""}><summary>${title}</summary><div class="fold-body">${body}</div></details>`;
const shareIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M10 13a5 5 0 0 0 7 .1l3-3a5 5 0 0 0-7-7l-2 2M14 11a5 5 0 0 0-7-.1l-3 3a5 5 0 0 0 7 7l2-2"/></svg>';
function section(id:string,title:string,description:string,body:string,cls=""){
  return `<section id="${id}" class="panel ${cls}" aria-labelledby="${id}-title"><div class="section-head"><div><h2 id="${id}-title"><a href="#${id}">${title}</a></h2>${description?`<p class="sub">${description}</p>`:""}</div><button class="share-section" type="button" data-share-section="${id}" aria-label="Скопировать ссылку на раздел ${esc(title)}" title="Скопировать ссылку">${shareIcon}</button></div>${body}</section>`;
}
function page(title:string,body:string,script="",preview?:{description:string;image?:string}){return layout(title,body,script,PROFILE_CSS,preview);}

export function renderPlayers(profiles:PlayerProfile[],period:Period){
  const sorted=[...profiles].sort((a,b)=>b.matches.length-a.matches.length||a.account-b.account);
  const cards=sorted.map(p=>{
    const top=p.heroes[0];
    return `<a class="player-card" data-name="${esc(nick(p.account).toLocaleLowerCase("ru"))}" href="/player/${p.account}?period=${period}">${top&&art(top.hero)?`<img class="card-art" src="${art(top.hero)}" alt="" loading="lazy">`:""}<div class="identity-heading">${playerAvatar(p.account,nick(p.account))}<div><h2>${esc(nick(p.account))}</h2></div></div><p class="sub">${top?`${esc(top.hero)} · самый частый герой`:"История ещё собирается"}</p><div class="card-stats"><div><b>${p.matches.length}</b><span>матчей</span></div><div><b>${pct(p.wins,p.known)}</b><span>побед</span></div><div><b>${p.avgApm??"—"}</b><span>APM · ${gameCount(p.measured.length)}</span></div></div><div class="card-foot">${p.matches[0]?`Последняя игра: ${date(p.matches[0].start,true)}`:"Появится с первой сохранённой игрой"}<span style="float:right" aria-hidden="true">↗</span></div></a>`;
  }).join("");
  return page("Игроки стака · Пёсики",`<main class="profile-view"><nav class="breadcrumbs" aria-label="Путь по сайту"><a href="/">Матчи</a><span aria-hidden="true">/</span><span>Игроки стака</span></nav><header class="directory-head"><p class="eyebrow">Пёсики / наши игроки</p><h1>Один стак. Разный почерк.</h1><p class="sub">Из чего складывается APM, на ком играем и с кем побеждаем. Личная история каждого из нас.</p></header><div class="profile-toolbar">${periods(period,"/players")}<div class="form-search"><label for="player-search">Найти</label><input id="player-search" class="player-search" type="search" placeholder="Ник игрока" autocomplete="off"></div></div><div class="player-grid">${cards}</div><p id="no-players" class="empty" role="status" hidden>Такого ника в стаке нет.</p><p class="micro-note">${PLAYERS.length} игроков · Только сохранённые матчи выбранного периода. APM — среднее по играм с измерением.</p></main>`,
    `const search=document.getElementById('player-search');search.addEventListener('input',()=>{let shown=0;document.querySelectorAll('.player-card').forEach(card=>{card.hidden=!card.dataset.name.includes(search.value.trim().toLocaleLowerCase('ru'));if(!card.hidden)shown++});document.getElementById('no-players').hidden=shown>0;});`);
}

const COMMAND_LABELS:Record<string,string>={MOVE_TO_POSITION:"Движение в точку",MOVE_TO_TARGET:"Движение к цели",ATTACK_MOVE:"Атакующее движение",ATTACK_TARGET:"Атака цели",CAST_POSITION:"Применение в точку",CAST_TARGET:"Применение на цель",CAST_TARGET_TREE:"Применение на дерево",CAST_NO_TARGET:"Применение без цели",CAST_TOGGLE:"Переключение способности",CAST_TOGGLE_AUTO:"Переключение автоприменения",HOLD_POSITION:"Удерживать позицию",STOP:"Остановиться",TRAIN_ABILITY:"Изучить способность",PURCHASE_ITEM:"Купить предмет",SELL_ITEM:"Продать предмет",MOVE_ITEM:"Переложить предмет",PICKUP_ITEM:"Подобрать предмет",PICKUP_RUNE:"Подобрать руну",GIVE_ITEM:"Передать предмет",DROP_ITEM:"Выбросить предмет",CAST_RUNE:"Активировать руну",GLYPH:"Глиф",RADAR:"Сканирование",BUYBACK:"Выкуп",TAUNT:"Насмешка"};
function composition(p:PlayerProfile,selectedMatch?:number){
  if(!p.detailed.length)return empty(p.measured.length?"Общий APM уже есть в истории. Подробные типы команд появятся после восстановления исходных реплеев или с новыми играми.":"Пока нет разобранных реплеев с APM. Измерения появятся после получения доступных исходников.");
  const chosen=p.detailed.find(m=>m.id===selectedMatch),detailed=chosen?[chosen]:p.detailed;
  const raw:Record<string,number>={};
  for(const m of detailed)for(const [key,value]of Object.entries(m.apm!.action_counts!))raw[key]=(raw[key]??0)+value;
  const groups=groupActions(raw),total=groups.reduce((sum,g)=>sum+g.count,0),seconds=detailed.reduce((sum,m)=>sum+m.apm!.duration_seconds,0);
  const picker=`<form class="breakdown-picker" action="/player/${p.account}#apm" method="get"><input type="hidden" name="period" value="${p.period}"><label for="breakdown-match">Какие игры разобрать</label><div><select id="breakdown-match" name="match"><option value="">Все игры с деталями (${p.detailed.length})</option>${p.detailed.map(m=>`<option value="${m.id}" ${chosen?.id===m.id?'selected':''}>${date(m.start,true)} ${time(m.start)} · ${esc(m.hero)} · ${m.apm!.apm} APM</option>`).join("")}</select><button type="submit">Показать</button></div></form>`;
  const commands=Object.entries(raw).sort((a,b)=>b[1]-a[1]).map(([key,value])=>{const type=key.replace("DOTA_UNIT_ORDER_","");return `<div class="command-row"><span>${esc(COMMAND_LABELS[type]??"Другой приказ")}<code>${esc(type)}</code></span><b>${n(value)}<small>${pct(value,total)}</small></b></div>`;}).join("");
  return `${picker}<div class="apm-lead"><div><strong>${chosen?chosen.apm!.apm:detailed.length} <small>${chosen?"APM":word(detailed.length,"матч","матча","матчей")}</small></strong><p>${chosen?"в выбранном матче":`Всего команд: ${n(total)}`}</p></div><div class="apm-detail-link">${chosen?`<a href="/match/${chosen.id}">Матч ↗</a><br><span class="sub">${duration(chosen.apm!.duration_seconds)}</span>`:`<span class="coverage"><i></i>из ${p.measured.length} с APM</span>`}</div></div><div class="apm-stack" role="img" aria-label="Доли типов команд">${groups.map(g=>`<i style="width:${total?g.count/total*100:0}%;background:${g.color}" title="${g.label}: ${pct(g.count,total)}"></i>`).join("")}</div><div class="action-list">${groups.map(g=>`<div class="action-row"><i style="background:${g.color}"></i><div><span class="action-label">${g.label}</span><small class="action-count">${commandCount(g.count)}</small></div><div><b>${pct(g.count,total)}</b><small class="action-rate">${seconds?(g.count*60/seconds).toFixed(1).replace(".",","):"0"} / мин</small></div></div>`).join("")}</div>${total?`<p class="apm-takeaway">${pct(groups[0].count,total)} команд — перемещения. Повторные приказы тоже входят в APM.</p>`:""}<p class="micro-note">${commandCount(total)}${chosen?" в выбранной игре":` в ${detailed.length} играх с деталями`}. Это приказы, а не физические клики или успешные попадания.</p>${fold("Конкретные команды",`<div class="command-list">${commands}</div>`)}${fold("Как читать эту разбивку",`<p class="micro-note">У общего APM в шапке и подробной разбивки может быть разное покрытие. В шапке ${p.measured.length} измеренных игр, здесь ${detailed.length}. Средний APM — среднее значений игр. Доли и команды в минуту считаются по суммарным командам и времени выбранных игр. Способности и активные предметы используют общие типы приказов.</p>`)}`;
}

function timeline(p:PlayerProfile){
  const matches=[...p.measured].filter(m=>m.start!==null).reverse();
  if(!matches.length)return empty("Для графика нужны матчи с APM и известной датой.");
  const max=Math.max(...matches.map(m=>m.apm!.apm),1)*1.15;
  const x=(i:number)=>40+i*460/Math.max(matches.length-1,1),y=(v:number)=>160-v/max*135;
  const points=matches.map((m,i)=>({id:m.id,hero:m.hero,apm:m.apm!.apm,date:date(m.start)+" "+time(m.start),outcome:m.win===null?"результат неизвестен":m.win?"победа":"поражение",detailed:m.apm!.action_counts!==undefined,x:x(i),y:y(m.apm!.apm)}));
  const last=points.at(-1)!;
  const svg=`<svg id="apm-chart" class="timeline" viewBox="0 0 520 180" role="img" aria-label="APM по ${matches.length} матчам. Выбор игры ползунком под графиком.">${[0,Math.round(max/2),Math.round(max)].map(v=>`<line x1="40" x2="510" y1="${y(v)}" y2="${y(v)}" stroke="var(--line)"/><text x="0" y="${y(v)+4}">${v}</text>`).join("")}<polyline points="${points.map(m=>`${m.x},${m.y}`).join(" ")}" fill="none" stroke="var(--muted)" stroke-opacity=".35" stroke-width="1.5"/>${matches.map((m,i)=>`<circle cx="${x(i)}" cy="${y(m.apm!.apm)}" r="3.7" fill="${m.win===null?'var(--muted)':m.win?'var(--good)':'var(--bad)'}"/>`).join("")}<circle id="chart-marker" cx="${last.x}" cy="${last.y}" r="7" fill="none" stroke="var(--ink)" stroke-width="2"/></svg>`;
  return `${svg}<div class="profile-toolbar sub"><span>${date(matches[0].start,true)}</span><span>${date(matches.at(-1)!.start,true)}</span></div><div class="chart-key"><span><i style="background:var(--good)"></i>победа</span><span><i style="background:var(--bad)"></i>поражение</span></div><label class="micro-note" for="chart-range">Выбери матч ползунком или коснись графика</label><input class="chart-range" id="chart-range" type="range" min="0" max="${points.length-1}" value="${points.length-1}" step="1"><div class="chart-selected"><a id="chart-match" href="/match/${last.id}"><span><b id="chart-hero">${esc(last.hero)}</b><span id="chart-date" class="sub" style="display:block">${esc(last.date)} · ${last.outcome}</span></span><strong id="chart-apm">${last.apm} APM</strong></a><a id="chart-detail" class="chart-detail" href="/player/${p.account}?period=${p.period}&match=${last.id}#apm" ${last.detailed?"":"hidden"}>Из чего складывается этот APM →</a></div><div class="chart-summary"><div><b>${p.median}</b><span>медиана APM</span></div><div><b>${p.peak?.apm!.apm??"—"}</b><span>максимум</span></div><div><b>${matches.length}</b><span>матчей</span></div></div><p class="micro-note">Игры идут по порядку. Расстояния между точками одинаковые, даже если между играми был перерыв.</p><script id="apm-series" type="application/json">${JSON.stringify(points).replace(/</g,"\\u003c")}</script>`;
}

function heroes(p:PlayerProfile){
  const row=(h:PlayerProfile["heroes"][number])=>`<a class="hero-row" href="/player/${p.account}?period=${p.period}&hero=${encodeURIComponent(h.hero)}#history">${portrait(h.hero)}<div><strong>${esc(h.hero)}</strong><small>${gameCount(h.games)} · ${h.wins} В / ${h.known-h.wins} П${h.games>h.known?` · ${h.games-h.known} без итога`:""}<br>${h.apm===null?"APM пока нет":`APM ${h.apm} · ${gameCount(h.apmGames)}`}</small></div><div class="hero-result"><b>${pct(h.wins,h.known)}</b><small>побед ↗</small></div></a>`;
  return p.heroes.length?`<div class="hero-list">${p.heroes.slice(0,5).map(row).join("")}</div>${p.heroes.length>5?fold(`Ещё ${heroCount(p.heroes.length-5)}`,p.heroes.slice(5).map(row).join("")):""}<p class="micro-note">Нажми на героя, чтобы посмотреть его матчи.</p>`:empty("Герои появятся вместе с матчами.");
}
function mastery(p:PlayerProfile){
  const rows=profileInsights(p.matches).mastery.filter(h=>h.known>=5);
  if(!rows.length)return empty("Для личного топа нужно хотя бы 5 игр с известным исходом на герое. Пока набираем историю.");
  return rows.slice(0,5).map((h,i)=>`<a class="mastery-row" href="/player/${p.account}?period=${p.period}&hero=${encodeURIComponent(h.hero)}#history"><span class="mastery-rank">${i+1}</span>${portrait(h.hero)}<div><strong>${esc(h.hero)}</strong><small>${gameCount(h.games)} · ${h.wins} В / ${h.known-h.wins} П</small><small>KDA ${h.kda===null?"—":h.kda.toFixed(2)} · ${gameCount(h.kdaGames)} с KDA</small></div><b>${pct(h.wins,h.known)}</b></a>`).join("")+`<p class="micro-note">Личный топ по нижней границе 95% интервала Уилсона: учитывает победы и объём выборки. Минимум 5 известных исходов. Это помогает не ставить 2 победы из 2 выше большой истории; не является мировым рейтингом. KDA = (убийства + ассисты) / смерти, при 0 смертей делим на 1.</p>`;
}
function form(p:PlayerProfile){
  const x=profileInsights(p.matches),a=x.recent,b=x.previous;
  const streak=x.recentMatches.map(m=>`<a href="/match/${m.id}" class="result-dot ${m.win===null?'':m.win?'win':'loss'}" aria-label="${esc(m.hero)}, ${date(m.start)}, ${m.win===null?'исход неизвестен':m.win?'победа':'поражение'}">${m.win===null?'?':m.win?'В':'П'}</a>`).join("");
  const delta=(v:number|null,old:number|null,suffix:string,decimals=0)=>v===null||old===null?"Нет данных для сравнения":`${v-old>0?'+':''}${(v-old).toFixed(decimals)}${suffix} к предыдущим 10`;
  const metric=(label:string,value:string,note:string)=>`<div class="form-metric"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`;
  return `<div class="result-strip">${streak}</div><p class="micro-note">Слева — самая свежая игра. Нажми на исход, чтобы открыть матч.</p><div class="form-grid">${metric("Победы",pct(a.wins,a.known),x.comparisonReady&&a.known===10&&b.known===10?delta(a.winRate===null?null:a.winRate*100,b.winRate===null?null:b.winRate*100," п.п."):`${a.known} известных исходов`)}${metric("KDA",a.kda===null?"—":a.kda.toFixed(2),x.comparisonReady&&a.kdaGames===10&&b.kdaGames===10?delta(a.kda,b.kda,"",2):`${gameCount(a.kdaGames)} с KDA`)}${metric("APM",a.apm===null?"—":String(Math.round(a.apm)),x.comparisonReady&&a.apmGames===10&&b.apmGames===10?delta(a.apm,b.apm,""):`${gameCount(a.apmGames)} с APM`)}</div><p class="micro-note">${x.comparisonReady?"Последние 10 игр против предыдущих 10. Изменения показываем только при полном покрытии метрики в обеих группах.":`В сравнении участвуют только игры с датой. Для двух полных групп нужно 20; сейчас ${a.games+b.games}.`} Герои и роли могли измениться; рост APM сам по себе не означает улучшение игры.</p>`;
}
function economySection(p:PlayerProfile,data:ProfileEconomy|null){
  const games=p.matches.filter(m=>m.apm||m.allyHeroes);
  const picker=games.length?`<form class="breakdown-picker economy-picker" action="/player/${p.account}#economy" method="get"><input type="hidden" name="period" value="${p.period}"><label for="economy-match">Выбрать игру</label><div><select id="economy-match" name="economy">${games.map(m=>`<option value="${m.id}" ${data?.matchId===m.id?'selected':''}>${date(m.start,true)} ${time(m.start)} · ${esc(m.hero)}</option>`).join("")}</select><button type="submit">Показать</button></div></form>`:"";
  return picker+renderEconomy(data);
}
function matchups(p:PlayerProfile){
  const x=profileInsights(p.matches);
  const list=(rows:typeof x.enemies)=>{
    const eligible=rows.filter(h=>h.known>=3).sort((a,b)=>(a.winRate??0)-(b.winRate??0)||b.known-a.known);
    if(!eligible.length)return empty("Пока нет героев с 3 известными исходами. Новые реплеи дополнят выборку.");
    const row=(h:typeof eligible[number])=>`<div class="matchup-row">${portrait(h.hero)}<div><strong>${esc(h.hero)}</strong><small>${h.wins} В / ${h.known-h.wins} П · ${gameCount(h.known)}</small></div><b>${pct(h.wins,h.known)}</b></div>`;
    return eligible.slice(0,5).map(row).join("")+(eligible.length>5?fold(`Все герои (${eligible.length})`,eligible.slice(5).map(row).join("")):"");
  };
  return `<div class="matchup-tabs" role="group" aria-label="Сторона героя"><button type="button" data-matchup="enemies" aria-pressed="true">Против</button><button type="button" data-matchup="allies" aria-pressed="false">Вместе</button></div><div id="matchup-enemies"><h3>Результаты против</h3>${list(x.enemies)}</div><div id="matchup-allies" hidden><h3>Результаты вместе</h3>${list(x.allies)}</div><p class="micro-note">Сначала меньший процент побед; минимум 3 известных исхода. Составы есть у ${x.rosterGames} из ${p.matches.length} игр. Герой мог быть на любой линии. Это результаты всей команды, а не доказательство контрпика или личного проигрыша линии.</p>`;
}
function partners(p:PlayerProfile){
  const row=(t:PlayerProfile["partners"][number])=>`<a class="partner-row" href="/player/${t.id}?period=${p.period}"><div><strong>${esc(t.name)} ↗</strong><p class="sub">${gameCount(t.games)} · ${t.wins} В / ${t.known-t.wins} П</p></div><div class="partner-score"><b>${pct(t.wins,t.known)}</b><small>побед вместе</small></div></a>`;
  if(!p.partners.length)return empty("Пока нет разобранных совместных матчей.");
  return `<div class="partner-list">${p.partners.slice(0,4).map(row).join("")}</div>${p.partners.length>4?fold(`Ещё ${p.partners.length-4} ${word(p.partners.length-4,"напарник","напарника","напарников")}`,p.partners.slice(4).map(row).join("")):""}<p class="partner-note">Составы известны для ${p.teammateCoverage} из ${p.matches.length} игр. Учитываем только одну сторону. Процент описывает совместные матчи, а не влияние человека на победу.</p>`;
}
function comparison(p:PlayerProfile,all:PlayerProfile[]){
  const peers=all.filter(x=>x.avgApm!==null).sort((a,b)=>b.avgApm!-a.avgApm!),max=Math.max(1,...peers.map(x=>x.avgApm!));
  return peers.map(q=>`<div class="comparison-row ${q.account===p.account?'current':''}"><a href="/player/${q.account}?period=${p.period}">${esc(nick(q.account))}<small>${matchCount(q.measured.length)}</small></a><div class="bar-track"><i style="width:${q.avgApm!/max*100}%"></i></div><b>${q.avgApm}</b></div>`).join("")+`<p class="micro-note">APM — темп команд, не рейтинг силы. У игроков разные герои, роли и наборы матчей.</p>`;
}
function rhythm(p:PlayerProfile){
  const bars=p.dated?`<div class="time-bars">${p.hours.map((v,i)=>`<div class="time-column"><b>${v}</b><i style="height:${v?Math.max(3,v/Math.max(...p.hours)*80):0}px"></i><span>${["00–06","06–12","12–18","18–24"][i]}</span></div>`).join("")}</div><p class="micro-note">Игры с датой начала: ${p.dated} из ${p.matches.length}. Часы на графике — по Москве, UTC+3.</p>`:empty("Для ритма нужны известные даты игр.");
  const record=(label:string,m:ProfileMatch,value:string)=>`<a class="record-row" href="/match/${m.id}"><span>${label}<small>${esc(m.hero)} · ${date(m.start,true)} ↗</small></span><strong>${value}</strong></a>`;
  const official=p.matches.filter(m=>m.kda&&["OpenDota","табло реплея"].includes(m.kdaSource??"")),kills=[...official].sort((a,b)=>b.kda![0]-a.kda![0])[0],assists=[...official].sort((a,b)=>b.kda![2]-a.kda![2])[0];
  return `${bars}<div class="record-list">${p.peak?record("Самый высокий APM",p.peak,String(p.peak.apm!.apm)):""}${p.longest?record("Самая долгая игра",p.longest,duration(p.longest.duration)):""}${kills?record("Больше всего убийств",kills,String(kills.kda![0])):""}${assists?record("Больше всего ассистов",assists,String(assists.kda![2])):""}</div><p class="micro-note">Рекорды только внутри выбранной сохранённой истории.${official.length?` Убийства и ассисты подтверждены таблом реплея или OpenDota в ${official.length} матчах.`:""}</p>`;
}
function history(p:PlayerProfile,requestedPage:number,requestedHero?:string){
  const hero=p.heroes.some(h=>h.hero===requestedHero)?requestedHero:undefined;
  const matches=hero?p.matches.filter(m=>m.hero===hero):p.matches;
  const pages=Math.max(1,Math.ceil(matches.length/PAGE_SIZE)),pageNumber=Math.min(pages,Math.max(1,Number.isSafeInteger(requestedPage)?requestedPage:1));
  const slice=matches.slice((pageNumber-1)*PAGE_SIZE,pageNumber*PAGE_SIZE),base=`/player/${p.account}?period=${p.period}`;
  const cards=slice.map(m=>`<article class="match-card"><a class="match-main" href="/match/${m.id}" aria-label="${esc(m.hero)}, матч ${m.id}"><span class="match-identity">${portrait(m.hero)}<span><strong>${esc(m.hero)}</strong><small>${date(m.start,true)} ${time(m.start)} · ${duration(m.duration)}</small></span></span><span class="outcome ${m.win===null?'':m.win?'good':'bad'}">${m.win===null?'Нет итога':m.win?'Победа':'Поражение'}</span></a><div class="match-bottom"><div class="kda" title="${esc(m.kdaSource??'Нет подтверждённого KDA')}"><small>K / D / A</small><b>${m.kda?m.kda.join(" / "):"—"}</b></div>${m.apm?.action_counts!==undefined?`<a class="apm-link" href="${base}&match=${m.id}#apm" aria-label="Разбивка ${m.apm.apm} APM, ${esc(m.hero)}">${m.apm.apm} APM ↗</a>`:`<span class="apm-plain">${m.apm?.apm??"—"} APM</span>`}</div></article>`).join("");
  const pageLink=(num:number)=>`${base}${hero?`&hero=${encodeURIComponent(hero)}`:""}&page=${num}#history`;
  return `<p><a class="plain-button" href="/player/${p.account}/compare">Сравнить две игры ↗</a></p>${hero?`<div class="history-filters"><span class="filter-pill">${esc(hero)}<a href="${base}#history" aria-label="Убрать фильтр героя">×</a></span><span class="sub">${gameCount(matches.length)}</span></div>`:""}${cards?`<div class="match-list">${cards}</div><div class="history-footer"><span>${(pageNumber-1)*PAGE_SIZE+1}–${Math.min(pageNumber*PAGE_SIZE,matches.length)} из ${matches.length}</span><nav class="pagination" aria-label="Страницы матчей">${pageNumber>1?`<a href="${pageLink(pageNumber-1)}" aria-label="Предыдущие матчи">←</a>`:""}${pageNumber<pages?`<a href="${pageLink(pageNumber+1)}">Ещё ${Math.min(PAGE_SIZE,matches.length-pageNumber*PAGE_SIZE)} →</a>`:""}</nav></div>`:empty("В выбранном периоде матчей нет.")}`;
}
function methodology(p:PlayerProfile){
  return `<details id="method" class="panel fold methodology"><summary>Откуда цифры</summary><div class="fold-body"><p>Это накопленная история бота, не вся карьера. Обновление матчей — раз в час; подробности появляются после разбора реплея. Данные хранятся постоянно, даже после обновления сайта.</p><p>APM = число приказов × 60 / точная длительность игры, с округлением вниз. Считаем от начала игры до завершения. Один приказ нескольким юнитам считается один раз, повторные приказы включены. Средний APM — среднее значений матчей; пропуски не считаются нулями.</p><p>KDA берём из финального табло реплея; для старых матчей используем сохранённые ответы OpenDota и сводки сайта. Источник указан у матча. Без сохранённого источника показываем прочерк. Результат, герой и сторона также доступны из реплея. Подробную разбивку APM можно восстановить только при наличии исходного реплея.</p><p>Покрытие: общий APM ${p.measured.length}/${p.matches.length}, подробности ${p.detailed.length}/${p.matches.length}, KDA ${p.matches.filter(m=>m.kda).length}/${p.matches.length}. Даты — МСК. Матчи без даты входят только во всю историю.</p><button type="button" class="plain-button" data-share-section="method">Скопировать ссылку на объяснение</button></div></details>`;
}

export function renderPlayer(p:PlayerProfile,all:PlayerProfile[],requestedPage=1,selectedMatch?:number,selectedHero?:string,economy:ProfileEconomy|null=null,progress?:PlayerProgress){
  const base=`/player/${p.account}`,top=p.heroes[0];
  const header=`<header id="overview" class="profile-head">${top&&art(top.hero)?`<img class="hero-art" src="${art(top.hero)}" alt="">`:""}<p class="eyebrow">Пёсики / профиль игрока</p><div class="identity-heading">${playerAvatar(p.account,nick(p.account),true)}<div><h1>${esc(nick(p.account))}</h1></div></div><p class="sub">${top?`Чаще всего ${esc(top.hero)} · ${heroCount(p.heroes.length)} · ${p.hoursPlayed.toFixed(1).replace(".",",")} ч в игре`:"Личная история матчей и темпа."}</p></header>`;
  const dated=p.matches.filter(m=>m.start);
  const toolbar=`<div class="profile-toolbar">${periods(p.period,base)}<p class="sub">${dated.length?`${date(dated.at(-1)!.start)} — ${date(dated[0].start)}`:"Нет датированных матчей"}${p.matches.length>p.dated?` · ${p.matches.length-p.dated} без даты`:""}</p></div>`;
  if(!p.matches.length)return page(`${nick(p.account)} · Профиль Пёсиков`,`<main class="profile-view"><nav class="breadcrumbs" aria-label="Путь по сайту"><a href="/players?period=${p.period}">← Все игроки</a><span aria-hidden="true">/</span><span>${esc(nick(p.account))}</span></nav>${header}${toolbar}${section("apm","Пока без матчей","В этом периоде нет сохранённых игр.",empty(p.period!=="all"?`<a href="${base}?period=all">Посмотреть всю историю →</a>`:"Новые матчи появятся после очередного часового обновления."))}<div class="profile-footer"><a href="/players?period=${p.period}">← Все игроки</a></div><div id="copy-status" class="copy-status" role="status"></div></main>`,PROFILE_SCRIPT);
  const metric=(label:string,value:string,note:string)=>`<div class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><p class="sub">${note}</p></div>`;
  const metrics=`<div class="profile-metrics">${metric("Матчи",String(p.matches.length),"в истории")}${metric("Победы",pct(p.wins,p.known),`${p.wins} В / ${p.known-p.wins} П`)}${metric("Средний APM",String(p.avgApm??"—"),`${p.measured.length} / ${p.matches.length} игр`)}</div>`;
  const navigation=`<nav class="profile-jumps" aria-label="Разделы профиля"><a href="#apm">APM</a><a href="#heroes">Герои</a><a href="#partners">Напарники</a><a href="#form">Форма</a><a href="#matchups">Матчапы</a><a href="#economy">Экономика</a><a href="#progress">Прогресс</a><a href="#history">Матчи</a></nav>`;
  const body=`<main class="profile-view"><nav class="breadcrumbs" aria-label="Путь по сайту"><a href="/players?period=${p.period}">← Все игроки</a><span aria-hidden="true">/</span><span>${esc(nick(p.account))}</span></nav>${header}${toolbar}${metrics}${navigation}<div class="profile-grid">${section("apm","APM под микроскопом","Перемещения, атаки и кнопки — отдельно.",composition(p,selectedMatch))}${section("tempo","Темп по матчам","Проведи по ползунку, чтобы выбрать игру.",timeline(p)+fold("Сравнить со стаком",comparison(p,all)))}</div><div class="profile-grid">${section("heroes","На ком играет",`${heroCount(p.heroes.length)} в выбранном периоде.`,heroes(p)+fold("Личный топ героев",mastery(p),"mastery"))}${section("partners","С кем играет","Наши игроки на одной стороне.",partners(p))}</div>${section("form","Текущая форма","Последние игры и сравнение с собой.",form(p))}${section("matchups","Герои вокруг тебя","Твоя история против героев и вместе с ними.",matchups(p))}${section("economy","Экономика и покупки","Как росла стоимость имущества в выбранной игре.",economySection(p,economy))}${progress?section("progress","Прогресс и привычки","Личные вехи и сравнение покупок с собой.",renderProgress(progress)):""}${section("rhythm","Ритм и рекорды","Когда играет и какие матчи выделяются.",rhythm(p))}${section("history","История матчей",`${matchCount(p.matches.length)} · нажми APM, чтобы увидеть разбивку.`,history(p,requestedPage,selectedHero))}${methodology(p)}<div class="profile-footer"><a href="/players?period=${p.period}">← Все игроки</a><a href="#overview">К началу ↑</a></div><div id="copy-status" class="copy-status" role="status"></div></main>`;
  return page(`${nick(p.account)} · Профиль Пёсиков`,body,PROFILE_SCRIPT,{description:`${matchCount(p.matches.length)} · ${pct(p.wins,p.known)} побед · APM ${p.avgApm??"—"}. Разбивка команд, герои, напарники и история игр.`,image:top?art(top.hero):undefined});
}
