import {gameLabel} from "./game-icon.js";
import type { PlayerProgress, ItemBenchmark } from "../player-progress.js";
import { esc } from "./render.js";
const n=(v:number)=>v.toLocaleString("ru-RU");
const clock=(v:number)=>`${Math.floor(v/60)}:${String(v%60).padStart(2,"0")}`;
function benchmarkRow(b:ItemBenchmark,account:number,period:string){
  const difference=b.differenceSeconds===0?"как обычно":`${clock(Math.abs(b.differenceSeconds))} ${b.differenceSeconds<0?"раньше":"позже"}`;
  return `<article style="padding:12px 0;border-bottom:1px solid var(--line)"><div style="display:flex;justify-content:space-between;gap:12px"><strong>${gameLabel(b.item,b.itemLabel,'item')}</strong><b>${clock(b.latestSeconds)}</b></div><p class="sub">${esc(b.hero)} · ${esc(b.mode==="mode_23"?"Turbo":b.mode==="mode_22"?"Рейтинговый All Pick":b.mode==="mode_1"?"All Pick":b.mode==="mode_18"?"Ability Draft":"Другой режим")}</p><p style="margin:6px 0">${difference}. Личная медиана: <b>${clock(b.medianSeconds)}</b>.</p><p class="micro-note">${b.sample} других игр на этом герое в этом режиме, где покупался предмет.</p><a href="/player/${account}?period=${esc(period)}&amp;economy=${b.matchId}#economy" style="display:inline-flex;align-items:center;min-height:44px">Открыть покупки матча ↗</a></article>`;
}
export function renderProgress(progress:PlayerProgress):string {
  const s=progress.streaks;
  return `<h3>Личные вехи</h3><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px">${progress.milestones.map(m=>((m.key==="kills"||m.key==="assists")&&!progress.officialKdaGames)?`<div><span class="sub">${esc(m.label)}</span><p style="font-size:24px;font-weight:700">—</p><p class="micro-note">Нет официального KDA</p></div>`:`<div style="min-width:0"><span class="sub">${esc(m.label)}</span><p style="margin:4px 0;font-size:24px;font-weight:700">${n(m.value)}</p><progress value="${m.value}" max="${m.next}" aria-label="${esc(m.label)}: ${n(m.value)} из ${n(m.next)}" style="width:100%;height:10px;accent-color:var(--accent)"></progress><p class="micro-note">${m.reached!==null?`Веха ${n(m.reached)} пройдена · `:""}Следующая: ${n(m.next)}</p></div>`).join("")}</div><p class="micro-note">За выбранный период и только по сохранённым играм. Убийства и помощь — из официального KDA (${progress.officialKdaGames} из ${progress.games} игр). Известный исход: ${progress.knownResults} игр.</p><h3>Серии в истории</h3><p>Лучшая серия побед: <b>${s.bestWins}</b>. ${s.currentWins?`Сейчас побед подряд: <b>${s.currentWins}</b>.`:s.currentLosses?`Сейчас поражений подряд: <b>${s.currentLosses}</b>.`:"Текущая серия неизвестна."}</p><p class="micro-note">По ${s.datedGames} играм с известной датой. Неизвестный исход прерывает серию; пропущенные игры могут изменить результат.</p><h3>Покупки относительно себя</h3><p class="sub">Последняя игра на герое — рядом с вашей обычной скоростью покупки в том же режиме.</p>${progress.benchmarks.length?progress.benchmarks.slice(0,4).map(b=>benchmarkRow(b,progress.account,progress.period)).join("")+(progress.benchmarks.length>4?`<details class="fold"><summary>Все сравнения · ${progress.benchmarks.length}</summary>${progress.benchmarks.slice(4).map(b=>benchmarkRow(b,progress.account,progress.period)).join("")}</details>`:""):`<p class="empty">Пока мало сравнимых покупок. Нужны последняя игра и минимум 5 других игр на том же герое в том же режиме с этим предметом.</p>`}<p class="micro-note">Проверено реплеев: ${progress.benchmarkCoverage.replays} из ${progress.benchmarkCoverage.considered} выбранных; максимум 100 последних измеренных игр. Сравнивается первая зафиксированная покупка, а не доставка. Более ранняя покупка сама по себе не означает лучшую игру.</p>`;
}
