import { PLAYERS } from "../config.js";
import { HERO_CATALOG } from "../hero-catalog.js";
import type { Period, PlayerProfile } from "../player-profile.js";
import { groupActions } from "../action-counts.js";
import { esc, layout } from "./render.js";
const n=(x:number)=>x.toLocaleString("ru-RU");
const pct=(a:number,b:number)=>!b?"—":a>0&&a/b<.01?"<1%":Math.round(a/b*100)+"%";
const nick=(id:number)=>PLAYERS.find(p=>p.steamId===id)?.dotaName??String(id);
const date=(ts:number|null, short=false)=>ts?new Date(ts*1000).toLocaleDateString("ru-RU",{timeZone:"Europe/Moscow",day:"numeric",month:"short",...(short?{}:{year:"numeric"})}):"Дата неизвестна";
const time=(ts:number|null)=>ts?new Date(ts*1000).toLocaleTimeString("ru-RU",{timeZone:"Europe/Moscow",hour:"2-digit",minute:"2-digit"}):"";
const duration=(sec:number)=>`${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,"0")}`;
const art=(hero:string)=>{
  const h=HERO_CATALOG.find(h=>h.localized_name===hero);
  return h?`https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/${h.name.replace("npc_dota_hero_","")}.png`:"";
};
const portrait=(hero:string)=>art(hero)?`<img class="hero-thumb" loading="lazy" src="${art(hero)}" alt="" width="52" height="30">`:"";
const periods=(period:Period,base:string)=>`<nav class="periods" aria-label="Период статистики">${([["7","7 дней"],["30","30 дней"],["all","Вся история"]] as const).map(([v,l])=>`<a href="${base}?period=${v}" ${period===v?'aria-current="page" class="selected"':""}>${l}</a>`).join("")}</nav>`;
const empty=(text:string)=>`<p class="empty">${text}</p>`;
const SECTION_IDS:Record<string,string>={"apm-panel":"apm","heroes-panel":"heroes","partners-panel":"partners","history-panel":"history"};
const section=(eyebrow:string,title:string,description:string,body:string,cls="")=>`<section ${SECTION_IDS[cls]?`id="${SECTION_IDS[cls]}"`:""} class="panel ${cls}"><div class="section-head"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p class="sub">${description}</p></div></div>${body}</section>`;
const css=`
.site-nav{display:flex;align-items:center;gap:22px;padding-bottom:18px;border-bottom:1px solid var(--line);font-size:13px}.site-nav a{text-decoration:none}.site-nav .brand{font-weight:800;letter-spacing:.13em;margin-right:auto}.site-nav a:hover{color:var(--accent)}
.profile-page{display:contents}.profile-head{position:relative;overflow:hidden;background:var(--surface);border:1px solid var(--line);border-radius:18px;padding:34px}.profile-head h1{font-size:clamp(30px,5vw,48px);line-height:1.1;max-width:75%;overflow-wrap:anywhere;position:relative}.profile-head .sub{margin-top:14px;position:relative;max-width:70%}.profile-head .hero-art{position:absolute;right:0;top:0;height:100%;width:39%;object-fit:cover;opacity:.19;mask-image:linear-gradient(90deg,transparent,#000 70%)}
.eyebrow{font-size:10px;letter-spacing:.15em;text-transform:uppercase;color:var(--accent);font-weight:750;margin:0 0 10px}.profile-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.periods{display:flex;gap:4px;padding:4px;background:var(--surface);border:1px solid var(--line);border-radius:10px}.periods a{padding:7px 12px;text-decoration:none;font-size:12px;border-radius:6px}.periods .selected{background:var(--ink);color:var(--surface)}
.profile-jumps{display:flex;gap:8px 18px;flex-wrap:wrap;margin-top:-6px;font-size:11px;color:var(--muted)}.profile-jumps a{text-decoration:none}.profile-jumps a:hover{color:var(--ink)}section[id]{scroll-margin-top:16px}.profile-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metric{padding:20px;background:var(--surface);border:1px solid var(--line);border-radius:12px}.metric-value{font-size:34px;letter-spacing:-.05em;font-weight:750;line-height:1.3;font-variant-numeric:tabular-nums}.metric .sub{font-size:11px;margin-top:4px}.metric-label{font-size:11px;color:var(--muted)}.profile-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(0,1fr);gap:18px}.panel{min-width:0;border:1px solid var(--line);border-radius:14px;background:var(--surface);padding:24px}.panel h2{font-size:20px;letter-spacing:-.03em;margin:0 0 5px}.panel .eyebrow{margin-bottom:7px}.section-head{margin-bottom:22px}.empty{padding:25px 0;margin:0;color:var(--muted);font-size:13px}.apm-composition{display:flex;align-items:center;gap:28px;margin:20px 0}.ring{width:174px;min-width:130px;max-width:40%;height:auto;overflow:visible}.ring text{fill:var(--ink);font-family:inherit}.ring .ring-value{font-size:26px;font-weight:750;letter-spacing:-1px}.ring .ring-label{font-size:9px;fill:var(--muted)}.legend{flex:1;min-width:0}.legend-row{display:grid;grid-template-columns:9px minmax(0,1fr) auto;gap:9px;align-items:center;margin:13px 0;font-size:12px}.legend-row i{width:8px;height:8px;border-radius:3px}.legend-row small{display:block;font-size:10px;color:var(--muted)}.legend-row b{font-variant-numeric:tabular-nums;font-size:14px}.micro-note{font-size:11px;color:var(--muted);line-height:1.65;margin:12px 0 0}.details{border-top:1px solid var(--line);margin-top:18px;padding-top:14px;font-size:12px}.details summary{cursor:pointer;color:var(--muted)}.details table{font-size:11px}.details td:first-child{white-space:normal;overflow-wrap:anywhere}.command-type{font-family:ui-monospace,monospace;font-size:10px}.timeline{width:100%;height:auto;display:block;overflow:visible}.timeline text{fill:var(--muted);font-size:10px}.timeline a:hover circle,.timeline a:focus circle{stroke:var(--ink);stroke-width:3}.chart-key{display:flex;gap:15px;font-size:11px;color:var(--muted);margin-top:12px}.chart-key i{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:5px}.chart-summary{display:flex;gap:24px;margin-top:20px;padding-top:15px;border-top:1px solid var(--line)}.chart-summary b{display:block;font-size:22px;line-height:1.4}.chart-summary span{font-size:11px;color:var(--muted)}
.hero-cell{display:flex;align-items:center;gap:10px;min-height:32px}.hero-thumb{object-fit:cover;border-radius:5px;flex-shrink:0;background:var(--surface-2)}.bar-track{height:5px;border-radius:4px;background:var(--surface-2);overflow:hidden;margin-top:8px}.bar-track i{display:block;height:100%;background:var(--accent-soft);border-radius:4px}.partner-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;padding:12px 0;border-bottom:1px solid var(--line)}.partner-row:last-child{border:0}.partner-row a{text-decoration:none;font-weight:600;font-size:13px}.partner-row .sub{font-size:11px}.partner-row strong{font-size:18px;font-variant-numeric:tabular-nums}.small-insights{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.insight{border:1px solid var(--line);border-radius:12px;padding:20px;background:var(--surface-2)}.insight h3{font-size:13px;margin:0 0 8px}.insight p{font-size:12px;color:var(--muted);margin:0;line-height:1.6}.insight .insight-icon{color:var(--accent);font-size:19px;display:block;margin-bottom:12px}.time-bars{height:135px;display:flex;gap:16px;align-items:flex-end;padding-top:22px}.time-column{flex:1;text-align:center;display:flex;height:100%;flex-direction:column;justify-content:flex-end}.time-column b{font-size:12px;color:var(--muted);font-weight:500}.time-column i{display:block;background:var(--accent-soft);border-radius:5px 5px 0 0;margin:6px 0}.time-column span{font-size:10px;color:var(--muted)}.comparison-row{display:grid;grid-template-columns:115px minmax(0,1fr) 40px;align-items:center;gap:12px;margin:11px 0;font-size:11px}.comparison-row a{text-decoration:none;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.comparison-row .bar-track{margin:0}.comparison-row.current{font-weight:750}.comparison-row:not(.current) i{background:var(--muted);opacity:.35}.comparison-row b{text-align:right}.sample{font-weight:400;color:var(--muted);font-size:10px}
.breakdown-picker{font-size:11px;color:var(--muted)}.breakdown-picker>div{display:flex;gap:8px;margin-top:6px}.breakdown-picker select{min-width:0;flex:1;border:1px solid var(--line);border-radius:7px;padding:9px;background:var(--surface-2);color:var(--ink);font:inherit}.breakdown-picker button{border:1px solid var(--line);border-radius:7px;padding:9px 12px;background:var(--surface-2);color:var(--ink);cursor:pointer;font:inherit}.match-clock{display:block;color:var(--muted);font-size:10px}.profile-history a{text-decoration:none}.profile-history a:hover{text-decoration:underline}.profile-history th{font-size:10px}.outcome{font-size:11px;font-weight:700}.history-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:18px;font-size:12px}.history-footer a{padding:7px 10px;border:1px solid var(--line);border-radius:6px;text-decoration:none}.player-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.player-card{display:block;text-decoration:none;background:var(--surface);border:1px solid var(--line);border-radius:14px;padding:24px;position:relative;overflow:hidden;transition:border-color .15s,transform .15s}.player-card:hover{border-color:var(--accent);transform:translateY(-2px)}.player-card h2{font-size:19px;margin:16px 0 4px;position:relative;overflow-wrap:anywhere}.player-card .card-art{position:absolute;right:0;top:0;width:62%;height:110px;object-fit:cover;opacity:.18;mask-image:linear-gradient(90deg,transparent,#000)}.player-card .card-index{font-family:ui-monospace,monospace;font-size:11px;color:var(--accent);position:relative}.card-stats{display:flex;gap:20px;margin-top:22px;position:relative}.card-stats b{display:block;font-size:21px;font-variant-numeric:tabular-nums}.card-stats span{font-size:10px;color:var(--muted)}.player-card .card-foot{margin-top:20px;padding-top:12px;border-top:1px solid var(--line);font-size:11px;color:var(--muted)}.player-search{border:1px solid var(--line);background:var(--surface);color:var(--ink);border-radius:9px;padding:11px 14px;font:inherit;font-size:13px;width:240px;max-width:100%}.directory-head h1{font-size:38px;letter-spacing:-.04em}.directory-head .sub{margin-top:8px;max-width:580px}.profile-footer{font-size:11px;color:var(--muted);display:flex;gap:12px;justify-content:space-between;flex-wrap:wrap}.profile-footer a{text-decoration:none}a:focus-visible,input:focus-visible,summary:focus-visible{outline:2px solid var(--accent);outline-offset:4px}[hidden]{display:none!important}.form-search{display:flex;align-items:center;gap:10px}.form-search label{font-size:12px;color:var(--muted)}
@media(max-width:800px){.profile-grid{grid-template-columns:1fr}.player-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.small-insights{grid-template-columns:1fr}.profile-head{padding:26px}.profile-head h1{max-width:95%}.profile-head .sub{max-width:90%}.profile-metrics{gap:8px}.metric{padding:14px}.metric-value{font-size:28px}}
@media(max-width:480px){.wrap{padding:20px 14px 50px;gap:16px}.player-grid{grid-template-columns:1fr}.profile-metrics{grid-template-columns:repeat(2,1fr)}.panel{padding:20px}.apm-composition{gap:18px}.ring{min-width:105px}.legend-row{gap:6px;font-size:11px}.profile-head .hero-art{width:65%}.profile-toolbar{align-items:flex-start}.periods a{padding:7px 10px}.profile-head .sub{font-size:12px}.directory-head h1{font-size:32px}.profile-history td{font-size:12px}.form-search{width:100%}.player-search{flex:1}.site-nav{gap:15px}.comparison-row{grid-template-columns:105px minmax(0,1fr) 35px}}
@media(prefers-reduced-motion:reduce){.player-card{transition:none}.player-card:hover{transform:none}}
`;
function page(title:string,body:string,script="") {return layout(title,body,script,css);}
export function renderPlayers(profiles:PlayerProfile[],period:Period) {
  const sorted=[...profiles].sort((a,b)=>b.matches.length-a.matches.length||a.account-b.account);
  return page("Игроки стака · Пёсики",`<header class="directory-head"><p class="eyebrow">Пёсики / личное дело</p><h1>Один стак. Разный почерк.</h1><p class="sub">Герои, темп, напарники и маленькие закономерности. Всё, что накопилось в наших матчах, — в профиле каждого.</p></header>
  <div class="profile-toolbar">${periods(period,"/players")}<div class="form-search"><label for="player-search">Найти</label><input id="player-search" class="player-search" type="search" placeholder="Ник игрока" autocomplete="off"></div></div>
  <div class="player-grid">${sorted.map((p,i)=>`<a class="player-card" data-name="${esc(nick(p.account).toLocaleLowerCase("ru"))}" href="/player/${p.account}?period=${period}">${p.heroes[0]&&art(p.heroes[0].hero)?`<img class="card-art" src="${art(p.heroes[0].hero)}" alt="" loading="lazy">`:""}<span class="card-index">${String(i+1).padStart(2,"0")} / СТАК</span><h2>${esc(nick(p.account))}</h2><p class="sub">${p.heroes[0]?esc(p.heroes[0].hero)+` · ${p.heroes[0].games} игр`:"История ещё собирается"}</p><div class="card-stats"><div><b>${p.matches.length}</b><span>матчей</span></div><div><b>${pct(p.wins,p.known)}</b><span>побед</span></div><div><b>${p.avgApm??"—"}</b><span>APM · ${p.measured.length} игр</span></div></div><div class="card-foot">${p.matches[0]?`Последняя игра: ${date(p.matches[0].start,true)}`:"Появится после первой сохранённой игры"}<span style="float:right" aria-hidden="true">↗</span></div></a>`).join("")}</div><p id="no-players" class="empty" role="status" hidden>Такого ника в стаке нет.</p><p class="micro-note">${PLAYERS.length} игроков · Статистика только по сохранённым матчам выбранного периода. APM — среднее по играм с измерением.</p>`,
  `const search=document.getElementById('player-search');search.addEventListener('input',()=>{let shown=0;document.querySelectorAll('.player-card').forEach(card=>{card.hidden=!card.dataset.name.includes(search.value.trim().toLocaleLowerCase('ru'));if(!card.hidden)shown++});document.getElementById('no-players').hidden=shown>0;});`);
}
function composition(p:PlayerProfile, selectedMatch?:number) {
  const chosen=p.detailed.find(m=>m.id===selectedMatch);
  const detailed=chosen?[chosen]:p.detailed;
  const raw:Record<string,number>={};
  for(const m of detailed) for(const [k,v] of Object.entries(m.apm!.action_counts!)) raw[k]=(raw[k]??0)+v;
  const groups=groupActions(raw),total=groups.reduce((s,g)=>s+g.count,0);
  const seconds=detailed.reduce((s,m)=>s+m.apm!.duration_seconds,0);
  const picker=`<form class="breakdown-picker" action="/player/${p.account}#apm" method="get"><input type="hidden" name="period" value="${p.period}"><label for="breakdown-match">Разбивка</label><div><select id="breakdown-match" name="match"><option value="">Все игры с деталями (${p.detailed.length})</option>${p.detailed.map(m=>`<option value="${m.id}" ${chosen?.id===m.id?'selected':''}>${date(m.start,true)} ${time(m.start)} · ${esc(m.hero)} · ${m.apm!.apm} APM</option>`).join("")}</select><button type="submit">Показать</button></div></form>`;
  if(!p.detailed.length)return empty(p.measured.length?"Подробной разбивки пока нет. Общий APM уже виден в истории; типы команд появятся с новыми реплеями.":"Пока нет разобранных реплеев с APM. Когда появятся измерения, здесь будут видны все типы команд.");
  let offset=0;
  const arcs=groups.map(g=>{const share=total?g.count/total*100:0;const arc=`<circle cx="90" cy="90" r="72" fill="none" stroke="${g.color}" stroke-width="15" pathLength="100" stroke-dasharray="${share} ${100-share}" stroke-dashoffset="${-offset}" transform="rotate(-90 90 90)"><title>${g.label}: ${n(g.count)} (${pct(g.count,total)})</title></circle>`;offset+=share;return arc;}).join("");
  return `${picker}${chosen?`<p class="micro-note"><a href="/match/${chosen.id}">Матч ${chosen.id} ↗</a> · ${duration(chosen.apm!.duration_seconds)} · ${chosen.apm!.apm} APM</p>`:""}<div class="apm-composition"><svg class="ring" viewBox="0 0 180 180" role="img" aria-label="Доли типов команд по ${detailed.length} матчам"><circle cx="90" cy="90" r="72" fill="none" stroke="var(--line)" stroke-width="15"/>${arcs}<text x="90" y="88" text-anchor="middle" class="ring-value">${chosen?chosen.apm!.apm:detailed.length}</text><text x="90" y="107" text-anchor="middle" class="ring-label">${chosen?"APM в этом матче":"матчей с деталями"}</text></svg><div class="legend">${groups.map(g=>`<div class="legend-row"><i style="background:${g.color}"></i><span>${g.label}<small>${n(g.count)} команд · ${seconds?(g.count*60/seconds).toFixed(1).replace(".",","):"0"}/мин</small></span><b>${pct(g.count,total)}</b></div>`).join("")}</div></div>
  <p class="micro-note">${n(total)} команд · Разбивка есть в ${p.detailed.length} из ${p.measured.length} игр с APM. ${chosen?"Показан выбранный матч.":`Доли считаются по сумме команд этих ${detailed.length} игр.`}</p>
  <details class="details"><summary>Посмотреть конкретные команды</summary><div class="tablewrap" tabindex="0" role="region" aria-label="Таблица данных"><table><thead><tr><th>Команда из реплея</th><th>Количество</th><th>Доля</th></tr></thead><tbody>${Object.entries(raw).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<tr><td class="command-type">${esc(k.replace("DOTA_UNIT_ORDER_",""))}</td><td>${n(v)}</td><td>${pct(v,total)}</td></tr>`).join("")}</tbody></table></div></details>`;
}
function timeline(p:PlayerProfile) {
  const ms=[...p.measured].filter(m=>m.start!==null).reverse();
  if(!ms.length)return empty("Для графика нужны матчи с APM и известной датой.");
  const max=Math.max(...ms.map(m=>m.apm!.apm),1)*1.15,w=520,h=180;
  const x=(i:number)=>40+i*(w-60)/Math.max(ms.length-1,1), y=(a:number)=>h-20-a/max*(h-40);
  return `<svg class="timeline" viewBox="0 0 ${w} ${h}" role="group" aria-label="APM по ${ms.length} матчам от ${date(ms[0].start)} до ${date(ms.at(-1)!.start)}">
  ${[0,Math.round(max/2),Math.round(max)].map(v=>`<line x1="40" x2="${w-10}" y1="${y(v)}" y2="${y(v)}" stroke="var(--line)"/><text x="0" y="${y(v)+4}">${v}</text>`).join("")}
  <polyline points="${ms.map((m,i)=>`${x(i)},${y(m.apm!.apm)}`).join(" ")}" fill="none" stroke="var(--muted)" stroke-opacity=".35" stroke-width="1.5"/>
  ${ms.map((m,i)=>`<a href="/match/${m.id}" aria-label="${esc(m.hero)}, ${m.apm!.apm} APM, ${date(m.start)}"><circle cx="${x(i)}" cy="${y(m.apm!.apm)}" r="4" fill="${m.win===null?'var(--muted)':m.win?'var(--good)':'var(--bad)'}"><title>${esc(m.hero)} · ${m.apm!.apm} APM · ${date(m.start)}</title></circle></a>`).join("")}</svg><div class="profile-toolbar sub"><span>${date(ms[0].start,true)}</span><span>${date(ms.at(-1)!.start,true)}</span></div><div class="chart-key"><span><i style="background:var(--good)"></i>победа</span><span><i style="background:var(--bad)"></i>поражение</span><span>точка → матч</span></div><div class="chart-summary"><div><b>${p.median}</b><span>медиана APM</span></div><div><b>${p.peak?.apm!.apm??"—"}</b><span>максимум</span></div><div><b>${ms.length}</b><span>точек на графике</span></div></div><p class="micro-note">Матчи идут по порядку, интервалы между точками одинаковые. Герой и длительность игры влияют на темп.</p>`;
}
function insights(p:PlayerProfile) {
  const items:{icon:string;title:string;text:string}[]=[];
  const top=p.heroes[0];if(top)items.push({icon:"◇",title:`Чаще всего — ${top.hero}`,text:`${top.games} из ${p.matches.length} матчей. Всего в истории ${p.heroes.length} разных героев.`});
  if(p.total)items.push({icon:"↗",title:`${pct(p.groups[0].count,p.total)} команд — движение`,text:`По ${p.detailed.length} матчам с подробностями. Повторные приказы тоже считаются: отсюда может набираться большой APM.`});
  if(p.partners[0])items.push({icon:"◎",title:`Частый напарник — ${p.partners[0].name}`,text:`${p.partners[0].games} совместных игр на одной стороне, ${p.partners[0].wins} побед. Это описание выборки, а не доказательство «идеального дуо».`});
  return items.length?`<div class="small-insights">${items.map(i=>`<article class="insight"><span class="insight-icon" aria-hidden="true">${i.icon}</span><h3>${esc(i.title)}</h3><p>${esc(i.text)}</p></article>`).join("")}</div>`:"";
}
export function renderPlayer(p:PlayerProfile,all:PlayerProfile[],requestedPage=1,selectedMatch?:number) {
  const base=`/player/${p.account}`,pages=Math.max(1,Math.ceil(p.matches.length/20)),pageNum=Math.min(pages,Math.max(1,requestedPage)), slice=p.matches.slice((pageNum-1)*20,pageNum*20);
  const stat=(label:string,value:string,sub:string)=>`<div class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><p class="sub">${sub}</p></div>`;
  const peers=all.filter(x=>x.avgApm!==null).sort((a,b)=>b.avgApm!-a.avgApm!),maxApm=Math.max(1,...peers.map(x=>x.avgApm!));
  const top=p.heroes[0];
  if(!p.matches.length) return page(`${nick(p.account)} · Профиль Пёсиков`, `<header class="profile-head"><p class="eyebrow">Пёсики / профиль игрока</p><h1>${esc(nick(p.account))}</h1><p class="sub">История игр и личный темп.</p></header><div class="profile-toolbar">${periods(p.period,base)}</div>${section("Начало истории","Пока без матчей","В этом периоде нет сохранённых игр.",`<p class="empty">${p.period!=="all"?`<a href="${base}?period=all">Посмотреть всю историю →</a>`:"Новые матчи появятся после очередного часового обновления."}</p>`)}<div class="profile-footer"><a href="/players?period=${p.period}">← Все игроки</a></div>`);
  const body=`<header class="profile-head">${top&&art(top.hero)?`<img class="hero-art" src="${art(top.hero)}" alt="">`:""}<p class="eyebrow">Пёсики / профиль игрока</p><h1>${esc(nick(p.account))}</h1><p class="sub">${top?`${esc(top.hero)} — самый частый герой · ${p.heroes.length} героев в выбранном периоде`:"В выбранном периоде пока нет сохранённых матчей."}</p></header>
  <div class="profile-toolbar">${periods(p.period,base)}<span class="sub">${p.dated?`${date(p.matches.filter(m=>m.start).at(-1)!.start)} — ${date(p.matches.find(m=>m.start)!.start)}`:"Нет датированных матчей"} · МСК${p.matches.length>p.dated?` · ${p.matches.length-p.dated} без даты`:""}</span></div>
  <nav class="profile-jumps" aria-label="Разделы профиля"><a href="#apm">Разбивка APM ↓</a><a href="#heroes">Герои ↓</a><a href="#partners">Напарники ↓</a><a href="#history">Матчи ↓</a></nav>
  <div class="profile-metrics">${stat("Матчи",String(p.matches.length),"в нашей сохранённой истории")}${stat("Победы",pct(p.wins,p.known),`${p.wins} В / ${p.known-p.wins} П${p.known<p.matches.length?` · ${p.matches.length-p.known} без результата`:""}`)}${stat("Средний APM",String(p.avgApm??"—"),`${p.measured.length} из ${p.matches.length} матчей с измерением`)}${stat("В игре",p.hoursPlayed.toFixed(1).replace(".",",")+" ч",`${p.heroes.length} разных героев`)}</div>
  ${insights(p)}
  <div class="profile-grid">${section("Из чего складывается темп","APM под микроскопом","Один приказ героям = одна команда. Повторные тоже считаем.",composition(p,selectedMatch),"apm-panel")}${section("История темпа","От матча к матчу","Каждая точка — отдельная игра с сохранённым APM.",timeline(p))}</div>
  <div class="profile-grid">${section("Пул героев","Кого выбирает","Частота пика, результат и средний темп на каждом герое.",p.heroes.length?`<div class="tablewrap" tabindex="0" role="region" aria-label="Таблица данных"><table><thead><tr><th>Герой</th><th>Игры</th><th>Победы</th><th>APM</th></tr></thead><tbody>${p.heroes.slice(0,8).map(h=>`<tr><td><div class="hero-cell">${portrait(h.hero)}<span>${esc(h.hero)}</span></div></td><td>${h.games}</td><td>${pct(h.wins,h.known)} <span class="sample">${h.wins}/${h.known}</span></td><td>${h.apm??"—"} <span class="sample">${h.apmGames?`· ${h.apmGames} игр`:""}</span></td></tr>`).join("")}</tbody></table></div>${p.heroes.length>8?`<details class="details"><summary>Ещё ${p.heroes.length-8} героев</summary>${p.heroes.slice(8).map(h=>`<div class="partner-row"><span>${esc(h.hero)}</span><span>${h.games} игр · ${pct(h.wins,h.known)} побед</span></div>`).join("")}</details>`:""}`:empty("Герои появятся вместе с матчами."),"heroes-panel")}
  ${section("Вместе на одной стороне","С кем играет","Совместные матчи среди наших игроков.",p.partners.length?p.partners.slice(0,6).map(t=>`<div class="partner-row"><div><a href="/player/${t.id}?period=${p.period}">${esc(t.name)} ↗</a><p class="sub">${t.games} игр · ${t.wins} В / ${t.known-t.wins} П</p></div><strong>${pct(t.wins,t.known)}</strong></div>`).join("")+`<p class="micro-note">Состав команд известен для ${p.teammateCoverage} из ${p.matches.length} матчей. Маленькие выборки особенно случайны.</p>`:empty("Пока нет разобранных совместных матчей."),"partners-panel")}</div>
  <div class="profile-grid">${section("Контекст стака","Темп рядом с остальными","Средний APM по доступным играм того же периода.",peers.length?peers.map(q=>`<div class="comparison-row ${q.account===p.account?'current':''}"><a href="/player/${q.account}?period=${p.period}" title="${esc(nick(q.account))} · ${q.measured.length} матчей">${esc(nick(q.account))}<br><span class="sample">${q.measured.length} матчей</span></a><div class="bar-track"><i style="width:${q.avgApm!/maxApm*100}%"></i></div><b>${q.avgApm}</b></div>`).join("")+`<p class="micro-note">Это темп команд, а не рейтинг силы. Наборы матчей, героев и ролей у игроков различаются.</p>`:empty("Пока нет измерений APM."))}
  ${section("Ритм игр","Когда заходит","Время начала матчей по Москве, UTC+3.",p.dated?`<div class="time-bars">${p.hours.map((v,i)=>`<div class="time-column"><b>${v}</b><i style="height:${v?Math.max(3,v/Math.max(...p.hours)*90):0}px"></i><span>${["00–06","06–12","12–18","18–24"][i]}</span></div>`).join("")}</div><p class="micro-note">${p.dated} матчей с известной датой. Это начало игры, а не распределение всех минут онлайн.</p>${p.longest?`<div class="details"><p class="eyebrow">Самая долгая катка</p><h2>${duration(p.longest.duration)}</h2><p class="sub">${esc(p.longest.hero)} · <a href="/match/${p.longest.id}">${date(p.longest.start,true)} ↗</a></p></div>`:""}${p.peak?`<div class="details"><p class="eyebrow">Личный пик темпа в выборке</p><h2>${p.peak.apm!.apm} APM</h2><p class="sub">${esc(p.peak.hero)} · ${n(p.peak.apm!.actions)} команд · <a href="/match/${p.peak.id}">открыть матч ↗</a></p></div>`:""}`:empty("Для ритма нужны известные даты игр."))}</div>
  ${section("Все исходные игры","История матчей",`${p.matches.length} матчей · герой, K / D / A и APM. Прочерк означает отсутствие данных.`,slice.length?`<div class="tablewrap" tabindex="0" role="region" aria-label="Таблица данных"><table class="profile-history"><thead><tr><th>Дата · МСК</th><th>Герой</th><th>Итог</th><th>K / D / A</th><th>APM</th><th>Время</th></tr></thead><tbody>${slice.map(m=>`<tr><td><a href="/match/${m.id}" title="Матч ${m.id}">${date(m.start,true)} ↗<span class="match-clock">${time(m.start)}</span></a></td><td><div class="hero-cell">${portrait(m.hero)}<span>${esc(m.hero)}</span></div></td><td class="outcome ${m.win===null?'':m.win?'good':'bad'}">${m.win===null?'—':m.win?'Победа':'Поражение'}</td><td class="mono" title="${esc(m.kdaSource??'Нет подтверждённого KDA')}">${m.kda?m.kda.join(" / "):"—"}</td><td class="mono">${m.apm?.action_counts!==undefined?`<a href="${base}?period=${p.period}&match=${m.id}#apm" title="Разбивка команд в этом матче">${m.apm.apm} ↗</a>`:m.apm?.apm??"—"}</td><td class="mono">${duration(m.duration)}</td></tr>`).join("")}</tbody></table></div><div class="history-footer"><span>${(pageNum-1)*20+1}–${Math.min(pageNum*20,p.matches.length)} из ${p.matches.length}</span><div>${pageNum>1?`<a href="${base}?period=${p.period}&page=${pageNum-1}#history">← Назад</a> `:""}${pageNum<pages?`<a href="${base}?period=${p.period}&page=${pageNum+1}#history">Дальше →</a>`:""}</div></div>`:empty("В выбранном периоде матчей нет."),"history-panel")}
  <details class="panel details"><summary>Откуда цифры и что они означают</summary><p class="micro-note">Здесь только накопленная история бота, не вся карьера Dota. Результаты и KDA берём из сохранённых ответов OpenDota или сводок сайта; KDA без такого источника не показываем. Реплеи дают героя, сторону и команды. Статистика обновляется после часового опроса и разбора доступных реплеев.</p><p class="micro-note">APM = число сообщений с приказами × 60 / точная длительность игры, с округлением вниз. Считаем от начала игры до её завершения; один приказ нескольким юнитам считается один раз. Средний APM в профиле — среднее значений матчей. Разбивка — сумма типов команд по играм с подробностями. Это не физические клики, не число успешных атак или заклинаний; способности и активные предметы используют одинаковые типы приказов. Отсутствие данных не считается нулём.</p><p class="micro-note">Повторные перемещения включены. Hold/Stop, обучение навыков, руны и неизвестные типы попадают в «Стоп и остальное». Для старых игр без исходного реплея восстановить состав APM нельзя. Покрытие: APM ${p.measured.length}/${p.matches.length}, подробности ${p.detailed.length}/${p.matches.length}, KDA ${p.matches.filter(m=>m.kda).length}/${p.matches.length}.</p></details>
  <div class="profile-footer"><a href="/players?period=${p.period}">← Все игроки</a><span>Сохранено у Пёсиков · Steam ${p.account}</span></div>`;
  return page(`${nick(p.account)} · Профиль Пёсиков`,body);
}
