/** Navigation surfaces: visible destinations, stable mobile touch targets. */
export const NAV_CSS = `
.breadcrumbs{display:flex;flex-wrap:wrap;align-items:center;gap:4px 8px;font-size:12px;line-height:1.5;color:var(--muted);margin:0 0 8px;min-width:0}.breadcrumbs a{display:inline-flex;align-items:center;min-height:44px;color:var(--muted);text-decoration:none}.breadcrumbs a:hover{color:var(--ink);text-decoration:underline}.breadcrumbs [aria-current=page]{color:var(--ink);overflow-wrap:anywhere}
.match-navigation{position:sticky;top:8px;z-index:30;border:1px solid var(--line);border-radius:5px;background:var(--surface);box-shadow:0 3px 12px #00000012;overflow:visible;min-width:0}.match-groups{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0;padding:3px;border-bottom:1px solid var(--line)}.match-groups a{display:flex;align-items:center;justify-content:center;min-height:44px;padding:6px 3px;font-size:12px;line-height:1.25;font-weight:650;text-decoration:none;text-align:center;color:var(--muted);border-radius:3px;min-width:0;overflow-wrap:anywhere}.match-groups a[aria-current=location],.match-groups a[aria-current=page],.match-groups a[aria-current=true],.match-groups a.active{color:var(--accent);background:var(--surface-2)}
.match-navigation .match-subnav.profile-jumps{position:static;display:flex;flex-wrap:wrap;overflow:visible;scroll-snap-type:none;border:0;border-radius:0;box-shadow:none;background:transparent;gap:0;padding:3px;margin:0;min-width:0}.match-navigation .match-subnav a{flex:1 1 80px;min-width:0;min-height:44px;padding:7px 8px;white-space:normal;text-align:center;line-height:1.3;border-left:0!important;margin-left:0!important;font-size:11px;justify-content:center}.match-navigation .match-subnav a[hidden]{display:none!important}.match-navigation a:focus-visible{outline:2px solid var(--accent);outline-offset:-3px}
.profile-jumps:not(.match-tabs){display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0;overflow:visible;scroll-snap-type:none;padding:3px;min-width:0}.profile-jumps:not(.match-tabs)>a{min-width:0;min-height:44px;padding:6px 3px;white-space:normal;text-align:center;justify-content:center;line-height:1.3;font-size:11px}.profile-view .panel[id],.profile-view .fold[id],.profile-section[id]{scroll-margin-top:var(--section-offset,125px)}.match-view .insight-panel[id],.match-view .ov-moment[id]{scroll-margin-top:var(--section-offset,125px)}
.mobile-site-nav{display:none}
@media(max-width:600px){body{padding-bottom:calc(76px + env(safe-area-inset-bottom,0px))}.mobile-site-nav{display:grid;grid-template-columns:1fr 1fr;position:fixed;left:0;right:0;bottom:0;z-index:60;gap:6px;background:var(--surface);border-top:1px solid var(--line);padding:5px 10px calc(5px + env(safe-area-inset-bottom,0px));box-shadow:0 -3px 12px #00000010}.mobile-site-nav a{display:flex;align-items:center;justify-content:center;min-height:44px;gap:7px;font-size:12px;font-weight:650;color:var(--muted);text-decoration:none;border-radius:4px}.mobile-site-nav a[aria-current=page],.mobile-site-nav a[aria-current=true],.mobile-site-nav a.active{background:var(--surface-2);color:var(--accent)}.mobile-site-nav a:focus-visible{outline:2px solid var(--accent);outline-offset:-2px}.copy-status,#copy-status{bottom:calc(74px + env(safe-area-inset-bottom,0px))!important}.match-navigation{top:6px}.match-groups a{font-size:11px}.match-navigation .match-subnav a{flex-basis:75px;padding:6px 4px;font-size:10px}.profile-jumps:not(.match-tabs){top:6px}.profile-jumps:not(.match-tabs)>a{font-size:10px}.profile-view .panel[id],.profile-view .fold[id],.profile-section[id]{scroll-margin-top:var(--section-offset,125px)}.match-view .insight-panel[id],.match-view .ov-moment[id]{scroll-margin-top:var(--section-offset,165px)}}
`;
