import type {ParsedMatch} from '../replay.js';
import {buildMatchCombatWindow} from '../match-combat-window.js';
import {heroName} from '../player-profile.js';
import {gameIcon} from './game-icon.js';
import {esc} from './render.js';
const n=(v:number)=>Math.round(v).toLocaleString('ru-RU');
const compact=(v:number)=>v>=1000?(v/1000).toLocaleString('ru-RU',{maximumFractionDigits:1})+'к':n(v);
const clock=(v:number)=>`${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`;
/** Enemy real-hero targets only; no inference that damage implies focus, kills, or good target selection. */
export function renderTeamDamageMatrix(match:ParsedMatch,startSeconds=0,endSeconds=match.apm_duration_seconds??match.duration_min*60):string {
 const w=buildMatchCombatWindow(match,startSeconds,endSeconds);
 if(w.coverage.state==='missing')return '<p class="ep-note">Матрица урона появится после сохранения секундного журнала реплея.</p>';
 if(w.coverage.state==='invalid'||!w.actualWindow)return '<p class="ep-note">Матрица урона недоступна: журнал не прошёл проверку.</p>';
 const partial=w.coverage.state!=='complete';
 const sides=(['radiant','dire'] as const).map(side=>{
  const attackers=w.players.filter(p=>p.team===side),targets=w.players.filter(p=>p.team!==side);
  // A fixed 5×5 chart must not silently hide unknown/extra participants or merge duplicate heroes.
  if(attackers.length!==5||targets.length!==5||new Set(w.players.map(p=>p.hero)).size!==10)return null;
  const rows=attackers.map(a=>targets.map(t=>a.enemyDamage.byTarget[t.hero]??0)),max=Math.max(0,...rows.flat()),total=rows.flat().reduce((a,b)=>a+b,0);
  const cells=attackers.map((a,ai)=>targets.map((t,ti)=>({from:a.heroIndex,to:t.heroIndex,attacker:heroName(a.hero),target:heroName(t.hero),damage:rows[ai][ti],attackerDamage:a.recorded.damageEnemies,targetDamage:rows.reduce((s,r)=>s+r[ti],0)}))).flat();
  const best=[...cells].sort((a,b)=>b.damage-a.damage)[0];
  const axis=(hero:string)=>`${gameIcon(hero,'hero')}<span class="dm-axis-name">${esc(heroName(hero))}</span>`;
  return {side,html:`<div class="dm-side" data-damage-side="${side}"><p class="dm-direction">${side==='radiant'?'Radiant → Dire':'Dire → Radiant'} <span>· ${n(total)} ${partial?'записанного ':''}урона врагам</span></p><table class="dm-table"><caption>Строки — атакующие, столбцы — цели. Нажми число.</caption><thead><tr><th scope="col"><span class="dm-axis-key">↓ / →</span></th>${targets.map(t=>`<th scope="col" title="${esc(heroName(t.hero))}">${axis(t.hero)}</th>`).join('')}</tr></thead><tbody>${attackers.map((a,ai)=>`<tr><th scope="row" title="${esc(heroName(a.hero))}">${axis(a.hero)}</th>${targets.map((t,ti)=>{const c=cells[ai*5+ti];return `<td><button type="button" class="dm-cell" data-matrix-from="${c.from}" data-matrix-to="${c.to}" data-matrix-damage="${c.damage}" aria-label="${esc(c.attacker)} → ${esc(c.target)}: ${n(c.damage)} ${partial?'записанного ':''}урона" aria-pressed="${c===best}" style="--dm-strength:${max?c.damage/max*.32:0}">${compact(c.damage)}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table><div class="dm-selection" aria-live="polite"><strong data-matrix-pair>${esc(best.attacker)} → ${esc(best.target)}</strong><b data-matrix-value>${n(best.damage)}</b><p data-matrix-detail>${best.damage?'Самая большая пара урона этой стороны.':'В этом окне урон этой стороны врагам не записан.'}</p></div></div>`,cells};
 });
 if(sides.some(s=>!s))return '<p class="ep-note">Для матрицы нужны два полных состава по пять разных героев.</p>';
 const data={partial,sides:sides.map(s=>({side:s!.side,cells:s!.cells}))};
 return `<section id="team-damage-matrix" class="damage-matrix" aria-labelledby="damage-matrix-title"><p class="pulse-eyebrow">Кого реально били</p><h3 id="damage-matrix-title">Урон между героями</h3><p class="ep-note">${clock(w.actualWindow.startSecond)}–${clock(w.actualWindow.endSecondExclusive)} · вся карта. Числа показывают урон, а не убийства или правильность выбора цели.</p>${partial?'<p class="cw-warning">Журнал окна неполный. Показаны только сохранившиеся события, не полные итоги.</p>':''}<div class="dm-switch" role="group" aria-label="Атакующая команда"><button type="button" data-matrix-side="radiant" aria-pressed="true">Radiant атакует</button><button type="button" data-matrix-side="dire" aria-pressed="false">Dire атакует</button></div>${sides.map(s=>s!.html).join('')}<p class="ep-note">Насыщенность — относительно самой большой пары выбранной стороны. Урон реальным вражеским героям, включая источники с подтверждённым владельцем. Урон себе, союзникам и от неизвестных владельцев исключён. Это не список участников одной драки. Правая граница интервала не включена.</p><script type="application/json" class="damage-matrix-data">${JSON.stringify(data).replace(/</g,'\\u003c')}</script></section>`;
}
export const TEAM_DAMAGE_MATRIX_SCRIPT=`{
 const root=document.getElementById('team-damage-matrix');
 if(root){const data=JSON.parse(root.querySelector('.damage-matrix-data').textContent),state=new URL(location.href);let side=state.searchParams.get('matrixSide')==='dire'?'dire':'radiant';const chosen={};
 const fmt=v=>Math.round(v).toLocaleString('ru-RU'),pct=(v,total)=>total?(v/total*100).toLocaleString('ru-RU',{maximumFractionDigits:1})+'%':'—';
 function render(update=false){const current=data.sides.find(s=>s.side===side);let cell=chosen[side]||[...current.cells].sort((a,b)=>b.damage-a.damage)[0];chosen[side]=cell;root.querySelectorAll('[data-damage-side]').forEach(p=>p.hidden=p.dataset.damageSide!==side);root.querySelectorAll('[data-matrix-side]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.matrixSide===side)));const panel=root.querySelector('[data-damage-side="'+side+'"]');panel.querySelectorAll('.dm-cell').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.matrixFrom)===cell.from&&Number(b.dataset.matrixTo)===cell.to)));panel.querySelector('[data-matrix-pair]').textContent=cell.attacker+' → '+cell.target;panel.querySelector('[data-matrix-value]').textContent=fmt(cell.damage)+(data.partial?' записано':' урона');panel.querySelector('[data-matrix-detail]').textContent=cell.damage?pct(cell.damage,cell.attackerDamage)+' урона этого героя врагам · '+pct(cell.damage,cell.targetDamage)+' урона цели от выбранной команды.':(data.partial?'В сохранённой части окна урон этой пары не записан.':'В этом окне урон этой пары не записан.');if(update){const u=new URL(location.href);u.searchParams.set('matrixSide',side);u.searchParams.set('matrixFrom',cell.from);u.searchParams.set('matrixTo',cell.to);u.hash='team-damage-matrix';history.replaceState(null,'',u.pathname+u.search+u.hash);}}
 const initial=data.sides.find(s=>s.side===side).cells.find(c=>String(c.from)===state.searchParams.get('matrixFrom')&&String(c.to)===state.searchParams.get('matrixTo'));if(initial)chosen[side]=initial;
 root.querySelectorAll('[data-matrix-side]').forEach(b=>b.addEventListener('click',()=>{side=b.dataset.matrixSide;render(true);}));root.querySelectorAll('.dm-cell').forEach(b=>b.addEventListener('click',()=>{chosen[side]=data.sides.find(s=>s.side===side).cells.find(c=>c.from===Number(b.dataset.matrixFrom)&&c.to===Number(b.dataset.matrixTo));render(true);}));render();
 }
}`;
export const TEAM_DAMAGE_MATRIX_CSS=`.damage-matrix{margin-top:24px;padding-top:24px;border-top:1px solid var(--line)}.damage-matrix>.pulse-eyebrow{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.damage-matrix>.ep-note{font-size:12px;line-height:1.6;color:var(--muted)}.damage-matrix h3{font-size:24px;margin:8px 0 12px}.dm-switch{display:flex;gap:6px;margin:16px 0}.dm-switch button{flex:1;min-width:0;min-height:44px;border:1px solid var(--line);border-radius:6px;background:var(--surface);color:var(--ink);font:inherit;font-size:12px}.dm-switch button[aria-pressed=true]{border-color:var(--ink);font-weight:700;background:var(--surface-2)}.dm-direction{font-weight:700;font-size:13px;line-height:1.5}.dm-direction span{font-weight:400;color:var(--muted)}.dm-table{width:100%;table-layout:fixed;border-collapse:separate;border-spacing:2px}.dm-table caption{caption-side:top;text-align:left;font-size:12px;color:var(--muted);padding:0 0 10px}.dm-table th:first-child{width:34px}.dm-table th,.dm-table td{padding:0;min-width:0;vertical-align:middle;text-align:center}.dm-table th{height:36px}.dm-table .game-icon.is-hero{width:30px!important;height:20px!important;min-width:0}.dm-axis-name{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.dm-axis-key{font-size:9px;color:var(--muted);font-weight:400}.dm-cell{position:relative;isolation:isolate;display:block;width:100%;min-height:44px;padding:1px;border:1px solid transparent;border-radius:4px;background:var(--surface-2);color:var(--ink);font:inherit;font-size:11px;font-weight:700;font-variant-numeric:tabular-nums;cursor:pointer;white-space:nowrap}.dm-cell::before{content:'';position:absolute;inset:0;border-radius:3px;background:var(--radiant);opacity:var(--dm-strength);z-index:-1}.dm-side[data-damage-side=dire] .dm-cell::before{background:var(--dire)}.dm-cell[aria-pressed=true]{border-color:var(--ink);box-shadow:inset 0 0 0 1px var(--ink)}.dm-cell:focus-visible,.dm-switch button:focus-visible{outline:2px solid var(--ink);outline-offset:2px}.dm-selection{margin-top:14px;padding:14px;background:var(--surface-2);border:1px solid var(--line);border-radius:8px}.dm-selection>strong{display:block;font-size:14px;overflow-wrap:anywhere}.dm-selection>b{display:block;font-size:28px;margin-top:7px;font-variant-numeric:tabular-nums}.dm-selection>p{font-size:12px;line-height:1.5;color:var(--muted);margin-bottom:0}@media(min-width:600px){.dm-table th:first-child{width:88px}.dm-table .game-icon.is-hero{width:48px!important;height:30px!important}.dm-cell{min-height:58px;font-size:14px}.dm-table{border-spacing:5px}}`;
