export const WARD_CSS=`
.ward-filters{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0 14px}.ward-filters label{font-size:12px;color:var(--muted);line-height:1.5;min-width:0}.ward-filters select{display:block;width:100%;min-width:0;margin-top:7px}.ward-legend{display:flex;flex-wrap:wrap;gap:8px 18px;padding:12px 0;border-bottom:1px solid var(--line);font-size:12px;color:var(--muted)}.ward-legend>span{display:inline-flex;align-items:center;gap:7px;min-height:28px}.ward-legend svg{width:28px;height:24px;flex:none;fill:none;stroke:var(--ink);stroke-width:2}.ward-legend .ward-observer{stroke:var(--ward-observer)}.ward-legend .ward-sentry{stroke:var(--ward-sentry)}.ward-map{--ward-observer:#FFD166;--ward-sentry:#68C8FF}.ward-legend{--ward-observer:#9A6B14;--ward-sentry:#2677AC}.ward-map .map-selection{min-height:44px;padding:12px;background:var(--surface-2);border-top:1px solid var(--line);margin:0;font-size:13px;line-height:1.6}.ward-map [role=button]{cursor:pointer}.ward-map [role=button]:focus-visible{outline:none;filter:drop-shadow(0 0 3px var(--ink))}.ward-map text{pointer-events:none}.ward-map svg{background:#182027}
html[data-theme=dark] .ward-legend{--ward-observer:#FFD166;--ward-sentry:#68C8FF}@media(prefers-color-scheme:dark){html:not([data-theme=light]) .ward-legend{--ward-observer:#FFD166;--ward-sentry:#68C8FF}}
@media(max-width:480px){.ward-filters{grid-template-columns:1fr;gap:10px}.ward-legend{gap:7px 12px;font-size:11px}.ward-legend>span{min-height:26px}}
.ward-summary-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:16px 0}.ward-team-summary{padding:14px;background:var(--surface-2);border:1px solid var(--line);border-radius:4px}.ward-team-summary h3{font-size:16px;margin:0 0 12px}.ward-team-summary.radiant h3{color:var(--radiant)}.ward-team-summary.dire h3{color:var(--dire)}.ward-team-summary>div{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.ward-team-summary span{font-size:11px;color:var(--muted);line-height:1.5}.ward-team-summary strong{display:block;font-size:24px;color:var(--ink);margin-top:5px;font-variant-numeric:tabular-nums}.ward-team-summary p{font-size:10px;line-height:1.6;color:var(--muted);margin:12px 0 0}#vision-events .event-row small{display:block;color:var(--muted);font-size:11px;margin-top:5px}@media(max-width:600px){.ward-summary-grid{grid-template-columns:1fr}.ward-filters{grid-template-columns:1fr 1fr}.ward-filters select{font-size:14px}.ward-filters label{font-size:11px}}@media(max-width:360px){.ward-filters{grid-template-columns:1fr}}
.ward-marker-number{opacity:0}.ward-map [aria-pressed=true] .ward-marker-number,.ward-map [role=button]:focus .ward-marker-number{opacity:1}
.map-layers{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin:12px 0}.map-layers label{display:flex;align-items:center;justify-content:center;gap:7px;min-height:44px;padding:7px;border:1px solid var(--line);background:var(--surface-2);border-radius:4px;font-size:11px;color:var(--muted);cursor:pointer}.map-layers label:has(input:checked){border-color:var(--accent);color:var(--ink)}.map-layers input{accent-color:var(--accent);width:15px;height:15px;flex:none}.map-layers label:focus-within{outline:2px solid var(--accent);outline-offset:2px}@media(max-width:480px){.map-layers{grid-template-columns:repeat(2,minmax(0,1fr))}.ward-filters{grid-template-columns:1fr 1fr}}
.map-layers{--ward-observer:#9A6B14;--ward-sentry:#2677AC}.map-layers label{gap:5px}.map-layers svg{width:23px;height:22px;flex:none;fill:none;stroke:var(--ink);stroke-width:2}.map-layers .ward-observer{stroke:var(--ward-observer)}.map-layers .ward-sentry{stroke:var(--ward-sentry)}html[data-theme=dark] .map-layers{--ward-observer:#FFD166;--ward-sentry:#68C8FF}@media(prefers-color-scheme:dark){html:not([data-theme=light]) .map-layers{--ward-observer:#FFD166;--ward-sentry:#68C8FF}}@media(max-width:360px){.map-layers label{font-size:10px;padding:6px 4px;gap:4px}.map-layers svg{width:21px}}

.map-expand,.map-dialog-head button{min-height:44px;padding:8px 14px;border:1px solid var(--line);border-radius:4px;color:var(--ink);background:var(--surface-2);font:inherit;font-size:12px;cursor:pointer}.map-expand{display:block;margin:0 0 8px auto}.map-dialog{box-sizing:border-box;position:fixed;inset:0;width:100vw;max-width:none;height:100dvh;max-height:none;margin:0;border:0;padding:max(12px,env(safe-area-inset-top)) max(10px,env(safe-area-inset-right)) max(12px,env(safe-area-inset-bottom)) max(10px,env(safe-area-inset-left));background:var(--surface);color:var(--ink);overflow:auto}.map-dialog::backdrop{background:#101820e8}.map-dialog-head{display:flex;align-items:center;justify-content:space-between;gap:10px;max-width:900px;margin:0 auto 8px}.map-dialog #vision-map{width:100%;max-width:900px;margin:auto}.map-dialog #vision-map>svg{display:block;width:min(100%,calc(100dvh - 180px));height:auto;max-height:none;margin:auto}.map-dialog .micro-note{font-size:11px}.map-dialog button:focus-visible,.map-expand:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
.map-dialog .map-layers{margin:0 auto 8px;max-width:900px}.map-dialog .map-time-controls{max-width:900px;margin:8px auto}.map-dialog .map-time-controls input{margin:0}.map-dialog .map-time-controls label{font-size:12px}.map-dialog #vision-map>svg{width:min(100%,max(240px,calc(100dvh - 350px)))}
.map-window-label{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:12px;margin:8px 0}.map-window-label .data-select{width:auto;max-width:75%;min-height:44px;font-size:16px}.map-dialog #vision-map>svg{width:min(100%,max(220px,calc(100dvh - 405px)))}
`;
