// Generated from pinned game data; see ability-labels.ts for semantics.
export const abilityCatalogSource = {
  "version": "valve-kv-5ad3d91b88d3",
  "fetchedAt": "2026-09-13",
  "classificationSource": "https://github.com/dotabuff/d2vpkr/tree/5ad3d91b88d39014c30f772ca71061f5686ca5de/dota/scripts/npc/heroes",
  "labelsSource": "https://github.com/odota/dotaconstants/tree/e7705ee975ebec2a88a59a7b455d4cae5dc69ca1/build",
  "heroFiles": 128,
  "classifiedAbilities": 377,
  "ultimateAbilities": 150,
  "labels": 1551,
  "filesSha256": "093c2e8cf5c6a26c32f476b0e60b6ea08618b9851af8ad41945232f93759574a"
} as const;
export const abilityNames:Readonly<Record<string,string>> = {
  "abaddon_aphotic_shield": "Aphotic Shield",
  "abaddon_borrowed_time": "Borrowed Time",
  "abaddon_death_coil": "Mist Coil",
  "abaddon_frostmourne": "Curse of Avernus",
  "abaddon_withering_mist": "Withering Mist",
  "abyssal_underling_archer_aoe": "Archer Aura",
  "abyssal_underling_warrior_last_will": "Last Will",
  "abyssal_underling_warrior_mana_burn": "Mana Break",
  "abyssal_underlord_abyssal_horde": "Abyssal Horde",
  "abyssal_underlord_atrophy_aura": "Atrophy Aura",
  "abyssal_underlord_dark_portal": "Fiend's Gate",
  "abyssal_underlord_firestorm": "Firestorm",
  "abyssal_underlord_pit_of_malice": "Pit of Malice",
  "abyssal_underlord_raid_boss": "Invading Force",
  "ad_special_bonus_gold_lvl10_l": "+250 Gold",
  "ad_special_bonus_gold_lvl10_r": "+250 Gold",
  "ad_special_bonus_gold_lvl15_l": "+500 Gold",
  "ad_special_bonus_gold_lvl15_r": "+500 Gold",
  "ad_special_bonus_gold_lvl20_l": "+750 Gold",
  "ad_special_bonus_gold_lvl20_r": "+750 Gold",
  "ad_special_bonus_gold_lvl25_l": "+1250 Gold",
  "ad_special_bonus_gold_lvl25_r": "+1250 Gold",
  "alchemist_acid_spray": "Acid Spray",
  "alchemist_berserk_potion": "Berserk Potion",
  "alchemist_chemical_rage": "Chemical Rage",
  "alchemist_corrosive_weaponry": "Corrosive Weaponry",
  "alchemist_goblins_greed": "Greevil's Greed",
  "alchemist_unstable_concoction": "Unstable Concoction",
  "alchemist_unstable_concoction_throw": "Unstable Concoction Throw",
  "alpha_wolf_command_aura": "Packleader's Aura",
  "alpha_wolf_critical_strike": "Critical Strike",
  "ancient_apparition_bone_chill": "Bone Chill",
  "ancient_apparition_chilling_touch": "Chilling Touch",
  "ancient_apparition_cold_feet": "Cold Feet",
  "ancient_apparition_ice_blast": "Ice Blast",
  "ancient_apparition_ice_blast_release": "Release",
  "ancient_apparition_ice_vortex": "Ice Vortex",
  "ancient_rock_golem_weakening_aura": "Weakening Aura",
  "antimage_blink": "Blink",
  "antimage_counterspell": "Counterspell",
  "antimage_counterspell_ally": "Counterspell Ally",
  "antimage_mana_break": "Mana Break",
  "antimage_mana_void": "Mana Void",
  "antimage_persectur": "Persecutor",
  "arc_warden_flux": "Flux",
  "arc_warden_magnetic_field": "Magnetic Field",
  "arc_warden_runic_infusion": "Runic Infusion",
  "arc_warden_spark_wraith": "Spark Wraith",
  "arc_warden_tempest_double": "Tempest Double",
  "axe_battle_hunger": "Battle Hunger",
  "axe_berserkers_call": "Berserker's Call",
  "axe_counter_helix": "Counter Helix",
  "axe_culling_blade": "Culling Blade",
  "axe_one_man_army": "One Man Army",
  "backdoor_protection": "Backdoor Protection",
  "backdoor_protection_in_base": "Backdoor Protection",
  "bane_brain_sap": "Brain Sap",
  "bane_enfeeble": "Enfeeble",
  "bane_fiends_grip": "Fiend's Grip",
  "bane_ichor_of_nyctasha": "Ichor of Nyctasha",
  "bane_nightmare": "Nightmare",
  "bane_nightmare_end": "Nightmare End",
  "batrider_firefly": "Firefly",
  "batrider_flamebreak": "Flamebreak",
  "batrider_flaming_lasso": "Flaming Lasso",
  "batrider_smoldering_resin": "Smoldering Resin",
  "batrider_sticky_napalm": "Sticky Napalm",
  "batrider_sticky_napalm_application_damage": "APPLICATION DAMAGE:",
  "beastmaster_boar_poison": "Poison",
  "beastmaster_drums_of_slom": "Drums of Slom",
  "beastmaster_greater_boar_poison": "Poison",
  "beastmaster_hawk_dive": "Dive Bomb",
  "beastmaster_inner_beast": "Inner Beast",
  "beastmaster_primal_roar": "Primal Roar",
  "beastmaster_rugged": "Rugged",
  "beastmaster_summon_raptor": "Summon Raptors",
  "beastmaster_summon_razorback": "Summon Razorback",
  "beastmaster_wild_axes": "Wild Axes",
  "berserker_troll_break": "Break",
  "big_thunder_lizard_frenzy": "Frenzy",
  "big_thunder_lizard_slam": "Slam",
  "big_thunder_lizard_wardrums_aura": "War Drums Aura",
  "black_dragon_dragonhide_aura": "Dragonhide Aura",
  "black_dragon_fireball": "Fireball",
  "black_dragon_splash_attack": "Splash Attack",
  "black_drake_magic_amplification_aura": "Magic Amplification Aura",
  "bloodseeker_blood_bath": "Blood Rite",
  "bloodseeker_blood_mist": "Blood Mist",
  "bloodseeker_bloodrage": "Bloodrage",
  "bloodseeker_rupture": "Rupture",
  "bloodseeker_sanguivore": "Sanguivore",
  "bloodseeker_thirst": "Thirst",
  "bounty_hunter_big_game_hunter": "Big Game Hunter",
  "bounty_hunter_cutpurse": "Cutpurse",
  "bounty_hunter_jinada": "Jinada",
  "bounty_hunter_shuriken_toss": "Shuriken Toss",
  "bounty_hunter_track": "Track",
  "bounty_hunter_wind_walk": "Shadow Walk",
  "bounty_hunter_wind_walk_ally": "Friendly Shadow",
  "brewmaster_cinder_brew": "Cinder Brew",
  "brewmaster_drunken_brawler": "Drunken Brawler",
  "brewmaster_drunken_brawler_brew_up": "Drunken Brawler - Brew Up",
  "brewmaster_earth_hurl_boulder": "Hurl Boulder",
  "brewmaster_earth_pulverize": "Demolish",
  "brewmaster_earth_spell_immunity": "Earth Element",
  "brewmaster_fire_permanent_immolation": "Permanent Immolation",
  "brewmaster_fire_phase": "Permanent Phase",
  "brewmaster_liquid_courage": "Liquid Courage",
  "brewmaster_primal_companion": "Primal Companion",
  "brewmaster_primal_split": "Primal Split",
  "brewmaster_primal_split_cancel": "Primal Split Cancel",
  "brewmaster_storm_cyclone": "Cyclone",
  "brewmaster_storm_dispel_magic": "Dispel Magic",
  "brewmaster_storm_wind_walk": "Wind Walk",
  "brewmaster_thunder_clap": "Thunder Clap",
  "bristleback_brawlers_grit": "Brawler's Grit",
  "bristleback_bristleback": "Bristleback",
  "bristleback_hairball": "Hairball",
  "bristleback_prickly": "Prickly",
  "bristleback_quill_spray": "Quill Spray",
  "bristleback_viscous_nasal_goo": "Viscous Nasal Goo",
  "bristleback_warpath": "Warpath",
  "broodmother_incapacitating_bite": "Incapacitating Bite",
  "broodmother_insatiable_hunger": "Insatiable Hunger",
  "broodmother_poison_sting": "Poison Sting",
  "broodmother_spawn_spiderite": "Spawn Spiderling",
  "broodmother_spawn_spiderlings": "Spawn Spiderlings",
  "broodmother_spiders_milk": "Spider's Milk",
  "broodmother_spin_web": "Spin Web",
  "broodmother_spin_web_destroy": "Destroy Spin Web",
  "broodmother_sticky_snare": "Spinner's Snare",
  "centaur_double_edge": "Double Edge",
  "centaur_hoof_stomp": "Hoof Stomp",
  "centaur_horsepower": "Horsepower",
  "centaur_khan_endurance_aura": "Swiftness Aura",
  "centaur_khan_war_stomp": "War Stomp",
  "centaur_mount": "Hitch A Ride",
  "centaur_rawhide": "Rawhide",
  "centaur_return": "Retaliate",
  "centaur_stampede": "Stampede",
  "centaur_work_horse": "Work Horse",
  "chaos_knight_chaos_bolt": "Chaos Bolt",
  "chaos_knight_chaos_strike": "Chaos Strike",
  "chaos_knight_fundamental_forging": "Fundamental Forging",
  "chaos_knight_phantasm": "Phantasm",
  "chaos_knight_phantasmagoria": "Phantasmagoria",
  "chaos_knight_reality_rift": "Reality Rift",
  "chaos_knight_reins_of_chaos": "Reins of Chaos",
  "chen_divine_favor": "Divine Favor",
  "chen_hand_of_god": "Hand of God",
  "chen_holy_persuasion": "Holy Persuasion",
  "chen_martyrdom": "Martyrdom",
  "chen_penitence": "Penitence",
  "chen_zealot": "Zealot",
  "clinkz_bone_and_arrow": "Bone and Arrow",
  "clinkz_burning_army": "Burning Army",
  "clinkz_burning_barrage": "Burning Barrage",
  "clinkz_death_pact": "Death Pact",
  "clinkz_infernal_shred": "Infernal Shred",
  "clinkz_searing_arrows": "Searing Arrows",
  "clinkz_strafe": "Strafe",
  "clinkz_tar_bomb": "Tar Bomb",
  "clinkz_wind_walk": "Skeleton Walk",
  "courier_autodeliver": "Auto Deliver",
  "courier_burst": "Speed Burst",
  "courier_go_to_secretshop": "Go To Secret Shop",
  "courier_return_stash_items": "Return Items",
  "courier_return_to_base": "Return to Base",
  "courier_shield": "Shield",
  "courier_take_stash_items": "Retrieve Items",
  "courier_transfer_items": "Transfer Items",
  "creep_irresolute": "Runty",
  "creep_piercing": "Piercing",
  "creep_siege": "Reinforced",
  "crystal_maiden_brilliance_aura": "Arcane Aura",
  "crystal_maiden_crystal_clone": "Crystal Clone",
  "crystal_maiden_crystal_nova": "Crystal Nova",
  "crystal_maiden_freezing_field": "Freezing Field",
  "crystal_maiden_freezing_field_stop": "Stop Freezing Field",
  "crystal_maiden_frostbite": "Frostbite",
  "crystal_maiden_glacial_guard": "Glacial Guard",
  "dark_seer_aggrandize": "Quick Wit",
  "dark_seer_heart_of_battle": "Heart of Battle",
  "dark_seer_ion_shell": "Ion Shell",
  "dark_seer_mental_fortitude": "Mental Fortitude",
  "dark_seer_normal_punch": "Normal Punch",
  "dark_seer_quick_wit": "Quick Wit",
  "dark_seer_surge": "Surge",
  "dark_seer_vacuum": "Vacuum",
  "dark_seer_wall_of_replica": "Wall of Replica",
  "dark_troll_warlord_ensnare": "Ensnare",
  "dark_troll_warlord_raise_dead": "Raise Dead",
  "dark_willow_bedlam": "Bedlam",
  "dark_willow_bramble_maze": "Bramble Maze",
  "dark_willow_cursed_crown": "Cursed Crown",
  "dark_willow_pixie_dust": "Pixie Dust",
  "dark_willow_shadow_realm": "Shadow Realm",
  "dark_willow_terrorize": "Terrorize",
  "dawnbreaker_break_of_dawn": "Break of Dawn",
  "dawnbreaker_celestial_hammer": "Celestial Hammer",
  "dawnbreaker_converge": "Converge",
  "dawnbreaker_fire_wreath": "Starbreaker",
  "dawnbreaker_luminosity": "Luminosity",
  "dawnbreaker_solar_guardian": "Solar Guardian",
  "dazzle_innate_weave": "Weave",
  "dazzle_nothl_boon": "Nothl Boon",
  "dazzle_nothl_projection": "Nothl Projection",
  "dazzle_nothl_projection_end": "End Projection",
  "dazzle_poison_touch": "Poison Touch",
  "dazzle_shadow_wave": "Shadow Wave",
  "dazzle_shallow_grave": "Shallow Grave",
  "death_prophet_carrion_swarm": "Crypt Swarm",
  "death_prophet_exorcism": "Exorcism",
  "death_prophet_mourning_ritual": "Mourning Ritual",
  "death_prophet_silence": "Silence",
  "death_prophet_spirit_collector": "Spirit Collector",
  "death_prophet_spirit_siphon": "Spirit Siphon",
  "death_prophet_witchcraft": "Witchcraft",
  "disruptor_electromagnetic_repulsion": "Electromagnetic Repulsion",
  "disruptor_glimpse": "Glimpse",
  "disruptor_kinetic_fence": "Kinetic Fence",
  "disruptor_kinetic_field": "Kinetic Field",
  "disruptor_static_storm": "Static Storm",
  "disruptor_thunder_strike": "Thunder Strike",
  "doom_bringer_devils_bargain": "Devil's Bargain",
  "doom_bringer_devour": "Devour",
  "doom_bringer_doom": "Doom",
  "doom_bringer_empty1": "Devoured Ability",
  "doom_bringer_empty2": "Devoured Ability",
  "doom_bringer_infernal_blade": "Infernal Blade",
  "doom_bringer_lvl_pain": "Lvl ? Pain",
  "doom_bringer_scorched_earth": "Scorched Earth",
  "dota_base_ability": "",
  "dragon_knight_breathe_fire": "Breathe Fire",
  "dragon_knight_dragon_blood": "Dragon Blood",
  "dragon_knight_dragon_tail": "Dragon Tail",
  "dragon_knight_elder_dragon_form": "Elder Dragon Form",
  "dragon_knight_fireball": "Fireball",
  "dragon_knight_wyrms_wrath": "Wyrm's Wrath",
  "drow_ranger_frost_arrows": "Frost Arrows",
  "drow_ranger_glacier": "Glacier",
  "drow_ranger_marksmanship": "Marksmanship",
  "drow_ranger_multishot": "Multishot",
  "drow_ranger_trueshot": "Precision Aura",
  "drow_ranger_wave_of_silence": "Gust",
  "earth_spirit_boulder_smash": "Boulder Smash",
  "earth_spirit_geomagnetic_grip": "Geomagnetic Grip",
  "earth_spirit_magnetize": "Magnetize",
  "earth_spirit_petrify": "Enchant Remnant",
  "earth_spirit_rolling_boulder": "Rolling Boulder",
  "earth_spirit_stone_caller": "Stone Remnant",
  "earthshaker_aftershock": "Aftershock",
  "earthshaker_echo_slam": "Echo Slam",
  "earthshaker_enchant_totem": "Enchant Totem",
  "earthshaker_fissure": "Fissure",
  "earthshaker_slugger": "Slugger",
  "earthshaker_spirit_cairn": "Spirit Cairn",
  "elder_titan_ancestral_spirit": "Astral Spirit",
  "elder_titan_earth_splitter": "Earth Splitter",
  "elder_titan_echo_stomp": "Echo Stomp",
  "elder_titan_echo_stomp_spirit": "Echo Stomp",
  "elder_titan_momentum": "Momentum",
  "elder_titan_move_spirit": "Move Astral Spirit",
  "elder_titan_natural_order": "Natural Order",
  "elder_titan_natural_order_spirit": "Natural Order",
  "elder_titan_return_spirit": "Return Astral Spirit",
  "elder_titan_tip_the_scales": "Tip the Scales",
  "ember_spirit_activate_fire_remnant": "Activate Fire Remnant",
  "ember_spirit_fire_remnant": "Fire Remnant",
  "ember_spirit_flame_guard": "Flame Guard",
  "ember_spirit_immolation": "Immolation",
  "ember_spirit_searing_chains": "Searing Chains",
  "ember_spirit_sleight_of_fist": "Sleight of Fist",
  "enchantress_bunny_hop": "Sproink",
  "enchantress_enchant": "Enchant",
  "enchantress_impetus": "Impetus",
  "enchantress_little_friends": "Little Friends",
  "enchantress_natures_attendants": "Nature's Attendants",
  "enchantress_rabblerouser": "Rabble-Rouser",
  "enchantress_untouchable": "Untouchable",
  "enigma_black_hole": "Black Hole",
  "enigma_demonic_conversion": "Demonic Summoning",
  "enigma_event_horizon": "Event Horizon",
  "enigma_gravity_well": "Gravity Well",
  "enigma_malefice": "Malefice",
  "enigma_midnight_pulse": "Midnight Pulse",
  "enigma_splitting_image": "Splitting Image",
  "enraged_wildkin_hurricane": "Hurricane",
  "enraged_wildkin_tornado": "Tornado",
  "enraged_wildkin_toughness_aura": "Toughness Aura",
  "faceless_void_chronosphere": "Chronosphere",
  "faceless_void_distortion_field": "Distortion Field",
  "faceless_void_time_dilation": "Time Dilation",
  "faceless_void_time_lock": "Time Lock",
  "faceless_void_time_walk": "Time Walk",
  "faceless_void_time_walk_reverse": "Reverse Time Walk",
  "faceless_void_time_zone": "Time Zone",
  "fel_beast_haunt": "Vex",
  "flagbearer_creep_aura_effect": "Inspiration Aura",
  "forest_troll_high_priest_heal": "Heal",
  "forest_troll_high_priest_heal_amp_aura": "Heal Amplification Aura",
  "forest_troll_high_priest_mana_aura": "Mana Aura",
  "forged_spirit_melting_strike": "Melting Strike",
  "frogmen_arm_of_the_deep": "Arm of the Deep",
  "frogmen_congregation_of_the_deep": "Congregations of the Deep",
  "frogmen_riverborn_aura": "Riverborn Aura",
  "frogmen_tendrils_of_the_deep": "Tendrils of the Deep",
  "frogmen_water_bubble_large": "Water Bubble (Large)",
  "frogmen_water_bubble_medium": "Water Bubble (Medium)",
  "frogmen_water_bubble_small": "Water Bubble (Small)",
  "frostbitten_golem_time_warp_aura": "Time Warp Aura",
  "furbolg_enrage_attack_speed": "Death Throe: Rush",
  "furbolg_enrage_damage": "Death Throe: Power",
  "furion_curse_of_the_forest": "Curse of the Oldgrowth",
  "furion_force_of_nature": "Nature's Call",
  "furion_natures_profit": "Nature's Profit",
  "furion_spirit_of_the_forest": "Spirit of the Forest",
  "furion_sprout": "Sprout",
  "furion_teleportation": "Teleportation",
  "furion_wrath_of_nature": "Wrath of Nature",
  "ghost_frost_attack": "Frost Attack",
  "giant_wolf_critical_strike": "Critical Strike",
  "giant_wolf_intimidate": "Intimidate",
  "gnoll_assassin_envenomed_weapon": "Envenomed Weapon",
  "granite_golem_hp_aura": "Granite Aura",
  "grimstroke_dark_artistry": "Stroke of Fate",
  "grimstroke_dark_portrait": "Dark Portrait",
  "grimstroke_ink_creature": "Phantom's Embrace",
  "grimstroke_ink_trail": "Ink Trail",
  "grimstroke_return": "Ink Explosion",
  "grimstroke_soul_chain": "Soulbind",
  "grimstroke_spirit_walk": "Ink Swell",
  "gyrocopter_afterburner": "Afterburner",
  "gyrocopter_call_down": "Call Down",
  "gyrocopter_chop_shop": "Chop Shop",
  "gyrocopter_flak_cannon": "Flak Cannon",
  "gyrocopter_homing_missile": "Homing Missile",
  "gyrocopter_rocket_barrage": "Rocket Barrage",
  "gyrocopter_side_gunner_spawn_ability": "Side Gunner",
  "harpy_scout_take_off": "Take Off",
  "harpy_storm_chain_lightning": "Chain Lightning",
  "hill_troll_rally": "Rally",
  "hoodwink_acorn_shot": "Acorn Shot",
  "hoodwink_bushwhack": "Bushwhack",
  "hoodwink_decoy": "Decoy",
  "hoodwink_hunters_boomerang": "Hunter's Boomerang",
  "hoodwink_mistwoods_wayfarer": "Mistwoods Wayfarer",
  "hoodwink_scurry": "Scurry",
  "hoodwink_sharpshooter": "Sharpshooter",
  "hoodwink_sharpshooter_release": "End Sharpshooter",
  "hoodwink_tomokan_tracker": "Tomo'kan Tracker",
  "huskar_berserkers_blood": "Berserker's Blood",
  "huskar_blood_magic": "Blood Magic",
  "huskar_burning_spear": "Burning Spear",
  "huskar_inner_fire": "Inner Fire",
  "huskar_life_break": "Life Break",
  "ice_shaman_incendiary_bomb": "Icefire Bomb",
  "invoker_alacrity": "Alacrity",
  "invoker_alacrity_ad": "Alacrity (AD)",
  "invoker_attribute_bonus": "Attribute Bonus",
  "invoker_chaos_meteor": "Chaos Meteor",
  "invoker_chaos_meteor_ad": "Chaos Meteor (AD)",
  "invoker_cold_snap": "Cold Snap",
  "invoker_cold_snap_ad": "Cold Snap (AD)",
  "invoker_deafening_blast": "Deafening Blast",
  "invoker_deafening_blast_ad": "Deafening Blast",
  "invoker_emp": "E.M.P.",
  "invoker_emp_ad": "E.M.P. (AD)",
  "invoker_empty1": "Invoked Spell",
  "invoker_empty2": "Invoked Spell",
  "invoker_exort": "Exort",
  "invoker_forge_spirit": "Forge Spirit",
  "invoker_forge_spirit_ad": "Forge Spirit (AD)",
  "invoker_ghost_walk": "Ghost Walk",
  "invoker_ghost_walk_ad": "Ghost Walk (AD)",
  "invoker_ice_wall": "Ice Wall",
  "invoker_ice_wall_ad": "Ice Wall (AD)",
  "invoker_invoke": "Invoke",
  "invoker_mastermind": "Mastermind",
  "invoker_quas": "Quas",
  "invoker_sun_strike": "Sun Strike",
  "invoker_sun_strike_ad": "Sun Strike (AD)",
  "invoker_tornado": "Tornado",
  "invoker_tornado_ad": "Tornado (AD)",
  "invoker_wex": "Wex",
  "item_abyssal_blade": "Abyssal Blade",
  "item_aegis": "Aegis of the Immortal",
  "item_aeon_disk": "Aeon Disk",
  "item_aether_lens": "Aether Lens",
  "item_aghanims_shard": "Aghanim's Shard",
  "item_aghanims_shard_roshan": "Aghanim's Shard - Consumable",
  "item_ancient_guardian": "Ancient Guardian",
  "item_ancient_janggo": "Drum of Endurance",
  "item_angels_demise": "Khanda",
  "item_apex": "Apex",
  "item_arcane_blink": "Arcane Blink",
  "item_arcane_boots": "Arcane Boots",
  "item_arcane_ring": "Arcane Ring",
  "item_armlet": "Armlet of Mordiggian",
  "item_ascetic_cap": "Ascetic's Cap",
  "item_ash_legion_shield": "Ash Legion Shield",
  "item_assault": "Assault Cuirass",
  "item_avianas_feather": "Aviana's Feather",
  "item_ballista": "Ballista",
  "item_basher": "Skull Basher",
  "item_belt_of_strength": "Belt of Strength",
  "item_bfury": "Battle Fury",
  "item_black_grimoire": "Black Grimoire\\n(Warlock)",
  "item_black_king_bar": "Black King Bar",
  "item_black_powder_bag": "Blast Rig",
  "item_blade_mail": "Blade Mail",
  "item_blade_of_alacrity": "Blade of Alacrity",
  "item_blades_of_attack": "Blades of Attack",
  "item_blight_stone": "Orb of Blight",
  "item_blink": "Blink Dagger",
  "item_blitz_knuckles": "Blitz Knuckles",
  "item_blood_grenade": "Blood Grenade",
  "item_bloodstone": "Bloodstone",
  "item_bloodthorn": "Bloodthorn",
  "item_book_of_shadows": "Book of Shadows",
  "item_boots": "Boots of Speed",
  "item_boots_of_bearing": "Boots of Bearing",
  "item_boots_of_elves": "Band of Elvenskin",
  "item_bottle": "Bottle",
  "item_bracer": "Bracer",
  "item_branches": "Iron Branch",
  "item_broadsword": "Broadsword",
  "item_broom_handle": "Broom Handle",
  "item_buckler": "Buckler",
  "item_bullwhip": "Bullwhip",
  "item_butterfly": "Butterfly",
  "item_ceremonial_robe": "Ceremonial Robe",
  "item_chainmail": "Chainmail",
  "item_chasm_stone": "Chasm Stone",
  "item_cheese": "Cheese",
  "item_chipped_vest": "Chipped Vest",
  "item_circlet": "Circlet",
  "item_clarity": "Clarity",
  "item_claymore": "Claymore",
  "item_cloak": "Cloak",
  "item_cloak_of_flames": "Cloak of Flames",
  "item_clumsy_net": "Clumsy Net",
  "item_conjurers_catalyst": "Conjurer's Catalyst",
  "item_consecrated_wraps": "Consecrated Wraps",
  "item_cornucopia": "Cornucopia",
  "item_courier": "Animal Courier",
  "item_craggy_coat": "Craggy Coat",
  "item_crellas_crozier": "Crella's Crozier",
  "item_crimson_guard": "Crimson Guard",
  "item_crippling_crossbow": "Crippling Crossbow",
  "item_crown": "Crown",
  "item_cyclone": "Eul's Scepter of Divinity",
  "item_dagger_of_ristul": "Dagger of Ristul",
  "item_dagon": "Dagon",
  "item_dagon_2": "Dagon",
  "item_dagon_3": "Dagon",
  "item_dagon_4": "Dagon",
  "item_dagon_5": "Dagon",
  "item_dandelion_amulet": "Dandelion Amulet",
  "item_defiant_shell": "Defiant Shell",
  "item_demon_edge": "Demon Edge",
  "item_demonicon": "Book of the Dead",
  "item_desolator": "Desolator",
  "item_desolator_2": "Stygian Desolator",
  "item_devastator": "Parasma",
  "item_dezun_bloodrite": "Dezun Bloodrite",
  "item_diadem": "Diadem",
  "item_diffusal_blade": "Diffusal Blade",
  "item_diffusal_blade_2": "Diffusal Blade",
  "item_disperser": "Disperser",
  "item_divine_regalia": "Divine Regalia",
  "item_divine_regalia_broken": "Disgraced Regalia",
  "item_dormant_curio": "Dormant Curio",
  "item_doubloon": "Doubloon",
  "item_dragon_lance": "Dragon Lance",
  "item_dragon_scale": "Dragon Scale",
  "item_duelist_gloves": "Duelist Gloves",
  "item_dust": "Dust of Appearance",
  "item_eagle": "Eaglesong",
  "item_echo_sabre": "Echo Sabre",
  "item_eldwurms_edda": "Eldwurm's Edda",
  "item_elixer": "Elixir",
  "item_elven_tunic": "Elven Tunic",
  "item_enchanted_mango": "Enchanted Mango",
  "item_enchanted_quiver": "Enchanted Quiver",
  "item_enchanters_bauble": "Enchanter's Bauble",
  "item_energy_booster": "Energy Booster",
  "item_enhancement_alert": "Alert",
  "item_enhancement_audacious": "Audacious",
  "item_enhancement_boundless": "Boundless",
  "item_enhancement_brawny": "Brawny",
  "item_enhancement_crude": "Crude",
  "item_enhancement_curious": "Unleashed",
  "item_enhancement_dominant": "Dominant",
  "item_enhancement_evolved": "Evolved",
  "item_enhancement_feverish": "Feverish",
  "item_enhancement_fierce": "Fierce",
  "item_enhancement_fleetfooted": "Fleetfooted",
  "item_enhancement_greedy": "Greedy",
  "item_enhancement_hulking": "Hulking",
  "item_enhancement_keen_eyed": "Keen-eyed",
  "item_enhancement_manic": "Manic",
  "item_enhancement_mystical": "Mystical",
  "item_enhancement_nimble": "Nimble",
  "item_enhancement_quickened": "Quickened",
  "item_enhancement_restorative": "Restorative",
  "item_enhancement_thick": "Thick",
  "item_enhancement_timeless": "Timeless",
  "item_enhancement_titanic": "Titanic",
  "item_enhancement_tough": "Tough",
  "item_enhancement_vampiric": "Vampiric",
  "item_enhancement_vast": "Vast",
  "item_enhancement_vital": "Vital",
  "item_enhancement_wise": "Wise",
  "item_essence_distiller": "Essence Distiller",
  "item_essence_ring": "Essence Ring",
  "item_eternal_shroud": "Eternal Shroud",
  "item_ethereal_blade": "Ethereal Blade",
  "item_ex_machina": "Ex Machina",
  "item_eye_of_the_vizier": "Eye of the Vizier",
  "item_faded_broach": "Faded Broach",
  "item_faerie_fire": "Faerie Fire",
  "item_falcon_blade": "Falcon Blade",
  "item_fallen_sky": "Fallen Sky",
  "item_famango": "Healing Lotus",
  "item_flask": "Healing Salve",
  "item_flayers_bota": "Flayer's Bota",
  "item_flicker": "Flicker",
  "item_fluffy_hat": "Fluffy Hat",
  "item_flying_courier": "Flying Courier",
  "item_foragers_health": "Vital Toadstool",
  "item_foragers_kit": "Forager's Kit",
  "item_foragers_mana": "Tomo'kan Ringcap",
  "item_foragers_stats": "Ironwood Nut",
  "item_force_boots": "Force Boots",
  "item_force_field": "Arcanist's Armor",
  "item_force_staff": "Force Staff",
  "item_furion_gold_bag": "Bag of Gold",
  "item_fusion_rune": "Fusion Rune",
  "item_gale_guard": "Gale Guard",
  "item_gauntlets": "Gauntlets of Strength",
  "item_gem": "Gem of True Sight",
  "item_ghost": "Ghost Scepter",
  "item_giant_maul": "Giant's Maul",
  "item_giants_ring": "Giant's Ring",
  "item_glimmer_cape": "Glimmer Cape",
  "item_gloves": "Gloves of Haste",
  "item_gossamer_cape": "Gossamer Cape",
  "item_great_famango": "Great Healing Lotus",
  "item_greater_crit": "Daedalus",
  "item_greater_faerie_fire": "Greater Faerie Fire",
  "item_greater_famango": "Greater Healing Lotus",
  "item_grisgris": "Gris-Gris",
  "item_grove_bow": "Grove Bow",
  "item_guardian_greaves": "Guardian Greaves",
  "item_gungir": "Gleipnir",
  "item_gunpowder_gauntlets": "Gunpowder Gauntlet",
  "item_hand_of_midas": "Hand of Midas",
  "item_harmonizer": "Harmonizer",
  "item_harpoon": "Harpoon",
  "item_havoc_hammer": "Havoc Hammer",
  "item_headdress": "Headdress",
  "item_heart": "Heart of Tarrasque",
  "item_heavens_halberd": "Heaven's Halberd",
  "item_heavy_blade": "Witchbane",
  "item_helm_of_iron_will": "Helm of Iron Will",
  "item_helm_of_the_dominator": "Helm of the Dominator",
  "item_helm_of_the_overlord": "Helm of the Overlord",
  "item_helm_of_the_undying": "Helm of the Undying",
  "item_holy_locket": "Holy Locket",
  "item_hood_of_defiance": "Hood of Defiance",
  "item_hurricane_pike": "Hurricane Pike",
  "item_hydras_breath": "Hydra's Breath",
  "item_hyperstone": "Hyperstone",
  "item_idol_of_screeauk": "Idol of Scree'auk",
  "item_illusionsts_cape": "Illusionist's Cape",
  "item_imp_claw": "Imp Claw",
  "item_infused_raindrop": "Infused Raindrops",
  "item_invis_sword": "Shadow Blade",
  "item_iron_talon": "Iron Talon",
  "item_ironwood_tree": "Ironwood Tree",
  "item_javelin": "Javelin",
  "item_jidi_pollen_bag": "Jidi Pollen Bag",
  "item_kaya": "Kaya",
  "item_kaya_and_sange": "Kaya and Sange",
  "item_keen_optic": "Keen Optic",
  "item_kobold_cup": "Kobold Cup",
  "item_lance_of_pursuit": "Lance of Pursuit",
  "item_lesser_crit": "Crystalys",
  "item_lifesteal": "Morbid Mask",
  "item_light_collector": "Light Collector",
  "item_lotus_orb": "Lotus Orb",
  "item_madstone_bundle": "Madstone Bundle",
  "item_maelstrom": "Maelstrom",
  "item_mage_slayer": "Mage Slayer",
  "item_magic_stick": "Magic Stick",
  "item_magic_wand": "Magic Wand",
  "item_magnifying_monocle": "Magnifying Monocle",
  "item_mana_draught": "Mana Draught",
  "item_mango_tree": "Mango Tree",
  "item_manta": "Manta Style",
  "item_mantle": "Mantle of Intelligence",
  "item_martyrs_plate": "Martyr's Plate",
  "item_mask_of_madness": "Mask of Madness",
  "item_medallion_of_courage": "Medallion of Courage",
  "item_mekansm": "Mekansm",
  "item_metamorphic_mandible": "Metamorphic Mandible",
  "item_meteor_hammer": "Meteor Hammer",
  "item_mind_breaker": "Mind Breaker",
  "item_minotaur_horn": "Minotaur Horn",
  "item_mirror_shield": "Mirror Shield",
  "item_misericorde": "Brigand's Blade",
  "item_mithril_hammer": "Mithril Hammer",
  "item_mjollnir": "Mjollnir",
  "item_monkey_king_bar": "Monkey King Bar",
  "item_moon_shard": "Moon Shard",
  "item_muertas_gun": "Mercy & Grace",
  "item_mutation_tombstone": "Tombstone",
  "item_mysterious_hat": "Fairy's Trinket",
  "item_mystic_staff": "Mystic Staff",
  "item_necronomicon": "Necronomicon",
  "item_necronomicon_2": "Necronomicon",
  "item_necronomicon_3": "Necronomicon",
  "item_nemesis_curse": "Nemesis Curse",
  "item_nether_shawl": "Nether Shawl",
  "item_ninja_gear": "Ninja Gear",
  "item_null_talisman": "Null Talisman",
  "item_nullifier": "Nullifier",
  "item_oblivion_staff": "Oblivion Staff",
  "item_occult_bracelet": "Occult Bracelet",
  "item_ocean_heart": "Ocean Heart",
  "item_octarine_core": "Octarine Core",
  "item_ofrenda": "Beloved Memory",
  "item_ofrenda_pledge": "Forebearer's Fortune",
  "item_ofrenda_shovel": "Scrying Shovel",
  "item_ogre_axe": "Ogre Axe",
  "item_ogre_seal_totem": "Ogre Seal Totem",
  "item_orb_of_corrosion": "Orb of Corrosion",
  "item_orb_of_destruction": "Orb of Destruction",
  "item_orb_of_frost": "Orb of Frost",
  "item_orb_of_venom": "Orb of Venom",
  "item_orchid": "Orchid Malevolence",
  "item_outworld_staff": "Outworld Staff",
  "item_overwhelming_blink": "Overwhelming Blink",
  "item_paintball": "Fae Grenade",
  "item_paladin_sword": "Paladin Sword",
  "item_panic_button": "Magic Lamp",
  "item_partisans_brand": "Partisan's Brand",
  "item_pavise": "Pavise",
  "item_penta_edged_sword": "Penta-Edged Sword",
  "item_pers": "Perseverance",
  "item_phase_boots": "Phase Boots",
  "item_philosophers_stone": "Philosopher's Stone",
  "item_phoenix_ash": "Phoenix Ash",
  "item_phylactery": "Phylactery",
  "item_pipe": "Pipe of Insight",
  "item_pirate_hat": "Pirate Hat",
  "item_platemail": "Platemail",
  "item_pocket_roshan": "Pocket Roshan",
  "item_pocket_tower": "Pocket Tower",
  "item_pogo_stick": "Tumbler's Toy",
  "item_point_booster": "Point Booster",
  "item_polliwog_charm": "Pollywog Charm",
  "item_poor_mans_shield": "Poor Man's Shield",
  "item_possessed_mask": "Possessed Mask",
  "item_power_treads": "Power Treads",
  "item_princes_knife": "Prince's Knife",
  "item_prophets_pendulum": "Prophet's Pendulum",
  "item_psychic_headband": "Psychic Headband",
  "item_pupils_gift": "Pupil's Gift",
  "item_pyrrhic_cloak": "Pyrrhic Cloak",
  "item_quarterstaff": "Quarterstaff",
  "item_quelling_blade": "Quelling Blade",
  "item_quickening_charm": "Quickening Charm",
  "item_quicksilver_amulet": "Quicksilver Amulet",
  "item_radiance": "Radiance",
  "item_rapier": "Divine Rapier",
  "item_rattlecage": "Rattlecage",
  "item_reaver": "Reaver",
  "item_recipe_abyssal_blade": "Abyssal Blade Recipe",
  "item_recipe_aeon_disk": "Aeon Disk Recipe",
  "item_recipe_aether_lens": "Aether Lens Recipe",
  "item_recipe_ancient_janggo": "Drum of Endurance Recipe",
  "item_recipe_arcane_blink": "Arcane Blink Recipe",
  "item_recipe_arcane_boots": "Arcane Boots Recipe",
  "item_recipe_armlet": "Armlet of Mordiggian Recipe",
  "item_recipe_assault": "Assault Cuirass Recipe",
  "item_recipe_basher": "Skull Basher Recipe",
  "item_recipe_bfury": "Battle Fury Recipe",
  "item_recipe_black_king_bar": "Black King Bar Recipe",
  "item_recipe_blade_mail": "Blade Mail Recipe",
  "item_recipe_bloodthorn": "Bloodthorn Recipe",
  "item_recipe_bracer": "Bracer Recipe",
  "item_recipe_buckler": "Buckler Recipe",
  "item_recipe_consecrated_wraps": "Consecrated Wraps Recipe",
  "item_recipe_crellas_crozier": "Crella's Crozier Recipe",
  "item_recipe_crimson_guard": "Crimson Guard Recipe",
  "item_recipe_cyclone": "Eul's Scepter Recipe",
  "item_recipe_dagon": "Dagon Recipe",
  "item_recipe_devastator": "Parasma Recipe",
  "item_recipe_diffusal_blade": "Diffusal Blade Recipe",
  "item_recipe_disperser": "Disperser Recipe",
  "item_recipe_dragon_lance": "Dragon Lance Recipe",
  "item_recipe_essence_distiller": "Essence Distiller Recipe",
  "item_recipe_eternal_shroud": "Eternal Shroud Recipe",
  "item_recipe_ethereal_blade": "Ethereal Blade Recipe",
  "item_recipe_falcon_blade": "Falcon Blade Recipe",
  "item_recipe_force_staff": "Force Staff Recipe",
  "item_recipe_glimmer_cape": "Glimmer Cape Recipe",
  "item_recipe_greater_crit": "Daedalus Recipe",
  "item_recipe_guardian_greaves": "Guardian Greaves Recipe",
  "item_recipe_gungir": "Gleipnir Recipe",
  "item_recipe_hand_of_midas": "Hand of Midas Recipe",
  "item_recipe_harpoon": "Harpoon Recipe",
  "item_recipe_headdress": "Headdress Recipe",
  "item_recipe_heart": "Heart of Tarrasque Recipe",
  "item_recipe_heavens_halberd": "Heaven's Halberd Recipe",
  "item_recipe_helm_of_the_dominator": "Helm of the Dominator Recipe",
  "item_recipe_helm_of_the_overlord": "Helm of the Overlord Recipe",
  "item_recipe_holy_locket": "Holy Locket Recipe",
  "item_recipe_hurricane_pike": "Hurricane Pike Recipe",
  "item_recipe_iron_talon": "Iron Talon Recipe",
  "item_recipe_kaya": "Kaya Recipe",
  "item_recipe_lesser_crit": "Crystalys Recipe",
  "item_recipe_lotus_orb": "Lotus Orb Recipe",
  "item_recipe_magic_wand": "Magic Wand Recipe",
  "item_recipe_manta": "Manta Style Recipe",
  "item_recipe_mekansm": "Mekansm Recipe",
  "item_recipe_meteor_hammer": "Meteor Hammer Recipe",
  "item_recipe_mjollnir": "Mjollnir Recipe",
  "item_recipe_monkey_king_bar": "Monkey King Bar Recipe",
  "item_recipe_necronomicon": "Necronomicon Recipe",
  "item_recipe_null_talisman": "Null Talisman Recipe",
  "item_recipe_octarine_core": "Octarine Core Recipe",
  "item_recipe_orchid": "Orchid Malevolence Recipe",
  "item_recipe_overwhelming_blink": "Overwhelming Blink Recipe",
  "item_recipe_pavise": "Pavise Recipe",
  "item_recipe_phylactery": "Phylactery Recipe",
  "item_recipe_pipe": "Pipe of Insight Recipe",
  "item_recipe_refresher": "Refresher Orb Recipe",
  "item_recipe_revenants_brooch": "Revenant's Brooch Recipe",
  "item_recipe_ring_of_basilius": "Ring of Basilius Recipe",
  "item_recipe_rod_of_atos": "Rod of Atos Recipe",
  "item_recipe_sange": "Sange Recipe",
  "item_recipe_sheepstick": "Scythe of Vyse Recipe",
  "item_recipe_shivas_guard": "Shiva's Guard Recipe",
  "item_recipe_silver_edge": "Silver Edge Recipe",
  "item_recipe_solar_crest": "Solar Crest Recipe",
  "item_recipe_soul_ring": "Soul Ring Recipe",
  "item_recipe_sphere": "Linken's Sphere Recipe",
  "item_recipe_spirit_vessel": "Spirit Vessel Recipe",
  "item_recipe_swift_blink": "Swift Blink Recipe",
  "item_recipe_travel_boots": "Boots of Travel Recipe",
  "item_recipe_trident": "Trident Recipe",
  "item_recipe_ultimate_scepter_2": "Aghanim's Blessing Recipe",
  "item_recipe_urn_of_shadows": "Urn of Shadows Recipe",
  "item_recipe_veil_of_discord": "Veil of Discord Recipe",
  "item_recipe_wind_waker": "Wind Waker Recipe",
  "item_recipe_witch_blade": "Witch Blade Recipe",
  "item_recipe_wraith_band": "Wraith Band Recipe",
  "item_recipe_yasha": "Yasha Recipe",
  "item_refresher": "Refresher Orb",
  "item_refresher_shard": "Refresher Shard",
  "item_relic": "Sacred Relic",
  "item_repair_kit": "Repair Kit",
  "item_revenants_brooch": "Revenant's Brooch",
  "item_riftshadow_prism": "Riftshadow Prism",
  "item_ring_of_aquila": "Ring of Aquila",
  "item_ring_of_basilius": "Ring of Basilius",
  "item_ring_of_health": "Ring of Health",
  "item_ring_of_protection": "Ring of Protection",
  "item_ring_of_regen": "Ring of Regen",
  "item_ring_of_tarrasque": "Ring of Tarrasque",
  "item_rippers_lash": "Ripper's Lash",
  "item_river_painter": "River Vial: Chrome",
  "item_river_painter2": "River Vial: Dry",
  "item_river_painter3": "River Vial: Slime",
  "item_river_painter4": "River Vial: Oil",
  "item_river_painter5": "River Vial: Electrified",
  "item_river_painter6": "River Vial: Potion",
  "item_river_painter7": "River Vial: Blood",
  "item_robe": "Robe of the Magi",
  "item_rod_of_atos": "Rod of Atos",
  "item_roshans_banner": "Roshan's Banner",
  "item_royal_jelly": "Royal Jelly",
  "item_royale_with_cheese": "Block of Cheese",
  "item_safety_bubble": "Safety Bubble",
  "item_sange": "Sange",
  "item_sange_and_yasha": "Sange and Yasha",
  "item_satanic": "Satanic",
  "item_searing_signet": "Searing Signet",
  "item_seeds_of_serenity": "Seeds of Serenity",
  "item_seer_stone": "Seer Stone",
  "item_serrated_shiv": "Serrated Shiv",
  "item_shadow_amulet": "Shadow Amulet",
  "item_shawl": "Shawl",
  "item_sheepstick": "Scythe of Vyse",
  "item_shivas_guard": "Shiva's Guard",
  "item_silver_edge": "Silver Edge",
  "item_sisters_shroud": "Sister's Shroud",
  "item_skadi": "Eye of Skadi",
  "item_slippers": "Slippers of Agility",
  "item_smoke_of_deceit": "Smoke of Deceit",
  "item_sobi_mask": "Sage's Mask",
  "item_solar_crest": "Solar Crest",
  "item_soul_booster": "Soul Booster",
  "item_soul_ring": "Soul Ring",
  "item_spark_of_courage": "Spark of Courage",
  "item_specialists_array": "Specialist's Array",
  "item_spell_prism": "Spell Prism",
  "item_spellslinger": "Spellslinger",
  "item_sphere": "Linken's Sphere",
  "item_spider_legs": "Spider Legs",
  "item_spirit_vessel": "Spirit Vessel",
  "item_splintmail": "Splintmail",
  "item_spy_gadget": "Telescope",
  "item_staff_of_wizardry": "Staff of Wizardry",
  "item_stonefeather_satchel": "Stonefeather Satchel",
  "item_stormcrafter": "Stormcrafter",
  "item_stout_shield": "Stout Shield",
  "item_swift_blink": "Swift Blink",
  "item_talisman_of_evasion": "Talisman of Evasion",
  "item_tango": "Tango",
  "item_tango_single": "Tango (Shared)",
  "item_the_leveller": "The Leveller",
  "item_third_eye": "Third Eye",
  "item_tiara_of_selemene": "Tiara of Selemene",
  "item_tidehunter_fish": "Leviathan's Fish",
  "item_tier1_token": "Tier 1 Token",
  "item_tier2_token": "Tier 2 Token",
  "item_tier3_token": "Tier 3 Token",
  "item_tier4_token": "Tier 4 Token",
  "item_tier5_token": "Tier 5 Token",
  "item_timeless_relic": "Timeless Relic",
  "item_titan_sliver": "Titan Sliver",
  "item_tome_of_aghanim": "Tome of Aghanim",
  "item_tome_of_knowledge": "Tome of Knowledge",
  "item_tpscroll": "Town Portal Scroll",
  "item_tranquil_boots": "Tranquil Boots",
  "item_travel_boots": "Boots of Travel",
  "item_travel_boots_2": "Boots of Travel 2",
  "item_trickster_cloak": "Trickster Cloak",
  "item_trident": "Trident",
  "item_trusty_shovel": "Trusty Shovel",
  "item_ultimate_orb": "Ultimate Orb",
  "item_ultimate_scepter": "Aghanim's Scepter",
  "item_ultimate_scepter_2": "Aghanim's Blessing",
  "item_ultimate_scepter_roshan": "Aghanim's Blessing - Roshan",
  "item_unrelenting_eye": "Unrelenting Eye",
  "item_unstable_wand": "Pig Pole",
  "item_unwavering_condition": "Unwavering Condition",
  "item_urn_of_shadows": "Urn of Shadows",
  "item_vambrace": "Vambrace",
  "item_vampire_fangs": "Vampire Fangs",
  "item_vanguard": "Vanguard",
  "item_veil_of_discord": "Veil of Discord",
  "item_vindicators_axe": "Vindicator's Axe",
  "item_vitality_booster": "Vitality Booster",
  "item_vladmir": "Vladmir's Offering",
  "item_void_stone": "Void Stone",
  "item_voodoo_mask": "Voodoo Mask",
  "item_ward_dispenser": "Observer and Sentry Wards",
  "item_ward_observer": "Observer Ward",
  "item_ward_sentry": "Sentry Ward",
  "item_weighted_dice": "Weighted Dice",
  "item_whisper_of_the_dread": "Whisper of the Dread",
  "item_wind_lace": "Wind Lace",
  "item_wind_waker": "Wind Waker",
  "item_witch_blade": "Witch Blade",
  "item_witless_shako": "Witless Shako",
  "item_wizard_hat": "Wizard Hat",
  "item_woodland_striders": "Woodland Striders",
  "item_wraith_band": "Wraith Band",
  "item_wraith_pact": "Wraith Pact",
  "item_yasha": "Yasha",
  "item_yasha_and_kaya": "Yasha and Kaya",
  "jakiro_double_trouble": "Double Trouble",
  "jakiro_dual_breath": "Dual Breath",
  "jakiro_ice_path": "Ice Path",
  "jakiro_ice_path_detonate": "Destroy Ice Path",
  "jakiro_liquid_fire": "Liquid Fire",
  "jakiro_liquid_ice": "Liquid Frost",
  "jakiro_macropyre": "Macropyre",
  "juggernaut_blade_dance": "Blade Dance",
  "juggernaut_blade_fury": "Blade Fury",
  "juggernaut_bladeform": "Bladeform",
  "juggernaut_duelist": "Duelist",
  "juggernaut_healing_ward": "Healing Ward",
  "juggernaut_omni_slash": "Omnislash",
  "juggernaut_swift_slash": "Swiftslash",
  "keeper_of_the_light_blinding_light": "Blinding Light",
  "keeper_of_the_light_bright_speed": "Bright Speed",
  "keeper_of_the_light_chakra_magic": "Chakra Magic",
  "keeper_of_the_light_illuminate": "Illuminate",
  "keeper_of_the_light_illuminate_end": "Release Illuminate",
  "keeper_of_the_light_radiant_bind": "Solar Bind",
  "keeper_of_the_light_recall": "Recall",
  "keeper_of_the_light_special_reserve": "Special Reserve",
  "keeper_of_the_light_spirit_form": "Spirit Form",
  "keeper_of_the_light_will_o_wisp": "Will-O-Wisp",
  "kez_echo_slash": "Echo Slash",
  "kez_falcon_rush": "Falcon Rush",
  "kez_grappling_claw": "Grappling Claw",
  "kez_kazurai_katana": "Kazurai Katana",
  "kez_raptor_dance": "Raptor Dance",
  "kez_ravens_veil": "Raven's Veil",
  "kez_shodo_sai": "Shodo Sai",
  "kez_shodo_sai_parry_cancel": "Cancel",
  "kez_switch_weapons": "Switch Discipline",
  "kez_talon_toss": "Talon Toss",
  "kobold_disarm": "Steal Weapon",
  "kobold_taskmaster_speed_aura": "Speed Aura",
  "kobold_tunneler_prospecting": "Prospecting Aura",
  "kunkka_admirals_rum": "Admiral's Rum",
  "kunkka_ghostship": "Ghostship",
  "kunkka_return": "Return",
  "kunkka_tidal_wave": "Tidal Wave",
  "kunkka_tidebringer": "Tidebringer",
  "kunkka_torrent": "Torrent",
  "kunkka_x_marks_the_spot": "X Marks the Spot",
  "largo_amphibian_rhapsody": "Amphibian Rhapsody",
  "largo_catchy_lick": "Catchy Lick",
  "largo_croak_of_genius": "Croak of Genius",
  "largo_encore": "Encore",
  "largo_frogstomp": "Frogstomp",
  "largo_song_double_time": "Hotfeet Hustle",
  "largo_song_fight_song": "Bullbelly Blitz",
  "largo_song_good_vibrations": "Island Elixir",
  "legion_commander_duel": "Duel",
  "legion_commander_moment_of_courage": "Moment of Courage",
  "legion_commander_outfight_them": "Outfight Them!",
  "legion_commander_overwhelming_odds": "Overwhelming Odds",
  "legion_commander_press_the_attack": "Press The Attack",
  "leshrac_chronoptic_nourishment": "Chronoptic Nourishment",
  "leshrac_defilement": "Defilement",
  "leshrac_diabolic_edict": "Diabolic Edict",
  "leshrac_greater_lightning_storm": "Nihilism",
  "leshrac_lightning_storm": "Lightning Storm",
  "leshrac_pulse_nova": "Pulse Nova",
  "leshrac_split_earth": "Split Earth",
  "lich_chain_frost": "Chain Frost",
  "lich_death_charge": "Sacrifice",
  "lich_frost_nova": "Frost Blast",
  "lich_frost_shield": "Frost Shield",
  "lich_ice_spire": "Ice Spire",
  "lich_sinister_gaze": "Sinister Gaze",
  "life_stealer_consume": "Consume",
  "life_stealer_feast": "Feast",
  "life_stealer_ghoul_frenzy": "Ghoul Frenzy",
  "life_stealer_infest": "Infest",
  "life_stealer_open_wounds": "Open Wounds",
  "life_stealer_rage": "Rage",
  "life_stealer_unfettered": "Unfettered",
  "lina_combustion": "Combustion",
  "lina_dragon_slave": "Dragon Slave",
  "lina_fiery_soul": "Fiery Soul",
  "lina_flame_cloak": "Flame Cloak",
  "lina_laguna_blade": "Laguna Blade",
  "lina_light_strike_array": "Light Strike Array",
  "lina_slow_burn": "Slow Burn",
  "lion_finger_of_death": "Finger of Death",
  "lion_impale": "Earth Spike",
  "lion_mana_drain": "Mana Drain",
  "lion_to_hell_and_back": "To Hell and Back",
  "lion_voodoo": "Hex",
  "lone_druid_bear_necessities": "Bear Necessities",
  "lone_druid_entangle": "Entangle",
  "lone_druid_gift_bearer": "Gift Bearer",
  "lone_druid_savage_roar": "Savage Roar",
  "lone_druid_savage_roar_bear": "Savage Roar",
  "lone_druid_spirit_bear": "Summon Spirit Bear",
  "lone_druid_spirit_bear_demolish": "Demolish",
  "lone_druid_spirit_bear_entangle": "Entangling Claws",
  "lone_druid_spirit_bear_fetch": "Fetch",
  "lone_druid_spirit_bear_return": "Return",
  "lone_druid_spirit_bear_spirit_link": "Spirit Link",
  "lone_druid_spirit_link": "Spirit Link",
  "lone_druid_true_form": "True Form",
  "luna_eclipse": "Eclipse",
  "luna_lucent_beam": "Lucent Beam",
  "luna_lunar_blessing": "Lunar Blessing",
  "luna_lunar_orbit": "Lunar Orbit",
  "luna_moon_glaive": "Moon Glaives",
  "lycan_apex_predator": "Apex Predator",
  "lycan_feral_impulse": "Feral Impulse",
  "lycan_howl": "Howl",
  "lycan_shapeshift": "Shapeshift",
  "lycan_summon_wolves": "Summon Wolves",
  "lycan_summon_wolves_critical_strike": "Cripple",
  "lycan_summon_wolves_hamstring": "Hamstring",
  "lycan_summon_wolves_hightail": "Hightail",
  "lycan_summon_wolves_invisibility": "Invisibility",
  "lycan_wolf_bite": "Wolf Bite",
  "magnataur_empower": "Empower",
  "magnataur_horn_toss": "Horn Toss",
  "magnataur_reverse_polarity": "Reverse Polarity",
  "magnataur_shockwave": "Shockwave",
  "magnataur_skewer": "Skewer",
  "magnataur_solid_core": "Solid Core",
  "marci_bodyguard": "Bodyguard",
  "marci_companion_run": "Rebound",
  "marci_grapple": "Dispose",
  "marci_special_delivery": "Special Delivery",
  "marci_unleash": "Unleash",
  "mars_arena_of_blood": "Arena Of Blood",
  "mars_bulwark": "Bulwark",
  "mars_dauntless": "Dauntless",
  "mars_gods_rebuke": "God's Rebuke",
  "mars_immovable": "Immovable",
  "mars_spear": "Spear of Mars",
  "medusa_cold_blooded": "Cold Blooded",
  "medusa_gorgon_grasp": "Gorgon's Grasp",
  "medusa_mana_shield": "Mana Shield",
  "medusa_mystic_snake": "Mystic Snake",
  "medusa_split_shot": "Split Shot",
  "medusa_stone_gaze": "Stone Gaze",
  "medusa_undulation": "Undulation",
  "meepo_divided_we_stand": "Divided We Stand",
  "meepo_earthbind": "Earthbind",
  "meepo_fling": "Fling",
  "meepo_fling_release": "Fling Release",
  "meepo_geomancy": "Geomancy",
  "meepo_megameepo": "MegaMeepo",
  "meepo_megameepo_fling": "MegaMeepo Fling",
  "meepo_pack_rat": "Pack Rat",
  "meepo_petrify": "Dig",
  "meepo_poof": "Poof",
  "meepo_ransack": "Ransack",
  "meepo_sticky_fingers": "Sticky Fingers",
  "miniboss_alleviation": "Alleviation",
  "miniboss_fortification": "Fortification",
  "miniboss_radiance": "The Shining",
  "miniboss_reflect": "Reflect",
  "miniboss_unyielding_shield": "Unyielding Shield",
  "mirana_arrow": "Sacred Arrow",
  "mirana_celestial_quiver": "Celestial Quiver",
  "mirana_invis": "Moonlight Shadow",
  "mirana_leap": "Leap",
  "mirana_selemenes_faithful": "Selemene's Faithful",
  "mirana_solar_flare": "Solar Flare",
  "mirana_starfall": "Starstorm",
  "monkey_king_boundless_strike": "Boundless Strike",
  "monkey_king_jingu_mastery": "Jingu Mastery",
  "monkey_king_mischief": "Mischief",
  "monkey_king_primal_spring": "Primal Spring",
  "monkey_king_primal_spring_early": "Spring Early",
  "monkey_king_transfiguration": "Changing of the Guard",
  "monkey_king_tree_dance": "Tree Dance",
  "monkey_king_untransform": "Revert Form",
  "monkey_king_wukongs_command": "Wukong's Command",
  "morphling_accumulation": "Accumulation",
  "morphling_adaptive_strike_agi": "Adaptive Strike",
  "morphling_ebb": "Ebb",
  "morphling_ebb_and_flow": "Ebb and Flow",
  "morphling_flow": "Flow",
  "morphling_morph_agi": "Attribute Shift (Agility Gain)",
  "morphling_morph_replicate": "Morph Replicate",
  "morphling_morph_str": "Attribute Shift (Strength Gain)",
  "morphling_replicate": "Morph",
  "morphling_syntropy": "Syntropy",
  "morphling_waveform": "Waveform",
  "mud_golem_hurl_boulder": "Hurl Boulder",
  "mud_golem_rock_destroy": "Shard Split",
  "mudgolem_cloak_aura": "Cloak Aura",
  "muerta_dead_shot": "Dead Shot",
  "muerta_gunslinger": "Gunslinger",
  "muerta_ofrenda": "Ofrenda",
  "muerta_ofrenda_destroy": "Destroy Ofrenda",
  "muerta_pierce_the_veil": "Pierce the Veil",
  "muerta_spectral_slug": "Spectral Slug",
  "muerta_supernatural": "Supernatural",
  "muerta_the_calling": "The Calling",
  "naga_siren_deluge": "Deluge",
  "naga_siren_eelskin": "Eelskin",
  "naga_siren_ensnare": "Ensnare",
  "naga_siren_mirror_image": "Mirror Image",
  "naga_siren_reel_in": "Reel In",
  "naga_siren_rip_tide": "Rip Tide",
  "naga_siren_slithereen_cutlass": "Slithereen Cutlass",
  "naga_siren_song_of_the_siren": "Song of the Siren",
  "naga_siren_song_of_the_siren_cancel": "Song of the Siren End",
  "necrolyte_death_pulse": "Death Pulse",
  "necrolyte_death_seeker": "Death Seeker",
  "necrolyte_ghost_shroud": "Ghost Shroud",
  "necrolyte_heartstopper_aura": "Heartstopper Aura",
  "necrolyte_reapers_scythe": "Reaper's Scythe",
  "necrolyte_sadist": "Sadist",
  "necronomicon_archer_aoe": "Archer Aura",
  "necronomicon_archer_mana_burn": "Mana Burn",
  "necronomicon_archer_purge": "Purge",
  "necronomicon_warrior_last_will": "Last Will",
  "necronomicon_warrior_mana_burn": "Mana Break",
  "necronomicon_warrior_sight": "True Sight",
  "neutral_spell_immunity": "Spell Immunity",
  "nevermore_dark_lord": "Presence of the Dark Lord",
  "nevermore_frenzy": "Feast of Souls",
  "nevermore_necromastery": "Necromastery",
  "nevermore_requiem": "Requiem of Souls",
  "nevermore_shadowraze1": "Shadowraze",
  "nevermore_shadowraze2": "Shadowraze",
  "nevermore_shadowraze3": "Shadowraze",
  "night_stalker_crippling_fear": "Crippling Fear",
  "night_stalker_darkness": "Dark Ascension",
  "night_stalker_heart_of_darkness": "Heart of Darkness",
  "night_stalker_hunter_in_the_night": "Hunter in the Night",
  "night_stalker_midnight_feast": "Midnight Feast",
  "night_stalker_night_reign": "Night Reign",
  "night_stalker_void": "Void",
  "nyx_assassin_burrow": "Burrow",
  "nyx_assassin_impale": "Impale",
  "nyx_assassin_jolt": "Mind Flare",
  "nyx_assassin_neuro_sting": "Mana Burn",
  "nyx_assassin_nyxth_sense": "Nyxth Sense",
  "nyx_assassin_spiked_carapace": "Spiked Carapace",
  "nyx_assassin_unburrow": "Unburrow",
  "nyx_assassin_vendetta": "Vendetta",
  "obsidian_destroyer_arcane_orb": "Arcane Orb",
  "obsidian_destroyer_astral_imprisonment": "Astral Imprisonment",
  "obsidian_destroyer_equilibrium": "Essence Flux",
  "obsidian_destroyer_objurgation": "Objurgation",
  "obsidian_destroyer_ominous_discernment": "Ominous Discernment",
  "obsidian_destroyer_sanity_eclipse": "Sanity's Eclipse",
  "ogre_bruiser_ogre_smash": "Ogre Smash!",
  "ogre_magi_bloodlust": "Bloodlust",
  "ogre_magi_dumb_luck": "Dumb Luck",
  "ogre_magi_fireblast": "Fireblast",
  "ogre_magi_frost_armor": "Ice Armor",
  "ogre_magi_ignite": "Ignite",
  "ogre_magi_multicast": "Multicast",
  "ogre_magi_smash": "Fire Shield",
  "ogre_magi_unrefined_fireblast": "Unrefined Fireblast",
  "omniknight_degen_aura": "Degen Aura",
  "omniknight_guardian_angel": "Guardian Angel",
  "omniknight_hammer_of_purity": "Hammer of Purity",
  "omniknight_healing_hammer": "Healing Hammer",
  "omniknight_martyr": "Repel",
  "omniknight_purification": "Purification",
  "oracle_clairvoyant_cure": "Clairvoyant Cure",
  "oracle_clairvoyant_curse": "Clairvoyant Curse",
  "oracle_diviners_deck": "Diviner's Deck",
  "oracle_false_promise": "False Promise",
  "oracle_fates_edict": "Fate's Edict",
  "oracle_fortunes_end": "Fortune's End",
  "oracle_prognosticate": "Prognosticate",
  "oracle_purifying_flames": "Purifying Flames",
  "oracle_rain_of_destiny": "Rain of Destiny",
  "pangolier_fortune_favors_the_bold": "Fortune Favors the Bold",
  "pangolier_gyroshell": "Rolling Thunder",
  "pangolier_gyroshell_stop": "Stop Rolling",
  "pangolier_lucky_shot": "Lucky Shot",
  "pangolier_rollup": "Roll Up",
  "pangolier_rollup_stop": "End Roll Up",
  "pangolier_shield_crash": "Shield Crash",
  "pangolier_swashbuckle": "Swashbuckle",
  "phantom_assassin_blur": "Blur",
  "phantom_assassin_coup_de_grace": "Coup de Grace",
  "phantom_assassin_fan_of_knives": "Fan of Knives",
  "phantom_assassin_immaterial": "Immaterial",
  "phantom_assassin_phantom_strike": "Phantom Strike",
  "phantom_assassin_stifling_dagger": "Stifling Dagger",
  "phantom_lancer_doppelwalk": "Doppelganger",
  "phantom_lancer_illusory_armaments": "Illusory Armaments",
  "phantom_lancer_juxtapose": "Juxtapose",
  "phantom_lancer_phantom_edge": "Phantom Rush",
  "phantom_lancer_spirit_lance": "Spirit Lance",
  "phoenix_blinding_sun": "Blinding Sun",
  "phoenix_dying_light": "Dying Light",
  "phoenix_fire_spirits": "Fire Spirits",
  "phoenix_icarus_dive": "Icarus Dive",
  "phoenix_icarus_dive_stop": "Stop Icarus Dive",
  "phoenix_launch_fire_spirit": "Launch Fire Spirit",
  "phoenix_sun_ray": "Sun Ray",
  "phoenix_sun_ray_stop": "Stop Sun Ray",
  "phoenix_sun_ray_toggle_move": "Toggle Movement",
  "phoenix_supernova": "Supernova",
  "plus_guild_banner": "Guild Banner",
  "plus_high_five": "High Five",
  "polar_furbolg_ursa_warrior_thunder_clap": "Thunder Clap",
  "primal_beast_colossal": "Colossal",
  "primal_beast_onslaught": "Onslaught",
  "primal_beast_onslaught_release": "Begin Onslaught",
  "primal_beast_pulverize": "Pulverize",
  "primal_beast_rock_throw": "Rock Throw",
  "primal_beast_trample": "Trample",
  "primal_beast_uproar": "Uproar",
  "puck_dream_coil": "Dream Coil",
  "puck_ethereal_jaunt": "Ethereal Jaunt",
  "puck_illusory_orb": "Illusory Orb",
  "puck_phase_shift": "Phase Shift",
  "puck_puckish": "Puckish",
  "puck_waning_rift": "Waning Rift",
  "pudge_dismember": "Dismember",
  "pudge_eject": "Eject",
  "pudge_flesh_heap": "Meat Shield",
  "pudge_innate_graft_flesh": "Flesh Heap",
  "pudge_meat_hook": "Meat Hook",
  "pudge_rot": "Rot",
  "pugna_decrepify": "Decrepify",
  "pugna_life_drain": "Life Drain",
  "pugna_nether_blast": "Nether Blast",
  "pugna_nether_ward": "Nether Ward",
  "pugna_oblivion_savant": "Oblivion Savant",
  "queenofpain_blink": "Blink",
  "queenofpain_bondage": "Bondage",
  "queenofpain_masochist": "Masochist",
  "queenofpain_scream_of_pain": "Scream Of Pain",
  "queenofpain_shadow_strike": "Shadow Strike",
  "queenofpain_sonic_wave": "Sonic Wave",
  "queenofpain_succubus": "Succubus",
  "rattletrap_armor_power": "Armor Power",
  "rattletrap_battery_assault": "Battery Assault",
  "rattletrap_hookshot": "Hookshot",
  "rattletrap_jetpack": "Jetpack",
  "rattletrap_jetpack_toggle": "Jetpack Toggle",
  "rattletrap_overclocking": "Overclocking",
  "rattletrap_power_cogs": "Power Cogs",
  "rattletrap_rocket_flare": "Rocket Flare",
  "razor_dynamo": "Dynamo",
  "razor_eye_of_the_storm": "Eye of the Storm",
  "razor_plasma_field": "Plasma Field",
  "razor_static_link": "Static Link",
  "razor_storm_surge": "Storm Surge",
  "razor_unstable_current": "Unstable Current",
  "riki_backstab": "Cloak and Dagger",
  "riki_blink_strike": "Blink Strike",
  "riki_innate_backstab": "Backstab",
  "riki_smoke_screen": "Smoke Screen",
  "riki_tricks_of_the_trade": "Tricks of the Trade",
  "ringmaster_crystal_ball": "Crystal Ball",
  "ringmaster_dark_carnival_souvenirs": "Dark Carnival Barker",
  "ringmaster_empty_souvenir": "Souvenir Slot",
  "ringmaster_funhouse_mirror": "Funhouse Mirror",
  "ringmaster_impalement": "Impalement Arts",
  "ringmaster_spotlight": "Spotlight",
  "ringmaster_strongman_tonic": "Strongman Tonic",
  "ringmaster_summon_unicycle": "Unicycle",
  "ringmaster_tame_the_beasts": "Tame the Beasts",
  "ringmaster_tame_the_beasts_crack": "Crack",
  "ringmaster_the_box": "Escape Act",
  "ringmaster_weighted_pie": "Weighted Pie",
  "ringmaster_wheel": "Wheel of Wonder",
  "ringmaster_whoopee_cushion": "Whoopee Cushion",
  "roshan_bash": "Bash",
  "roshan_devotion": "Strength of the Immortal",
  "roshan_grab_and_throw": "Throw",
  "roshan_revengeroar": "Roar of Retribution",
  "roshan_slam": "Slam",
  "roshan_spell_block": "Spell Block",
  "rubick_arcane_supremacy": "Arcane Supremacy",
  "rubick_curiosity": "Curiosity",
  "rubick_empty1": "Stolen Spell",
  "rubick_empty2": "Stolen Spell",
  "rubick_fade_bolt": "Fade Bolt",
  "rubick_might_and_magus": "Might and Magus",
  "rubick_spell_steal": "Spell Steal",
  "rubick_telekinesis": "Telekinesis",
  "rubick_telekinesis_land": "Telekinesis Land",
  "rubick_telekinesis_land_self": "Telekinesis Land",
  "sandking_burrowstrike": "Burrowstrike",
  "sandking_caustic_finale": "Caustic Finale",
  "sandking_epicenter": "Epicenter",
  "sandking_sand_storm": "Sand Storm",
  "sandking_scorpion_strike": "Stinger",
  "satyr_hellcaller_shockwave": "Shockwave",
  "satyr_hellcaller_unholy_aura": "Unholy Aura",
  "satyr_soulstealer_mana_burn": "Mana Burn",
  "satyr_trickster_purge": "Purge",
  "seasonal_dark_carnival_balloon": "Carnival Balloon",
  "seasonal_dark_carnival_firework": "Carnival Firework",
  "seasonal_dark_carnival_pie": "Carnival Pie",
  "seasonal_decorate_tree": "Decorate Tree",
  "seasonal_festive_firework": "Festive Firework",
  "seasonal_party_hat": "Spirit of Frostivus",
  "seasonal_summon_penguin": "Summon Penguin",
  "seasonal_summon_snowman": "Build Snowman",
  "seasonal_throw_snowball": "Throw Snowball",
  "shadow_demon_demonic_cleanse": "Demonic Cleanse",
  "shadow_demon_demonic_purge": "Demonic Purge",
  "shadow_demon_disruption": "Disruption",
  "shadow_demon_disseminate": "Disseminate",
  "shadow_demon_menace": "Menace",
  "shadow_demon_shadow_poison": "Shadow Poison",
  "shadow_demon_shadow_poison_release": "Shadow Poison Release",
  "shadow_demon_shadow_servant": "Soul Catcher",
  "shadow_shaman_ether_shock": "Ether Shock",
  "shadow_shaman_fowl_play": "Fowl Play",
  "shadow_shaman_mass_serpent_ward": "Mass Serpent Ward",
  "shadow_shaman_shackles": "Shackles",
  "shadow_shaman_urnaconda": "Urnaconda",
  "shadow_shaman_voodoo": "Hex",
  "shadow_shaman_voodoo_hands": "Chicken Fingers",
  "shredder_chakram": "Chakram",
  "shredder_exposure_therapy": "Exposure Therapy",
  "shredder_flamethrower": "Flamethrower",
  "shredder_reactive_armor": "Reactive Armor",
  "shredder_return_chakram": "Return Chakram",
  "shredder_timber_chain": "Timber Chain",
  "shredder_twisted_chakram": "Twisted Chakram",
  "shredder_whirling_death": "Whirling Death",
  "silencer_brain_drain": "Suffer In Silence",
  "silencer_curse_of_the_silent": "Arcane Curse",
  "silencer_glaives_of_wisdom": "Glaives of Wisdom",
  "silencer_global_silence": "Global Silence",
  "silencer_last_word": "Last Word",
  "silencer_oppressive_silence": "Suffer In Silence",
  "skeleton_king_bone_guard": "Bone Guard",
  "skeleton_king_hellfire_blast": "Wraithfire Blast",
  "skeleton_king_mortal_strike": "Mortal Strike",
  "skeleton_king_reincarnation": "Reincarnation",
  "skeleton_king_spectral_blade": "Spectral Blade",
  "skeleton_king_vampiric_spirit": "Vampiric Spirit",
  "skywrath_mage_ancient_seal": "Ancient Seal",
  "skywrath_mage_arcane_bolt": "Arcane Bolt",
  "skywrath_mage_concussive_shot": "Concussive Shot",
  "skywrath_mage_mystic_flare": "Mystic Flare",
  "skywrath_mage_ruin_and_restoration": "Ruin and Restoration",
  "skywrath_mage_shield_of_the_scion": "Shield of the Scion",
  "skywrath_mage_staff_of_the_scion": "Staff of the Scion",
  "slardar_amplify_damage": "Corrosive Haze",
  "slardar_bash": "Bash of the Deep",
  "slardar_seaborn_sentinel": "Seaborn Sentinel",
  "slardar_slithereen_crush": "Slithereen Crush",
  "slardar_sprint": "Guardian Sprint",
  "slark_dark_pact": "Dark Pact",
  "slark_depth_shroud": "Depth Shroud",
  "slark_essence_shift": "Essence Shift",
  "slark_pounce": "Pounce",
  "slark_saltwater_shiv": "Saltwater Shiv",
  "slark_shadow_dance": "Shadow Dance",
  "snapfire_boomstick": "Boomstick",
  "snapfire_buckshot": "Buckshot",
  "snapfire_firesnap_cookie": "Firesnap Cookie",
  "snapfire_gobble_up": "Gobble Up",
  "snapfire_lil_shredder": "Lil' Shredder",
  "snapfire_mortimer_kisses": "Mortimer Kisses",
  "snapfire_scatterblast": "Scatterblast",
  "snapfire_spit_creep": "Spit Out",
  "sniper_assassinate": "Assassinate",
  "sniper_concussive_grenade": "Concussive Grenade",
  "sniper_headshot": "Headshot",
  "sniper_keen_scope": "Keen Scope",
  "sniper_shrapnel": "Shrapnel",
  "sniper_take_aim": "Take Aim",
  "sniper_take_aim_stop": "Stop Take Aim",
  "spawnlord_aura": "Prowler Aura",
  "spawnlord_master_freeze": "Petrify",
  "spawnlord_master_stomp": "Desecrate",
  "spectre_desolate": "Desolate",
  "spectre_dispersion": "Dispersion",
  "spectre_haunt": "Haunt",
  "spectre_reality": "Reality",
  "spectre_shadow_step": "Shadow Step",
  "spectre_spectral": "Spectral",
  "spectre_spectral_dagger": "Spectral Dagger",
  "spirit_breaker_bull_rush": "Empowering Haste",
  "spirit_breaker_bulldoze": "Bulldoze",
  "spirit_breaker_charge_of_darkness": "Charge of Darkness",
  "spirit_breaker_greater_bash": "Greater Bash",
  "spirit_breaker_herd_mentality": "Herd Mentality",
  "spirit_breaker_nether_strike": "Nether Strike",
  "spirit_breaker_planar_pocket": "Planar Pocket",
  "storm_spirit_ball_lightning": "Ball Lightning",
  "storm_spirit_electric_rave": "Electric Rave",
  "storm_spirit_electric_vortex": "Electric Vortex",
  "storm_spirit_galvanized": "Galvanized",
  "storm_spirit_overload": "Overload",
  "storm_spirit_static_remnant": "Static Remnant",
  "sven_gods_strength": "God's Strength",
  "sven_great_cleave": "Great Cleave",
  "sven_storm_bolt": "Storm Hammer",
  "sven_vanquisher": "Vanquisher",
  "sven_warcry": "Warcry",
  "sven_wrath_of_god": "Wrath of God",
  "techies_focused_detonate": "Detonate M.A.D.",
  "techies_land_mines": "Proximity Mines",
  "techies_minefield_sign": "Minefield Sign",
  "techies_mutually_assured_destruction": "M.A.D.",
  "techies_reactive_tazer": "Reactive Tazer",
  "techies_reactive_tazer_stop": "Detonate Tazer",
  "techies_remote_mines": "Remote Mines",
  "techies_remote_mines_self_detonate": "PINPOINT DETONATE",
  "techies_snare_trap": "Snare Trap",
  "techies_spoons_stash": "Spoon's Stash",
  "techies_squees_scope": "Squee's Scope",
  "techies_stasis_trap": "Stasis Trap",
  "techies_sticky_bomb": "Sticky Bomb",
  "techies_suicide": "Blast Off!",
  "templar_assassin_hidden_gates": "Hidden Gates",
  "templar_assassin_inner_peace": "Inner Peace",
  "templar_assassin_meditation_end": "End Meditation",
  "templar_assassin_meld": "Meld",
  "templar_assassin_psi_blades": "Psi Blades",
  "templar_assassin_psionic_trap": "Psionic Trap",
  "templar_assassin_refraction": "Refraction",
  "templar_assassin_self_trap": "Trap",
  "templar_assassin_third_eye": "Third Eye",
  "templar_assassin_trap": "Trap",
  "templar_assassin_trap_teleport": "Psionic Projection",
  "terrorblade_conjure_image": "Conjure Image",
  "terrorblade_dark_unity": "Dark Unity",
  "terrorblade_demon_zeal": "Demon Zeal",
  "terrorblade_metamorphosis": "Metamorphosis",
  "terrorblade_reflection": "Reflection",
  "terrorblade_sunder": "Sunder",
  "terrorblade_terror_wave": "Terror Wave",
  "tidehunter_anchor_smash": "Anchor Smash",
  "tidehunter_blubber": "Blubber",
  "tidehunter_dead_in_the_water": "Dead in the Water",
  "tidehunter_gush": "Gush",
  "tidehunter_kraken_shell": "Kraken Shell",
  "tidehunter_leviathans_catch": "Leviathan's Catch",
  "tidehunter_ravage": "Ravage",
  "tinker_defense_matrix": "Defense Matrix",
  "tinker_deploy_turrets": "Deploy Turrets",
  "tinker_eureka": "Eureka!",
  "tinker_keen_teleport": "Keen Conveyance",
  "tinker_laser": "Laser",
  "tinker_march_of_the_machines": "March of the Machines",
  "tinker_rearm": "Rearm",
  "tinker_warp_grenade": "Warp Flare",
  "tiny_avalanche": "Avalanche",
  "tiny_craggy_exterior": "Craggy Exterior",
  "tiny_grow": "Grow",
  "tiny_insurmountable": "Insurmountable",
  "tiny_toss": "Toss",
  "tiny_toss_tree": "Tree Throw",
  "tiny_tree_channel": "Tree Volley",
  "tiny_tree_grab": "Tree Grab",
  "tornado_tempest": "Tempest",
  "treant_eyes_in_the_forest": "Eyes In The Forest",
  "treant_leech_seed": "Leech Seed",
  "treant_living_armor": "Living Armor",
  "treant_natures_grasp": "Nature's Grasp",
  "treant_natures_guise": "Nature's Guise",
  "treant_overgrowth": "Overgrowth",
  "treant_super_bloom": "Super Bloom",
  "troll_warlord_battle_trance": "Battle Trance",
  "troll_warlord_berserkers_rage": "Berserker's Rage",
  "troll_warlord_fervor": "Fervor",
  "troll_warlord_switch_stance": "Battle Stance",
  "troll_warlord_whirling_axes_melee": "Whirling Axes (Melee)",
  "troll_warlord_whirling_axes_ranged": "Whirling Axes (Ranged)",
  "tusk_bitter_chill": "Bitter Chill",
  "tusk_drinking_buddies": "Drinking Buddies",
  "tusk_ice_shards": "Ice Shards",
  "tusk_launch_snowball": "Launch Snowball",
  "tusk_snowball": "Snowball",
  "tusk_tag_team": "Tag Team",
  "tusk_walrus_kick": "Walrus Kick",
  "tusk_walrus_punch": "Walrus PUNCH!",
  "undying_ceaseless_dirge": "Ceaseless Dirge",
  "undying_decay": "Decay",
  "undying_flesh_golem": "Flesh Golem",
  "undying_soul_rip": "Soul Rip",
  "undying_tombstone": "Tombstone",
  "undying_tombstone_zombie_deathstrike": "Deathlust",
  "ursa_bear_down": "Bear Down",
  "ursa_earthshock": "Earthshock",
  "ursa_enrage": "Enrage",
  "ursa_fury_swipes": "Fury Swipes",
  "ursa_maul": "Maul",
  "ursa_overpower": "Overpower",
  "vengefulspirit_command_aura": "Vengeance Aura",
  "vengefulspirit_magic_missile": "Magic Missile",
  "vengefulspirit_nether_swap": "Nether Swap",
  "vengefulspirit_retribution": "Retribution",
  "vengefulspirit_soul_strike": "Soul Strike",
  "vengefulspirit_wave_of_terror": "Wave of Terror",
  "venomancer_noxious_plague": "Noxious Plague",
  "venomancer_plague_ward": "Plague Ward",
  "venomancer_poison_nova": "Poison Nova",
  "venomancer_poison_sting": "Poison Sting",
  "venomancer_sepsis": "Septic Shock",
  "venomancer_snakebite": "Snakebite",
  "venomancer_venomous_gale": "Venomous Gale",
  "viper_corrosive_skin": "Corrosive Skin",
  "viper_nethertoxin": "Nethertoxin",
  "viper_nose_dive": "Nosedive",
  "viper_poison_attack": "Poison Attack",
  "viper_predator": "Predator",
  "viper_viper_strike": "Viper Strike",
  "visage_grave_chill": "Grave Chill",
  "visage_gravekeepers_cloak": "Gravekeeper's Cloak",
  "visage_lurker": "Lurker",
  "visage_silent_as_the_grave": "Silent as the Grave",
  "visage_soul_assumption": "Soul Assumption",
  "visage_stone_form_self_cast": "Stone Form",
  "visage_summon_familiars": "Summon Familiars",
  "visage_summon_familiars_recall": "Recall Familiar",
  "visage_summon_familiars_stone_form": "Stone Form",
  "void_spirit_aether_remnant": "Aether Remnant",
  "void_spirit_astral_step": "Astral Step",
  "void_spirit_dissimilate": "Dissimilate",
  "void_spirit_intrinsic_edge": "Intrinsic Edge",
  "void_spirit_resonant_pulse": "Resonant Pulse",
  "void_spirit_symmetry": "Symmetry",
  "warlock_black_grimoire": "Black Grimoire",
  "warlock_eldritch_summoning": "Eldritch Summoning",
  "warlock_fatal_bonds": "Fatal Bonds",
  "warlock_golem_flaming_fists": "Flaming Fists",
  "warlock_golem_permanent_immolation": "Permanent Immolation",
  "warlock_imp_explode": "Eldritch Explosion",
  "warlock_rain_of_chaos": "Chaotic Offering",
  "warlock_shadow_word": "Shadow Word",
  "warlock_upheaval": "Upheaval",
  "warpine_raider_seed_shot": "Seed Shot",
  "weaver_geminate_attack": "Geminate Attack",
  "weaver_rewoven": "Rewoven",
  "weaver_shukuchi": "Shukuchi",
  "weaver_the_swarm": "The Swarm",
  "weaver_threads_of_fate": "Threads of Fate",
  "weaver_time_lapse": "Time Lapse",
  "windrunner_easy_breezy": "Easy Breezy",
  "windrunner_focusfire": "Focus Fire",
  "windrunner_focusfire_cancel": "Focus Fire Cancel",
  "windrunner_gale_force": "Gale Force",
  "windrunner_powershot": "Powershot",
  "windrunner_shackleshot": "Shackleshot",
  "windrunner_tailwind": "Tailwind",
  "windrunner_windrun": "Windrun",
  "winter_wyvern_accelerated_learning": "Eldwurm Studies",
  "winter_wyvern_arctic_burn": "Arctic Burn",
  "winter_wyvern_cold_embrace": "Cold Embrace",
  "winter_wyvern_dragon_sight": "Dragon Sight",
  "winter_wyvern_eldwurm_scholar": "Eldwurm Scholar",
  "winter_wyvern_eldwurms_edda": "Eldwurm's Edda",
  "winter_wyvern_essence_of_the_blueheart": "Essence of the Blueheart",
  "winter_wyvern_splinter_blast": "Splinter Blast",
  "winter_wyvern_winters_curse": "Winter's Curse",
  "wisp_equilibrium": "Equilibrium",
  "wisp_essence_conduction": "Wellspring",
  "wisp_overcharge": "Overcharge",
  "wisp_relocate": "Relocate",
  "wisp_spirits": "Spirits",
  "wisp_spirits_in": "Spirits In",
  "wisp_spirits_out": "Spirits Out",
  "wisp_tether": "Tether",
  "wisp_tether_break": "Break Tether",
  "witch_doctor_death_ward": "Death Ward",
  "witch_doctor_gris_gris": "Gris-Gris",
  "witch_doctor_maledict": "Maledict",
  "witch_doctor_paralyzing_cask": "Paralyzing Cask",
  "witch_doctor_voodoo_restoration": "Voodoo Restoration",
  "witch_doctor_voodoo_switcheroo": "Voodoo Switcheroo",
  "zuus_arc_lightning": "Arc Lightning",
  "zuus_cloud": "Nimbus",
  "zuus_heavenly_jump": "Heavenly Jump",
  "zuus_lightning_bolt": "Lightning Bolt",
  "zuus_lightning_hands": "Lightning Hands",
  "zuus_static_field": "Static Field",
  "zuus_thundergods_wrath": "Thundergod's Wrath"
};
export const ultimateTypes:Readonly<Record<string,boolean>> = {
  "abaddon_borrowed_time": true,
  "abyssal_underling_archer_aoe": false,
  "abyssal_underling_warrior_last_will": false,
  "abyssal_underling_warrior_mana_burn": false,
  "abyssal_underlord_cancel_dark_rift": true,
  "abyssal_underlord_dark_portal": true,
  "abyssal_underlord_dark_rift": true,
  "alchemist_chemical_rage": true,
  "ancient_apparition_ice_blast": true,
  "ancient_apparition_ice_blast_release": true,
  "antimage_mana_void": true,
  "arc_warden_tempest_double": true,
  "arc_warden_tempest_recall": true,
  "axe_culling_blade": true,
  "bane_fiends_grip": true,
  "batrider_flaming_lasso": true,
  "beastmaster_primal_roar": true,
  "bloodseeker_rupture": true,
  "bounty_hunter_lookout": true,
  "bounty_hunter_track": true,
  "brewmaster_primal_companion": false,
  "brewmaster_primal_split": true,
  "bristleback_warpath": true,
  "broodmother_spawn_spiderlings": true,
  "centaur_stampede": true,
  "chaos_knight_phantasm": true,
  "chen_hand_of_god": true,
  "clinkz_burning_army": false,
  "clinkz_wind_walk": true,
  "crystal_maiden_crystal_nova": false,
  "crystal_maiden_freezing_field": true,
  "crystal_maiden_freezing_field_stop": true,
  "crystal_maiden_frostbite": false,
  "crystal_maiden_glacial_guard": false,
  "dark_seer_wall_of_replica": true,
  "dark_willow_bedlam": true,
  "dark_willow_bramble_maze": false,
  "dark_willow_terrorize": true,
  "dawnbreaker_solar_guardian": true,
  "dazzle_bad_juju": true,
  "dazzle_good_juju": true,
  "dazzle_nothl_projection": true,
  "dazzle_weave": true,
  "death_prophet_exorcism": true,
  "disruptor_static_storm": true,
  "doom_bringer_doom": true,
  "dragon_knight_elder_dragon_form": true,
  "dragon_knight_fireball": false,
  "drow_ranger_marksmanship": true,
  "earth_spirit_magnetize": true,
  "earth_spirit_stone_caller": false,
  "earthshaker_echo_slam": true,
  "elder_titan_earth_splitter": true,
  "ember_spirit_activate_fire_remnant": false,
  "ember_spirit_fire_remnant": true,
  "enchantress_untouchable": true,
  "enigma_black_hole": true,
  "faceless_void_chronosphere": true,
  "faceless_void_time_zone": true,
  "furion_wrath_of_nature": true,
  "grimstroke_soul_chain": true,
  "gyrocopter_call_down": true,
  "hoodwink_sharpshooter": true,
  "hoodwink_sharpshooter_release": true,
  "huskar_life_break": true,
  "invoker_attribute_bonus": false,
  "invoker_invoke": true,
  "jakiro_macropyre": true,
  "juggernaut_omni_slash": true,
  "keeper_of_the_light_spirit_form": true,
  "kez_raptor_dance": true,
  "kez_ravens_veil": true,
  "kunkka_ghostship": true,
  "largo_amphibian_rhapsody": true,
  "largo_catchy_lick": false,
  "largo_croak_of_genius": false,
  "largo_frogstomp": false,
  "largo_song_double_time": false,
  "largo_song_fight_song": false,
  "largo_song_good_vibrations": false,
  "legion_commander_duel": true,
  "leshrac_pulse_nova": true,
  "lich_chain_frost": true,
  "life_stealer_consume": true,
  "life_stealer_infest": true,
  "lina_laguna_blade": true,
  "lion_finger_of_death": true,
  "lone_druid_true_form": true,
  "lone_druid_true_form_druid": true,
  "luna_eclipse": true,
  "lycan_shapeshift": true,
  "magnataur_reverse_polarity": true,
  "marci_unleash": true,
  "mars_arena_of_blood": true,
  "medusa_stone_gaze": true,
  "meepo_divided_we_stand": true,
  "mirana_invis": true,
  "mirana_solar_flare": true,
  "monkey_king_wukongs_command": true,
  "morphling_morph_replicate": true,
  "morphling_replicate": true,
  "muerta_grave_tracker": false,
  "muerta_gunslinger": false,
  "muerta_pierce_the_veil": true,
  "naga_siren_song_of_the_siren": true,
  "naga_siren_song_of_the_siren_cancel": true,
  "necrolyte_reapers_scythe": true,
  "nevermore_requiem": true,
  "night_stalker_darkness": true,
  "nyx_assassin_vendetta": true,
  "obsidian_destroyer_sanity_eclipse": true,
  "ogre_magi_multicast": true,
  "ogre_magi_school": false,
  "omniknight_guardian_angel": true,
  "omniknight_pacify": false,
  "oracle_false_promise": true,
  "pangolier_gyroshell": true,
  "pangolier_gyroshell_stop": true,
  "phantom_assassin_coup_de_grace": true,
  "phantom_lancer_juxtapose": true,
  "phoenix_launch_fire_spirit": false,
  "phoenix_supernova": true,
  "primal_beast_pulverize": true,
  "primal_beast_rock_throw": false,
  "puck_dream_coil": true,
  "pudge_dismember": true,
  "pugna_life_drain": true,
  "queenofpain_sonic_wave": true,
  "rattletrap_hookshot": true,
  "razor_eye_of_the_storm": true,
  "riki_backstab": true,
  "riki_permanent_invisibility": true,
  "ringmaster_wheel": true,
  "rubick_spell_steal": true,
  "sandking_epicenter": true,
  "shadow_demon_demonic_purge": true,
  "shadow_shaman_mass_serpent_ward": true,
  "shredder_chakram": true,
  "shredder_return_chakram": true,
  "silencer_curse_of_the_silent": false,
  "silencer_global_silence": true,
  "skeleton_king_reincarnation": true,
  "skywrath_mage_mystic_flare": true,
  "slardar_amplify_damage": true,
  "slark_shadow_dance": true,
  "snapfire_mortimer_kisses": true,
  "sniper_assassinate": true,
  "special_bonus_unique_abaddon": false,
  "special_bonus_unique_abaddon_2": false,
  "special_bonus_unique_abaddon_3": false,
  "special_bonus_unique_abaddon_4": false,
  "special_bonus_unique_abaddon_5": false,
  "special_bonus_unique_abaddon_6": false,
  "special_bonus_unique_abaddon_7": false,
  "special_bonus_unique_abaddon_immolation": false,
  "special_bonus_unique_ancient_apparition_1": false,
  "special_bonus_unique_ancient_apparition_2": false,
  "special_bonus_unique_ancient_apparition_3": false,
  "special_bonus_unique_ancient_apparition_5": false,
  "special_bonus_unique_ancient_apparition_6": false,
  "special_bonus_unique_ancient_apparition_7": false,
  "special_bonus_unique_ancient_apparition_8": false,
  "special_bonus_unique_ancient_apparition_ice_vortex_duration": false,
  "special_bonus_unique_arc_warden": false,
  "special_bonus_unique_arc_warden_3": false,
  "special_bonus_unique_arc_warden_4": false,
  "special_bonus_unique_arc_warden_5": false,
  "special_bonus_unique_arc_warden_7": false,
  "special_bonus_unique_arc_warden_8": false,
  "special_bonus_unique_arc_warden_9": false,
  "special_bonus_unique_arc_warden_flux_silences": false,
  "special_bonus_unique_batrider_1": false,
  "special_bonus_unique_batrider_2": false,
  "special_bonus_unique_batrider_3": false,
  "special_bonus_unique_batrider_4": false,
  "special_bonus_unique_batrider_5": false,
  "special_bonus_unique_batrider_6": false,
  "special_bonus_unique_batrider_7": false,
  "special_bonus_unique_batrider_smoldering_resin_ticks": false,
  "special_bonus_unique_beastmaster_5": false,
  "special_bonus_unique_beastmaster_6": false,
  "special_bonus_unique_dawnbreaker_break_of_dawn_damage": false,
  "special_bonus_unique_dawnbreaker_gleaming_hammer": false,
  "special_bonus_unique_dazzle_1": false,
  "special_bonus_unique_dazzle_2": false,
  "special_bonus_unique_dazzle_3": false,
  "special_bonus_unique_dazzle_4": false,
  "special_bonus_unique_dazzle_5": false,
  "special_bonus_unique_dazzle_poison_touch_attack_range_bonus": false,
  "special_bonus_unique_dazzle_shallow_grave_cooldown": false,
  "special_bonus_unique_disruptor": false,
  "special_bonus_unique_disruptor_2": false,
  "special_bonus_unique_disruptor_4": false,
  "special_bonus_unique_disruptor_5": false,
  "special_bonus_unique_disruptor_7": false,
  "special_bonus_unique_disruptor_8": false,
  "special_bonus_unique_disruptor_9": false,
  "special_bonus_unique_disruptor_consecutive_strike_damage": false,
  "special_bonus_unique_disruptor_fence_charge": false,
  "special_bonus_unique_drow_ranger_1": false,
  "special_bonus_unique_drow_ranger_2": false,
  "special_bonus_unique_drow_ranger_3": false,
  "special_bonus_unique_drow_ranger_6": false,
  "special_bonus_unique_drow_ranger_7": false,
  "special_bonus_unique_drow_ranger_8": false,
  "special_bonus_unique_drow_ranger_gust_selfmovespeed": false,
  "special_bonus_unique_earth_spirit": false,
  "special_bonus_unique_earth_spirit_2": false,
  "special_bonus_unique_earth_spirit_3": false,
  "special_bonus_unique_earth_spirit_4": false,
  "special_bonus_unique_earth_spirit_5": false,
  "special_bonus_unique_earth_spirit_6": false,
  "special_bonus_unique_earth_spirit_7": false,
  "special_bonus_unique_earth_spirit_8": false,
  "special_bonus_unique_earthshaker": false,
  "special_bonus_unique_earthshaker_2": false,
  "special_bonus_unique_earthshaker_3": false,
  "special_bonus_unique_earthshaker_4": false,
  "special_bonus_unique_earthshaker_6": false,
  "special_bonus_unique_earthshaker_echo_cd": false,
  "special_bonus_unique_earthshaker_totem_damage": false,
  "special_bonus_unique_ember_spirit_1": false,
  "special_bonus_unique_ember_spirit_2": false,
  "special_bonus_unique_ember_spirit_3": false,
  "special_bonus_unique_ember_spirit_4": false,
  "special_bonus_unique_ember_spirit_5": false,
  "special_bonus_unique_ember_spirit_6": false,
  "special_bonus_unique_ember_spirit_chains_dps": false,
  "special_bonus_unique_enigma": false,
  "special_bonus_unique_enigma_2": false,
  "special_bonus_unique_enigma_3": false,
  "special_bonus_unique_enigma_4": false,
  "special_bonus_unique_enigma_5": false,
  "special_bonus_unique_enigma_6": false,
  "special_bonus_unique_enigma_9": false,
  "special_bonus_unique_faceless_void_4": false,
  "special_bonus_unique_furion": false,
  "special_bonus_unique_furion_2": false,
  "special_bonus_unique_furion_3": false,
  "special_bonus_unique_furion_4": false,
  "special_bonus_unique_furion_5": false,
  "special_bonus_unique_furion_6": false,
  "special_bonus_unique_furion_7": false,
  "special_bonus_unique_furion_8": false,
  "special_bonus_unique_furion_teleportation_barrier": false,
  "special_bonus_unique_juggernaut_2": false,
  "special_bonus_unique_juggernaut_3": false,
  "special_bonus_unique_juggernaut_4": false,
  "special_bonus_unique_juggernaut_5": false,
  "special_bonus_unique_juggernaut_blade_dance_lifesteal": false,
  "special_bonus_unique_juggernaut_blade_fury_cooldown": false,
  "special_bonus_unique_juggernaut_blade_fury_movespeed": false,
  "special_bonus_unique_juggernaut_healing_ward_heal": false,
  "special_bonus_unique_juggernaut_omnislash_duration": false,
  "special_bonus_unique_lina_1": false,
  "special_bonus_unique_lina_2": false,
  "special_bonus_unique_lina_3": false,
  "special_bonus_unique_lina_4": false,
  "special_bonus_unique_lina_6": false,
  "special_bonus_unique_lina_7": false,
  "special_bonus_unique_lina_crit_debuff": false,
  "special_bonus_unique_lina_dragon_slave_crits": false,
  "special_bonus_unique_lone_druid_11": false,
  "special_bonus_unique_lone_druid_2": false,
  "special_bonus_unique_lone_druid_4": false,
  "special_bonus_unique_lone_druid_8": false,
  "special_bonus_unique_lone_druid_entangle_cd": false,
  "special_bonus_unique_lone_druid_entangle_hits": false,
  "special_bonus_unique_lone_druid_savage_roar_aoe": false,
  "special_bonus_unique_lone_druid_spirit_bear_damage_against_entangled": false,
  "special_bonus_unique_lone_druid_spirit_bear_demolish": false,
  "special_bonus_unique_lone_druid_spirit_bear_return_cd": false,
  "special_bonus_unique_lone_druid_spirit_bear_return_channel": false,
  "special_bonus_unique_marci_dispose_slow": false,
  "special_bonus_unique_marci_grapple_damage": false,
  "special_bonus_unique_marci_grapple_stun_duration": false,
  "special_bonus_unique_marci_guardian_damage": false,
  "special_bonus_unique_marci_guardian_lifesteal": false,
  "special_bonus_unique_marci_lunge_movespeed": false,
  "special_bonus_unique_marci_lunge_range": false,
  "special_bonus_unique_marci_rebound_radius": false,
  "special_bonus_unique_marci_unleash_extend_duration": false,
  "special_bonus_unique_marci_unleash_speed": false,
  "special_bonus_unique_mirana_1": false,
  "special_bonus_unique_mirana_2": false,
  "special_bonus_unique_mirana_3": false,
  "special_bonus_unique_mirana_4": false,
  "special_bonus_unique_mirana_5": false,
  "special_bonus_unique_mirana_6": false,
  "special_bonus_unique_mirana_7": false,
  "special_bonus_unique_mirana_arrow_damage": false,
  "special_bonus_unique_omniknight_1": false,
  "special_bonus_unique_omniknight_2": false,
  "special_bonus_unique_omniknight_3": false,
  "special_bonus_unique_omniknight_4": false,
  "special_bonus_unique_omniknight_5": false,
  "special_bonus_unique_omniknight_6": false,
  "special_bonus_unique_omniknight_7": false,
  "special_bonus_unique_omniknight_guardian_angel_duration": false,
  "special_bonus_unique_pangolier": false,
  "special_bonus_unique_pangolier_3": false,
  "special_bonus_unique_pangolier_4": false,
  "special_bonus_unique_pangolier_5": false,
  "special_bonus_unique_pangolier_6": false,
  "special_bonus_unique_pangolier_luckyshot_armor": false,
  "special_bonus_unique_pangolier_shield_crash_cooldown": false,
  "special_bonus_unique_pangolier_shield_crash_herostacks": false,
  "special_bonus_unique_phoenix_1": false,
  "special_bonus_unique_phoenix_2": false,
  "special_bonus_unique_phoenix_3": false,
  "special_bonus_unique_phoenix_4": false,
  "special_bonus_unique_phoenix_5": false,
  "special_bonus_unique_phoenix_6": false,
  "special_bonus_unique_phoenix_blinding_sun_misschance": false,
  "special_bonus_unique_phoenix_dive_damage": false,
  "special_bonus_unique_phoenix_dying_light_damage": false,
  "special_bonus_unique_primal_beast_onslaught_damage": false,
  "special_bonus_unique_primal_beast_pulverize_duration": false,
  "special_bonus_unique_primal_beast_roar_dispells": false,
  "special_bonus_unique_primal_beast_trample_attack_damage": false,
  "special_bonus_unique_primal_beast_trample_cooldown": false,
  "special_bonus_unique_primal_beast_trample_magic_resist": false,
  "special_bonus_unique_primal_beast_trample_unslowable": false,
  "special_bonus_unique_primal_beast_uproar_armor": false,
  "special_bonus_unique_ringmaster_box_cast_range": false,
  "special_bonus_unique_ringmaster_dagger_bleed_and_slow_duration": false,
  "special_bonus_unique_ringmaster_dagger_impact_damage": false,
  "special_bonus_unique_ringmaster_dagger_penetrates": false,
  "special_bonus_unique_ringmaster_the_box_strong_dispel_and_flying": false,
  "special_bonus_unique_ringmaster_wheel_radius": false,
  "special_bonus_unique_ringmaster_whip_damage": false,
  "special_bonus_unique_ringmaster_whip_debuff_immunity": false,
  "special_bonus_unique_ringmaster_whip_radius": false,
  "special_bonus_unique_undying_3": false,
  "special_bonus_unique_winter_wyvern_1": false,
  "special_bonus_unique_winter_wyvern_2": false,
  "special_bonus_unique_winter_wyvern_3": false,
  "special_bonus_unique_winter_wyvern_4": false,
  "special_bonus_unique_winter_wyvern_5": false,
  "special_bonus_unique_winter_wyvern_6": false,
  "special_bonus_unique_winter_wyvern_7": false,
  "spectre_haunt": true,
  "spectre_reality": false,
  "spirit_breaker_nether_strike": true,
  "storm_spirit_ball_lightning": true,
  "sven_gods_strength": true,
  "techies_land_mines": true,
  "techies_remote_mines": true,
  "templar_assassin_psionic_trap": true,
  "terrorblade_sunder": true,
  "tidehunter_ravage": true,
  "tinker_rearm": true,
  "tiny_grow": true,
  "treant_overgrowth": true,
  "troll_warlord_battle_trance": true,
  "tusk_walrus_punch": true,
  "undying_flesh_golem": true,
  "ursa_enrage": true,
  "vengefulspirit_nether_swap": true,
  "venomancer_noxious_plague": true,
  "venomancer_poison_nova": true,
  "venomancer_poison_sting": false,
  "viper_viper_strike": true,
  "visage_summon_familiars": true,
  "void_spirit_astral_step": true,
  "warlock_golem_flaming_fists": false,
  "warlock_golem_permanent_immolation": false,
  "warlock_imp_explode": false,
  "warlock_imp_explode_major": false,
  "warlock_rain_of_chaos": true,
  "weaver_time_lapse": true,
  "windrunner_focusfire": true,
  "winter_wyvern_accelerated_learning": false,
  "winter_wyvern_winters_curse": true,
  "wisp_relocate": true,
  "witch_doctor_death_ward": true,
  "zuus_thundergods_wrath": true
};
