import assert from "node:assert/strict";
import type { ApmStore } from "./apm-store.js";
import type { PlayerProfile,ProfileMatch } from "./player-profile.js";
import type { ParsedMatch } from "./replay.js";
import { buildPlayerProgress } from "./player-progress.js";
import { renderProgress } from "./web/player-progress-render.js";
const account=94014640,steam=String(BigInt(account)+76561197960265728n);
let reads=0;
const raw=new Map<number,ParsedMatch>();
const matches:ProfileMatch[]=Array.from({length:8},(_,i)=>({id:100+i,start:10000-i*100,duration:1200,hero:"Zeus",win:i===2?null:i!==4,kda:[10,2,20],kdaSource:i===0?"сохранённая сводка":"OpenDota",teammates:[]}));
for(const [i,m] of matches.entries())raw.set(m.id,{match_id:m.id,duration_min:20,game_mode:i===7?"mode_22":"mode_23",players:[{steam_id:steam,hero:"zuus",item_timings:[{item:"arcane_boots",min:i===0?4:5+i/10},{item:"arcane_boots",min:15}]}]} as unknown as ParsedMatch);
const store={economyHistory:()=>{reads++;return [...raw.values()].map(m=>({matchId:m.match_id,start:10000,hero:m.players[0].hero,mode:m.game_mode,duration:m.duration_min,items:JSON.stringify(m.players[0].item_timings),networth10:null,networth20:null}));},replay:()=>{throw new Error("Full replay JSON must not be loaded for benchmarks");}} as unknown as ApmStore;
const profile={account,period:"all",matches,measured:matches} as PlayerProfile;
const result=buildPlayerProgress(store,profile,1000);
assert.equal(result.totals.kills,70,"feed KDA excluded from official milestones");
assert.equal(result.totals.assists,140);assert.equal(result.totals.wins,6);
assert.equal(result.streaks.currentWins,2,"unknown outcome breaks streak");
assert.equal(result.streaks.bestWins,3);
assert.equal(result.benchmarks.length,1);
const b=result.benchmarks[0];assert.equal(b.sample,6,"latest game and different mode excluded");
assert.equal(b.medianSeconds,321,"median uses first purchase in each other game");
assert.equal(b.latestSeconds,240);assert.equal(b.differenceSeconds,-81);
assert.equal(reads,1);
buildPlayerProgress(store,profile,2000);assert.equal(reads,1,"cached profile does not reread history projection");
buildPlayerProgress(store,profile,62000);assert.equal(reads,2,"cache expires after one minute");
const html=renderProgress(result);assert.ok(html.includes("1:21 раньше"));assert.ok(html.includes("6 других игр"));
assert.ok(html.includes("period=all&amp;economy=100#economy"));
const sparse=buildPlayerProgress(store,{...profile,period:"7",matches:matches.slice(0,5),measured:matches.slice(0,5)},63000);
assert.equal(reads,2,"switching period reuses the account projection within the minute");
assert.equal(sparse.benchmarks.length,0,"four other games do not meet minimum of five");
const missing=buildPlayerProgress(store,{...profile,period:"30",matches:[{...matches[0],win:null,kda:undefined,start:null}],measured:[]},63000);
assert.equal(missing.totals.kills,0);assert.equal(missing.streaks.currentWins,0);assert.equal(missing.benchmarkCoverage.considered,0);
const dangerous=renderProgress({...result,benchmarks:[{...b,hero:'<script>alert(1)</script>',itemLabel:'<img onerror=evil>'}]});
assert.ok(!dangerous.includes('<script>'));assert.ok(dangerous.includes('&lt;script&gt;'));
console.log("Player progress tests passed");
