import { assertReplayIdentity } from "./replay-identity.js";
import { profileInsights, conservativeWinRate } from "./profile-insights.js";
import Database from "better-sqlite3";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { ApmStore, APM_VERSION } from "./apm-store.js";
import { buildProfile, importFeed, type ProfileMatch } from "./player-profile.js";
import { groupActions, validActionCounts } from "./action-counts.js";
import { renderPlayer, renderPlayers } from "./web/player-render.js";
import { PLAYERS } from "./config.js";
import type { ParsedMatch } from "./replay.js";
const dir=mkdtempSync(path.join(os.tmpdir(),"profiles-test-")),file=path.join(dir,"stats.sqlite");
let store=new ApmStore(file);
const id=94014640,partner=1869377945,enemy=126449680;
const now=Date.UTC(2026,8,13,12),start=now/1000-3600;
const steam=(n:number)=>String(BigInt(n)+76561197960265728n);
const match={match_id:123,start_time:start,duration_min:2,winner:"radiant",apm_version:APM_VERSION,apm_duration_seconds:120,
 players:[{steam_id:steam(id),team:"radiant",hero:"npc_dota_hero_crystal_maiden",actions:200,actions_per_min:100,kills:999,deaths:0,assists:999,
 action_counts:{DOTA_UNIT_ORDER_MOVE_TO_POSITION:180,DOTA_UNIT_ORDER_CAST_NO_TARGET:19,UNKNOWN_NEW_COMMAND:1}},
 {steam_id:steam(partner),team:"radiant",hero:"invoker"},{steam_id:steam(enemy),team:"dire",hero:"pudge"}]} as unknown as ParsedMatch;
try {
  store.save(match);store.save(match);
  assert.equal(store.history(id).length,1);
  assert.equal(store.history(id)[0].action_counts?.DOTA_UNIT_ORDER_MOVE_TO_POSITION,180);
  store.save({...match,players:match.players.map(p=>({...p,action_counts:undefined}))});
  assert.equal(store.history(id)[0].action_counts?.DOTA_UNIT_ORDER_MOVE_TO_POSITION,180,"old caches must preserve detailed commands");
  assert.equal(store.replay(123)?.players[0].action_counts?.DOTA_UNIT_ORDER_MOVE_TO_POSITION,180);
  store.save({...match,players:match.players.map(p=>({...p,action_counts:{broken:10000}}))});
  assert.equal(store.history(id)[0].action_counts?.DOTA_UNIT_ORDER_MOVE_TO_POSITION,180,"invalid sums must not overwrite valid details");
  store.save({...match,match_id:124,start_time:start-86400*8,players:match.players.map(p=>({...p,actions:0,actions_per_min:0,action_counts:{}}))});
  store.save({...match,match_id:125,start_time:undefined,players:match.players.map(p=>({...p,action_counts:undefined}))});
  store.save({...match,match_id:126,start_time:start-86400,apm_version:undefined,players:match.players.map(p=>({...p,actions:undefined,actions_per_min:undefined,action_counts:undefined}))});
  store.close();
  // Simulate upgrading a pre-profile database: projection must rebuild from old full JSON.
  const legacy=new Database(file);legacy.exec("DROP TABLE profile_rosters");legacy.close();
  store=new ApmStore(file);
  assert.equal(store.profileRosters().length,4,"existing archived games migrate without reparsing");
  assert.ok(!JSON.stringify(store.profileRosters()).includes("action_counts"),"profile reads stay compact");
  assert.equal(store.history(id).length,3,"history survives reopening");
  let p=buildProfile(store,id,"all",now);
  assert.equal(p.matches.length,4);assert.equal(p.measured.length,3);assert.equal(p.detailed.length,2);
  assert.equal(p.avgApm,67,"average includes measured zero, excludes unavailable");
  assert.equal(p.median,100);assert.equal(p.groups.reduce((s,g)=>s+g.count,0),200);
  assert.equal(p.groups.at(-1)!.count,1,"unknown commands stay counted");
  assert.deepEqual(p.partners.map(p=>p.id),[partner],"opponents in our tracked list are not teammates");
  assert.deepEqual(p.matches[0].enemyHeroes,["Pudge"]);
  assert.deepEqual(p.matches[0].allyHeroes,["Invoker"],"own hero cannot become ally matchup");
  const insight=profileInsights(p.matches);
  assert.equal(insight.enemies[0].games,4);
  assert.equal(insight.comparisonReady,false);
  assert.ok(conservativeWinRate(70,100)>conservativeWinRate(2,2),"two wins must not outrank established success");
  const twenty:ProfileMatch[]=Array.from({length:20},(_,i)=>({...p.matches[0],id:1000+i,start:start-i*100,win:i<10,kda:[2,1,3] as [number,number,number],enemyHeroes:["Pudge","Pudge"]}));
  const trend=profileInsights([...twenty].reverse());
  assert.equal(trend.comparisonReady,true);assert.equal(trend.recent.winRate,1);assert.equal(trend.previous.winRate,0);
  assert.equal(trend.recent.kda,5);assert.equal(trend.enemies[0].games,20,"hero counted at most once per match");
  twenty[0].win=null;
  assert.equal(profileInsights(twenty).recent.known,9,"missing outcome is not a loss");
  const partial=twenty.map((m,i)=>({...m,win:i<10?null:m.win,kda:i<10?undefined:m.kda,apm:i<10?undefined:m.apm}));
  const partialTrend=profileInsights(partial);
  assert.equal(partialTrend.comparisonReady,true,"date coverage does not imply metric coverage");
  assert.equal(partialTrend.recent.winRate,null,"unknown outcomes must not turn into zero percent");
  assert.equal(partialTrend.recent.kda,null);assert.equal(partialTrend.recent.apm,null);
  assert.equal(partialTrend.previous.kdaGames,10);assert.equal(partialTrend.previous.apmGames,10);
  const noDeaths=profileInsights([{...twenty[0],kda:[2,0,3]},{...twenty[1],kda:[1,0,4]}]);
  assert.equal(noDeaths.recent.kda,10,"pooled KDA divides total kills + assists by max(1, total deaths)");
  const invalidDates=[0,NaN,Infinity].map((date,i)=>({...twenty[0],id:2000+i,start:date}));
  assert.equal(profileInsights([...twenty.slice(0,19),...invalidDates]).comparisonReady,false,"invalid dates cannot complete a recent-ten comparison");
  assert.equal(conservativeWinRate(0,0),0);assert.equal(conservativeWinRate(0,10),0);
  assert.ok(Math.abs(conservativeWinRate(50,100)-0.40383)<0.0001,"Wilson lower bound reference value");
  for(const [wins,total] of [[-1,10],[11,10],[1,NaN],[1,0],[0.5,1]]) assert.equal(conservativeWinRate(wins,total),0,"invalid counts cannot create a ranking");
  const unknownRoster={match_id:500,start_time:0,duration_min:2,winner:"unknown",players:[
    {steam_id:steam(id),team:"unknown",hero:"crystal_maiden"},
    {steam_id:steam(partner),team:"unknown",hero:"invoker"},
    {steam_id:steam(enemy),team:"dire",hero:"pudge"}]};
  const uncertain=buildProfile(store,id,"all",now,[unknownRoster]);
  const uncertainMatch=uncertain.matches.find(m=>m.id===500)!;
  assert.equal(uncertainMatch.win,null,"unknown winner cannot become a loss");
  assert.equal(uncertainMatch.start,null,"zero timestamp is unavailable, not January 1970");
  assert.deepEqual(uncertainMatch.teammates,[],"unknown sides cannot imply a partnership");
  assert.equal(uncertainMatch.allyHeroes,undefined);assert.equal(uncertainMatch.enemyHeroes,undefined);
  assert.equal(uncertain.teammateCoverage,0,"unclassified roster is not side coverage");
  const validSideUnknownWinner=buildProfile(store,id,"all",now,[{...unknownRoster,players:unknownRoster.players.map((p,i)=>({...p,team:i<2?"radiant":"unknown"}))}]);
  const incomplete=validSideUnknownWinner.matches.find(m=>m.id===500)!;
  assert.equal(incomplete.win,null);assert.deepEqual(incomplete.allyHeroes,["Invoker"]);
  assert.deepEqual(incomplete.enemyHeroes,[],"unclassified players are not opponents");
  assert.equal(p.matches.filter(m=>m.kda).length,0,"raw combat log kills must not become official KDA");
  assert.equal(buildProfile(store,id,"7",now).matches.length,2,"old/undated matches excluded from rolling periods");
  const official={match_id:123,start_time:start,duration:120,hero_id:5,kills:1,deaths:4,assists:20,player_slot:0,radiant_win:true};
  store.saveResults(id,[official]);
  importFeed(store,[{matchId:123,startTime:start,duration:120,win:false,ours:[{steamId:id,name:"ignored",hero:"Crystal Maiden",heroId:5,kills:999,deaths:0,assists:1,win:false}]}]);
  p=buildProfile(store,id,"all",now);
  assert.deepEqual(p.matches.find(m=>m.id===123)?.kda,[1,4,20],"feed must not downgrade official result");
  assert.equal(p.matches.find(m=>m.id===123)?.win,true);
  assert.equal(p.matches.find(m=>m.id===123)?.kdaSource,"OpenDota");
  const one=renderPlayer(p,[p],1,123);
  assert.ok(one.includes('value="123" selected'),"per-match selection is retained");
  assert.ok(one.includes("100 APM"));
  assert.ok(!renderPlayer(p,[p],1,999999).includes('value="999999"'),"unknown selected match cannot add data");
  const html=renderPlayer(p,[p]);
  assert.ok(html.includes("APM под микроскопом")&&html.includes("UNKNOWN_NEW_COMMAND"));
  for(const player of PLAYERS) {
    assert.ok(!html.includes(String(player.telegramId??"PRIVATE_ID_SENTINEL")),"no private Telegram IDs");
    if(player.birthday) assert.ok(!html.includes(player.birthday));
    if(player.botAttitude) assert.ok(!html.includes(player.botAttitude));
  }
  const absent=buildProfile(store,93921511,"7",now);
  assert.ok(renderPlayer(absent,[absent]).includes("В этом периоде нет сохранённых игр"));
  assert.ok(!renderPlayer(absent,[absent]).includes("NaN"));
  assert.ok(renderPlayers([absent],"7").includes("История ещё собирается"));
  p.matches[0].hero='<script>alert("x")</script>';
  assert.ok(!renderPlayer(p,[p]).includes('<script>alert("x")</script>'),"escape untrusted names");
  assert.equal(validActionCounts({a:1,b:-1},0),false);
  assert.equal(validActionCounts({a:1.5},1.5),false);
  assert.equal(validActionCounts({},0),true);
  assert.equal(validActionCounts(null,0),false);
  assert.equal(groupActions({DOTA_UNIT_ORDER_MOVE_TO_DIRECTION:5,DOTA_UNIT_ORDER_HOLD_POSITION:3}).map(g=>g.count).join(","),"5,0,0,0,3");
  const mergeStore=new ApmStore(":memory:");
  const single={...match,players:[match.players[0]]};
  mergeStore.save({...single,players:[{...single.players[0],kills:7,action_counts:undefined}]});
  mergeStore.mergeReplayActions({...single,players:[{...single.players[0],kills:1}]});
  assert.equal(mergeStore.replay(123)?.players[0].kills,7,"offline backfill preserves latest official enrichment");
  assert.equal(mergeStore.history(id)[0].action_counts?.DOTA_UNIT_ORDER_MOVE_TO_POSITION,180);
  assert.throws(()=>mergeStore.mergeReplayActions({...single,players:[{...single.players[0],actions:300,actions_per_min:150,action_counts:{x:300}}]}),/APM changed/);
  assert.equal(mergeStore.history(id)[0].actions,200,"rejected backfill cannot partially mutate totals");
  mergeStore.close();
  const anonymousHeader={...single,match_id:0,players:[{...single.players[0]}]};
  const evidence={match_id:123,players:[{account_id:id,hero_id:5,player_slot:0}]} as any;
  assertReplayIdentity(anonymousHeader,123,evidence);assert.equal(anonymousHeader.match_id,123);
  assert.throws(()=>assertReplayIdentity({...anonymousHeader,match_id:999},123,evidence),/mismatch/);
  assert.throws(()=>assertReplayIdentity({...anonymousHeader,match_id:0},123,{...evidence,players:[{...evidence.players[0],account_id:999}]}),/account mismatch/);
  assert.throws(()=>assertReplayIdentity({...anonymousHeader,match_id:0},123),/no independent roster evidence/);
  console.log("Player profile tests passed: persistence, sources, coverage, periods, teams, rendering, privacy.");
} finally {store.close();rmSync(dir,{recursive:true,force:true});}
