import assert from 'node:assert/strict';
import {currentMatchText} from './current-match-message.js';
import {replyCurrentMatch} from './current-match-command.js';
import type {LiveMatch} from './live-match.js';
const match:LiveMatch={matchId:'123456',kind:'stack',stackCount:2,time:1234,delay:120,updatedAt:Date.now(),detailed:true,buildings:[],history:[],teams:[{name:'Radiant',score:15,netWorth:25000,players:[{account:1,slot:0,name:'<b>Foo</b>\nother',hero:'Axe',level:16,kills:4,deaths:2,assists:8,netWorth:12000,ours:true,items:[]}]},{name:'Dire',score:12,netWorth:22000,players:[]}]};
const text=currentMatchText(match);
assert.ok(text.includes('Radiant 15 : 12 Dire'));assert.ok(text.includes('20:34'));assert.ok(text.includes('Radiant +3.0k'));assert.ok(text.includes('★ <b>Foo</b> other'));assert.ok(text.includes('4/2/8'));assert.ok(text.includes('задержка 2:00'));
assert.ok(currentMatchText({...match,kind:'public'}).includes('Публичный матч'));
assert.ok(currentMatchText(null).includes('нет доступного матча'));
assert.ok(currentMatchText({...match,updatedAt:Date.now()-100000}).includes('нет доступного матча'));
const edits:any[]=[],replies:any[]=[];
const ctx={message:{message_id:7},chat:{id:9},reply:async(...args:any[])=>{replies.push(args);return {message_id:8};},api:{editMessageText:async(...args:any[])=>{edits.push(args);}}};
await replyCurrentMatch(ctx as any,async()=>match);
assert.equal(replies[0][1].reply_parameters.message_id,7);assert.deepEqual(edits[0].slice(0,2),[9,8]);assert.equal(edits[0][3].parse_mode,undefined);assert.ok(edits[0][3].reply_markup.inline_keyboard[0][0].url.endsWith('/#home-live'));
await replyCurrentMatch(ctx as any,async()=>null);assert.equal(edits[1][3].reply_markup,undefined);
await replyCurrentMatch(ctx as any,async()=>{throw new Error('private-token');});assert.ok(!edits[2][2].includes('private-token'));
const full={...match,teams:match.teams.map((t,i)=>({...t,players:Array.from({length:5},(_,n)=>({...match.teams[0].players[0],slot:i*5+n,name:'я'.repeat(500),hero:'a'.repeat(500)}))}))};assert.ok(currentMatchText(full).length<4096);
console.log('Current match: stats, public fallback, stale/empty/error, plain-text safety, reply/button, Telegram length passed.');
const {setupCommands}=await import('./bot.js');
const commands=new Map<string,unknown>();let menu:Array<{command:string}>=[];
setupCommands({command:(name:string,handler:unknown)=>commands.set(name,handler),api:{setMyCommands:async(value:any)=>{menu=value;}}} as any,async()=>'',()=>{});
assert.ok(commands.has('current_match'));assert.ok(menu.some(item=>item.command==='current_match'));
console.log('Command registration and Telegram menu passed.');
