import assert from "node:assert/strict";
import type { ParsedMatch } from "./replay.js";
import { buildMatchInsights, damageTypeLabel, goldReasonLabel } from "./match-insights.js";
const legacy={match_id:1,duration_min:2,players:[{steam_id:"1",hero:"warlock",team:"radiant",healing:22000,hero_damage:0,top_spells:{warlock_shadow_word:38},networth_by_minute:[1000,2000,3000],death_times_min:[1.5],buybacks:0,obs_wards_placed:12,sentry_wards_placed:21}],kills:[],buildings:[],roshan_kills_min:[],teamfights:[]} as unknown as ParsedMatch;
const l=buildMatchInsights(legacy);
assert.equal(l.players[0].healing.totalIncludingSelf,22000);
assert.equal(l.players[0].healing.allies,null,"legacy aggregate healing is not allied healing");
assert.equal(l.players[0].damage.byAbility,null,"cast counts are never damage");
assert.equal(l.coverage.damage.available,1,"valid measured zero remains available");
assert.equal(l.coverage.damageBreakdown.available,0);
assert.equal(l.players[0].vision.placements,null,"ward purchases are not placements");
assert.equal(l.players[0].vision.observerPurchases,12);
assert.deepEqual(l.players[0].economy.networth,[{minute:1,value:1000},{minute:2,value:2000}]);
assert.equal(l.players[0].economy.xp,null);
assert.deepEqual(l.players[0].deaths,[{seconds:90,x:null,y:null,killer:null,incoming:null}]);
assert.equal(l.players[0].control.stunSeconds,null);
const extended={...legacy,players:[{...legacy.players[0],combat_details:{version:"combat-log-v1",healing:{self:19000,other_heroes:2900,units:100,by_target:{npc_dota_hero_warlock:19000,npc_dota_hero_lina:2000,npc_dota_hero_pudge:900,npc_dota_creep:100}},damage:{by_ability:{warlock_fatal_bonds:500,attack:200},by_target:{pudge:700},by_type:{"1":700}},casts:[{min:.2,ability:"warlock_rain_of_chaos",ultimate:true},{min:.3,ability:"warlock_shadow_word"}],deaths:[{min:1.5,killer:"pudge",x:-100,y:0}],wards:[{min:1,kind:"observer",event:"purchase",x:10,y:20}],buybacks:[{min:1.7}],gold:[{min:1,value:-200,reason:1},{min:1.1,value:100}],xp_by_minute:[100,200],last_hits_by_minute:[0,1],denies_by_minute:[0,0],modifiers:[{min:1,target:"pudge",modifier:"stunned",stun:2},{min:1,target:"pudge",modifier:"stunned",stun:2}],coverage:{xp:true,ultimate_classification:false,healing_target_identity:true}}},{steam_id:"2",hero:"lina",team:"radiant"},{steam_id:"3",hero:"pudge",team:"dire"}]} as unknown as ParsedMatch;
const e=buildMatchInsights(extended),p=e.players[0];
assert.equal(p.healing.allies,2000,"allied healing includes only mapped same-team heroes, excludes self/enemies/units");
assert.equal(p.healing.self,19000);assert.equal(p.healing.otherHeroes,2900);
assert.equal(p.healing.byAbility,null,"target split cannot become ability split");
assert.equal(p.damage.byAbility![0].value,500);
assert.equal(p.deaths![0].x,-100);assert.equal(p.deaths![0].y,0,"zero coordinate is valid");
assert.equal(p.vision.placements,null,"purchase XY cannot become placement XY");
assert.equal(p.vision.events![0].event,"purchase");
assert.equal(p.ultimates!.length,1);
assert.equal(p.control.stunSeconds,null,"overlapping modifier observations are not summed as CC seconds");
assert.equal(p.control.observations!.length,2);
assert.equal(p.economy.gold,null,"gold delta events do not imply gold balance");
assert.equal(p.economy.goldEvents![0].value,-200);assert.equal(p.economy.goldEvents![1].reason,null);
assert.equal(p.economy.xp![0].minute,1);
assert.equal(p.buybacks.events![0].seconds,102);
assert.equal(e.coverage.healingBreakdown.available,1);
assert.equal(e.coverage.healingBreakdown.total,3);
const unknown=buildMatchInsights({...extended,players:[{...extended.players[0],combat_details:{version:"future-v99",healing:{self:1}}}]} as unknown as ParsedMatch);
assert.equal(unknown.players[0].healing.self,null,"unknown schema version cannot be silently interpreted");

const placementMatch=JSON.parse(JSON.stringify(extended));
placementMatch.players[0].combat_details.wards.push({min:.5,kind:"observer",event:"place",x:0,y:-1,coordinates_source:"ward_entity"});
const placed=buildMatchInsights(placementMatch).players[0];
assert.equal(placed.vision.events![0].event,"place","ward creation appends after parsing and must be sorted");
assert.equal(placed.vision.placements!.length,1);
assert.equal(placed.vision.placements![0].coordinatesSource,"ward_entity");
const v2=JSON.parse(JSON.stringify(extended));
v2.players[0].combat_details.version="combat-log-v2";
v2.players[0].combat_details.healing.by_ability={warlock_shadow_word:22000};
v2.players[0].combat_details.deaths[0].incoming={window_seconds:8,total:1300,by_attacker:{pudge:1000,npc_dota_creep:300},by_ability:{rot:1000,unknown_or_attack:300},complete:true};
const v2player=buildMatchInsights(v2).players[0];
assert.equal(v2player.healing.byAbility![0].value,22000);
assert.equal(v2player.deaths![0].incoming!.windowSeconds,8);
assert.equal(v2player.deaths![0].incoming!.total,1300);
assert.equal(v2player.deaths![0].incoming!.byAttacker.length,2,"creep damage retained, not silently attributed to an enemy hero");
const ambiguous=JSON.parse(JSON.stringify(extended));delete ambiguous.players[0].combat_details.coverage.healing_target_identity;
assert.equal(buildMatchInsights(ambiguous).players[0].healing.allies,null,"legacy unit heals can hide ally illusions under hero names");
ambiguous.players[0].combat_details.healing.units=0;
assert.equal(buildMatchInsights(ambiguous).players[0].healing.allies,2000,"no unit healing means no illusion collision");
console.log("Match insights tests passed");

assert.equal(damageTypeLabel("1"),"Физический");assert.equal(damageTypeLabel("2"),"Магический");assert.equal(damageTypeLabel("4"),"Чистый");
assert.equal(damageTypeLabel("0"),"Тип из реплея 0","zero is NONE, not the GC enum's physical type");
assert.equal(damageTypeLabel("unknown"),"Тип не записан");assert.equal(damageTypeLabel("999"),"Тип из реплея 999");
assert.equal(goldReasonLabel(1),"Смерть");assert.equal(goldReasonLabel(2),"Выкуп");assert.equal(goldReasonLabel(12),"Убийство героя");assert.equal(goldReasonLabel(17),"Руна богатства");assert.equal(goldReasonLabel(20),"Уничтожение варда");assert.equal(goldReasonLabel(null),"Причина не записана");assert.equal(goldReasonLabel(999),"Причина из реплея 999");
