import assert from "node:assert/strict";
import {buildMatchOverview} from "./match-overview.js";
import type {ParsedMatch} from "./replay.js";
const fixture=():ParsedMatch=>({match_id:77,duration_min:25.5,apm_duration_seconds:1530,winner:"radiant",radiant_score:0,dire_score:3,
 players:Array.from({length:10},(_,i)=>({steam_id:String(i+1),hero:`hero_${i}`,team:i<5?"radiant":"dire",networth_by_minute:Array.from({length:25},(_,j)=>(j+1)*(i<5?100:110)),networth_final:i<5?2000:2100,hero_damage:999999,tower_damage:0,damage_taken:0,buybacks:0,combat_details:{version:"combat-log-v2",coverage:{xp:true,ward_placements:true,healing_target_identity:true},damage:{by_ability:{spell:i<5?10:20},by_target:{},by_type:{}},healing:{self:0,other_heroes:0,units:0,by_target:{}},xp_by_minute:Array.from({length:25},(_,j)=>(j+1)*(i<5?50:40)),wards:[]}})),teamfights:[],buildings:[],roshan_kills_min:[],kills:[]} as unknown as ParsedMatch);
let m=fixture(),o=buildMatchOverview(m);
assert.equal(o.rosterComplete,true);assert.equal(o.networthAdvantage[0].minute,1);assert.equal(o.networthAdvantage[0].advantage,-50);assert.equal(o.xpAdvantage[0].advantage,50);
assert.equal(o.phases[0].networth?.advantage,-500);assert.equal(o.phases[1].networth?.advantage,-1000);assert.equal(o.phases[2].networth?.minute,25.5);assert.equal(o.phases[2].xp?.minute,25,"final XP retains its actual minute, not fake end timestamp");
assert.equal(o.teams[0].heroDamage.total,50,"mixed official hero_damage must not enter replay team totals");assert.equal(o.teams[0].heroDamage.players[0].share,.2);assert.equal(o.teams[0].towerDamage.total,0);assert.equal(o.teams[0].towerDamage.players[0].share,null,"zero total does not fabricate percentage");
assert.equal(o.score.radiant,0);assert.deepEqual(o.winnerMaxDeficit,{minute:25,amount:1250});assert.match(o.headline,/Radiant/);
assert.ok(o.swings.every((a,i)=>o.swings.every((b,j)=>i===j||a.toMinute<=b.fromMinute||a.fromMinute>=b.toMinute)),"windows do not overlap");
// One bad value removes that minute, not the entire series or its neighbours.
m.players[0].networth_by_minute[9]=NaN;o=buildMatchOverview(m);assert.equal(o.networthAdvantage.length,24);assert.equal(o.phases[0].networth,null);assert.ok(!o.swings.some(s=>s.fromMinute<=10&&s.toMinute>=10),"no swing may bridge a gap");
m=fixture();m.players[0].combat_details!.coverage.xp=false;o=buildMatchOverview(m);assert.equal(o.xpAdvantage.length,0);assert.equal(o.phases[2].xp,null);
m=fixture();m.players[0].combat_details!.damage.by_ability=undefined as any;o=buildMatchOverview(m);assert.equal(o.teams[0].heroDamage.total,null);assert.equal(o.teams[1].heroDamage.total,null,"both teams require the same full replay source");
for(const change of [(m:ParsedMatch)=>m.players.pop(),(m:ParsedMatch)=>m.players[0].team="dire",(m:ParsedMatch)=>m.players[0].hero=m.players[1].hero,(m:ParsedMatch)=>m.players[0].steam_id=m.players[1].steam_id]){m=fixture();change(m);o=buildMatchOverview(m);assert.equal(o.rosterComplete,false);assert.equal(o.networthAdvantage.length,0);assert.equal(o.teams[0].heroDamage.total,null)}
m=fixture();m.players.forEach(p=>{p.steam_id="0";p.networth_by_minute.fill(0);p.networth_final=0});o=buildMatchOverview(m);assert.equal(o.rosterComplete,true,"anonymous accounts are allowed when heroes and sides are unambiguous");assert.equal(o.networthAdvantage[0].advantage,0);assert.equal(o.swings.length,0);assert.equal(o.winnerMaxDeficit,null);
m=fixture();m.duration_min=3.01;m.apm_duration_seconds=179.99;o=buildMatchOverview(m);assert.equal(o.coverage.totalFullMinutes,2,"exact duration takes priority over rounded display minutes");assert.equal(o.phases[0].networth,null);assert.equal(o.phases[2].xp?.minute,2);
m=fixture();m.buildings=[{min:5,name:"npc_dota_goodguys_tower1_mid",killed_by_team:"dire"},{min:6,name:"npc_dota_badguys_tower4_top",killed_by_team:"dire"},{min:6,name:"npc_dota_badguys_tower4_top",killed_by_team:"dire"},{min:7,name:"npc_dota_badguys_fillers",killed_by_team:"dire"},{min:8,name:"npc_dota_underlord_portal",killed_by_team:"dire"},{min:99,name:"npc_dota_goodguys_fort",killed_by_team:"dire"}];
m.roshan_kills_min=[6,-1,99];m.teamfights=[{start_min:4,end_min:5,deaths:8,radiant_died:6,dire_died:2,winner:"dire",heroes_died:[]}];o=buildMatchOverview(m);
assert.equal(o.events.filter(e=>e.kind==="building").length,3,"exclude fillers and portals, retain two separate same-time towers");assert.equal(o.events.find(e=>e.kind==="building")?.lostTeam,"radiant");assert.ok(o.events.every(e=>e.team===null),"never infer a Roshan owner or trust building attacker side");assert.match(o.events[0].label,/смертей Radiant 6/);assert.equal(o.events.filter(e=>e.kind==="roshan").length,1);
const saved=JSON.stringify(m);assert.deepEqual(buildMatchOverview(m),buildMatchOverview(m));assert.equal(JSON.stringify(m),saved,"overview must not mutate the parsed match");
console.log("Match overview tests passed: full-roster sums, gaps, zeroes, exact minutes, source consistency, event provenance, swings, determinism.");

m=fixture();m.players[0].combat_details!.coverage.ward_placements=false;m.players[0].combat_details!.wards=[{min:1,kind:"observer",event:"place"}];o=buildMatchOverview(m);assert.equal(o.teams[0].wardsPlaced.total,null,"partial recorded placements cannot become a full team total");assert.equal(o.teams[0].wardsPlaced.known,4);assert.ok(o.story.length<=3);
