import assert from "node:assert/strict";
import { mkdtempSync, rmSync, readFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { ApmStore, APM_VERSION } from "./apm-store.js";
import { summarizeApm } from "./apm-stats.js";
import { withAnalysisApm } from "./analysis-apm.js";
import type { ParsedMatch } from "./replay.js";
import { formatStatsMessage } from "./formatter.js";
import { calculateStats } from "./stats.js";

const dir = mkdtempSync(path.join(os.tmpdir(), "pesiki-apm-"));
const filename = path.join(dir, "stats.sqlite");
let store = new ApmStore(filename);
const match = {
 match_id: 100, start_time: 1000, apm_version: APM_VERSION, apm_duration_seconds: 120,
 players: [{ steam_id: String(76561197960265728n + 1869377945n), name: "zladey", hero:"invoker", kills:1, deaths:2, assists:3, actions:371, actions_per_min:185 }],
} as ParsedMatch;
try {
 store.save(match); store.save(match);
 assert.equal(store.history(1869377945).length, 1, "retries must not duplicate history");
 assert.equal(store.replay(100)?.players[0].hero, "invoker", "full parsed replay is archived");
 store.close(); store = new ApmStore(filename);
 assert.equal(store.replay(100)?.players[0].kills, 1, "parsed data survives reopen");
 assert.equal(store.history(1869377945)[0].actions, 371, "survives reopen");
 store.save({...match, start_time:undefined});
 assert.equal(store.history(1869377945)[0].start_time, 1000, "unknown date must not erase known date");
 store.save({...match, apm_version:undefined});
 assert.equal(store.replay(100)?.apm_version, APM_VERSION, "legacy cache does not replace richer replay");
 store.save({...match, players:match.players.map(p => ({...p, actions_per_min:999}))});
 assert.equal(store.history(1869377945)[0].apm, 185, "legacy and malformed records do not overwrite history");
 store.save({...match, match_id:101, players:match.players.map(p => ({...p, actions:0, actions_per_min:0}))});
 assert.deepEqual(summarizeApm(store.history(1869377945), [{match_id:100},{match_id:101},{match_id:102}]), {avgApm:93,apmMatches:2});
 assert.deepEqual(summarizeApm(store.history(1869377945), [{match_id:102}]), {avgApm:undefined,apmMatches:0});
 assert.deepEqual(summarizeApm(store.history(1869377945), [{match_id:101}]), {avgApm:0,apmMatches:1});
 const old = "Рассказ.\n\n👤 НАШИ\nzladey · Invoker · 1/2/3 — нажимал кнопки";
 const updated = withAnalysisApm(old, match);
 assert.match(updated, /Invoker · 1\/2\/3 · APM 185 — нажимал кнопки/u);
 assert.equal(withAnalysisApm(updated, match), updated, "cached decoration is idempotent");
 const missing = {...match, players:match.players.map(p => ({...p, actions_per_min:undefined}))};
 const missingText = withAnalysisApm(old, missing);
 assert.equal(withAnalysisApm(missingText, missing), missingText, "unknown APM decoration is idempotent");
 store.hydrate(missing);
 assert.equal(missing.players[0].actions_per_min,185);
 // Optional real-replay regression output, generated by the Go parser.
 if (process.env.APM_TEST_REPLAY_JSON) {
  const real = JSON.parse(readFileSync(process.env.APM_TEST_REPLAY_JSON,"utf8")) as ParsedMatch;
  assert.equal(real.apm_version, APM_VERSION);
  assert.equal(real.players.reduce((sum,p)=>sum+p.actions!,0),38750);
  for (const [name,apm] of [["zladey",185],["Shootema",123],["Marinad",147]] as const) {
   assert.equal(real.players.find(p=>p.name===name)?.actions_per_min,apm);
  }
  store.save(real);
  assert.equal(store.history(1869377945).find(r=>r.match_id===8994933487)?.apm,185);
 }
 const stats = {...calculateStats(1869377945, "zladey", []), totalMatches:3, wins:2, losses:1, avgApm:185, apmMatches:2};
 const statsText = await formatStatsMessage([stats]);
 assert.match(statsText, /APM: 185 \(2\/3 матчей\)/u);
 const noApmText = await formatStatsMessage([{...stats, avgApm:undefined, apmMatches:0}]);
 assert.match(noApmText, /APM: нет разобранных реплеев/u);
 console.log("✓ APM: persistence, deduplication, periods, missing/zero values, analysis display, real replay (when supplied)");
} finally {store.close();rmSync(dir,{recursive:true,force:true});}
