import assert from 'node:assert/strict';
import {buildMatchCombatWindow} from './match-combat-window.js';
import type {ParsedMatch,CombatTimelineRow} from './replay.js';
const fixture=():ParsedMatch=>({match_id:1,duration_min:1,apm_duration_seconds:60,players:[{hero:'warlock',steam_id:'1',team:'radiant',hero_damage:999},{hero:'crystal_maiden',steam_id:'2',team:'radiant'},{hero:'axe',steam_id:'3',team:'dire'}],combat_timeline:{version:'combat-timeline-v1',bucket_seconds:1,heroes:['warlock','crystal_maiden','axe'],sources:['npc_dota_hero_warlock','npc_dota_warlock_golem','npc_dota_hero_axe','neutral_creep'],abilities:['hit','heal'],damage:[[10,0,0,2,0,1,0,100],[11,1,0,2,0,1,0,200],[12,0,0,2,0,1,1,300],[12,3,-1,0,0,-1,0,50],[13,2,2,0,0,1,0,75],[20,0,0,2,0,1,0,1000]],healing:[[10,0,0,0,1,-1,0,10],[11,0,0,1,1,-1,0,20],[12,0,0,2,1,-1,0,30]],coverage:{target_scope:'real-heroes',damage_events:6,healing_events:3,stored_damage_events:6,stored_healing_events:3,owner_known_damage_events:5,damage_rows:6,healing_rows:3,dropped_events:0,truncated:false,complete_until_second:null,row_limit:10000,byte_limit:1000000}}} as unknown as ParsedMatch);
let m=fixture();const before=JSON.stringify(m);let x=buildMatchCombatWindow(m,10.2,13.1);
assert.deepEqual(x.actualWindow,{startSecond:10,endSecondExclusive:14});assert.equal(x.coverage.state,'complete');assert.equal(x.totals!.damage,725);assert.equal(x.players[0].totals!.damage,600);assert.equal(x.players[0].totals!.controlledDamage,500);assert.equal(x.players[0].totals!.illusionDamage,300);assert.equal(x.players[2].totals!.incoming,600);assert.equal(x.players[0].totals!.incoming,125);assert.equal(x.unknownOwner.totals!.damage,50);assert.equal(x.coverage.ownerAttributionComplete,false);
assert.equal(x.players[0].totals!.healingSelf,10);assert.equal(x.players[0].totals!.healingAllies,20);assert.equal(x.players[0].totals!.healingEnemies,30);assert.equal(x.teams.radiant.totals!.damage,600);assert.equal(x.teams.dire.totals!.damage,75);assert.equal(x.players[0].damage.bySource.npc_dota_warlock_golem,200);assert.equal(x.players[0].damage.byTarget.axe,600);assert.equal(JSON.stringify(m),before,'legacy metrics remain untouched');
assert.equal(buildMatchCombatWindow(m,14,20).totals!.damage,0,'exclusive ending omits second20');assert.equal(buildMatchCombatWindow(m,-4,100).actualWindow!.endSecondExclusive,60);
m.combat_timeline!.coverage={...m.combat_timeline!.coverage,damage_events:7,dropped_events:1,truncated:true,complete_until_second:13};
assert.equal(buildMatchCombatWindow(m,10,13).coverage.state,'complete','end equal to exclusive prefix boundary is complete');x=buildMatchCombatWindow(m,10,14);assert.equal(x.coverage.state,'partial');assert.equal(x.totals,null);assert.equal(x.players[0].totals,null);assert.equal(x.teams.radiant.totals,null);assert.equal(x.unknownOwner.totals,null);assert.equal(x.recordedTotals.damage,725);
for(const mutate of [(m:ParsedMatch)=>m.combat_timeline!.heroes.reverse(),(m:ParsedMatch)=>m.combat_timeline!.damage[0][3]=99,(m:ParsedMatch)=>m.combat_timeline!.damage[0][7]=NaN,(m:ParsedMatch)=>m.combat_timeline!.damage[0][6]=2,(m:ParsedMatch)=>m.combat_timeline!.damage[0][0]=60,(m:ParsedMatch)=>m.combat_timeline!.damage[0][1]=-1,(m:ParsedMatch)=>m.combat_timeline!.coverage.damage_rows=999,(m:ParsedMatch)=>m.combat_timeline!.coverage.truncated=true,(m:ParsedMatch)=>(m.players[0] as any).team='unknown',(m:ParsedMatch)=>m.combat_timeline!.damage[1]=[...m.combat_timeline!.damage[0]]]){m=fixture();mutate(m);x=buildMatchCombatWindow(m,30,40);assert.equal(x.coverage.state,'invalid');assert.equal(x.totals,null,'invalid data outside window does not silently yield exact zero');}
m=fixture();delete m.combat_timeline;assert.equal(buildMatchCombatWindow(m,0,10).coverage.state,'missing');assert.equal(buildMatchCombatWindow(m,0,10).totals,null);
for(const pair of [[NaN,10],[20,10],[60,70],[0,Infinity]])assert.equal(buildMatchCombatWindow(fixture(),pair[0],pair[1]).coverage.state,'invalid');
m=fixture();m.combat_timeline!.sources[0]='__proto__';assert.equal(buildMatchCombatWindow(m,10,14).players[0].damage.bySource.__proto__,400,'dictionary keys cannot mutate map prototype');
m=fixture();m.combat_timeline!.damage[0][7]=Number.MAX_SAFE_INTEGER;assert.equal(buildMatchCombatWindow(m,10,14).coverage.state,'invalid','sum overflow invalidates exact totals');
console.log('Combat window tests passed: second bins, owner-controlled sources, illusion flag, healing teams, unknown sources, exclusive coverage prefix, invalid dictionaries/rows, no legacy mutation.');
