import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {once} from 'node:events';
import os from 'node:os';
import path from 'node:path';
import {ApmStore,APM_VERSION} from './apm-store.js';
import type {ParsedMatch} from './replay.js';
import {buildMatchEpisodes} from './match-episodes.js';
import {renderMatchEpisodes} from './web/match-episode-render.js';
import {renderReplayInsights} from './web/match-render.js';
const account=94014640,steam=String(BigInt(account)+76561197960265728n);
const heroes=['crystal_maiden','warlock','pudge','lina','zuus','axe','slark','antimage','sniper','kunkka'];
const fixture=():ParsedMatch=>({match_id:777,start_time:1700000000,duration_min:8,apm_duration_seconds:480,apm_version:APM_VERSION,winner:'radiant',players:heroes.map((hero,i)=>({steam_id:i?String(76561197960265728n+BigInt(i+10)):steam,hero,team:i<5?'radiant':'dire',kills:999,deaths:999,assists:999,actions:480,actions_per_min:60,networth_final:800,networth_by_minute:Array(8).fill(800),item_timings:[],combat_details:{version:'combat-log-v2',coverage:{xp:true,ward_placements:true,healing_target_identity:true},damage:{by_ability:{},by_target:{},by_type:{}},healing:{self:0,other_heroes:0,units:0,by_target:{}},xp_by_minute:Array(8).fill(100),deaths:[],wards:[],casts:[],gold:[],buybacks:[],modifiers:[]}})),kills:[],teamfights:[],buildings:[],roshan_kills_min:[]} as unknown as ParsedMatch);
const m=fixture();
for(const [i,seconds] of [[0,120],[1,130],[5,140],[2,300],[3,310],[6,320]])m.players[i].combat_details!.deaths.push({min:seconds/60,killer:seconds<200?'FirstSentinel':'SecondSentinel',x:0,y:0});
const episodes=buildMatchEpisodes(m).episodes;assert.equal(episodes.length,2);
const selected=episodes[1].id;
const html=renderMatchEpisodes(m,selected);
assert.ok(html.includes('SecondSentinel'));assert.ok(!html.includes('FirstSentinel'),'only selected episode details are rendered');
assert.equal((html.match(/data-episode-death="/g)||[]).length,3);
assert.ok(html.includes(`value="${selected}" selected`));
assert.ok(html.includes('Погибшие герои'));assert.ok(!/Участники (боя|эпизода)|все участники/i.test(html));
assert.ok(html.includes('в другой части карты'));assert.ok(html.includes('Это не награда за конкретное столкновение'));
assert.ok(html.includes('Разбивка урона перед этой смертью не сохранена'));assert.ok(!/NaN|Infinity|undefined/.test(html));
const official=[{account_id:account,hero_id:5,player_slot:0,kills:7,deaths:9,assists:17}];
const page=renderReplayInsights(m,steam,undefined,official as any,selected);
assert.ok(page.includes('<b>7 / 9 / 17</b>'));assert.ok(!page.includes('<b>999 / 999 / 999</b>'));
assert.ok(!renderReplayInsights(m,steam,undefined,[{...official[0],player_slot:128}] as any).includes('<b>7 / 9 / 17</b>'),'wrong team must not match');
assert.ok(!renderReplayInsights(m,steam,undefined,[{...official[0],account_id:account+1}] as any).includes('<b>7 / 9 / 17</b>'),'wrong public account must not match');
const ids=[...page.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);
for(const [,id]of page.matchAll(/href="#([^"]+)"/g))assert.ok(id==='analysis'||ids.includes(id),`anchor ${id} exists`);
for(const [,id]of html.matchAll(/data-share-section="([^"]+)"/g))assert.ok(ids.includes(id));
for(const [,query]of html.matchAll(/href="\?episode=([^"#]+)#episodes"/g))assert.ok(episodes.some(e=>e.id===query));
const empty=renderMatchEpisodes(fixture());assert.ok(empty.includes('Это не означает, что в матче не было столкновений'));assert.ok(!empty.includes('episode-map-data'));
const unsafe=fixture(),attack='</script><img src=x onerror=evil>';
unsafe.players[0].hero=attack;unsafe.players[0].combat_details!.deaths=[{min:1,killer:attack},{min:1.1,killer:attack},{min:1.2,killer:attack}];
const escaped=renderMatchEpisodes(unsafe);assert.ok(!escaped.includes(attack));assert.ok(escaped.includes('&lt;/script&gt;&lt;img'));
const map=JSON.parse(escaped.match(/id="episode-map-data">([\s\S]*?)<\/script>/)![1]);assert.equal(map.deaths[0].hero,attack,'safe JSON escaping preserves labels after parsing');
const dir=await mkdtemp(path.join(os.tmpdir(),'episode-http-'));const db=path.join(dir,'stats.sqlite');const store=new ApmStore(db);
store.save(m);store.saveResults(account,[{match_id:777,start_time:1700000000,duration:480,hero_id:5,kills:7,deaths:9,assists:17,radiant_win:true,player_slot:0}],'opendota');store.close();
await writeFile(path.join(dir,'feed.json'),JSON.stringify({updatedAt:Date.now(),matches:[]}));
const worker=spawn(process.execPath,['--import','tsx','--input-type=module','-e',`globalThis.fetch=async()=>{console.error('UNEXPECTED_NETWORK_CALL');throw Error('offline');};const {startWebServer}=await import('./src/web/server.ts');startWebServer(3027);`],{cwd:process.cwd(),env:{...process.env,DATA_DIR:dir,APM_DB_PATH:db,FEED_SYNC_DISABLED:'1'},stdio:['ignore','pipe','pipe']});
let output='';worker.stdout.on('data',c=>output+=c);worker.stderr.on('data',c=>output+=c);
try{
 await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(output)),10000);worker.once('exit',()=>{clearTimeout(timer);reject(Error(output));});worker.stdout.on('data',c=>{if(String(c).includes('витрина на')){clearTimeout(timer);resolve();}});});
 const response=await fetch(`http://localhost:3027/match/777?player=${steam}&episode=${selected}`);assert.equal(response.status,200);const body=await response.text();
 assert.ok(body.includes(`value="${selected}" selected`),'route forwards selected episode');assert.ok(body.includes('<b>7 / 9 / 17</b>'),'route forwards saved partial official players without full API snapshot');
 assert.ok(!output.includes('UNEXPECTED_NETWORK_CALL'),output);assert.ok(!output.includes('ошибка запроса'),output);
 console.log('Match episode web tests passed: selected detail, honest scope, missing data, XSS roundtrip, IDs, official matching, offline HTTP route.');
}finally{const exited=once(worker,'exit');worker.kill('SIGTERM');await exited;await rm(dir,{recursive:true,force:true});}
