import assert from 'node:assert/strict';
import {verifiedReplayScoreboard,withReplayScoreboards} from './replay-scoreboard.js';
import {ApmStore,APM_VERSION} from './apm-store.js';
import {renderPlayer} from './web/player-render.js';
import {buildProfile} from './player-profile.js';
import {resolveOfficialRosterPlayer} from './web/match-official.js';
import {buildMatchInsights} from './match-insights.js';
import type {ParsedMatch,ParsedPlayer} from './replay.js';
const account=94014640,steam=String(BigInt(account)+76561197960265728n);
const p={steam_id:steam,hero:'warlock',team:'radiant',kills:99,deaths:99,assists:99,actions:200,actions_per_min:100,action_counts:{MOVE:200},replay_scoreboard:{version:'player-resource-v1',source:'CDOTA_PlayerResource',resource_slot:7,team_slot:2,hero_id:37,kills:0,deaths:3,assists:27,complete:true,end_state_observed:true}} as unknown as ParsedPlayer;
const m={match_id:999,start_time:1700000000,parser_version:'pesiki-replay-v8',duration_min:2,apm_duration_seconds:120,apm_version:APM_VERSION,winner:'radiant',game_mode:'mode_23',players:[p]} as ParsedMatch;
assert.equal(verifiedReplayScoreboard(p)?.kills,0);
for(const steam_id of ["0","bad","76561197960265728"])assert.equal(verifiedReplayScoreboard({...p,steam_id}),undefined);
for(const patch of [{version:'future'},{source:'estimated'},{complete:false},{end_state_observed:false},{kills:-1},{deaths:NaN},{assists:undefined},{resource_slot:64},{team_slot:5},{hero_id:14}])assert.equal(verifiedReplayScoreboard({...p,replay_scoreboard:{...p.replay_scoreboard,...patch}} as ParsedPlayer),undefined);
const before=JSON.stringify(m),view=withReplayScoreboards(m);assert.equal(view.players[0].kills,0);assert.equal(view.players[0].assists,27);assert.equal(view.players[0].kda_source,'replay-scoreboard');assert.equal(JSON.stringify(m),before,'analysis projection must not mutate raw replay KDA');
const store=new ApmStore(':memory:');
try{
 const fullOfficial={match_id:999,start_time:1700000000,duration:120,hero_id:37,player_slot:2,radiant_win:true,kills:1,deaths:2,assists:3,gold_per_min:501,xp_per_min:612,last_hits:210,denies:8,lobby_type:7,game_mode:23,average_rank:54,hero_damage:19000,item_uses:{blink:5}};
 store.saveResults(account,[fullOfficial]);
 store.save(m);const result=store.results(account)[0];assert.equal(result.result_source,'replay-scoreboard');assert.equal(result.kills,0);assert.equal(result.assists,27);assert.equal(result.player_slot,2);assert.equal(result.scoreboard_provenance?.resource_slot,7);
 for(const key of ['gold_per_min','xp_per_min','last_hits','denies','lobby_type','game_mode','average_rank','hero_damage','item_uses'])assert.deepEqual((result as any)[key],(fullOfficial as any)[key],`scoreboard upgrade preserves official extra ${key}`);
 assert.equal(store.replay(999)!.players[0].kills,99,'stored legacy count preserved');const apm=store.history(account);
 store.saveResults(account,[{...result,kills:888}], 'opendota');store.saveResults(account,[{...result,kills:777}], 'feed');assert.deepEqual(store.results(account),[result],'lower provenance cannot overwrite verified replay scoreboard');
 const refreshedApi={...fullOfficial,kills:888,deaths:888,assists:888,gold_per_min:650,xp_per_min:720,last_hits:240,start_time:1800000000,duration:999,radiant_win:false};
 store.saveResults(account,[refreshedApi]);const refreshed=store.results(account)[0];
 assert.equal((refreshed as any).gold_per_min,650);assert.equal((refreshed as any).xp_per_min,720);assert.equal((refreshed as any).last_hits,240);
 for(const key of ['kills','deaths','assists','hero_id','player_slot','start_time','duration','radiant_win','result_source','scoreboard_provenance'])assert.deepEqual((refreshed as any)[key],(result as any)[key],`API extra refresh protects ${key}`);
 const wrongHeroApi={...refreshedApi,hero_id:14,gold_per_min:9999};store.saveResults(account,[wrongHeroApi]);assert.equal((store.results(account)[0] as any).gold_per_min,650,'wrong hero cannot enrich extras');
 store.saveResults(account,[{...fullOfficial,gold_per_min:null,xp_per_min:undefined} as any]);assert.equal((store.results(account)[0] as any).gold_per_min,650,'thin/null API fields do not erase measured extras');
 const profile=buildProfile(store,account,'all');assert.equal(profile.matches[0].kdaSource,'табло реплея');assert.deepEqual(profile.matches[0].kda,[0,3,27]);
 store.saveReplay({...m,players:[{...p,replay_scoreboard:undefined}]});assert.deepEqual(store.replay(999)!.players[0].replay_scoreboard,p.replay_scoreboard,'thin snapshot preserves scoreboard');assert.deepEqual(store.history(account),apm);
 const old={...m,match_id:1000,parser_version:'pesiki-replay-v7',analytics_version:'combat-log-v3',players:[{...p,replay_scoreboard:undefined,combat_details:{version:'combat-log-v3'}}]} as ParsedMatch;
 store.save(old);const beforeUpgrade=store.history(account);
 const next={...old,parser_version:'pesiki-replay-v8',players:[{...old.players[0],kills:777,replay_scoreboard:p.replay_scoreboard}]};
 store.mergeReplayAnalytics(next);
 assert.equal(store.replay(1000)!.players[0].kills,99,'v8 analytics merge must keep existing raw/official KDA');assert.deepEqual(store.replay(1000)!.players[0].replay_scoreboard,p.replay_scoreboard);
 assert.deepEqual(store.history(account),beforeUpgrade,'v8 analytics merge preserves APM');assert.equal(store.results(account).find(x=>x.match_id===1000)!.result_source,'replay-scoreboard');
 store.mergeReplayAnalytics({...next,players:[{...next.players[0],replay_scoreboard:undefined}]});assert.deepEqual(store.replay(1000)!.players[0].replay_scoreboard,p.replay_scoreboard);
 assert.throws(()=>store.mergeReplayAnalytics(old),/downgrade/);
 store.save({...m,match_id:1001,start_time:undefined});const undated=store.results(account).find(x=>x.match_id===1001)!;
 assert.equal(undated.start_time,0,'unknown start is a sentinel, never fabricated current time');assert.equal(undated.result_source,'replay-scoreboard');
 const undatedProfile=buildProfile(store,account,'all');assert.equal(undatedProfile.matches.find(x=>x.id===1001)!.start,null);assert.deepEqual(undatedProfile.matches.find(x=>x.id===1001)!.kda,[0,3,27]);assert.ok(!buildProfile(store,account,'7').matches.some(x=>x.id===1001),'undated scoreboard belongs only to all-time history');
 const html=renderPlayer(undatedProfile,[undatedProfile]);assert.ok(html.includes('Больше всего ассистов'),'verified replay KDA retains record cards');assert.ok(html.includes('таблом реплея или OpenDota'));
 store.saveResults(account,[{...fullOfficial,match_id:1002,start_time:1700000050}]);store.save({...m,match_id:1002,start_time:undefined});assert.equal(store.results(account).find(x=>x.match_id===1002)!.start_time,1700000050,'undated parse preserves already known official start');
 store.saveResults(account,[{...fullOfficial,match_id:1003,start_time:0}]);assert.ok(!store.results(account).some(x=>x.match_id===1003),'API/feed zero-date input remains rejected');
 const insight=buildMatchInsights(m).players[0];const official=resolveOfficialRosterPlayer(m,insight,undefined,[{account_id:account,hero_id:37,player_slot:2,kills:888,deaths:888,assists:888}]);assert.equal(official?.kills,0);assert.equal((official as any).kda_source,'replay-scoreboard');
}finally{store.close()}
console.log('Replay scoreboard tests passed: strict validation, raw preservation, provenance precedence, profile and roster');
