import assert from 'node:assert/strict';
import {selectLiveGame,liveSnapshot} from './live-match.js';
import {renderLiveMatch} from './web/live-match-render.js';
import type {TVGame} from './dota-observer.js';
const game=(id:string,ids:number[],extra:Partial<TVGame>={}):TVGame=>({lobby_id:id,match_id:id,is_watch_eligible:true,last_update_time:Date.now()/1000,players:ids.map(account_id=>({account_id,hero_id:2,team:0})),...extra});
const active=new Set([1,2,3]);
const members=new Map([['10',[1,2]]]);
assert.equal(selectLiveGame([game('11',[3]),game('10',[1,1])],members,active)?.count,2);
assert.equal(selectLiveGame([game('11',[3]),game('10',[1,1])],members,active)?.game.match_id,'10');
assert.equal(selectLiveGame([game('1',[99]),game('2',[1])],new Map(),active)?.game.match_id,'2');
assert.equal(selectLiveGame([game('1',[1],{is_watch_eligible:false})],members,active),undefined);
assert.equal(selectLiveGame([game('1',[],{league_id:12}),game('2',[])],new Map(),active)?.game.match_id,'2');
assert.equal(selectLiveGame([game('1',[1],{last_update_time:Date.now()/1000-600})],members,active),undefined);
const g=game('20',[],{game_time:240,radiant_score:3,dire_score:4,delay:120});
const detail={match:{match_id:'20',game_time:120,game_state:5},teams:[{team_number:2,score:1,players:[{accountid:1,name:'<script>oops</script>',heroid:2,level:5,kill_count:1,death_count:0,assists_count:2}]},{team_number:3,score:2,players:[]}]};
const snapshot=liveSnapshot(g,0,detail)!;
assert.equal(snapshot.time,120);assert.equal(snapshot.teams[0].score,1);assert.equal(snapshot.teams[0].players[0].level,5);
assert.equal(liveSnapshot(g,0,{...detail,match:{...detail.match,match_id:'21'}})?.time,240);
assert.equal(liveSnapshot(g,0,{...detail,match:{...detail.match,game_state:6}}),null);
const html=renderLiveMatch(snapshot);assert.ok(html.includes('Публичный матч'));assert.ok(html.includes('2:00'));assert.ok(!html.includes('<script>oops'));assert.ok(html.includes('&lt;script&gt;'));
assert.ok(renderLiveMatch({...snapshot,kind:'stack',stackCount:3}).includes('Участников стака: 3'));
assert.equal(renderLiveMatch(null),'');
console.log('Live match: stack ranking, deduplication, active roster, public fallback, snapshot consistency, completed games, HTML escaping passed.');
